### ISSUE TITLE
[Bug]: Error when refreshing continuous aggregates that use bucket time of 1 month with `start offset = NULL`

### ISSUE THREAD

**Issue by H25E** [timescale/timescaledb#5534] opened 2023-04-07 12:05 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Refresh continuous aggregates that use bucket time of 1 month with `start offset = NULL` returns `ERROR: timestamp out of range`

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

15.2

### What operating system did you use?

Debian 11 (Bullseye)

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ERROR:  timestamp out of range
SQL state: 22008
```

### How can we reproduce the bug?

Table & CA creation:

```SQL
CREATE TABLE IF NOT EXISTS test
(
    ts timestamp without time zone NOT NULL,
    value double precision
);
SELECT create_hypertable('test', 'ts');
```

```SQL
CREATE MATERIALIZED VIEW month_ca
WITH (timescaledb.continuous) AS
SELECT
	time_bucket(INTERVAL '1 month', ts) AS bucket,
	AVG("value") AS "avg"
FROM test
GROUP BY bucket;
```
Then this works:
```SQL
CALL refresh_continuous_aggregate(
	'month_ca',
	'2017-01-01',
	'1 month'::INTERVAL
);
```
But this doesn't:

```SQL
CALL refresh_continuous_aggregate(
	'month_ca',
	NULL,
	'1 month'::INTERVAL
);
```
CA refresh through policy behaves the same way as manual refresh described here.

**Comment by konskov** [comment] 2023-04-10 06:46
hi @H25E, thank you for reaching out. I was able to reproduce this with the example you have provided.

**Comment by konskov** [comment] 2023-04-10 08:29
This issue looks like a duplicate of https://github.com/timescale/timescaledb/issues/5474

**Comment by fabriziomello** [comment] 2023-04-17 17:59
Fix merged https://github.com/timescale/timescaledb/pull/5544

**Closed by fabriziomello** 2023-04-17 17:59 UTC
Labels: bug, continuous_aggregate
