### ISSUE TITLE
Segmentation Fault on start in Docker Container

### ISSUE THREAD

**Issue by mschaar** [timescale/timescaledb#3390] opened 2021-07-05 13:44 UTC
**Relevant system information:**
 - OS: Kernel Version: 5.10.17-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
- Docker Version: 20.10.6
- Container: timescale/timescaledb:2.3.0-pg12

**Describe the bug**
Container is not usable anymore on armv6 based systems.

** Logs **

The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... GMT
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
1970-05-03 08:35:28.010 GMT [31] WARNING:  no usable system locales were found
ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....1970-04-30 07:46:24.010 GMT [36] LOG:  starting PostgreSQL 12.7 on arm-unknown-linux-musleabihf, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 32-bit
1970-04-30 07:46:24.010 GMT [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
....1970-04-30 07:46:24.010 GMT [36] LOG:  startup process (PID 37) was terminated by signal 11: Segmentation fault
1970-04-30 07:46:24.010 GMT [36] LOG:  aborting startup due to startup process failure
1970-04-30 07:46:24.010 GMT [36] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.

**To Reproduce**
Start the docker container on a arm platform and see the logs.

**Expected behavior**
normal startup

**Last working**
The last tried working image is the: timescale/timescaledb:2.0.0-pg12 image.

**Comment by svenklemm** [comment] 2021-07-08 07:48
This looks like a duplicate of https://github.com/timescale/timescaledb/issues/2968. You need to update your docker environment. https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements.
Feel free to reopen the issue if you can reproduce after upgrading your docker environment.

**Closed by svenklemm** 2021-07-08 07:48 UTC
Labels: bug, platform-issue
