### ISSUE TITLE
Error Using CONSTRAINT TRIGGER on hypertable

### ISSUE THREAD

**Issue by esatterwhite** [timescale/timescaledb#1343] opened 2019-07-09 09:43 UTC
**Relevant system information:**
 - OS: debian 
 - PostgreSQL: 11 + 10 (PostgreSQL 11.3 (Debian 11.3-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit)
 - TimescaleDB version: 1.0.0 - 1.3.1
 - Installation method: source build

**Describe the bug**
Using a contraint tigger to a hypertable results in an error when the chunks are being created. If the chunks already exists, this works fine. Seems to be something with how the initial create triggers are being re-written / propagated to the chunks.

**To Reproduce**
1. Add a constraint trigger to an empty hyper table
2. Try to insert records into the table

```sql
CREATE TABLE fake (
  id INT
, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

SELECT create_hypertable('fake', 'created_at', if_not_exists => TRUE);

CREATE OR REPLACE FUNCTION events_conversation_constraints_trig()
RETURNS TRIGGER AS
$$
  BEGIN
    RETURN NEW;
  END;
$$ LANGUAGE plpgsql volatile;


CREATE CONSTRAINT TRIGGER fake_fk
    AFTER INSERT
    ON public.fake
    DEFERRABLE INITIALLY DEFERRED
	FOR EACH ROW EXECUTE PROCEDURE public.events_conversation_constraints_trig();
	
	
INSERT INTO fake(id) VALUES (1)
```

**Expected behavior**
Should be a complete insert resulting in the chunk being created and rows being inserted

**Actual behavior**
When TSDB tries to create the chunk, it runs into a syntax error trying to add the trigger as a constraint

```
postgres | 2019-07-09 09:24:26.887 UTC [249] ERROR:  syntax error at or near "TRIGGER" at character 98
postgres | 2019-07-09 09:24:26.887 UTC [249] QUERY:   ALTER TABLE _timescaledb_internal._hyper_1_9_chunk ADD CONSTRAINT "9_18_events_conversation_fk" TRIGGER DEFERRABLE INITIALLY DEFERRED 
postgres | 2019-07-09 09:24:26.887 UTC [249] CONTEXT:  PL/pgSQL function _timescaledb_internal.chunk_constraint_add_table_constraint(_timescaledb_catalog.chunk_constraint) line 29
```

```
ERR! lib:conver | { error: syntax error at or near "TRIGGER"
ERR! lib:conver |     at Connection.parseE (/home/esatterwhite/dev/js/helpdotcom/voltron/node_modules/pg/lib/connection.js:602:11)
ERR! lib:conver |     at Connection.parseMessage (/home/esatterwhite/dev/js/helpdotcom/voltron/node_modules/pg/lib/connection.js:399:19)
ERR! lib:conver |     at Socket.<anonymous> (/home/esatterwhite/dev/js/helpdotcom/voltron/node_modules/pg/lib/connection.js:121:22)
ERR! lib:conver |     at Socket.emit (events.js:182:13)
ERR! lib:conver |     at Socket.EventEmitter.emit (domain.js:460:23)
ERR! lib:conver |     at addChunk (_stream_readable.js:283:12)
ERR! lib:conver |     at readableAddChunk (_stream_readable.js:264:11)
ERR! lib:conver |     at Socket.Readable.push (_stream_readable.js:219:10)
ERR! lib:conver |     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
ERR! lib:conver |   name: 'error',
ERR! lib:conver |   length: 343,
ERR! lib:conver |   severity: 'ERROR',
ERR! lib:conver |   code: '42601',
ERR! lib:conver |   detail: undefined,
ERR! lib:conver |   hint: undefined,
ERR! lib:conver |   position: undefined,
ERR! lib:conver |   internalPosition: '100',
ERR! lib:conver |   internalQuery:
ERR! lib:conver |    ' ALTER TABLE _timescaledb_internal._hyper_1_18_chunk ADD CONSTRAINT "18_36_events_conversation_fk" TRIGGER ',
ERR! lib:conver |   where:
ERR! lib:conver |    'PL/pgSQL function _timescaledb_internal.chunk_constraint_add_table_constraint(_timescaledb_catalog.chunk_constraint) line 29 at EXECUTE',
ERR! lib:conver |   schema: undefined,
ERR! lib:conver |   table: undefined,
ERR! lib:conver |   column: undefined,
ERR! lib:conver |   dataType: undefined,
ERR! lib:conver |   constraint: undefined,
ERR! lib:conver |   file: 'scan.l',
ERR! lib:conver |   line: '1134',

```

**Comment by dianasaur323** [comment] 2019-07-09 15:56
@davidkohn88 mind taking a quick look to see what the issue is here?

**Comment by esatterwhite** [comment] 2019-08-09 03:26
any luck with this? able to reproduce?

**Comment by dianasaur323** [comment] 2019-08-13 14:09
@esatterwhite thanks for following up on this - currently triaging to get someone on this.

**Comment by svenklemm** [comment] 2020-10-13 09:34
Looks like there is something wrong with your SQL. The following works for me:
```
CREATE TABLE fake (
  id INT
, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

SELECT create_hypertable('fake', 'created_at', if_not_exists => TRUE);

CREATE OR REPLACE FUNCTION events_conversation_constraints_trig()
RETURNS TRIGGER AS
$$
  BEGIN
    RETURN NEW;
  END;
$$ LANGUAGE plpgsql volatile;


CREATE TRIGGER fake_fk
    AFTER INSERT
    ON public.fake
    DEFERRABLE INITIALLY DEFERRED
	FOR EACH ROW EXECUTE PROCEDURE public.events_conversation_constraints_trig();
	
	
INSERT INTO fake(id) VALUES (1);
```

**Comment by svenklemm** [comment] 2020-10-13 09:35
Closing this since it seems to be resolved. Feel free to reopen if the issue is still relevant.

**Closed by svenklemm** 2020-10-13 09:35 UTC
Labels: investigate
