### ISSUE TITLE
Delete query consuming all the memory available 

### ISSUE THREAD

**Issue by himkool** [timescale/timescaledb#2486] opened 2020-10-03 09:43 UTC
Os: Centos7
PostgresSQL version: 11
Timescale version: 1.6.0
Installed memory: 64Gb

Query: delete from data.samples_interface_errors where time>='2020-06-18 00:00:00' and time <'2020-06-19 00:00:00';
Delete query consuming all the memory available and then the database goes in the recovery mode.

**Comment by mfreed** [comment] 2020-10-23 06:13
Hi @himkool We need more information.  Do you see any log entries?  Is this due to the Linux OOM killer?  How much memory is consumed and/or what are some of your GUC settings here?

**Comment by mfreed** [comment] 2020-10-29 12:56
Hi @himkool wanted to follow up here to see if you can provide more information?  (Otherwise, I'll probably close out this issue; we can always re-open if you can provide more.  Thanks!)

**Comment by k1th** [comment] 2020-12-16 22:36
Same issue here, might be related to #1569.
We're on PG 12 with Timescale 1.7.2.

We have 2321 chunks in a table and we're trying to delete 25K records due to duplicate issues. As we don't have a unique index, we need to do this by ctid.
Statement is like this
```
WITH cte AS
  (SELECT ctid,
          meta_id,
          row_number() over (partition BY meta_id) AS dup_count
   FROM rep_table maru
   WHERE rec_creationtime BETWEEN '2020-12-15 12:00:00' AND '2020-12-15 18:00:00')
DELETE
FROM rep_table
WHERE rec_creationtime BETWEEN '2020-12-15 12:00:00' AND '2020-12-15 18:00:00'
  AND ctid IN
    (SELECT ctid
     FROM cte
     WHERE cte.dup_count > 1)
```

This ends up with an OOM crash of the process. And the crash even happens if we only do an explain.
Based on similar issues this might rather be a Postgres bug that's caused by the number of child tables?

Our current solution is to create SQL commands in the SQL script and execute those one by one – which takes forever.

**Comment by NunoFilipeSantos** [comment] 2021-10-01 13:50
@himkool can you please try against our latest TimescaleDB version (2.4.2) and get back to us?

**Comment by NunoFilipeSantos** [comment] 2021-10-20 13:32
@himkool Feel free to reopen the issue if you experience it on the latest Timescale version.

**Comment by sallvador** [comment] 2021-12-29 10:41
@NunoFilipeSantos Experiencing same problem on PostgreSQL 13 and TimescaleDB 2.4.2. I am working with a table partitioned by date and segmented by text field, both **delete** and **explain delete** lead to crash with OOM, while we have 192 GB RAM, and whole table is 15 GB

**Comment by akuzm** [comment] 2022-01-24 11:09
High memory usage even for `EXPLAIN DELETE` is concerning, I'll try to investigate.

**Comment by akuzm** [comment] 2022-01-27 14:06
This issue should be largely fixed by this PR https://github.com/timescale/timescaledb/pull/3928 that is already in 2.6-dev.

I'll make some more tweaks to reduce the memory usage further.

**Closed** 2022-01-31 12:02 UTC
Labels: performance, 2.4.2
