### ISSUE TITLE
time_bucket could not find pathkey item to sort

### ISSUE THREAD

**Issue by Daennes** [timescale/timescaledb#3080] opened 2021-04-01 13:15 UTC
**Relevant system information:**
 - Image: timescale/timescaledb:latest-pg11
 - PostgreSQL version: latest-11
 - TimescaleDB version: 2.02
 - Installation method: Docker

Same issue for timescaleDB 1.7.5 and 2.1.0

Hello All,
I get an unexpected error when I use the time_bucket function. Especially when in our case small time ranges are used < 2h. Timerange is here the diff between timestamp A and B.
Explanation:
I have table A and B. They have a one-to-many relationship.I now join B to A on an ID and the time column.

```
SELECT time_bucket('1 hour', metricA.time, 'timestampA') "time",
       sum(metricB.costs)
FROM metricA
INNER JOIN metricB ON metricB.name = metricA.name AND metricB.time = metricA.time
WHERE metricA.time BETWEEN 'timestampA' AND 'timestampB'
GROUP BY 1
```

The error no longer occurs if metricB.time is used in the time_bucket function. time_bucket('1 hour', metricB.time, 'timestampA')

Error:
```
ERROR: could not find pathkey item to sort
SQL state: XX000
```
Any ides?

**Comment by svenklemm** [comment] 2021-04-03 09:55
Can you provide a minimal sql script to reproduce the issue in a new database?

**Comment by emmanuel-kubermatic** [comment] 2021-04-13 12:18
Hello @svenklemm , we have resolved the issue by using a `TRUNCATE` instead of a `DELETE`  to empty out our current database.

That seemed to fix the pathkey item issue for now but we're not quite aware why that works 

Any notes from your end?

**Comment by genedavis** [comment] 2021-12-02 19:54
I would be curious why TRUNCATE vs DELETE is sufficient to close this issue?  Is there any explanation?

**Comment by genedavis** [comment] 2021-12-02 19:59
Hi any update on this issue?  Thx

**Comment by svenklemm** [comment] 2022-01-20 18:39
There have been many bugfixes that could be a potential cause for this since this has been reported. Can you try on the latest version or provide a self-contained script to reproduce the error.

**Closed** 2022-10-17 02:15 UTC
Labels: bug, need-more-info, time_bucket, docker-build, no-activity

**Comment by cchenggit** [comment] 2023-05-06 08:57
I have met the same error using `time_bucket_gapfill ` recently. 
As far as I know, this bug may exist in postgres and timescaledb, and both versions are  upgraded after the fixed version. 
but still NOT WORK for me...

links:
- [Fix "could not find pathkey item to sort" planner errors that occur in some situations when the sort key involves an aggregate or window function.](https://www.postgresql.org/about/news/postgresql-133-127-1112-1017-and-9622-released-2210/)
- #2232 

![image](https://user-images.githubusercontent.com/16542961/236613567-50dbea49-60d6-40ee-91e7-1c093339bff6.png)

```psql
db> explain SELECT time_bucket_gapfill('1 h', time) as bucket, count(*) as n FROM "logs"  WHERE
 (time >= '2023-04-24T00:00:00') AND (time < '2023-05-05T00:00:00') AND (event @@ '$.actor.type == "user"') GROUP BY 1

could not find pathkey item to sort
Time: 0.004s
``

**Comment by kgyrtkirk** [comment] 2023-05-09 11:02
@cchenggit could you please see if the issue is solved by upgrading to the latest version?

I think the original issue here was specific to `time_bucket` ; `time_bucket_gapfill` has a slightly different path ; so in case the problem persists:
* please open a separate ticket
* add explains
* try to simplify - and/or try to remove uses of unrelated features (does this happen if you don't use `@@` ? )  
* ...and most importantly: provide repro steps so that we could reproduce your issue
