### ISSUE TITLE
Concurrent COPY commands blocking

### ISSUE THREAD

**Issue by kmatt** [timescale/timescaledb#158] opened 2017-08-14 19:49 UTC
CREATE DATABASE customer;
    CREATE EXTENSION timescaledb;
    CREATE TABLE tbl1 (...) TABLESPACE xfsdata;
    SELECT create_hypertable('tbl1', 'date_tm', chunk_time_interval => 86400000000);
    CREATE TABLE tbl2(...) TABLESPACE zfsdata;
    SELECT create_hypertable('tbl2', 'date_tm', chunk_time_interval => 86400000000);

Running two COPY commands in separate tmux splits:

    pv customer_201707.dat.gz | zcat | psql -d caspr -c "copy tbl1 from stdin"
    pv customer_201707.dat.gz | zcat | psql -d caspr -c "copy tbl2 from stdin"

The first COPY block the second on exclusive chunk access.

**Comment by kmatt** [comment] 2017-08-14 19:51
```sql
SELECT DISTINCT
    bl.pid AS blocked_pid,
    bl.usename AS blocked_user,
    bl.query AS blocked_query,
    bl.query_start AS blocked_query_start,
    relname AS blocked_on,
    lq.pid AS blocking_pid,
    lq.usename AS blocking_user,
    lq.query AS blocking_query,
    lq.query_start AS blocking_query_start,
    now(),
    pgl2.mode AS lock_type
FROM pg_stat_activity bl,
    pg_locks pgl1,
    pg_stat_activity lq,
    pg_locks pgl2,
    pg_class
WHERE bl.pid = pgl1.pid
    AND NOT pgl1.granted
    AND pg_class.oid = pgl1.relation
    AND pgl2.relation = pgl1.relation
    AND pgl2.granted
    AND lq.pid = pgl2.pid;
```

```
blocked_pid  blocked_user  blocked_query                   blocked_query_start  blocked_on  blocking_pid  blocking_user  blocking_query                   blocking_query_start  now                  lock_type         
-----------  ------------  ------------------------------  -------------------  ----------  ------------  -------------  -------------------------------  --------------------  -------------------  ----------------  
335451       postgres      copy tbl1 from stdin  2017-08-14 15:26:45  chunk       335441        postgres       copy tbl2 from stdin  2017-08-14 15:26:42   2017-08-14 15:38:39  AccessShareLock   
335451       postgres      copy tbl1 from stdin  2017-08-14 15:26:45  chunk       335441        postgres       copy tbl2 from stdin  2017-08-14 15:26:42   2017-08-14 15:38:39  ExclusiveLock     
335451       postgres      copy tbl1 from stdin  2017-08-14 15:26:45  chunk       335441        postgres       copy tbl2 from stdin  2017-08-14 15:26:42   2017-08-14 15:38:39  RowExclusiveLock  
335451       postgres      copy tbl1 from stdin  2017-08-14 15:26:45  chunk       335441        postgres       copy tbl2 from stdin  2017-08-14 15:26:42   2017-08-14 15:38:39  RowShareLock       
```

**Comment by kmatt** [comment] 2017-08-14 19:52
Locks displayed with:

```sql
SELECT DISTINCT
    bl.pid AS blocked_pid,
    bl.usename AS blocked_user,
    bl.query AS blocked_query,
    bl.query_start AS blocked_query_start,
    relname AS blocked_on,
    lq.pid AS blocking_pid,
    lq.usename AS blocking_user,
    lq.query AS blocking_query,
    lq.query_start AS blocking_query_start,
    now(),
    pgl2.mode AS lock_type
FROM pg_stat_activity bl,
    pg_locks pgl1,
    pg_stat_activity lq,
    pg_locks pgl2,
    pg_class
WHERE bl.pid = pgl1.pid
    AND NOT pgl1.granted
    AND pg_class.oid = pgl1.relation
    AND pgl2.relation = pgl1.relation
    AND pgl2.granted
    AND lq.pid = pgl2.pid;
```

```
blocked_pid  blocked_user  blocked_query                   blocked_query_start  blocked_on  blocking_pid  blocking_user  blocking_query                   blocking_query_start  now                  lock_type         
-----------  ------------  ------------------------------  -------------------  ----------  ------------  -------------  -------------------------------  --------------------  -------------------  ----------------  
335451       postgres      copy tbl1 from stdin  2017-08-14 15:26:45  chunk       335441        postgres       copy tbl2 from stdin  2017-08-14 15:26:42   2017-08-14 15:38:39  AccessShareLock   
335451       postgres      copy tbl1 from stdin  2017-08-14 15:26:45  chunk       335441        postgres       copy tbl2 from stdin  2017-08-14 15:26:42   2017-08-14 15:38:39  ExclusiveLock     
335451       postgres      copy tbl1 from stdin  2017-08-14 15:26:45  chunk       335441        postgres       copy tbl2 from stdin  2017-08-14 15:26:42   2017-08-14 15:38:39  RowExclusiveLock  
335451       postgres      copy tbl1 from stdin  2017-08-14 15:26:45  chunk       335441        postgres       copy tbl2 from stdin  2017-08-14 15:26:42   2017-08-14 15:38:39  RowShareLock      
```

**Comment by olofr** [comment] 2017-08-16 09:14
This issue is unfortunately by design but it is something we have on our road map to fix. When chunks are created, we need to take a lock on our chunk metadata table and that will block parallel writers for the duration of the transaction.   

(Remember that in Timescale, unlike standard Postgres, just importing a lot of data can lead to the creation of many tables.)

So, this will have a great impact when you do long copy statements; it's one benefit of our parallel importer (https://github.com/timescale/timescaledb-parallel-copy) -- more small transactions than just one long one.

We have some ideas how to fix, though, so will follow-up when further along.

**Comment by pranasblk** [comment] 2017-09-06 06:44
Just to understand the scope of the locking. Would regular PG tables not managed by TimescaleDB  impacted?

**Comment by olofr** [comment] 2017-09-06 07:23
No they won't @pranasblk. When a writer creates a chunk in a hypertable, other writers that need to create chunks will block. This is due to the fact that the chunks created won't be visible to the other writes before the first writer has ended the transaction. Inserts to already created chunks, or other PG tables, will not block.

**Comment by Pratapkarn** [comment] 2018-03-14 12:18
Any idea by when we are expecting the fix as need to do parallel copy and amount of data can be huge.

**Comment by cevian** [comment] 2018-03-14 14:26
@Pratapkarn. We have created a parallel copy utility that avoids this issue https://github.com/timescale/timescaledb-parallel-copy

**Comment by dianasaur323** [comment] 2019-07-16 17:53
@cevian based on your response and since we have a parallel COPY utility, closing out.

**Closed by dianasaur323** 2019-07-16 17:53 UTC
Labels: limitation

**Comment by patleb** [comment] 2019-10-27 21:19
@dianasaur323, @cevian, the parallel copy utility fetches to the COPY command by batching its CSV reads to STDIN. The utility is unrelated to this issue and I don't think that this issue should be closed, since you still have the same table lock when using the utility or not.
