### ISSUE TITLE
Release candidate instead of stable version is installed when following docs instructions

### ISSUE THREAD

**Issue by NeroVanbiervliet** [timescale/timescaledb#2549] opened 2020-10-15 09:49 UTC
**Relevant system information:**
 - OS: Ubuntu
 - PostgreSQL version: 12
 - Installation method: apt in docker

**Describe the bug**
Release candidate is installed instead of the latest stable version

**To Reproduce**
Follow installation steps of the [docs](https://docs.timescale.com/latest/getting-started/installation/ubuntu/installation-apt-ubuntu)

**Expected behavior**
Version `1.7.4` is installed

**Actual behavior**
Version `2.0.0-rc1` is installed

**Additional context**
The following error message shown by postgres upon adding the extension with `psql --dbname <db_name> -c "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;"`
```
ERROR:  extension "timescaledb" has no installation script nor update path for version "2.0.0-rc1"
```

**Comment by WGH-** [comment] 2020-10-15 11:17
The problem is not just it's an RC version. The new loader package version is simply broken, and it replaced the old one.

**Comment by Barolina** [comment] 2020-10-15 11:28
what to do?

**Comment by svenklemm** [comment] 2020-10-15 12:00
Unfortunately the package update for the loader package pulled in some 2.0 stuff that was supposed to be stay hidden unless explicitly requested. As a temporary workaround you can install 1.7.4 with the following command:
```
CREATE EXTENSION IF NOT EXISTS timescaledb VERSION '1.7.4';
```

**Comment by svenklemm** [comment] 2020-10-16 15:44
Packages should be fixed now. Feel free to reopen if the problem persists.

**Closed by svenklemm** 2020-10-16 15:44 UTC
Labels: packaging, severity-p1
