### ISSUE TITLE
Build errors with Pg 12.5 and TimescaleDB 2.0.1

### ISSUE THREAD

**Issue by nkukard** [timescale/timescaledb#2881] opened 2021-01-29 04:42 UTC
**Relevant system information:**
 - OS: ArchLinux
 - PostgreSQL version (output of `postgres --version`): 12.5
 - TimescaleDB version (output of `\dx` in `psql`): 2.0.1
 - Build method: Docker

**Describe the bug**
Compile errors against PostgreSQL 12.5.

**Steps to reproduce**
Build PostgreSQL 12.5
Build TimescaleDB 2.0.1  (1.7.4 works fine)

**Actual behavior**

> -- The C compiler identification is GNU 10.2.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: /usr/sbin/cc - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- TimescaleDB version 2.0.1. Can be updated from version 2.0.0
> -- Build type is Release
> -- Install method is 'source'
> -- Performing Test CC_SUPPORTS_NO_FORMAT_TRUNCATION
> -- Performing Test CC_SUPPORTS_NO_FORMAT_TRUNCATION - Success
> -- Performing Test CC_SUPPORTS_IMPLICIT_FALLTHROUGH
> -- Performing Test CC_SUPPORTS_IMPLICIT_FALLTHROUGH - Success
> -- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN
> -- Performing Test CC_SUPPORTS_VISIBILITY_HIDDEN - Success
> -- Using compiler GNU
> -- Found Git: /usr/sbin/git (found version "2.30.0") 
> -- Using pg_config /usr/sbin/pg_config
> -- Compiling against PostgreSQL version 12.5
> CMake Warning at CMakeLists.txt:325 (message):
>   clang-format is disabled (can't find clang-format or docker)
> -- Assertion checks are OFF
> -- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.1i")  
> -- OPENSSL_LIBRARIES: /usr/lib/libssl.so;/usr/lib/libcrypto.so
> -- Using OpenSSL version 1.1.1i
> -- Using nm /usr/sbin/nm
> -- Using pg_regress /usr/lib/postgresql/pgxs/src/test/regress/pg_regress
> -- Skipping isolation regress checks since program 'pg_isolation_regress' was not found
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build
> TimescaleDB build system initialized in ./build. To compile, do:
> cd ./build && make
> Scanning dependencies of target sqlfile
> Scanning dependencies of target sqlupdatescripts
> [  0%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--2.0.1.sql
> [  1%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/updates/post-update.sql.processed
> Scanning dependencies of target timescaledb-loader
> [  1%] Built target sqlfile
> [  2%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--2.0.0-rc4--2.0.1.sql
> [  2%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--2.0.0--2.0.1.sql
> [  3%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--2.0.0-rc2--2.0.1.sql
> [  3%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--2.0.0-rc3--2.0.1.sql
> [  3%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--2.0.0-rc1--2.0.1.sql
> [  4%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.7.4--2.0.1.sql
> [  5%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.7.2--2.0.1.sql
> [  5%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.7.1--2.0.1.sql
> [  5%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.7.3--2.0.1.sql
> [  5%] Building C object src/loader/CMakeFiles/timescaledb-loader.dir/bgw_message_queue.c.o
> [  6%] Building C object src/loader/CMakeFiles/timescaledb-loader.dir/loader.c.o
> [  7%] Building C object src/loader/CMakeFiles/timescaledb-loader.dir/bgw_counter.c.o
> [  8%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.7.0--2.0.1.sql
> [  8%] Building C object src/loader/CMakeFiles/timescaledb-loader.dir/bgw_launcher.c.o
> [  8%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.6.1--2.0.1.sql
> [  9%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.6.0--2.0.1.sql
> [  9%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.5.1--2.0.1.sql
> [  9%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.4.2--2.0.1.sql
> [ 10%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.5.0--2.0.1.sql
> [ 11%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.4.1--2.0.1.sql
> [ 11%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.4.0--2.0.1.sql
> [ 12%] Building C object src/loader/CMakeFiles/timescaledb-loader.dir/bgw_interface.c.o
> [ 12%] Building C object src/loader/CMakeFiles/timescaledb-loader.dir/lwlocks.c.o
> [ 13%] Building C object src/loader/CMakeFiles/timescaledb-loader.dir/seclabel.c.o
> [ 14%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.3.2--2.0.1.sql
> [ 14%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.3.1--2.0.1.sql
> [ 15%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.3.0--2.0.1.sql
> [ 16%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.2.1--2.0.1.sql
> [ 16%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.2.2--2.0.1.sql
> [ 16%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.2.0--2.0.1.sql
> [ 17%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.1.1--2.0.1.sql
> [ 17%] Generating /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/build/sql/timescaledb--1.1.0--2.0.1.sql
> [ 17%] Built target sqlupdatescripts
> Scanning dependencies of target timescaledb
> Scanning dependencies of target timescaledb-tsl
> [ 17%] Building C object src/CMakeFiles/timescaledb.dir/agg_bookend.c.o
> [ 18%] Building C object src/CMakeFiles/timescaledb.dir/func_cache.c.o
> [ 18%] Building C object src/CMakeFiles/timescaledb.dir/cache.c.o
> [ 19%] Building C object src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o
> [ 19%] Building C object src/CMakeFiles/timescaledb.dir/catalog.c.o
> [ 20%] Building C object src/CMakeFiles/timescaledb.dir/continuous_agg.c.o
> [ 20%] Building C object src/CMakeFiles/timescaledb.dir/chunk.c.o
> [ 21%] Building C object src/CMakeFiles/timescaledb.dir/chunk_adaptive.c.o
> [ 22%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/async_append.c.o
> [ 22%] Building C object src/CMakeFiles/timescaledb.dir/chunk_constraint.c.o
> [ 22%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/chunk_api.c.o
> [ 22%] Linking C shared module timescaledb.so
> [ 22%] Built target timescaledb-loader
> [ 23%] Building C object src/CMakeFiles/timescaledb.dir/chunk_dispatch.c.o
> [ 23%] Building C object src/CMakeFiles/timescaledb.dir/chunk_dispatch_plan.c.o
> [ 24%] Building C object src/CMakeFiles/timescaledb.dir/chunk_dispatch_state.c.o
> [ 24%] Building C object src/CMakeFiles/timescaledb.dir/chunk_index.c.o
> [ 25%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/chunk.c.o
> [ 26%] Building C object src/CMakeFiles/timescaledb.dir/chunk_insert_state.c.o
> [ 26%] Building C object src/CMakeFiles/timescaledb.dir/chunk_data_node.c.o
> [ 27%] Building C object src/CMakeFiles/timescaledb.dir/constraint.c.o
> [ 27%] Building C object src/CMakeFiles/timescaledb.dir/constraint_aware_append.c.o
> [ 28%] Building C object src/CMakeFiles/timescaledb.dir/cross_module_fn.c.o
> [ 28%] Building C object src/CMakeFiles/timescaledb.dir/copy.c.o
> [ 29%] Building C object src/CMakeFiles/timescaledb.dir/compression_chunk_size.c.o
> [ 29%] Building C object src/CMakeFiles/timescaledb.dir/compression_with_clause.c.o
> [ 29%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/data_node.c.o
> [ 30%] Building C object src/CMakeFiles/timescaledb.dir/dimension.c.o
> [ 30%] Building C object src/CMakeFiles/timescaledb.dir/dimension_slice.c.o
> [ 31%] Building C object src/CMakeFiles/timescaledb.dir/dimension_vector.c.o
> [ 32%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/data_node_dispatch.c.o
> [ 32%] Building C object src/CMakeFiles/timescaledb.dir/estimate.c.o
> [ 33%] Building C object src/CMakeFiles/timescaledb.dir/event_trigger.c.o
> [ 33%] Building C object src/CMakeFiles/timescaledb.dir/extension.c.o
> [ 34%] Building C object src/CMakeFiles/timescaledb.dir/gapfill.c.o
> [ 34%] Building C object src/CMakeFiles/timescaledb.dir/guc.c.o
> [ 35%] Building C object src/CMakeFiles/timescaledb.dir/histogram.c.o
> [ 35%] Building C object src/CMakeFiles/timescaledb.dir/hypercube.c.o
> [ 36%] Building C object src/CMakeFiles/timescaledb.dir/hypertable.c.o
> [ 36%] Building C object src/CMakeFiles/timescaledb.dir/hypertable_cache.c.o
> [ 37%] Building C object src/CMakeFiles/timescaledb.dir/hypertable_compression.c.o
> [ 37%] Building C object src/CMakeFiles/timescaledb.dir/hypertable_insert.c.o
> [ 38%] Building C object src/CMakeFiles/timescaledb.dir/hypertable_restrict_info.c.o
> [ 38%] Building C object src/CMakeFiles/timescaledb.dir/hypertable_data_node.c.o
> [ 39%] Building C object src/CMakeFiles/timescaledb.dir/indexing.c.o
> [ 39%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/deparse.c.o
> [ 40%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/dist_util.c.o
> [ 40%] Building C object src/CMakeFiles/timescaledb.dir/init.c.o
> [ 40%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/hypertable.c.o
> [ 41%] Building C object src/CMakeFiles/timescaledb.dir/metadata.c.o
> [ 41%] Building C object src/CMakeFiles/timescaledb.dir/jsonb_utils.c.o
> [ 42%] Building C object src/CMakeFiles/timescaledb.dir/license_guc.c.o
> [ 42%] Building C object src/CMakeFiles/timescaledb.dir/partitioning.c.o
> [ 43%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/init.c.o
> [ 43%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/partialize_finalize.c.o
> [ 44%] Building C object src/CMakeFiles/timescaledb.dir/planner.c.o
> [ 44%] Building C object src/CMakeFiles/timescaledb.dir/plan_expand_hypertable.c.o
> [ 45%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/planner.c.o
> [ 45%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/process_utility.c.o
> [ 46%] Building C object src/CMakeFiles/timescaledb.dir/plan_add_hashagg.c.o
> [ 46%] Building C object src/CMakeFiles/timescaledb.dir/plan_agg_bookend.c.o
> [ 47%] Building C object src/CMakeFiles/timescaledb.dir/plan_partialize.c.o
> [ 47%] Building C object src/CMakeFiles/timescaledb.dir/process_utility.c.o
> [ 48%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/reorder.c.o
> In file included from /usr/include/string.h:519,
>                  from /usr/include/postgresql/server/c.h:61,
>                  from /usr/include/postgresql/server/postgres.h:46,
>                  from /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/src/partitioning.c:6:
> In function ‘strncpy’,
>     inlined from ‘ts_partitioning_info_create’ at /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/src/partitioning.c:187:2:
> /usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
>   106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In function ‘strncpy’,
>     inlined from ‘ts_partitioning_info_create’ at /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/src/partitioning.c:188:2:
> /usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
>   106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> In function ‘strncpy’,
>     inlined from ‘ts_partitioning_info_create’ at /builds/packages/enterprise/timescaledb/build-dir/timescaledb/src/timescaledb-2.0.1/src/partitioning.c:196:2:
> /usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 64 equals destination size [-Werror=stringop-truncation]
>   106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> [ 49%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/bgw_policy/compression_api.c.o
> [ 49%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/telemetry.c.o
> cc1: all warnings being treated as errors
> [ 49%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/bgw_policy/continuous_aggregate_api.c.o
> make[2]: *** [src/CMakeFiles/timescaledb.dir/build.make:628: src/CMakeFiles/timescaledb.dir/partitioning.c.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> [ 50%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/bgw_policy/job.c.o
> [ 50%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/bgw_policy/job_api.c.o
> [ 51%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/bgw_policy/reorder_api.c.o
> [ 51%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/bgw_policy/retention_api.c.o
> [ 52%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/bgw_policy/policy_utils.c.o
> [ 52%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/compression/array.c.o
> [ 53%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/compression/compression.c.o
> [ 53%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/compression/create.c.o
> [ 54%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/compression/compress_utils.c.o
> [ 54%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/compression/datum_serialize.c.o
> [ 55%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/compression/deltadelta.c.o
> [ 55%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/compression/dictionary.c.o
> [ 56%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/compression/gorilla.c.o
> [ 56%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/compression/segment_meta.c.o
> [ 57%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/continuous_aggs/create.c.o
> [ 57%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/continuous_aggs/insert.c.o
> [ 58%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/continuous_aggs/job.c.o
> [ 58%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/continuous_aggs/materialize.c.o
> [ 59%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/continuous_aggs/options.c.o
> [ 59%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/continuous_aggs/refresh.c.o
> [ 60%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/continuous_aggs/invalidation.c.o
> [ 60%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/continuous_aggs/invalidation_threshold.c.o
> [ 61%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/relinfo.c.o
> make[1]: *** [CMakeFiles/Makefile2:1011: src/CMakeFiles/timescaledb.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 61%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/estimate.c.o
> [ 62%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/fdw.c.o
> [ 62%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/fdw_utils.c.o
> [ 63%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/modify_plan.c.o
> [ 63%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/modify_exec.c.o
> [ 64%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/scan_plan.c.o
> [ 64%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/scan_exec.c.o
> [ 65%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/deparse.c.o
> [ 65%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/shippable.c.o
> [ 66%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/option.c.o
> [ 66%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/data_node_chunk_assignment.c.o
> [ 67%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/data_node_scan_plan.c.o
> [ 67%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/fdw/data_node_scan_exec.c.o
> [ 68%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/compress_dml/compress_dml.c.o
> [ 68%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/decompress_chunk/decompress_chunk.c.o
> [ 69%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/decompress_chunk/exec.c.o
> [ 69%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/decompress_chunk/planner.c.o
> [ 70%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/decompress_chunk/qual_pushdown.c.o
> [ 70%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/gapfill/gapfill.c.o
> [ 71%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/gapfill/planner.c.o
> [ 71%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/gapfill/exec.c.o
> [ 72%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/gapfill/locf.c.o
> [ 72%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/nodes/gapfill/interpolate.c.o
> [ 73%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/async.c.o
> [ 73%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/connection.c.o
> [ 74%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/connection_cache.c.o
> [ 74%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/cursor_fetcher.c.o
> [ 75%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/data_fetcher.c.o
> [ 75%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/data_format.c.o
> [ 76%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/dist_txn.c.o
> [ 76%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/dist_commands.c.o
> [ 77%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/dist_copy.c.o
> [ 77%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/dist_ddl.c.o
> [ 78%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/row_by_row_fetcher.c.o
> [ 78%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/stmt_params.c.o
> [ 79%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/tuplefactory.c.o
> [ 79%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/txn.c.o
> [ 80%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/txn_store.c.o
> [ 80%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/txn_id.c.o
> [ 81%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/txn_resolve.c.o
> [ 81%] Building C object tsl/src/CMakeFiles/timescaledb-tsl.dir/remote/utils.c.o
> [ 82%] Linking C shared module timescaledb-tsl-2.0.1.so
> [ 82%] Built target timescaledb-tsl
> make: *** [Makefile:149: all] Error 2

**Comment by svenklemm** [comment] 2021-01-29 08:05
By default we build with warnings as errors, it should build fine with that disabled
```
./bootstrap -DWARNINGS_AS_ERRORS=OFF
```

**Comment by mkindahl** [comment] 2021-01-29 08:38
Thanks for reporting an issue on this @nkukard! This is a duplicate of #2770, so I'll close this issue because we will address the problem under the hat of #2770. We will address this in the near future.

**Closed by mkindahl** 2021-01-29 08:38 UTC
Labels: build
