### ISSUE TITLE
CREATE MATERIALIZED VIEW WITH timescaledb.continuous will throw Segmentation fault

### ISSUE THREAD

**Issue by jasperchen912** [timescale/timescaledb#2815] opened 2021-01-13 02:55 UTC
**Relevant system information:**
 - OS: [Centos 7]
 - PostgreSQL version 11.10
 - TimescaleDB version 2.0
 - Installation method: yum install

**Describe the bug**
While executing the sql
```sql
CREATE MATERIALIZED VIEW view_a
WITH (timescaledb.continuous) AS
SELECT time_bucket('10 minutes', timestamp) + '10 minutes' as timestamp, cast(sum(cd) as int) as cd,
tj, lt, ml, oi,
cast(count(cd) as int) as cd
FROM table_1
GROUP BY time_bucket('10 minutes', timestamp), lt, ml, oi, tj;
```

**To Reproduce**
1. ddl
```sql
CREATE TABLE mdd
(
mi varchar default 'mdd',
timestamp timestamp not null,
lt varchar (30),
ml varchar (30),
oi varchar (61),
type varchar (30),
cd integer not null,
cst timestamp,
li varchar,
tj integer,
mlt timestamp,
unique (mi,timestamp,lt,ml,oi,type,cd,li)
);
```
2. execute sql
```sql
CREATE MATERIALIZED VIEW view_a
WITH (timescaledb.continuous) AS
SELECT time_bucket('10 minutes', timestamp) + '10 minutes' as timestamp, cast(sum(cd) as int) as cd,
tj, lt, ml, oi,
cast(count(cd) as int) as cd
FROM mdd
GROUP BY time_bucket('10 minutes', timestamp), lt, ml, oi, tj;
```
3. See error
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

```
2021-01-11 07:53:13.098 GMT [14417] LOG:  TimescaleDB background worker launcher connected to shared catalogs
2021-01-11 07:58:07.379 GMT [14003] LOG:  server process (PID 15048) was terminated by signal 11: Segmentation fault
2021-01-11 07:58:07.379 GMT [14003] DETAIL:  Failed process was running: CREATE MATERIALIZED VIEW view_a
WITH (timescaledb.continuous) AS
SELECT time_bucket('10 minutes', timestamp) + '10 minutes' as timestamp, cast(sum(cd) as int) as cd,
tj, lt, ml, oi,
cast(count(cd) as int) as cd
FROM mdd
GROUP BY time_bucket('10 minutes', timestamp), lt, ml, oi, tj;
2021-01-11 07:58:07.379 GMT [14003] LOG:  terminating any other active server processes
2021-01-11 07:58:07.379 GMT [14435] WARNING:  terminating connection because of crash of another server process
2021-01-11 07:58:07.379 GMT [14435] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-01-11 07:58:07.379 GMT [14435] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-01-11 07:58:07.379 GMT [14414] WARNING:  terminating connection because of crash of another server process
2021-01-11 07:58:07.379 GMT [14414] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-01-11 07:58:07.379 GMT [14414] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-01-11 07:58:07.380 GMT [14433] WARNING:  terminating connection because of crash of another server process
2021-01-11 07:58:07.380 GMT [14433] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-01-11 07:58:07.380 GMT [14433] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-01-11 07:58:07.381 GMT [14003] LOG:  archiver process (PID 14415) exited with exit code 1
2021-01-11 07:58:07.382 GMT [15120] FATAL:  the database system is in recovery mode
2021-01-11 07:58:07.389 GMT [14003] LOG:  all server processes terminated; reinitializing
```

**Comment by k-rus** [comment] 2021-01-19 08:18
@jasperchen912 I tried to reproduce this issue, but without success. Few questions:
- The materialized view above gives an error `column "cd" specified more than once`. It would be nice to see the view, which triggers the crash
- How do you create the hypertable? It is not in the above description.
- Is the hypertable populated with data? I would expect so. Can the repro updated with the data insertion statements?
- Was it clean installation of TimescaleDB or was it updated from an early version?
- Do you have a crash dump? Can you provide the stack trace?

This issue looks similar to https://github.com/timescale/timescaledb/issues/2616, which was fixed.

**Comment by mkindahl** [comment] 2021-03-03 14:26
Closing issues since it is not reproducible and we do not have stack trace or log that we can work from.

**Closed by mkindahl** 2021-03-03 14:26 UTC
Labels: bug, continuous-aggs, need-more-info, segfault
