### ISSUE TITLE
[Bug]: Losing storage space on failed decompress_chunk

### ISSUE THREAD

**Issue by Andi2405** [timescale/timescaledb#5036] opened 2022-11-28 21:40 UTC
### What type of bug is this?

Other

### What subsystems and features are affected?

Compression, Platform/OS

### What happened?

When decompressing chunks fails e.g. due to deadlocks (which I do not know why they would come up, but they happen) or some other error, the already consumed storage space is not freed up. Because I needed several attempts to successfully decompress, my storage space was used up completely. I tried to use `VACUUM FULL` but it did not help at all. Still searching for a way to get my storage back.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.6

### What operating system did you use?

AlmaLinux 8.7

### What installation method did you use?

dnf/yum

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Tell me, what I should look for and I will add it.
```

### How can we reproduce the bug?

Attempt to decompress a chunk (with decompress_chunk) and produce a deadlock or do it on a system that does not have enough storage space for the decompressed chunk. So the decompression will fail but the already extended usage of storage will stay.

**Comment by Andi2405** [comment] 2022-11-28 21:57
Update: My deadlocks seem to be produced by some continuous aggregate refresh policy which refreshes totally different timestamps, which should be handled by totally different chunks.

**Comment by mkindahl** [comment] 2022-11-29 10:43
@Andi2405 Thanks for filing the issue. We're missing enough information to actually be able to debug this issue. Bugs in continuous aggregates can be at many different levels and to debug this we need to know how it was constructed. For starters, can you add a reproducible case for this issue, preferably as a sequence of statements to execute, or at least the definition of the continuous aggregate and the queries that you execute.

**Comment by sb230132** [comment] 2022-12-06 12:15
This is a duplicate of #4578

**Comment by Andi2405** [comment] 2022-12-09 15:17
Thanks for providing more information @sb230132 !

> Increase in storage space is due to dead tuples which are not cleaned up when compression/decompression fails. 

Is there a way to manually clean those dead tuples? It would be nice to be able to free up the storage space at least manually until this is fixed. 

> However patch for this issue can be a saviour https://github.com/timescale/timescaledb/issues/4610 
> PR associated with this issue will allow compression policy to continue even when there is an error compressing/decompressing a chunk.

Would continuing on errors fill up the storage space much faster if errors occur continuously or would it avoid dead tuples in the first place? I assume it would also work outside of compression policies like with manual compress_chunk/decompress_chunk. Is that correct?

**Comment by WalkerWalker** [comment] 2022-12-10 01:19
Not sure if it would work,  I have encountered the same problem and solved by

To remove incorrectly large index of a chunk
```
reindex table _timescaledb_internal._hyper_11_197_chunk
```
and if the chunk size is still incorrectly big
```
vacuum _timescaledb_internal._hyper_11_197_chunk
```

replacing `_hyper_11_197_chunk` with your chunk name of course.

**Comment by Andi2405** [comment] 2022-12-11 12:33
Thanks @WalkerWalker !

As I said I already tried `VACUUM FULL` but directly after a run of decompress_chunk failed and it did nothing to the used storage space. In the mean time I was able to decompress all the chunks and now it works really well. It freed about half of the database size in space. Although adding the `FULL` will exclusively lock the table (which is chunk by chunk I guess). So this might not be a solution for a all-time-load database. 

I was able to get even more space back as I noticed that the *pg_wal* folder was pretty large on my replication master. Because one of my replica servers has less storage space to play with, the replica database died. So the master stored everything the replica did not get. After fixing the replica the *pg_wal* folder shrank to a minimum. 

Before I did those two fixes, the database size was about 2.5 TB and now it is about 260 GB! If someone still thought this issue is minor...

I will try `REINDEX TABLE` in the next few days as well.

**Comment by sb230132** [comment] 2022-12-12 05:23
> Thanks for providing more information @sb230132 !
> 
> > Increase in storage space is due to dead tuples which are not cleaned up when compression/decompression fails.
> 
> Is there a way to manually clean those dead tuples? It would be nice to be able to free up the storage space at least manually until this is fixed.
>>> Please run VACUUM on specific chunks to reclaim space. If you still dont see storage space being freed, please run VACUUM VERBOSE to get more details to get some idea on why dead tuples cannot be reclaimed. Mostly it should be related to some other long pending transactions holding to those dead tuples.
> 
> > However patch for this issue can be a saviour #4610
> > PR associated with this issue will allow compression policy to continue even when there is an error compressing/decompressing a chunk.
> 
> Would continuing on errors fill up the storage space much faster if errors occur continuously or would it avoid dead tuples in the first place? 
>>> While continuing on errors, dead tuples are left uncleaned which results filling up the storage space faster.

> I assume it would also work outside of compression policies like with manual compress_chunk/decompress_chunk. Is that correct?
>>> Yes, correct.

**Comment by sb230132** [comment] 2022-12-12 05:25
Hi @Andi2405 
If your decompress_chunk operation was part of a transaction and if this transaction was not committed or rollbacked yet,
then VACUUM will not clean up dead tuples. Can you please run VACUUM VERBOSE and share the details for me to understand more on why VACUUM does not solve the issue.

**Comment by WalkerWalker** [comment] 2022-12-12 07:53
@sb230132 

Speaking of properly closing the transaction when exception is raised,  what is the right way to do so?  I encounter with this extra dead tuples taking space several times already and I am sure there is something I don't do right.  For now my sqlalchemy code looks like the following.  

```
class TsdbSessionFactory():
    def __init__(self, url):
        self.engine = create_engine(
            url=url,
        )

        self.session_maker = sessionmaker(
            autocommit=true,
            autoflush=true,
            bind=self.engine,
        )

    def build(self) -> TsdbSessionMaker:
        return TsdbSessionMaker(
            engine=self.engine,
            session_maker=self.session_maker,
        )

class TsdbSessionMaker:
    def __init__(self, engine, session_maker):
        self.engine = engine
        self.session_maker = session_maker

    @property
    def session(self):
        return TsdbSession(
            session=self.session_maker(),
        )

class TsdbSession:
    def __init__(self, session: Session):
        self.session = session
        self._transaction = None

    def __enter__(self):
        self._transaction = self.session.begin()
        self._transaction.__enter__()
        return self.session

    def __exit__(self, exc_type, exc_val, exc_tb):
        self._transaction.__exit__(exc_type, exc_val, exc_tb)
        self._transaction = None
```

```
url = url_from_config()
tsdb_session_maker = TsdbSessionFactory(url).build()
try:
    with tsdb_session_maker.session as session
        session.execute(f"select decompress_chunk('_timescaledb_internal._hyper_11_197_chunk', True);")
except OptionalError:
    print("deadlock detected error caught here")
```

**Comment by sb230132** [comment] 2022-12-13 06:21
Hi @WalkerWalker 
Iam not much familiar with sqlalchemy. What i read is that if you have nested transactions and when an exception is raised only outer most transaction is rollbacked. May be you can try something like below as described in 
https://docs.sqlalchemy.org/en/20/orm/session_transaction.html#explicit-begin
```
Session = sessionmaker(bind=engine)
session = Session()
session.begin()
try:
    item1 = session.get(Item, 1)
    item2 = session.get(Item, 2)
    item1.foo = "bar"
    item2.bar = "foo"
    session.commit()
except:
    session.rollback()
    raise
```

Also what does this line do in TsdbSession::enter() ?
self._transaction.__enter__()

**Comment by WalkerWalker** [comment] 2022-12-13 08:50
I simplified quite a lot and here is the new code gist.  Would it make more sense?  Essentially the session is configured to be autocommit and autoflush.  I don't want to change it to manually commit.

Multiple sessions running the following code will lead to deadlock (separate issue [here](https://github.com/timescale/timescaledb/issues/5069) and it is now solved with an alternative). I can indeed catch the exception.  Problem/Question is whether I can should do anything in the catching block, in order to prevent losing disk space caused by decompression failure.

```
    url = url_from_config()

    engine = create_engine(url=url)
    session_maker = sessionmaker(
        bind = engine,
        autocommit=True,
        autoflush=True,
    )

    try:
        with session_maker.begin() as session:
            session.execute(
                """
                SELECT tableoid::regclass FROM sensor_data
                  WHERE time < '2022-11-18' AND time > '2022-11-17'
                  GROUP BY tableoid;
                """
            )
            session.execute("""select decompress_chunk('_timescaledb_internal._hyper_11_197_chunk', True);""")

    except OperationalError as e:
        print(f"caught OperationalError with origin error {e.orig.__class__} {e.orig}")
```

**Comment by sb230132** [comment] 2022-12-13 10:04
In catching block you can run VACUUM like below.
```
except OperationalError as e:
session.execute(
                """
                VACUUM _timescaledb_internal._hyper_11_197_chunk;
                """
            )
```

**Comment by sb230132** [comment] 2022-12-19 04:44
@WalkerWalker If you are ok with the work around can we close the issue ?

**Comment by WalkerWalker** [comment] 2022-12-19 10:56
yup!  Thank you for the help.

**Comment by svenklemm** [comment] 2022-12-21 19:15
The next version will also change this behaviour and no longer disable autovacuum on chunks and therefor postgres will clean up space from failed decompress operations

**Closed by svenklemm** 2022-12-21 19:15 UTC
Labels: bug, compression

**Comment by WalkerWalker** [comment] 2022-12-21 19:19
in 2.9.0?

**Comment by svenklemm** [comment] 2022-12-21 22:47
in 2.10
