### ISSUE TITLE
Cannot extract attribute from empty tuple slot

### ISSUE THREAD

**Issue by optijon** [timescale/timescaledb#1729] opened 2020-03-07 00:01 UTC
- OS: OSX and Timescale cloud
 - PostgreSQL version (output of `postgres --version`):  11.7
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.0
 - Installation method: Docker for the local install

I'm trying to execute the following (simplified) query on my local install and on timescale cloud. Both database instances have the same data. The `prev` query has been replaced for simplicity.
```
          SELECT
            time_bucket_gapfill( '5 minutes', timestamp) AS bucket,
            locf(
              avg((sparse_values->>'sparse1')::DOUBLE PRECISION),
              treat_null_as_missing => true,
              prev => (select (1::DOUBLE PRECISION))
              )
           AS "sparse1"
          FROM data_point_values values
          WHERE values.timestamp >= '2020-03-06 21:45:00Z'::timestamptz
          AND values.timestamp <= '2020-03-06 21:49:59Z'::timestamptz
          GROUP BY bucket
```
The schema of `data_point_values` is as follows.
```
timestamp: timestamptz
raw_values: JSONB
sparse_values: JSONB
```
There is a value set for `sparse1` on January 1st 1988. All other sparse values are set to `{}`.

Running the query on the remote machine give me an error: `Cannot extract attribute from empty tuple slot`.

Running this same query locally did give me the error until I ran `VACUUM ANALYZE data_point_values`, after which, the query executed successfully. 

Remotely, depending on the date range, I can get results to appear. I tried running `VACUUM` by itself, with `ANALYZE`, `FREEZE` and `FULL`, with no luck. I copied the table over to a new table, dropped and recreated the hypertable and copied the data back but the error persists, this time with more frequency when changing date selections.

One thing I've noted, the query will run successfully if you change `treat_null_as_missing` to false. Toggling this setting, the query will return `null` on previously failing queries, but `1` on previously succeeding queries.

I have not been able to reproduce this issue in any deterministic way, the few simple examples I came up with all succeeded, but I'm happy to provide any additional information. 

Thanks!

**Comment by svenklemm** [comment] 2020-03-07 08:11
Having a self-contained script to reproduce the error would be really helpful here. Is the prev expression relevant to trigger the bug or do you still get the bug without it?

**Comment by optijon** [comment] 2020-03-09 18:40
I'm only seeing the bug with both `prev` set and `treat_null_as_missing => true`. 

You can try and reproduce this locally by downloading and importing the following data set: 
https://storage.cloud.google.com/public_oe/data_point_values_2.sql
Then running the following script:
https://storage.cloud.google.com/public_oe/test_script.sql

Using this script, I'm seeing the error consistently on timescale cloud.

One other interesting point, if I delete data not related to the station I'm querying, the query works as expected. Let me know if there's anything else I can do to help. Thanks!

**Comment by svenklemm** [comment] 2020-03-10 20:08
@optijon i cannot reproduce the error with the supplied script, neither locally nor in cloud. The script runs without errors for me.

**Comment by jflambert** [comment] 2020-03-16 19:03
It's hitting me right now as well! It has nothing to do with using `prev` and `treat_null_as_missing` together, rather it has to do with your `GROUP BY` lacking an extra dimension. I'll try to put up an example.

**Comment by jflambert** [comment] 2020-03-16 19:13
> You can try and reproduce this locally by downloading and importing the following data set:
> https://storage.cloud.google.com/public_oe/data_point_values_2.sql
> Then running the following script:
> https://storage.cloud.google.com/public_oe/test_script.sql

I can easily replicate the bug with your dataset and script so thanks for saving me the effort of having to anonymise my own ;)

I have the fix for you, add `station_id` to the `GROUP BY`

@svenklemm what would you need from me in terms of replication steps?

**Comment by optijon** [comment] 2020-03-16 19:15
Adding `station_id` to the `GROUP BY` clause indeed fixed the issue. Thanks @jflambert!!!

**Comment by optijon** [comment] 2020-03-16 21:24
Just as a followup in case anyone has the same issue, we've removed the `station_id` dimension from our hypertable so that we can continue development. While adding the `station_id` to the `GROUP BY` clause does get us past the immediate tuple error, it changes the results of our query and is not a sufficient fix in our case.

**Comment by optijon** [comment] 2020-03-18 21:46
A further update on this issue. After removing the `station_id` dimension this issue is still cropping up in our dev environment. Adding `station_id` to the `GROUP BY` clause still fixes the error but gives us incorrect results. 

As far as I can tell, it only seems to be impacting queries with using `locf` with `treat_missing_as_null`. Adjusting the query's date ranges, `prev` locf query, and `treat_missing_as_null` parameter,  seem to have an effect on if the error happens or not but I haven't been able to discern any sort of pattern.

**Comment by svenklemm** [comment] 2020-04-06 23:06
@jflambert a selfcontained script to reproduce the error in a new database would be helpful, i get no errors when running the supplied scripts.

**Comment by svenklemm** [comment] 2020-06-01 15:03
Closing this since this seems to be the same issue as #1937

**Closed by svenklemm** 2020-06-01 15:03 UTC
Labels: bug, core, need-more-info, severity-p1
