### ISSUE TITLE
[Bug]: [XX000] ERROR: ORDER/GROUP BY expression not found in targetlist

### ISSUE THREAD

**Issue by Claud** [timescale/timescaledb#6459] opened 2023-12-21 18:13 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Query executor

### What happened?

When executing a normal query with guppings, an error is thrown. `[XX000] ERROR: ORDER/GROUP BY expression not found in targetlist`. 

Example (With an = sign instead of IN, the code doesn't work either):

```
SELECT ticker_id, Last(date, date) AS date, Last(close, date) AS close
FROM prices_2
WHERE (date <= '2005-09-19'::DATE AND ticker_id in (3))
GROUP BY ticker_id
```

or 

```
SELECT ticker_id, max(date, date) AS date
FROM prices_2
WHERE (date <= '2005-09-19'::DATE AND ticker_id in (3))
GROUP BY ticker_id
```
If I remove the aggregate functions, the query works fine. 

```
SELECT ticker_id
FROM prices_2
WHERE (date <= '2005-09-19'::DATE AND ticker_id in (3))
GROUP BY ticker_id
```

If I add more id's to the conditions, the query works the same way. Note, below 0 is not an existing id, just a made up number to get around the query execution error.

```
SELECT ticker_id, Last(date, date) AS date, Last(close, date) AS close
FROM prices_2
WHERE (date <= '2005-09-19'::DATE AND ticker_id in (3, 0))
GROUP BY ticker_id
```

### TimescaleDB version affected

2.13.0

### PostgreSQL version used

16.1

### What operating system did you use?

Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
[XX000] ERROR: ORDER/GROUP BY expression not found in targetlist
```

### How can we reproduce the bug?

```bash
DO LANGUAGE plpgsql
$tran$
    DECLARE
        _ret text;
    BEGIN

        create table prices_2
        (
            ticker_id                 bigint                   not null,
            date                      date                     not null,
            date_time                 timestamp with time zone not null,
            open                      numeric                  not null,
            high                      numeric                  not null,
            low                       numeric                  not null,
            close                     numeric                  not null,
            adj_close                 numeric,
            volume                    bigint                   not null,
            close_sma_20              numeric,
            close_sma_50              numeric,
            close_sma_100             numeric,
            close_sma_200             numeric,
            close_sma_20_200_kpi      numeric,
            closed_3_months_ago       numeric,
            yield_3_months_in_percent numeric,
            close_sma_10              numeric,
            close_sma_20_100_kpi      numeric,
            close_sma_10_200_kpi      numeric,
            close_sma_10_100_kpi      numeric,
            close_sma_50_200_kpi      numeric,
            primary key (ticker_id, date)
        );

        create index prices_2__date_desc__ix
            on prices_2 (date desc);

        create index prices_2__ticker_id__where_closed_3_months_ago_null
            on prices_2 (ticker_id)
            where ((closed_3_months_ago IS NULL) OR (yield_3_months_in_percent IS NULL));

        create index prices_2__ticker_id__where_all_sma_null
            on prices_2 (ticker_id)
            where ((close_sma_10 IS NULL) OR (close_sma_20 IS NULL) OR (close_sma_50 IS NULL) OR
                   (close_sma_100 IS NULL) OR
                   (close_sma_200 IS NULL));

        SELECT *
        INTO _ret
        FROM create_hypertable('prices_2', 'date', 
                               chunk_time_interval => INTERVAL '1 year');
        RAISE NOTICE 'Table A Hypertable created %', _ret;

        insert into prices_2 (ticker_id, date, date_time, open, high, low, close, adj_close, volume, close_sma_20, close_sma_50, close_sma_100, close_sma_200, close_sma_20_200_kpi, closed_3_months_ago, yield_3_months_in_percent, close_sma_10, close_sma_20_100_kpi, close_sma_10_200_kpi, close_sma_10_100_kpi, close_sma_50_200_kpi)
        values  (3, '1998-12-21', '1998-12-21 08:00:00.000000 +03:00', 1188.030029296875, 1210.8800048828125, 1188.030029296875, 1202.8399658203125, null, 744800000, null, null, null, null, null, null, null, null, null, null, null, null),
                (3, '1998-12-22', '1998-12-22 08:00:00.000000 +03:00', 1202.8399658203125, 1209.219970703125, 1192.719970703125, 1203.5699462890625, null, 680500000, null, null, null, null, null, null, null, null, null, null, null, null),
                (3, '1998-12-23', '1998-12-23 08:00:00.000000 +03:00', 1203.5699462890625, 1229.8900146484375, 1203.5699462890625, 1228.5400390625, null, 697500000, null, null, null, null, null, null, null, null, null, null, null, null),
                (3, '1998-12-24', '1998-12-24 08:00:00.000000 +03:00', 1228.5400390625, 1229.719970703125, 1224.8499755859375, 1226.27001953125, null, 246980000, null, null, null, null, null, null, null, null, null, null, null, null),
                (3, '1998-12-28', '1998-12-28 08:00:00.000000 +03:00', 1226.27001953125, 1231.52001953125, 1221.1700439453125, 1225.489990234375, null, 531560000, null, null, null, null, null, null, null, null, null, null, null, null);

    END;
$tran$;

```

```
SELECT ticker_id, Last(date, date) AS date, Last(close, date) AS close
FROM prices_2
WHERE (date <= '2005-09-19'::DATE AND ticker_id in (3))
GROUP BY ticker_id
```
```

**Comment by jnidzwetzki** [comment] 2023-12-21 20:49
Hi @Claud,

Thank you for opening this bug report and the detailed steps to reproduce the issue. I was able to reproduce the problem on my local system. This problem is caused by a known bug in TimescaleDB 2.13.0 on PG 16. It has already been fixed in this pull request https://github.com/timescale/timescaledb/pull/6377, which will be part of TimescaleDB 2.13.1.

In our current development version, the query can be executed without any error:

```sql
test2=# SELECT VERSION();
                                              version                                              
---------------------------------------------------------------------------------------------------
 PostgreSQL 16.0 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
(1 row)

test2=# SELECT ticker_id, Last(date, date) AS date, Last(close, date) AS close
FROM prices_2
WHERE (date <= '2005-09-19'::DATE AND ticker_id in (3))
GROUP BY ticker_id;
 ticker_id |    date    |       close       
-----------+------------+-------------------
         3 | 1998-12-28 | 1225.489990234375
(1 row)
```

**Closed by jnidzwetzki** 2023-12-21 20:49 UTC
Labels: bug
