### ISSUE TITLE
Build issue on Alpine Linux

### ISSUE THREAD

**Issue by jayadevanm** [timescale/timescaledb#2882] opened 2021-01-29 10:05 UTC
I am trying to build TimescaleDB from source. on Alpine Linux. 
Alpine Linux version - 3.12.3
PostgreSQL Version - 12.5
TimescaleDB Version - 2.0.1
The bootstrap command works with just a couple of warnings.
```
./bootstrap -DREGRESS_CHECKS=OFF
CMake Warning at CMakeLists.txt:316 (message):
  clang-format version 7 or 8 required
CMake Warning at CMakeLists.txt:325 (message):
  clang-format is disabled (can't find clang-format or docker)
```
But build fails 
```
[ 13%] Building C object src/CMakeFiles/timescaledb.dir/agg_bookend.c.o
[ 14%] Building C object src/CMakeFiles/timescaledb.dir/func_cache.c.o
[ 14%] Building C object src/CMakeFiles/timescaledb.dir/cache.c.o
[ 15%] Building C object src/CMakeFiles/timescaledb.dir/cache_invalidate.c.o
[ 15%] Building C object src/CMakeFiles/timescaledb.dir/catalog.c.o
In file included from /usr/include/postgresql/server/postgres.h:46,
                 from /root/sw/timescaledb/src/catalog.c:6:
In function 'catalog_database_info_init',
    inlined from 'ts_catalog_database_info_get' at /root/sw/timescaledb/src/catalog.c:364:3:
/root/sw/timescaledb/src/catalog.c:344:2: error: 'strncpy' specified bound 64 equals destination size [-Werror=stringop-truncation]
  344 |  StrNCpy(info->database_name, get_database_name(MyDatabaseId), NAMEDATALEN);
      |  ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [src/CMakeFiles/timescaledb.dir/build.make:135: src/CMakeFiles/timescaledb.dir/catalog.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1012: src/CMakeFiles/timescaledb.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```
Could you please take a look?

**Comment by svenklemm** [comment] 2021-01-29 10:37
This should work:
```
./bootstrap -DREGRESS_CHECKS=OFF -DWARNINGS_AS_ERRORS=OFF
```

**Comment by mkindahl** [comment] 2021-01-29 10:49
This is a duplicate of #2770 so closing this issue.

**Closed by mkindahl** 2021-01-29 10:49 UTC
