### ISSUE TITLE
[Bug]: Cannot find function during refresh of continuous aggregate

### ISSUE THREAD

**Issue by sylvainv** [timescale/timescaledb#5504] opened 2023-03-28 20:22 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

So before I had timescale 2.7. This used to work without issue before I updated to 2.10.0

I have a CAGG which is using functions that I have defined.

```PLPGSQL
CREATE MATERIALIZED VIEW cagg(time, unit_uuid, speed, count )
WITH (timescaledb.continuous,
    timescaledb.materialized_only = TRUE,
    timescaledb.create_group_indexes = TRUE
) AS
  SELECT time_bucket('1 hour', time),
    unit_uuid,
    range_speed(data->>'speed', 'mph') as range_speed,
    count(*)
FROM speed
GROUP BY 1, 2, 3;

CREATE OR REPLACE FUNCTION range_speed(value text, output_unit text) RETURNS smallint
    LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
    AS $$
DECLARE _value SMALLINT;
BEGIN
    _value = convert_speed(value, output_unit);
    return CASE
        WHEN _value >= 5 AND _value < 10
        THEN 5
        WHEN _value >= 10 AND _value < 15
        THEN 10
        WHEN _value >= 15 AND _value < 20
        THEN 15
        WHEN _value >= 20
        THEN 20
        ELSE 0
    END;
END;
$$;

CREATE OR REPLACE FUNCTION convert_speed(value integer, output_unit text) RETURNS integer
    LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
    AS $$
BEGIN
    IF output_unit = 'mph' THEN
        -- FLOOR! and nothing else, no round, no ceiling
        RETURN FLOOR(value::NUMERIC(7,4) / 1.60934);
    ELSIF output_unit = 'kmh' THEN
        RETURN value::int;
    ELSE
        RAISE EXCEPTION 'Cannot convert value to unknown unit %, allowed values are kmh and mph', unit;
    END IF;
END;
$$;

```

Notice how I use function `range_speed` which in turns uses `convert_speed`. `public` schema is in my search_path. For that matter, the call to `range_speed` is done correctly although I didn't specify the schema. But the call to `convert_speed` is failing because it says the function doesn't exist. 

It used to work correctly with version 2.7. Adding the schema explicitly to call `public.convert_speed` in the `range_speed` function definition fixes the problem.

I don't understand how the call to `range_speed` works fine but not the call to `convert_speed`. Since they are both ( by default ) defined as security invoker, it should be the same user, with the same search path calling the functions ?

### TimescaleDB version affected

2.10.0

### PostgreSQL version used

12.11

### What operating system did you use?

Debian 10.13

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Amazon Web Services (AWS)

### Relevant log output and stack trace

```bash
select * from timescaledb_information.job_errors ;
   1117 | _timescaledb_internal | policy_refresh_continuous_aggregate | 32128 | 2023-03-28 19:24:35.746317+00 | 2023-03-28 19:24:36.839091+00 | 42883      | function convert_speed(text, text) does not exist. No function matches the given name and argument types. You might need to add explicit type casts.
```

### How can we reproduce the bug?

```sql
CREATE OR REPLACE FUNCTION test_b(value integer) RETURNS integer
    LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
    AS $$
BEGIN
    return value * 10;
END;
$$;

CREATE OR REPLACE FUNCTION test_a(value integer) RETURNS integer
    LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
    AS $$
BEGIN
    return test_b(value);
END;
$$;

create table test(time timestamptz not null, car_id integer not null, speed int not null default 0);
SELECT create_hypertable('test', 'time');

CREATE MATERIALIZED VIEW test_cagg (time, car_id, avg_speed_10 )
WITH (timescaledb.continuous,
    timescaledb.materialized_only = TRUE,
    timescaledb.create_group_indexes = TRUE
) AS
  SELECT time_bucket('1 minute', time), car_id, avg(test_a(speed)) FROM test GROUP BY 1, 2 WITH NO DATA;

SELECT add_continuous_aggregate_policy('test_cagg',
     start_offset => INTERVAL '2 hours',
     end_offset => INTERVAL '1 hour',
     schedule_interval => INTERVAL '1 minute');

insert into test values(current_timestamp, 1, 2);
insert into test values(current_timestamp, 1, 3);
insert into test values(current_timestamp, 1, 4);

CALL refresh_continuous_aggregate('test_cagg', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP);
```

**Comment by konskov** [comment] 2023-03-29 08:31
hi @sylvainv thank you for the detailed reproduction steps in the bug report. The issue you are facing is due to [this commit](https://github.com/timescale/timescaledb/pull/5259/commits/014b40fb7e8d59087cf1c1988a68dd1979f86cb3). Glad to hear that you already have a solution. Actually it is one of the solutions we would recommend as well, to fully schema-qualify your function calls. 
Alternatively, you could specify an explicit search path when defining function `test_a`:
```
CREATE OR REPLACE FUNCTION test_a(value integer) RETURNS integer
    LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
    AS $$
BEGIN
    return test_b(value);
END;
$$ SET search_path TO public;
```

I will go ahead and close this issue, but please feel free to ask us to reopen it if your refresh policies are not working as expected or if there are any further unresolved questions. Thank you!

**Closed by konskov** 2023-03-29 08:31 UTC
Labels: bug
