### ISSUE TITLE
Permisson denied for _timescaledb_cache when exporting with pg_dump

### ISSUE THREAD

**Issue by mx781** [timescale/timescaledb#720] opened 2018-09-15 11:43 UTC
I'm trying to export a database running on Aiven Cloud that has a single hypertable and a few regular tables using `pg_dump` by following the [page in the official docs](https://docs.timescale.com/v1.0/using-timescaledb/backup).

The command I am running looks like this:
`pg_dump 'postgres://avnadmin@<aiven_project>.aivencloud.com:<aiven_port>/<my-db-name>?sslmode=require' -Fc -f my-backup`

The backup command fails with the following messages:
```
pg_dump: [archiver (db)] query failed: ERROR:  permission denied for schema _timescaledb_cache
pg_dump: [archiver (db)] query was: LOCK TABLE _timescaledb_cache.cache_inval_hypertable IN ACCESS SHARE MODE
```

Even after trying to exclude the cache schema, by running the command with `-N`, as so:
`pg_dump 'postgres://avnadmin@<aiven_project>.aivencloud.com:<aiven_port>/<my-db-name>?sslmode=require' -N _timescaledb_cache -Fc -f my-backup`

the same message appears (which seems quite odd). The same error seems to occur on a locally deployed instance, so it doesn't seem to be an Aiven issue. What am I missing?

```
pg_dump (PostgreSQL) 10.3 (Ubuntu 10.3-1.pgdg16.04+1)
PostgreSQL@10.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5), 64-bit
timescaledb@0.11.0
```

P.S. In case this has some impact on the code, I'll note that I intentionally exclude the password from the command and enter it separately when prompted to avoid storing it in the command history.

**Comment by mfreed** [comment] 2018-09-16 17:01
Hi @mx781 can you provide a bit more information about the user permissions with which the hypertable was created/assigned, as well as the permissions with which you ran the `pg_dump` command?

If you could detail exactly how you recreate the problem on the local instance (non-Aiven), would be helpful.  Thanks!

**Comment by martinhale** [comment] 2018-09-19 17:30
Hi @mfreed, I work alongside @mx781 and have also been working on the above.

I was struggling to reproduce the problem locally so reached out to Aiven and I received the following response:

>This is an issue with grants on TimescaleDB extension. TimescaleDB has plans on updating this logic on the upstream, but right now we have implemented a workaround for this. Unfortunately this workaround is only applied to services created after beginning of September. We can retroactively manually apply this to older databases as well as needed.

After they retroactively applied their workaround the issue has been resolved (for us, at least).

Thanks for taking the time to look into it!

**Comment by dianasaur323** [comment] 2018-09-22 02:08
HI @martinhale and @mx781 - we've spoken to Aiven about this before, and it has to do with Timescale requiring more permissions, as they mentioned. We are tracking a fix, but since Aiven has addressed the problem on their end, we don't currently have a timeline yet on when we'll update the logic. That being said, I'm glad this is working for you now! Let's keep this issue open so that we can close it out when we address it on our side.

**Comment by dianasaur323** [comment] 2018-09-22 21:57
Actually, @svenklemm has put in a fix that will go in shortly. Let us know if you see any other issues!

**Closed** 2018-09-26 16:04 UTC
Labels: need-more-info
