### ISSUE TITLE
hypertable_relation_size returns NULL when no data in hypertable

### ISSUE THREAD

**Issue by pedrokost** [timescale/timescaledb#2925] opened 2021-02-10 16:07 UTC
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version (output of `postgres --version`): 12.2
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.4
 - Installation method: apt install

**Describe the bug**

`hypertable_relation_size` returns NULL values (instead of 0) when there is no data in the table.

**To Reproduce**

```
SELECT create_hypertable('test',...)
SELECT * hypertable_relation_size('test')
 hypertable_relation_size 
--------------------------
 (,,,)
(1 row)

INSERT INTO test(...
SELECT * hypertable_relation_size('test')
 hypertable_relation_size 
--------------------------
 (8192,16384,8192,32768)
 (1 row)
```

**Expected behavior**

If the table is empty, I expect it to return 0 for table size.

**Actual behavior**

It returns NULL values

**Comment by erimatnor** [comment] 2021-02-16 15:49
@pedrokost Thank you for this request. I believe this applies also to `hypertable_size` in 2.0.

**Comment by erimatnor** [comment] 2021-02-24 07:55
This is a duplicate of https://github.com/timescale/timescaledb/issues/2871 so closing this issue. Also note that this will likely be addressed in an upcoming 2.x version, so would likely require upgrade to get the fix.

**Closed by erimatnor** 2021-02-24 07:55 UTC
Labels: ui/ux
