### ISSUE TITLE
Indexing & Vacuuming efficient way

### ISSUE THREAD

**Issue by rtpsr** [timescale/timescaledb#1762] opened 2020-03-19 01:10 UTC
I am trying to understand efficient way to index and vacuum TSDB tables on Azure managed PG 11.X running TSDB 1.3.2 version. I have ~2.3 billion rows containing geospatial and timeseries data partitioned by day. Azure defaults to 512MB maintenance_work_mem for 8 core Postgres instance which is kind of low for data of this size and can only go upto ~2GB by setting it before the transaction.

1) If I were to vacuum this parent hypertable, this takes a good amount of time (possibly days). So, what I tried was to run vacuum in parallel on individual chunk tables. It ran in ~10 hours. 

2) Similarly, when I ran geometry gist index on this parent hypertable, it took ~ 48 hours. Is there a easy way for index creation on chunk tables similar to vacuum above. I looked at https://github.com/timescale/timescaledb/pull/1005 but could not infer how to do this. My understanding is that index has to be created on the parent for it to propagate to chunks (I may be wrong). Generally other index creations are also taking good amount of time.

3) Also tsdb creates timeseries index on empty table. Is it a good idea to delete this index before ingesting for speeding up using timescaledb-parallel-copy?

Thanks!

**Comment by mfreed** [comment] 2020-03-19 01:38
Are you doing a lot of updates?  I'm less clear why you need to do full manual vacuums in the first place?  Even if so, what's not working with autovacuum?

**Comment by rtpsr** [comment] 2020-03-19 01:50
It is a one time insert at first and geometry needs to be computed from lat/lngs.  The data gets updated and deleted every quarter. The amount of time for autovacuum seems too big and not clear when that will complete. 

When I created index on the main table, the indexes on most of the chunks has bloat possibly due to the geometry update and autovacuum not triggered. EXPLAIN on a query is giving index scan on some chunks and sequential scan on some chunks for the time column. So, I had to force vacuum to make everything read from index and return the results in a timely manner.

**Comment by mfreed** [comment] 2020-03-19 03:31
Ah, on reading the question closer, I better understand what you are asking.

We don't allow you to create indexes on chunks individually, but you can use this command to prevent unnecessarily locking:

`CREATE INDEX ... WITH (timescaledb.transaction_per_chunk, ...);`

https://docs.timescale.com/latest/api#create_index

**Comment by rtpsr** [comment] 2020-03-19 16:13
Thanks Mike. Do you have any input for 3)?

**Comment by svenklemm** [comment] 2020-10-14 08:13
Regarding 3) yes dropping an index before bulk inserts will make the inserts faster

**Comment by svenklemm** [comment] 2020-10-14 08:13
Closing this since it seems answered. Feel free to reopen if the issue is still relevant.

**Closed by svenklemm** 2020-10-14 08:13 UTC
Labels: question
