### ISSUE TITLE
Add Compression Support for Continuous Aggregates View

### ISSUE THREAD

**Issue by rahulbsw** [timescale/timescaledb#2685] opened 2020-11-25 22:03 UTC
Timescale DB support compression on hypertable. 
Similar if it can support for continuous aggregates view it will help for the view which need to keep data longer time .
```sql
ALTER VIEW measurements_hourly SET (
  timescaledb.compress,
  timescaledb.compress_segmentby = 'device_id'
);

SELECT add_view_compression_policy('measurements_hourly', INTERVAL '7 days');
```

**Comment by mfreed** [comment] 2020-11-25 23:35
Totally agree this is useful (and certainly something we are tracking).

Closing out this issue currently as a duplicate of https://github.com/timescale/timescaledb/issues/2072 

Please leave any comments/discussion on that issue.  Thanks!

**Closed by mfreed** 2020-11-25 23:35 UTC
Labels: Compression, continuous-aggs
