### ISSUE TITLE
Adding column to empty, compressed table

### ISSUE THREAD

**Issue by wrobell** [timescale/timescaledb#1540] opened 2019-11-20 16:58 UTC
It would be nice to allow to add a column to an empty, compressed table (I suspect adding column to a table with data will be more complex and for that separate issue shall be created).

At the moment adding a column results in error
```
$ alter table ts add column x int;
ERROR:  operation not supported on hypertables that have compression enabled`
```

However, there are no chunks, so I hope it is easy to add the feature
```
$ select show_chunks('ts');
 show_chunks 
-------------
(0 rows)
```

**Comment by svenklemm** [comment] 2020-10-12 15:29
Duplicate of #1543

**Closed by svenklemm** 2020-10-12 15:29 UTC
Labels: enhancement
