### ISSUE TITLE
Update/delete of current chunk data blocked during compression of old data (reproducible on test data from official documentation)

### ISSUE THREAD

**Issue by MaximBoguk** [timescale/timescaledb#4432] opened 2022-06-10 10:22 UTC
### What type of bug is this?

Locking issue

### What subsystems and features are affected?

Query planner

### What happened?

PostgreSQL 14.3 standalone server
 timescaledb | 2.7.0
20.04 Ubuntu linux

typical standalone setup and test data loaded from documentation https://docs.timescale.com/getting-started/latest/create-hypertable/ (including https://docs.timescale.com/getting-started/latest/compress-data/ enable compression step).

Now on console 1:
BEGIN;
SELECT compress_chunk(i, if_not_compressed=>true)
  FROM show_chunks('stocks_real_time', older_than => INTERVAL ' 2 weeks') i;
wait...

On console 2 verify row 
explain analyze select * from stocks_real_time where  symbol='SNAP' and time='2022-06-09 11:57:49+00';
                                                                    QUERY PLAN                                                                     
---------------------------------------------------------------------------------------------------------------------------------------------------
 Index Scan using _hyper_1_6_chunk_ix_symbol_time on _hyper_1_6_chunk  (cost=0.28..0.52 rows=1 width=24) (actual time=0.009..0.010 rows=1 loops=1)
   Index Cond: ((symbol = 'SNAP'::text) AND ("time" = '2022-06-09 11:57:49+00'::timestamp with time zone))
 Planning Time: 0.202 ms
all good...

Now try plan update 
explain update stocks_real_time set  day_volume=10 where symbol='SNAP' and time='2022-06-09 11:57:49+00';
^CCancel request sent
ERROR:  canceling statement due to user request
I will be stuck until I commit or rollback compress_chunk in console one.
update itself blocked as well ofcourse.

pg_locks show that compress_chunk took an AccessExclusiveLock on compressed partitions (_timescaledb_internal._hyper_1_1_chunk, _timescaledb_internal._hyper_1_2_chunk, _timescaledb_internal._hyper_1_3_chunk)
but Custom Scan (HypertableModify) plan node trying get RowExclusiveLock lock on partition _timescaledb_internal._hyper_1_1_chunk and of course cannot get it.

As a result during multihour night compression job on prouduction system - every delete/update on fresh uncompressed data getting blocked leading to huge unavoidable downtime.

### TimescaleDB version affected

2.7,0

### PostgreSQL version used

14.3

### What operating system did you use?

Ubuntu 20.04 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
relevant pg_locks content

test=# select relation::regclass,classid,objid,objsubid,virtualtransaction,pid,mode,granted,granted from pg_locks where database=6104614  and (granted=false or mode='AccessExclusiveLock') order by pid,1;
                             relation                             | classid | objid | objsubid | virtualtransaction |   pid   |        mode         | granted | granted 
------------------------------------------------------------------+---------+-------+----------+--------------------+---------+---------------------+---------+---------
 _timescaledb_internal._hyper_1_1_chunk                           |         |       |          | 8/10520713         | 2107216 | RowExclusiveLock    | f       | f
 _timescaledb_internal._hyper_1_1_chunk                           |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 pg_toast.pg_toast_6105229                                        |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 pg_toast.pg_toast_6105229_index                                  |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 _timescaledb_internal._hyper_1_1_chunk_stocks_real_time_time_idx |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 _timescaledb_internal._hyper_1_1_chunk_ix_symbol_time            |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 _timescaledb_internal._hyper_1_2_chunk                           |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 pg_toast.pg_toast_6105237                                        |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 pg_toast.pg_toast_6105237_index                                  |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 _timescaledb_internal._hyper_1_2_chunk_stocks_real_time_time_idx |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 _timescaledb_internal._hyper_1_2_chunk_ix_symbol_time            |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 _timescaledb_internal._hyper_1_3_chunk                           |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 pg_toast.pg_toast_6105245                                        |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 pg_toast.pg_toast_6105245_index                                  |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 _timescaledb_internal._hyper_1_3_chunk_stocks_real_time_time_idx |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
 _timescaledb_internal._hyper_1_3_chunk_ix_symbol_time            |         |       |          | 14/9495213         | 2108052 | AccessExclusiveLock | t       | t
```

### How can we reproduce the bug?

```bash
Load test data as described in https://docs.timescale.com/getting-started/latest/create-hypertable/
enable compression.

On console 1 run compression job:
test=# begin;
BEGIN
test=*# SELECT compress_chunk(i, if_not_compressed=>true)
  FROM show_chunks('stocks_real_time', older_than => INTERVAL ' 2 weeks') i;
             compress_chunk             
----------------------------------------
 _timescaledb_internal._hyper_1_1_chunk
 _timescaledb_internal._hyper_1_2_chunk
 _timescaledb_internal._hyper_1_3_chunk



On console two try run
explain update stocks_real_time set  day_volume=10 where symbol='SNAP' and time='2022-06-09 11:57:49+00';
or
update stocks_real_time set  day_volume=10 where symbol='SNAP' and time='2022-06-09 11:57:49+00';


I will be blocked until commit of compression job TX.
```

**Comment by gayyappan** [comment] 2022-06-15 15:26
Trying to call compress_chunk in 1 big transaction is bad practice. compress_chunk needs an exclusive lock.

If you are doing this manually, note that your code tries to compress EVERY  chunk older than  2 weeks in 1 big transaction. At a minimum, you should commit after every compress_chunk call. (You are also calling compress_chunk even on chunks that are previously compressed).

If you use compression_policy to compress data, it will manage the locking for you and compress only the necessary chunks. Is there a reason that you are not able to use the policy framework?

**Comment by konskov** [comment] 2022-06-16 09:35
It might be worth considering creating smaller chunks. That is expected to decrease the amount of time required to compress a single chunk.

**Comment by MaximBoguk** [comment] 2022-06-16 11:18
Problem that with business point of view - blocking critical updates even for 10 second not acceptable (10 second block = 10 second complete downtime of whole product), there are no maintenance breaks at all. 
And smaller chunk will create tens thousands partitions per year (which from my experience have very bad effect on PostgreSQL query planner).
I found no reference in TimescaleDB manual that it will block current/today chunk updates during automatic or manual compression of older data.

**Comment by MaximBoguk** [comment] 2022-06-16 12:20
Problem that with business point of view - blocking critical updates even for 10 second not acceptable (10 second block = 10 second complete downtime of whole product), there are no maintenance breaks at all. 
And smaller chunk will create tens thousands partitions per year (which from my experience have very bad effect on PostgreSQL query planner).
I found no reference in TimescaleDB manual that it will block current/today chunk updates during automatic or manual compression of older data.

**Comment by konskov** [comment] 2022-06-17 11:09
@MaximBoguk thank you for raising the issue concerning this limitation. It is due to Postgres table inheritance: When doing an `UPDATE`  operation on a table, a `RowExclusiveLock` is taken on all child tables. As chunks are child tables of the parent hypertable, and compression also locks the chunk - child table that is being compressed, the update operation on other chunks will currently block. 
The issue is currently on our roadmap and we will look at it on a priority soon.
Thank you for reporting the lack of documentation on this issue as well, we will be updating our documentation soon.

**Comment by MaximBoguk** [comment] 2022-06-18 19:50
Technically speaking there are no reason to

**Comment by phemmer** [comment] 2022-06-19 05:27
Also just FYI, dup of #2732

**Comment by RafiaSabih** [comment] 2022-07-26 10:57
This is a limitation for now and not a bug. Hence, closing.

**Closed by RafiaSabih** 2022-07-26 10:57 UTC
Labels: bug, limitation, compression, locking

**Comment by phemmer** [comment] 2022-07-26 12:47
We still have #2732 which also tracks the issue, so I'm not going to complain too loudly, but just because it was filed as a bug when it's technically not doesn't mean it's not undesired behavior.  
Are we supposed to re-open closed bug requests as feature requests and lose the history? Why not just change the label?

**Comment by maierru** [comment] 2022-07-26 21:00
"Build powerful data-intensive applications" they said :(((

**Comment by erimatnor** [comment] 2022-09-23 08:38
Thanks for all the valuable input on this issue. It is definitely something are looking into, and issue https://github.com/timescale/timescaledb/issues/2732 remains open. And, as stated earlier, the blocking behavior is a known limitation that we want to address. We often introduce features that bring benefits to users even though we know there are limitations. Hearing the community's feedback is valuable to us as that helps us prioritize on what to work on, including addressing limitations like this. Let's keep tracking the issue in https://github.com/timescale/timescaledb/issues/2732.
