### ISSUE TITLE
[Bug]: run_job fail in python

### ISSUE THREAD

**Issue by Kirill-Ulich** [timescale/timescaledb#6251] opened 2023-10-30 13:27 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

I'm working with TSDB via python. I run the backfill process but get an error when I execute run_job function. But if I run it through the psql-console, I don't get any errors.

### TimescaleDB version affected

2.12.0

### PostgreSQL version used

14.9

### What operating system did you use?

Ubuntu 20.04

### What installation method did you use?

Source

### What platform did you run on?

Timescale Cloud

### Relevant log output and stack trace

```bash
psycopg2.errors.InvalidTransactionTermination: invalid transaction termination
CONTEXT:  PL/pgSQL function _timescaledb_functions.policy_compression_execute(integer,integer,anyelement,integer,boolean,boolean) line 86 at COMMIT
SQL statement "CALL _timescaledb_functions.policy_compression_execute(
        job_id, htid, lag_value::INTERVAL,
        maxchunks, verbose_log, recompress_enabled
      )"
PL/pgSQL function _timescaledb_functions.policy_compression(integer,jsonb) line 51 at CALL
```

### How can we reproduce the bug?

```bash
with psycopg2.connect(<url_string>) as conn:
    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

    job_id = <job_id>

    logger.info('Pause compression')
    pause_compression_query = f"SELECT alter_job({job_id}, scheduled => false);"
    cursor.execute(pause_compression_query)
    conn.commit()

    logger.info('Decompress all chunks')
    decompress_query = f"SELECT decompress_chunk(i, if_compressed => true) " \
                       f"FROM show_chunks('{<schema>}.{<table>}') i;"
    cursor.execute(decompress_query)
    conn.commit()

    ...

    logger.info('Run compression job')
    cursor.execute(f"CALL run_job({job_id});")
    conn.commit()

    logger.info('Restart the compression policy job')
    restart_compression_query = f"SELECT alter_job({job_id}, scheduled => true);"
    cursor.execute(restart_compression_query)
    conn.commit()

    cursor.close()
```

**Comment by mkindahl** [comment] 2023-10-31 08:22
The function `_timescaledb_function.policy_compression_execute` works using different transactions, so you cannot run it inside a transaction. This means that you need to set `autocommit=True` for the connection.

**Comment by mkindahl** [comment] 2023-10-31 08:24
Closing since it is not a bug.

**Closed by mkindahl** 2023-10-31 08:24 UTC
Labels: question, psycopg2

**Comment by Kirill-Ulich** [comment] 2023-10-31 08:40
Thank you for the answer.
Just one more point. For some reason, autocommit does not work with the context manager. Please take this into account.
