### ISSUE TITLE
[Enhancement]: Allow chunks aligning to determinate time frame 

### ISSUE THREAD

**Issue by holymonson** [timescale/timescaledb#4274] opened 2022-04-26 05:53 UTC
### What type of enhancement is this?

API improvement

### What subsystems and features will be improved?

Adaptive chunking

### What does the enhancement do?

We desire chunks are chopped in unbroken weeks or months, e.g. `2022-01-03T00:00:00.000000000` to `2022-01-09T23:59:59.999999999`, instead of random 7-day-period.

### Implementation challenges

Provide argument in `create_hypertable`, allow user to anchor the base point of time interval.

**Comment by holymonson** [comment] 2022-05-06 09:30
related: #287 #1500

**Comment by svenklemm** [comment] 2022-07-18 09:09
Duplicate of #287

**Closed by svenklemm** 2022-07-18 09:09 UTC
Labels: enhancement
