### ISSUE TITLE
Very high planning time when many many chunks

### ISSUE THREAD

**Issue by lrolsen1** [timescale/timescaledb#2911] opened 2021-02-06 09:13 UTC
**Relevant system information:**
 - Running on Timescale Cloud (4 CPU, 16 GB RAM, 1024 GB storage)
 - PostgreSQL version 12.5
 - TimescaleDB version 1.7.4

**Describe the bug**
We experience very high planning times when executing queries on tables with a lot of chunks

**To Reproduce**
1. Create a table with 1000+ chunks. In our case each chunks represents 1 day
2. EXPLAIN ANALYZE select * from table where column = XXX ORDER BY ts limit 10000
3. The plan tells us that the planning time was 900+ msec where as the actual execution was 23msec.

**Expected behavior**
We expect the planning time to be significantly lower. Coming from SQLServer we have never had any such issues even with 5000+ partitions. 

**Actual behavior**
A planning time in excess of 900msec and a total execution time close to 1sec.

**Additional context**
See the execution plan below:

|QUERY PLAN                                                                                          |
|----------------------------------------------------------------------------------------------------|
|Limit  (cost=0.15..2406.27 rows=10000 width=47) (actual time=5.045..12.277 rows=10000 loops=1)      |
|  ->  Custom Scan (ChunkAppend) on table_test  (cost=0.15..2411.08 rows=10020 width=47) (ac|
|        Order: table_test.ts                                                               |
|        ->  Index Scan Backward using _hyper_97_17047_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 42                                                            |
|        ->  Index Scan Backward using _hyper_97_17046_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 94                                                            |
|        ->  Index Scan Backward using _hyper_97_17045_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 215                                                           |
|        ->  Index Scan Backward using _hyper_97_17044_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 251                                                           |
|        ->  Index Scan Backward using _hyper_97_17043_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 291                                                           |
|        ->  Index Scan Backward using _hyper_97_17042_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 190                                                           |
|        ->  Index Scan Backward using _hyper_97_17048_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 346                                                           |
|        ->  Index Scan Backward using _hyper_97_17088_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 288                                                           |
|        ->  Index Scan Backward using _hyper_97_17087_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 283                                                           |
|        ->  Index Scan Backward using _hyper_97_17086_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 197                                                           |
|        ->  Index Scan Backward using _hyper_97_17085_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 268                                                           |
|        ->  Index Scan Backward using _hyper_97_17084_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 166                                                           |
|        ->  Index Scan Backward using _hyper_97_17083_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 78                                                            |
|        ->  Index Scan Backward using _hyper_97_17082_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 168                                                           |
|        ->  Index Scan Backward using _hyper_97_17081_chunk_table_test_ts_idx on _hyper_97_|
|              Filter: (buyareaid = 3)                                                               |
|              Rows Removed by Filter: 295                                                           |
...........
                                         |
|Planning Time: 916.165 ms                                                                           |
|Execution Time: 23.096 ms                                                                           |

**Comment by erimatnor** [comment] 2021-02-09 14:00
Perhaps related to https://github.com/timescale/timescaledb/issues/2897

**Comment by NunoFilipeSantos** [comment] 2021-09-28 11:17
This looks like a duplicate of #2897. Closing.

**Closed by NunoFilipeSantos** 2021-09-28 11:17 UTC
Labels: feature-enhancement, performance, hypertables
