### ISSUE TITLE
Can not create extension with timescaledb version 1.3.1 on Fedora 28

### ISSUE THREAD

**Issue by dylrich** [timescale/timescaledb#1301] opened 2019-06-19 05:24 UTC
**Relevant system information:**
 - OS: Fedora 28 x86
 - PostgreSQL 11.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6), 64-bit
 - TimescaleDB version 1.3.1
 - Installation method: `dnf install -y timescaledb-postgresql-11`after adding the full timescaledb source repository record

**Describe the bug**
After installing timescaledb 1.3.1 to my system and creating the extension, I get the following error: `ERROR: could not load library "/usr/pgsql-11/lib/timescaledb-1.3.1.so": /usr/pgsql-11/lib/timescaledb-1.3.1.so: undefined symbol: is_dummy_rel`. When I install an earlier version of timescaledb, e.g. 1.1.1-0, I am able to create the extension with no issues.

**To Reproduce**
1. On Fedora 28, install latest version of tsl timescaledb
2. Add timescaledb to the `shared_preload_libraries` record in postgresql.conf (I did this via the tune utility)
3. restart postgresql service
4. run `CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;` and get the above error

**Expected behavior**
After installing the timescaledb system package, extension creation to work after stopping and restarting the postgresql service.

**Actual behavior**
The timescale extension could not be created.

**Comment by erimatnor** [comment] 2019-06-19 09:05
Hi @dylrich, thanks for reporting this issue. The problem seems to be that the extension package has been compiled against PostgreSQL 11.3 while you are running 11.2. I'd recommend either installing PostgreSQL 11.3 or compiling the TimescaleDB extension from source against PostgreSQL 11.2 (or build a new RPM from the source package). I'd actually recommend sticking with PostgreSQL 11.2 because there is a known regression in 11.3 when using TimescaleDB.

I'll reach out to our packaging peoplein the meantime to try to figure out if there's a way to provide packages for specific point releases of PostgreSQL.

**Comment by dylrich** [comment] 2019-06-20 00:37
Thanks for the response! I will just compile Timescale against my PostgreSQL 11.2 install as you suggest for the time being.

**Comment by svenklemm** [comment] 2020-10-19 01:21
Closing this since this references an old version. Feel free to reopen if you can reproduce with a recent version.

**Closed by svenklemm** 2020-10-19 01:21 UTC
