### ISSUE TITLE
Hypertable_id in _timescaledb_catalog.dimension_slice table is incorrect

### ISSUE THREAD

**Issue by rogerdwan** [timescale/timescaledb#1563] opened 2019-12-02 09:44 UTC
**Relevant system information:**
 - OS: MAC OS 1.14.x
 - PostgreSQL version :11.x
 - TimescaleDB version: 1.5.1
 - Installation method: Docker

**Describe the bug**
When I try to join this two table ( _timescaledb_catalog.dimension_slice and _timescaledb_catalog.chunk), I found out that some of the dimension_id is different from the one in chunk catalog.

**To Reproduce**
1. Insert lots of data and wait and see...

**Screenshots**
https://imgur.com/a/BDYkAzU

**Additional context**
I'm not sure if I only using id to join this two table is enough for me if i want to see the time range of each chunk which belong to one table.

**Comment by cevian** [comment] 2019-12-19 17:53
@rogerdwan this is not a bug. dimension_slice.dimension_id is not the same as chunk.hypertable_id. The correct join is through the table `_timescaledb_catalog.chunk_constraint` so chunk.id = chunk_constraint.chunk_id and chunk_constraint.dimension_slice_id = dimension_slice.id and dimension_slice.dimension_id = dimension.id.

You can also get ranges from the chunk_relation_size function https://docs.timescale.com/latest/api#chunk_relation_size

**Comment by svenklemm** [comment] 2020-10-12 15:26
Closing this since it seems it was resolved. feel free to reopen if the issue is still current.

**Closed by svenklemm** 2020-10-12 15:26 UTC
Labels: question
