### ISSUE TITLE
OOM during UPDATE in a transaction.

### ISSUE THREAD

**Issue by traxanos** [timescale/timescaledb#1569] opened 2019-12-04 13:16 UTC
**Relevant system information:**
 - OS: CentOS 7
 - PostgreSQL version (output of `postgres --version`): 11.6
 - TimescaleDB version (output of `\dx` in `psql`): 1.4.1 upto 1.5.1
 - Installation method: source

**Describe the bug**
I use zabbix with timescale. For writing trends, the zabbix server use multiple UPDATE statements in a transaction. In this case the postgresql run into an oom. I have started with 1.4.1 and have manual update up to 1.5.1.

**To Reproduce**
when you send update many line during a transaction the oom occured.

**Expected behavior**
server should run without crash

**Actual behavior**
the server growing up for 50GB memory and run into oom

**Additional context**
you can find the zabbix bug report here: https://support.zabbix.com/browse/ZBX-16347

**Comment by bboule** [comment] 2019-12-04 16:44
@traxanos thanks for the bug report, we may need to gather some additional information from you, let me discuss with the team and circle back with you.

**Comment by traxanos** [comment] 2019-12-05 09:34
Hi i have try to create partial dump, but in this partial the oom isn't reproducable. and the original dump contain sensitive data and is very very large ...

**Comment by bboule** [comment] 2019-12-05 22:20
Ok no worries there may be some timescale/pg  logs we can look at that should not contain any sensitive info stay tuned as we consider next steps!!

**Comment by traxanos** [comment] 2019-12-19 12:11
do you discussed the problem with your team? any new info how can support you?

**Comment by traxanos** [comment] 2020-01-20 09:14
do you have new informations for us?

**Comment by overhacked** [comment] 2020-01-22 20:57
I also have this bug and I may be able to find a reproducible scenario. Do you want a full DB dump or something less?

**Comment by konstantin-kornienko** [comment] 2020-01-31 09:54
Same situation with clean Postgres, without timescale.

Sending one request with ~900 lines like:
```
update partitioned_table set a=1 where id=3;
update partitioned_table set a=2 where id=4;
...
```
kills the DB. Even analyze explain does it, not actual update.

**Comment by eertul** [comment] 2020-01-31 12:27
Hello, we had transformed TREND tables into traditional tables instead of hypertables and the issue is gone for now. We are waiting for the exact solution to move them into hypertables again. Z4.4 P11.6

**Comment by stumbaumr** [comment] 2020-03-16 00:21
Hi,
I migrated this weekend from a Zabbix MySQL setup to TimeScaleDB and I am experiencing the same problem - but with the trends_uint table.

During the migration I dropped the primary key in the migration process and unfortunately ran parts of the migration a second time.

While trying to remove the duplicates from the trends_uint table by using
```
DELETE FROM public.trends_uint T1
    USING public.trends_uint T2
WHERE   T1.ctid < T2.ctid
    AND T1.itemid  = T2.itemid
    and T1.clock = T2.clock;
```
the table got locked and the INSERT statements coming from the zabbix server process got queued.

After canceling above statement zabbix server tries to INSERT the held up entries and then the memory get's used up and I get an OOM kill.

```
2020-03-15 23:14:57.129 UTC [604] WARNING:  there is no transaction in progress
2020-03-15 23:16:12.615 UTC [1] LOG:  server process (PID 578) was terminated by signal 9
2020-03-15 23:16:12.615 UTC [1] DETAIL:  Failed process was running: update trends_uint set num=29,value_min=1217753088,value_avg=1277251019,value_max=1336111104 where itemid=200200000030428 and clock=1584309600;
	update trends_uint set num=119,value_min=4,value_avg=4,value_max=4 where itemid=200200000398365 and clock=1584309600;
	update trends_uint set num=120,value_min=1,value_avg=1,value_max=1 where itemid=200200000579962 and clock=1584309600;
	update trends_uint set num=120,value_min=0,value_avg=0,value_max=0 where itemid=200200000579994 and clock=1584309600;
	update trends_uint set num=120,value_min=1,value_avg=1,value_max=1 where itemid=200200000580026 and clock=1584309600;
	update trends_uint set num=120,value_min=0,value_avg=0,value_max=0 where itemid=200200000580078 and clock=1584309600;
	update trends_uint set num=120,value_min=0,value_avg=0,value_max=0 where itemid=200200000580079 and clock=1584309600;
	update trends_uint set num=120,value_min=0,value_avg=0,value_max=0 where itemid=200200000580090 and clock=1584309600;
	update trends_uint set num=120,value_min=1,value_avg=
2020-03-15 23:16:12.616 UTC [1] LOG:  terminating any other active server processes
2020-03-15 23:16:12.616 UTC [626] WARNING:  terminating connection because of crash of another server process
2020-03-15 23:16:12.616 UTC [626] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
```

No idea where to look further from here.

**Comment by rockaut** [comment] 2020-04-01 09:56
Heja there ... we have the exact same problem here ( just with a way less smaller db ).

```
zabbix=> \dx
                                         List of installed extensions
        Name        | Version |   Schema   |                            Description
--------------------+---------+------------+-------------------------------------------------------------------
 timescaledb        | 1.3.2   | public     | Enables scalable inserts and complex queries for time-series data
(5 rows)

zabbix=> SELECT version();
                                                 version
---------------------------------------------------------------------------------------------------------
 PostgreSQL 11.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
(1 row)

zabbix=>
```

**Comment by neogan74** [comment] 2020-04-09 06:34
I investigated this deeply. It seems it all related to some PostgreSQL issue, On clean Postgres 10,11 with partitioning. If trends also partitioned by day, and when you reach 350-400 partitions you can face such an OOM crash. SO solution at least for zabbix could use bigger partitions by week or month, then you never face this.

**Comment by rockaut** [comment] 2020-04-09 07:02
Interesting. We had 32 days for history and 365 for trends. I don't know
how much chunks we had for trends but even with history we would have had 5
* 32 and I guess we had at least 5 months worth of trends too so add 2 *
150.
When we ran into the problem I lowered the history days to 14 but the
troubles resisted. Only converting trends back to non hypertables helped.

I may test that theory once I got back to work after the current situation.
You may loose some performance optimization from build in timescale
functions.

Hmm... Will post some thoughts o er at Zabbix issue too.

**Comment by GioMac** [comment] 2020-04-10 14:19
Same here
Centos 7 (latest updates)
Zabbix 4.4.7 from repo.zabbix.com
postgresql11-server-11.7-1PGDG.rhel7.x86_64
timescaledb_11-1.6.1-1.rhel7.x86_64

**Comment by rockaut** [comment] 2020-04-14 06:45
The Zabbix team are working on a workaround -> https://support.zabbix.com/browse/ZBX-16347
The of course cant fix it as the problem seams to be in Timescale or even in Postgres but they seam to highlight the problem in Docs and change the partition timespans for the trend tables.

@bboule you from Timescale team? Have you had any insights on this problem maybe for postgres itself or other reports too?

**Comment by GioMac** [comment] 2020-04-14 08:01
According to Zabbix community, issue confirmed on Centos, Ubuntu and Debian distributions, probably, there are no others using this particular feature yet, therefore, I assume, it's not an issue with specific build...

**Comment by erimatnor** [comment] 2021-01-12 13:52
Touching lots of partitions/chunks during UPDATEs can lead to OOM. PostgreSQL 12 should improve the situations as it prunes subtables during deletes and updates. Note that TimescaleDB doesn't specifically optimize updates right now.

Closing since this issue doesn't seem specific to TimescaleDB.

**Closed by erimatnor** 2021-01-12 13:52 UTC
Labels: bug, severity-p3

**Comment by hostops** [comment] 2021-07-16 06:42
Hello! I do not think this issue should be closed. We have same problem with DELETE statements in pg13.3 and ts2.3.1.
I wrote the details of our issue here: https://github.com/timescale/timescaledb/issues/1085
