### ISSUE TITLE
Segfault in get_single_response_nonblocking in CI

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#5085] opened 2022-12-13 08:02 UTC
Link to failed run: https://github.com/timescale/timescaledb/actions/runs/3681682921/jobs/6228619683

Query:
```
WITH 
jennifer_0 AS (select  
    ref_0.location as c0, 
    ref_0.team2 as c1, 
    cast(nullif(ref_0.location,
          ) as bool)) as bool) as c21, 
    subq_1.c0 as c22
  from 
    public.distinct_on_hypertable as ref_1,
    lateral (select  
          subq_0.c3 as c0
        from 
          (select  
                ref_1.val as c0, 
                sample_0.value as c1, 
                sample_0.value as c2, 
                ref_1.val as c3, 
                ref_1.ts as c4, 
                ref_1.ts as c5, 
                sample_0.time as c6, 
                sample_0.value as c7, 
                ref_1.ts as c8, 
                ref_1.id as c9, 
                sample_0.time as c10, 
                ref_1.ts as c11
              from 
                public.mvcp_hyper as sample_0 tablesample system (6) 
              where ref_1.val = ref_1.val) as subq_0
        where subq_0.c10 is not NULL
        limit 141) as subq_1
  where true
  limit 15
```

Stacktrace:
```
#0  get_single_response_nonblocking (set=<optimized out>)
    at /home/runner/work/timescaledb/timescaledb/tsl/src/remote/async.c:623
        req = 0x0
        pg_conn = <optimized out>
        lc__state = {l = <optimized out>, i = 0}
        lc = 0x55e91653ec08
        lc = <optimized out>
        lc__state = {l = <optimized out>, i = <optimized out>}
        req = <optimized out>
        pg_conn = <optimized out>
        res = <optimized out>
#1  async_request_set_wait_any_response_deadline (
    set=set@entry=0x7ffff65d7400, endtime=endtime@entry=-9223372036854775808)
    at /home/runner/work/timescaledb/timescaledb/tsl/src/remote/async.c:794
        response = <optimized out>
#2  0x00007f4301ded42b in async_request_set_wait_any_result (
    set=set@entry=0x7ffff65d7400)
    at /home/runner/work/timescaledb/timescaledb/tsl/src/remote/async.c:847
        res = <optimized out>
#3  0x00007f4301ded73f in async_request_discard_response (req=0x0)
    at /home/runner/work/timescaledb/timescaledb/tsl/src/remote/async.c:925
        set = {requests = 0x55e91653ebf0}
        result = <optimized out>
#4  0x00007f4301df1c1a in cursor_fetcher_rewind (df=0x55e91653e5c0)
    at /home/runner/work/timescaledb/timescaledb/tsl/src/remote/cursor_fetcher.c:377

warning: Can't open file /dev/zero (deleted) during file-backed mapping note processing

warning: Can't open file /SYSV0010111f (deleted) during file-backed mapping note processing
        sql = {<optimized out> <repeats 64 times>}
        cursor = 0x55e91653e5c0
#5  0x000055e912e30537 in ExecReScan ()
No symbol table info available.
#6  0x000055e912e3066f in ExecReScan ()
No symbol table info available.
#7  0x000055e912e53c62 in ?? ()
No symbol table info available.
#8  0x00007f4301de1cb3 in ExecProcNode (node=0x55e91943[157](https://github.com/timescale/timescaledb/actions/runs/3681682921/jobs/6228619683#step:11:158)0)
    at /usr/include/postgresql/14/server/executor/executor.h:257
No locals.
#9  async_append_exec (node=0x55e919430f90)
    at /home/runner/work/timescaledb/timescaledb/tsl/src/nodes/async_append.c:278
        slot = <optimized out>
        state = 0x55e919430f90
        econtext = 0x55e9194311a0
```

**Comment by jnidzwetzki** [comment] 2022-12-13 08:17
Seems to be a duplicate of #5053

**Closed** 2022-12-14 15:30 UTC
Labels: bug
