### ISSUE TITLE
[Bug]: Tuning requests unreasonable amount of memory

### ISSUE THREAD

**Issue by paniccia-taurob** [timescale/timescaledb#4127] opened 2022-02-24 16:11 UTC
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Other

### What happened?

In my company, we've often experienced the problem at start-up of the docker container that, without the flag "NO_TS_TUNE" activated, timescaledb would request more swap memory than actually on the system.
I've always overlooked that bug as a problem due to running on VM's.

Now we started it on a native Linux server with 32 GB of memory, it managed to request an amount that, by log message "overflows size_t".

I believe this isn't supposed to happen.

### TimescaleDB version affected

2.3.1

### PostgreSQL version used

13.3

### What operating system did you use?

Ubuntu 18.04

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
In the case of VM's, the log line looks like:
:  could not map anonymous shared memory: Out of memory
In the case of the server, it looked similar, but with the twist of "overflows size_t".
```

### How can we reproduce the bug?

```bash
The bug appears at start-up of the docker container, when it's running the "tuning" to the system around it.
It's a standard docker image (from digest sha256:f2e18f836623255f223512c5f6c6a7fe9741798adbadc7728736a3e32d560519), running as part of a docker-compose environment, where several other services are set as "depends_on" this one, and its entry looks like:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: unless-stopped
    networks:
      private:
    volumes:
      - db-data:/var/lib/postgresql/data

(The dockerfile sets only the password and some .sql files to run at start-up, which aren't reached).
```

**Comment by erimatnor** [comment] 2022-02-25 08:52
@paniccia-taurob Is this an issue with timescaledb-tune or TimescaleDB itself. It isn't clear from your bug report where the log message comes from. Also note that you can manually configure TimescaleDB when starting up to set your own memory limits.

We can't reproduce this from the information you provided since it lacks a lot of information. For instance, we don't have the file `Dockerfile.db`.

Please provide a script or step-by-step instructions to generate this error.

**Comment by paniccia-taurob** [comment] 2022-02-25 09:37
This is how the Dockerfile.db looks like:

FROM timescale/timescaledb@sha256:f2e18f836623255f223512c5f6c6a7fe9741798adbadc7728736a3e32d560519

COPY db/*.sql /docker-entrypoint-initdb.d/

ENV POSTGRES_PASSWORD=****


The issue is with timescaledb-tune, I'd imagine, as it's before the launch of:
"/usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/000_install_timescaledb.sh
All the files we copy in the image would be read after, so their content doesn't matter.

I don't have step-by-step instructions, as with the same steps, it fails in some machines and not in other ones. But when it fails, it does so consistently.

**Comment by paniccia-taurob** [comment] 2022-02-25 13:25
We tried now without docker-compose or files added:

**docker run -e POSTGRES_PASSWORD=password**
```
timescale/timescaledb@sha256:f2e18f836623255f223512c5f6c6a7fe9741798adbadc7728736a3e32d560519
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/amd64) and no specific platform was requested
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.



The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".



Data page checksums are disabled.



fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
2022-02-25 13:21:47.268 UTC [30] WARNING: no usable system locales were found
ok
syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
ok




Success. You can now start the database server using:



pg_ctl -D /var/lib/postgresql/data -l logfile start



waiting for server to start....2022-02-25 13:21:47.907 UTC [35] LOG: starting PostgreSQL 13.3 on i686-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 32-bit
2022-02-25 13:21:47.908 UTC [35] LOG: listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-02-25 13:21:47.910 UTC [36] LOG: database system was shut down at 2022-02-25 13:21:47 UTC
2022-02-25 13:21:47.912 UTC [35] LOG: database system is ready to accept connections
2022-02-25 13:21:47.913 UTC [42] LOG: TimescaleDB background worker launcher connected to shared catalogs
done
server started



/usr/local/bin/docker-entrypoint.sh: sourcing /docker-entrypoint-initdb.d/000_install_timescaledb.sh
psql:/tmp/tmp.NOfHIk:1: WARNING:
WELCOME TO
_____ _ _ ____________
|_ _(_) | | | _ \ ___ \
| | _ _ __ ___ ___ ___ ___ __ _| | ___| | | | |_/ /
| | | | _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
| | | | | | | | | __/\__ \ (_| (_| | | __/ |/ /| |_/ /
|_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
Running version 2.3.1
For more information on TimescaleDB, please visit the following links:



1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
2. API reference documentation: https://docs.timescale.com/api/latest
3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts



Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.



2022-02-25 13:21:48.294 UTC [51] WARNING:
WELCOME TO
_____ _ _ ____________
|_ _(_) | | | _ \ ___ \
| | _ _ __ ___ ___ ___ ___ __ _| | ___| | | | |_/ /
| | | | _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
| | | | | | | | | __/\__ \ (_| (_| | | __/ |/ /| |_/ /
|_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
Running version 2.3.1
For more information on TimescaleDB, please visit the following links:

1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
2. API reference documentation: https://docs.timescale.com/api/latest
3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.

2022-02-25 13:21:48.294 UTC [51] CONTEXT: PL/pgSQL function inline_code_block line 12 at RAISE
CREATE EXTENSION
2022-02-25 13:21:48.577 UTC [54] WARNING:
WELCOME TO
_____ _ _ ____________
|_ _(_) | | | _ \ ___ \
| | _ _ __ ___ ___ ___ ___ __ _| | ___| | | | |_/ /
| | | | _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
| | | | | | | | | __/\__ \ (_| (_| | | __/ |/ /| |_/ /
|_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
Running version 2.3.1
For more information on TimescaleDB, please visit the following links:

1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
2. API reference documentation: https://docs.timescale.com/api/latest
3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.

2022-02-25 13:21:48.577 UTC [54] CONTEXT: PL/pgSQL function inline_code_block line 12 at RAISE
psql:/tmp/tmp.NOfHIk:1: WARNING:
WELCOME TO
_____ _ _ ____________
|_ _(_) | | | _ \ ___ \
| | _ _ __ ___ ___ ___ ___ __ _| | ___| | | | |_/ /
| | | | _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
| | | | | | | | | __/\__ \ (_| (_| | | __/ |/ /| |_/ /
|_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
Running version 2.3.1
For more information on TimescaleDB, please visit the following links:



1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
2. API reference documentation: https://docs.timescale.com/api/latest
3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts



Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.



CREATE EXTENSION



/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/001_timescaledb_tune.sh
2022-02-25 13:21:48.581 UTC [56] ERROR: TimescaleDB background worker connected to template database, exiting
2022-02-25 13:21:48.582 UTC [35] LOG: background worker "TimescaleDB Background Worker Scheduler" (PID 56) exited with exit code 1
Using postgresql.conf at this path:
/var/lib/postgresql/data/postgresql.conf



Writing backup to:
/tmp/timescaledb_tune.backup202202251321



Recommendations based on 11.66 GB of available memory and 12 CPUs for PostgreSQL 13
shared_buffers = 2983MB
effective_cache_size = 8951MB
maintenance_work_mem = 1491MB
work_mem = 2546kB
timescaledb.max_background_workers = 8
max_worker_processes = 23
max_parallel_workers_per_gather = 6
max_parallel_workers = 12
wal_buffers = 16MB
min_wal_size = 512MB
default_statistics_target = 500
random_page_cost = 1.1
checkpoint_completion_target = 0.9
max_locks_per_transaction = 128
autovacuum_max_workers = 10
autovacuum_naptime = 10
effective_io_concurrency = 200
timescaledb.last_tuned = '2022-02-25T13:21:48Z'
timescaledb.last_tuned_version = '0.11.0'
Saving changes to: /var/lib/postgresql/data/postgresql.conf



waiting for server to shut down....2022-02-25 13:21:48.609 UTC [35] LOG: received fast shutdown request
2022-02-25 13:21:48.611 UTC [35] LOG: aborting any active transactions
2022-02-25 13:21:48.611 UTC [55] LOG: terminating TimescaleDB background job "Telemetry Reporter [1]" due to administrator command
2022-02-25 13:21:48.611 UTC [52] LOG: terminating TimescaleDB job scheduler due to administrator command
2022-02-25 13:21:48.611 UTC [42] LOG: terminating TimescaleDB background worker launcher due to administrator command
2022-02-25 13:21:48.611 UTC [52] FATAL: terminating connection due to administrator command
2022-02-25 13:21:48.611 UTC [42] FATAL: terminating connection due to administrator command
2022-02-25 13:21:48.611 UTC [52] LOG: terminating TimescaleDB job scheduler due to administrator command
2022-02-25 13:21:48.612 UTC [55] LOG: terminating TimescaleDB background job "Telemetry Reporter [1]" due to administrator command
2022-02-25 13:21:48.612 UTC [55] FATAL: terminating connection due to administrator command
2022-02-25 13:21:48.613 UTC [69] FATAL: terminating autovacuum process due to administrator command
2022-02-25 13:21:48.613 UTC [35] LOG: background worker "TimescaleDB Background Worker Launcher" (PID 42) exited with exit code 1
2022-02-25 13:21:48.613 UTC [35] LOG: background worker "logical replication launcher" (PID 43) exited with exit code 1
2022-02-25 13:21:48.615 UTC [35] LOG: background worker "TimescaleDB Background Worker Scheduler" (PID 52) exited with exit code 1
2022-02-25 13:21:48.616 UTC [35] LOG: background worker "Telemetry Reporter [1]" (PID 55) exited with exit code 1
2022-02-25 13:21:48.616 UTC [37] LOG: shutting down
2022-02-25 13:21:48.658 UTC [35] LOG: database system is shut down
done
server stopped



PostgreSQL init process complete; ready for start up.



2022-02-25 13:21:48.718 UTC [1] FATAL: could not map anonymous shared memory: Out of memory
2022-02-25 13:21:48.718 UTC [1] HINT: This error usually means that PostgreSQL's request for a shared memory segment exceeded available memory, swap space, or huge pages. To reduce the request size (currently 3218317312 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buffers or max_connections.
2022-02-25 13:21:48.718 UTC [1] LOG: database system is shut down
```

**Comment by NunoFilipeSantos** [comment] 2022-03-29 10:50
Hi @paniccia-taurob ! 👋 Can you please try to reproduce it on 2.6.0 and get back to us? Thank you. 👍

**Comment by NunoFilipeSantos** [comment] 2022-04-27 09:26
Hi @paniccia-taurob ! 👋 We're closing this issue, feel free to reopen it if you can reproduce it on our latest version (2.6.1). Thank you. 😃

**Closed by NunoFilipeSantos** 2022-04-27 09:26 UTC
Labels: bug, need-more-info
