### ISSUE TITLE
time_bucket_gapfill pulling much data forward

### ISSUE THREAD

**Issue by pauljamescleary** [timescale/timescaledb#1763] opened 2020-03-19 23:20 UTC
**Relevant system information:**
 - OS: timescaledb docker
 - PostgreSQL version: PostgreSQL 11.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.0
 - Installation method: docker

**Describe the bug**
When using time_bucket_gapfill, I am seeing old values being pulled into the time period.

Looking at timescaledb, I am trying to manufacture observations as part of gapfill.  For example, I have 2 students Janet and Sam, my metric is attendance.  When people are absent, that is recorded.  However, I do not know if they are present, and they are present almost all the time, so I want to _assume_ present unless explicitly marked absent.  Now imagine that Sam is out all week, and I run a query to generate attendance for the week.

I would like to see NULLs (ideally force a value but NULL is good enough for now).  However, old values beyond the time period are being pulled in

**To Reproduce**

```
-- Our simple table
CREATE TABLE attendance (
 time TIMESTAMPTZ NOT NULL,
 student TEXT NOT NULL,
 absent SMALLINT DEFAULT 1 -- indicates the student was absent for this day
);
SELECT create_hypertable('attendance', 'time');

-- Add two absent days, but these were in JANUARY
INSERT INTO attendance(time, student, absent) VALUES('2015-01-01 00:00:00', 'Sam', 1);
INSERT INTO attendance(time, student, absent) VALUES('2015-01-02 00:00:00', 'Sam', 1);
INSERT INTO attendance(time, student, absent) VALUES('2015-01-08 00:00:00', 'Janet', 1);

-- Query now for the week in FEBRUARY to see how many days SAM was absent
SELECT
  time_bucket_gapfill('1 day', time, '2015-02-01 00:00:00', '2015-02-07 00:00:00') AS t,
  student,
  interpolate(sum(absent)) AS days_absent
FROM attendance
WHERE student = 'Sam'
GROUP BY t, student
ORDER BY t;
```

**Expected behavior**
I would expect results like the following, OR empty (as I am new to timescaledb):

```
t            | student | days_absent 
------------------------+---------+-------------
2015-02-01 00:00:00+00 | Sam     |            
2015-02-02 00:00:00+00 | Sam     |            
2015-02-03 00:00:00+00 | Sam     |            
2015-02-04 00:00:00+00 | Sam     |            
2015-02-05 00:00:00+00 | Sam     |            
2015-02-06 00:00:00+00 | Sam     |            
(8 rows)
```

**Actual behavior**

```
-- Here is the output, notice the first records pulled in...
t            | student | days_absent 
------------------------+---------+-------------
2015-01-01 00:00:00+00 | Sam     |           1
2015-01-02 00:00:00+00 | Sam     |           1
2015-02-01 00:00:00+00 | Sam     |            
2015-02-02 00:00:00+00 | Sam     |            
2015-02-03 00:00:00+00 | Sam     |            
2015-02-04 00:00:00+00 | Sam     |            
2015-02-05 00:00:00+00 | Sam     |            
2015-02-06 00:00:00+00 | Sam     |            
(8 rows)
```

**Screenshots**

**Additional context**

**Comment by svenklemm** [comment] 2020-03-27 12:14
This was brought up and resolved in community slack and this is the intended behaviour. gapfill will not remove tuples from the resultset. If you want to exclude tuples from the resultset you need a WHERE-clause.

**Closed by svenklemm** 2020-03-27 12:14 UTC
Labels: Gap Fill
