### ISSUE TITLE
[Bug]: time_bucket_gapfill returns one more bucket

### ISSUE THREAD

**Issue by jiyeonseo** [timescale/timescaledb#5287] opened 2023-02-06 03:01 UTC
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Gapfill

### What happened?

According to [the doc](https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/time_bucket_gapfill/),  `time_bucket` and `time_bucket_gapfill` make time bucket between 'start' and 'finish`. However, it includes the start date(in case, `bucket_width` is `1 day`) even that bucket is not in time range condition. 

It is reproduced on both my local(docker) and managed cloud.  

### TimescaleDB version affected

2.9

### PostgreSQL version used

14.6

### What operating system did you use?

Mac OS X 12.3

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted, Timescale Cloud

### How can we reproduce the bug?

```bash
### test data 


CREATE TABLE metrics(
    time      TIMESTAMP WITH TIME ZONE,
    device_id INT,
    value     DOUBLE PRECISION
);

INSERT INTO metrics
VALUES
('2023-02-06T00:00:00Z', 1, 4),
('2023-02-05T00:00:00Z', 1, 4),
('2023-02-04T00:00:00Z', 1, 4),
('2023-02-03T00:00:00Z', 1, 4),
('2023-02-02T00:00:00Z', 1, 4),
('2023-02-01T00:00:00Z', 1, 4),
('2023-01-31T00:00:00Z', 1, 6),
('2023-01-30T00:00:00Z', 1, 6),
('2023-01-28T00:00:00Z', 1, 6);


### test environment 

```sql
select now() - INTERVAL '1 week' as start, now() as end

start                        |end                          |
-----------------------------+-----------------------------+
2023-01-30 02:48:30.070 +0000|2023-02-06 02:48:30.070 +0000|
```

### Query the metric value every day over the last seven days

```
SELECT
  time_bucket_gapfill('1 day', time) AS day,
  device_id,
  count(*) as count
FROM metrics
WHERE 
	time  > now() - INTERVAL '1 week' AND time < now()
GROUP BY day, device_id
order by day desc;
```
### Result 
```
day                          |device_id|count|
-----------------------------+---------+-----+
2023-02-06 00:00:00.000 +0000|        1|    1|
2023-02-05 00:00:00.000 +0000|        1|    1|
2023-02-04 00:00:00.000 +0000|        1|    1|
2023-02-03 00:00:00.000 +0000|        1|    1|
2023-02-02 00:00:00.000 +0000|        1|    1|
2023-02-01 00:00:00.000 +0000|        1|    1|
2023-01-31 00:00:00.000 +0000|        1|    1|
2023-01-30 00:00:00.000 +0000|        1|     |
(8 row)
```

### Expected result 
```
day                          |device_id|count|
-----------------------------+---------+-----+
2023-02-06 00:00:00.000 +0000|        1|    1|
2023-02-05 00:00:00.000 +0000|        1|    1|
2023-02-04 00:00:00.000 +0000|        1|    1|
2023-02-03 00:00:00.000 +0000|        1|    1|
2023-02-02 00:00:00.000 +0000|        1|    1|
2023-02-01 00:00:00.000 +0000|        1|    1|
2023-01-31 00:00:00.000 +0000|        1|    1|
(7 row)
```
```

**Comment by konskov** [comment] 2023-02-07 10:44
hi @jiyeonseo, thank you for reaching out. This is actually not unexpected behavior for `time_bucket_gapfill`:
(Added one extra row to the sample data you provided for Feb 7)
```
postgres@kon[54970]=# select * from metrics order by time;
          time          | device_id | value
------------------------+-----------+-------
 2023-01-28 02:00:00+02 |         1 |     6
 2023-01-30 02:00:00+02 |         1 |     6
 2023-01-31 02:00:00+02 |         1 |     6
 2023-02-01 02:00:00+02 |         1 |     4
 2023-02-02 02:00:00+02 |         1 |     4
 2023-02-03 02:00:00+02 |         1 |     4
 2023-02-04 02:00:00+02 |         1 |     4
 2023-02-05 02:00:00+02 |         1 |     4
 2023-02-06 02:00:00+02 |         1 |     4
 2023-02-07 02:00:00+02 |         1 |     4
(10 rows)
```
And the results of the query are:
```
          day           | device_id | count
------------------------+-----------+-------
 2023-02-07 02:00:00+02 |         1 |     1
 2023-02-06 02:00:00+02 |         1 |     1
 2023-02-05 02:00:00+02 |         1 |     1
 2023-02-04 02:00:00+02 |         1 |     1
 2023-02-03 02:00:00+02 |         1 |     1
 2023-02-02 02:00:00+02 |         1 |     1
 2023-02-01 02:00:00+02 |         1 |     1
 2023-01-31 02:00:00+02 |         1 |
(8 rows)
```
If we do `EXPLAIN ANALYZE ` for the query, 
we get the output:
```
                                                                              QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=48.83..48.87 rows=8 width=20) (actual time=0.798..0.802 rows=8 loops=1)
   Sort Key: (time_bucket_gapfill('1 day'::interval, "time", NULL::timestamp with time zone, NULL::timestamp with time zone)) DESC
   Sort Method: quicksort  Memory: 25kB
   ->  Custom Scan (GapFill)  (cost=48.69..48.71 rows=8 width=0) (actual time=0.510..0.524 rows=8 loops=1)
         ->  Sort  (cost=48.69..48.71 rows=8 width=0) (actual time=0.502..0.504 rows=7 loops=1)
               Sort Key: device_id, (time_bucket_gapfill('1 day'::interval, "time", NULL::timestamp with time zone, NULL::timestamp with time zone)) NULLS FIRST
               Sort Method: quicksort  Memory: 25kB
               ->  GroupAggregate  (cost=48.39..48.57 rows=8 width=0) (actual time=0.434..0.455 rows=7 loops=1)
                     Group Key: (time_bucket_gapfill('1 day'::interval, "time", NULL::timestamp with time zone, NULL::timestamp with time zone)), device_id
                     ->  Sort  (cost=48.39..48.41 rows=8 width=12) (actual time=0.413..0.415 rows=7 loops=1)
                           Sort Key: (time_bucket_gapfill('1 day'::interval, "time", NULL::timestamp with time zone, NULL::timestamp with time zone)) DESC, device_id
                           Sort Method: quicksort  Memory: 25kB
                           ->  Seq Scan on metrics  (cost=0.00..48.27 rows=8 width=12) (actual time=0.089..0.118 rows=7 loops=1)
                                 Filter: (("time" < now()) AND ("time" > (now() - '7 days'::interval)))
                                 Rows Removed by Filter: 3
 Planning Time: 2.598 ms
 Execution Time: 1.793 ms
(17 rows)
```
We can see the WHERE filter is applied first, and the gapfill operation will only see the filtered rows. So the bucket for ` 2023-01-31 02:00:00+02` is empty

**Comment by jiyeonseo** [comment] 2023-02-11 05:42
@konskov Thanks for the explanation  :) 

Could you give me more details about the example in [this doc](https://docs.timescale.com/api/latest/hyperfunctions/gapfilling-interpolation/time_bucket_gapfill/#sample-usage )? As I understand, The query for 1 week data(`time > now() - INTERVAL '1 week' AND time < now()`) with `time_bucket_gapfill` always returns 8 rows. but the doc says it will return 7 rows. is it right?

**Comment by kgyrtkirk** [comment] 2023-02-17 12:06
@jiyeonseo your understanding is right; the doc suggests that there will be 7 rows; while it will be 8 in most cases.
I've opened a docs ticket to correct that.

I think you might want/expecting to align the start/end boundaries with the bucket boundaries; see my examples below; for now I'll close this is kinda caused by the fact that the documentation was inaccurate.

Thank you for reporting this issue @jiyeonseo! 

```
drop table if EXISTS c1;
drop table if EXISTS conditions;
CREATE TABLE conditions (
    t timestamp with time ZONE NOT NULL,
    temperature NUMERIC
);
INSERT INTO conditions (t, temperature)
SELECT
    generate_series('2022-01-01 00:00:00-00'::timestamptz, '2022-01-31 23:59:59-00'::timestamptz, '1 hour'),
    0.25;
create table c1 as select * from conditions where t BETWEEN '2022-01-04 1:00:00-00' and '2022-01-04 11:00:00-00';

SELECT time_bucket_gapfill('1 day', t) AS tb,
    count(1)
FROM conditions
where '2022-01-03 11:00:00-00'::timestamptz <= t and t < '2022-01-05 11:00:00-00'::timestamptz
GROUP BY tb;


SELECT time_bucket_gapfill('1 day', t) AS tb,
    count(1)
FROM c1
where '2022-01-03 11:00:00-00'::timestamptz <= t and t < '2022-01-05 11:00:00-00'::timestamptz
GROUP BY tb;

-- offset alignment within day via 'offset'
SELECT time_bucket('1 day', t, "offset":=INTERVAL '11 hour') AS tb,
    count(1)
FROM conditions
where '2022-01-03 11:00:00-00'::timestamptz <= t and t < '2022-01-05 11:00:00-00'::timestamptz
GROUP BY tb;

-- offset alignment within day by date_trunc on condition
SELECT time_bucket_gapfill('1 day', t) AS tb,
    count(1)
FROM conditions
where date_trunc('day','2022-01-03 11:00:00-00'::timestamptz) <= t and t < date_trunc('day','2022-01-05 11:00:00-00'::timestamptz)
GROUP BY tb;

-- offset alignment within day by date_trunc on condition
SELECT time_bucket_gapfill('1 day', t) AS tb,
    count(1)
FROM c1
where date_trunc('day','2022-01-03 11:00:00-00'::timestamptz) <= t and t < date_trunc('day','2022-01-06 11:00:00-00'::timestamptz)
GROUP BY tb;

```

**Closed by kgyrtkirk** 2023-02-17 12:06 UTC
Labels: bug, gapfill, time_bucket_gapfill
