### ISSUE TITLE
[Bug]: timescaledb_post_restore does not set timescaledb.restoring to off

### ISSUE THREAD

**Issue by jgpruitt** [timescale/timescaledb#4267] opened 2022-04-22 16:23 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Restore

### What happened?

`select public.timescaledb_post_restore();` does not set the `timescaledb.restoring` setting to `off`. It stays `on`.

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

14.2

### What operating system did you use?

docker image timescale/timescaledb:latest-pg14

### What installation method did you use?

Docker

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
john@john ~ % docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg14
edb5c3b5569927380afde0fe1487dbe56cba59175abca6c71f110dc903ae306e
john@john ~ % psql -h localhost -p 5432 -d postgres -U postgres
Password for user postgres: 
Timing is on.
Line style is unicode.
Border style is 2.
Pager usage is off.
Expanded display is used automatically.
psql (14.2)
Type "help" for help.

postgres=# \dx
                                       List of installed extensions
┌─────────────┬─────────┬────────────┬───────────────────────────────────────────────────────────────────┐
│    Name     │ Version │   Schema   │                            Description                            │
├─────────────┼─────────┼────────────┼───────────────────────────────────────────────────────────────────┤
│ plpgsql     │ 1.0     │ pg_catalog │ PL/pgSQL procedural language                                      │
│ timescaledb │ 2.6.1   │ public     │ Enables scalable inserts and complex queries for time-series data │
└─────────────┴─────────┴────────────┴───────────────────────────────────────────────────────────────────┘
(2 rows)

postgres=# select public.timescaledb_pre_restore();
┌─────────────────────────┐
│ timescaledb_pre_restore │
├─────────────────────────┤
│ t                       │
└─────────────────────────┘
(1 row)

Time: 10.144 ms
postgres=# show timescaledb.restoring;
┌───────────────────────┐
│ timescaledb.restoring │
├───────────────────────┤
│ on                    │
└───────────────────────┘
(1 row)

Time: 2.588 ms
postgres=# \q
john@john ~ % psql -h localhost -p 5432 -d postgres -U postgres
Password for user postgres: 
Timing is on.
Line style is unicode.
Border style is 2.
Pager usage is off.
Expanded display is used automatically.
psql (14.2)
Type "help" for help.

postgres=# show timescaledb.restoring;
┌───────────────────────┐
│ timescaledb.restoring │
├───────────────────────┤
│ on                    │
└───────────────────────┘
(1 row)

Time: 9.110 ms
postgres=# select setting, reset_val from pg_settings where name = 'timescaledb.restoring';
┌─────────┬───────────┐
│ setting │ reset_val │
├─────────┼───────────┤
│ on      │ on        │
└─────────┴───────────┘
(1 row)

Time: 6.071 ms
postgres=# select public.timescaledb_post_restore();
┌──────────────────────────┐
│ timescaledb_post_restore │
├──────────────────────────┤
│ t                        │
└──────────────────────────┘
(1 row)

Time: 9.437 ms
postgres=# select setting, reset_val from pg_settings where name = 'timescaledb.restoring';
┌─────────┬───────────┐
│ setting │ reset_val │
├─────────┼───────────┤
│ on      │ on        │
└─────────┴───────────┘
(1 row)

Time: 4.517 ms
postgres=# \q
john@john ~ % psql -h localhost -p 5432 -d postgres -U postgres
Password for user postgres: 
Timing is on.
Line style is unicode.
Border style is 2.
Pager usage is off.
Expanded display is used automatically.
psql (14.2)
Type "help" for help.

postgres=# select public.timescaledb_post_restore();
┌──────────────────────────┐
│ timescaledb_post_restore │
├──────────────────────────┤
│ t                        │
└──────────────────────────┘
(1 row)

Time: 17.626 ms
postgres=# select setting, reset_val from pg_settings where name = 'timescaledb.restoring';
┌─────────┬───────────┐
│ setting │ reset_val │
├─────────┼───────────┤
│ off     │ off       │
└─────────┴───────────┘
(1 row)

Time: 5.546 ms
```

### How can we reproduce the bug?

```bash
1. connect to the database
2. call `select public.timescaledb_pre_restore();`
3. disconnect from the database
4. connect to the database
5. call `select public.timescaledb_post_restore();`
6. `show timescaledb.restoring;` returns `on`. I would have expected this to be `off`. I cannot insert into hypertables at this point.
7. disconnect from the database
8. connect to the database
9. call `select public.timescaledb_post_restore();`
10. `show timescaledb.restoring;` returns `off`.
```

**Comment by konskov** [comment] 2022-05-03 08:05
I believe that is because `ALTER DATABASE ... RESET` in `timescaledb_post_restore` will change the value of the GUC for subsequent sessions, in the current session the previous value is still visible, which is `on`. The choice to implement it that way is explained by [`66544c7`](https://github.com/timescale/timescaledb/commit/66544c75647e5935faeb901e3d8ab07602b44907), so while this behavior is somewhat unexpected, it probably should not be changed. I'll close this issue for now, we can come back to it if I've missed something.

**Comment by konskov** [comment] 2022-05-03 09:42
Okay, after some discussion it turns out I was wrong to close this issue, as this unexpected behavior is ...buggy... so apologies for closing! However we think this could actually be difficult or impossible to fix, we will look further into it.

**Closed** 2022-07-28 09:20 UTC
Labels: bug, backup-and-restore
