### ISSUE TITLE
[Bug]: ORDER/GROUP BY expression not found in targetlist

### ISSUE THREAD

**Issue by jledentu** [timescale/timescaledb#6872] opened 2024-04-29 14:45 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Query executor

### What happened?

Some `SELECT` requests on an hypertable return the error below:

```
ERROR:  ORDER/GROUP BY expression not found in targetlist 

SQL state: XX000
```

### TimescaleDB version affected

2.14.2

### PostgreSQL version used

15.6

### What operating system did you use?

Ubuntu 22.04

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

1. Run `docker run -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg15.6-ts2.14.2`
2. Connect to the database
3. Execute the queries below:

```sql
CREATE TABLE test (
	date timestamp with time zone NOT NULL,
    quantity double precision,
    "isText" boolean
);

CREATE INDEX IF NOT EXISTS test_idx ON test (date) WHERE "isText" IS NULL;
SELECT create_hypertable('test', 'date', chunk_time_interval => interval 'P7D', create_default_indexes => false);

INSERT INTO test(date, quantity)
SELECT date, round((random() * (100-3) + 3)::NUMERIC) AS quantity
FROM generate_series('2023-01-01T00:00:00+01:00', '2023-05-01T00:00:00+01:00', interval 'PT10M') AS t(date);

SELECT time_bucket_gapfill('PT1H', date - (- interval 'P1Y'), start => '2024-01-01T00:00:00+01:00', finish => '2024-04-26T00:00:00+02:00') AS date, first(quantity, date) AS quantity FROM test WHERE date >= '2024-01-01T00:00:00+01:00'::timestamp with time zone + (- interval 'P1Y') AND date < '2024-04-26T00:00:00+02:00'::timestamp with time zone + (- interval 'P1Y') AND "isText" IS NULL AND quantity != 0 AND date = date - (- interval 'P1Y') + (- interval 'P1Y') GROUP BY 1;
```

It seems that the partial index is not well handled. If I remove the condition `WHERE "isText" IS NULL;` on the index, the error disappears.

**Comment by gayyappan** [comment] 2024-04-29 16:13
I am able to repro this: 
```
test=# SELECT time_bucket_gapfill('PT1H', date - (- interval 'P1Y'), start => '2024-01-01T00:00:00+01:00', finish => '2024-04-26T00:00:00+02:00') AS date, first(quantity, date) AS quantity FROM test WHERE date >= '2024-01-01T00:00:00+01:00'::timestamp with time zone + (- interval 'P1Y') AND date < '2024-04-26T00:00:00+02:00'::timestamp with time zone + (- interval 'P1Y') AND "isText" IS NULL AND quantity != 0 AND date = date - (- interval 'P1Y') + (- interval 'P1Y') GROUP BY 1;
ERROR:  ORDER/GROUP BY expression not found in targetlist
```

**Comment by jledentu** [comment] 2024-07-11 12:19
I also met this bug on tables using full indexes (without condition), even if I can't reproduce the error on a minimal case. It may depend on the amount of data, I guess.
As workaround, I dropped indexes on concerned tables, resulting in degraded performances. Another solution is to not use `time_bucket_gapfill`, but it doesn't avoid this other bug: https://github.com/timescale/timescaledb/issues/7097

**Comment by RobAtticus** [comment] 2024-07-17 20:27
I think this was fixed with https://github.com/timescale/timescaledb/pull/7091 which went out in 2.15.3

**Comment by jledentu** [comment] 2024-07-22 22:36
@RobAtticus Hi, no I reproduce the bug in 2.15.3 

```
docker run -p 5433:5432 -e POSTGRES_PASSWORD=password -e TS_TUNE_MEMORY="1GB" timescale/timescaledb-ha:pg15.7-ts2.15.3
```

I use PG15, and the fix you mention targets PG16.

Note that the bug doesn't occur if I disable optimizations:

```sql
SET LOCAL timescaledb.enable_optimizations TO true;
```

**Comment by RobAtticus** [comment] 2024-07-23 00:56
cc @fabriziomello since you did the original fix

**Comment by fabriziomello** [comment] 2024-07-27 19:26
> cc [@fabriziomello](https://github.com/fabriziomello) since you did the original fix

Looks like it is another problem. I had a look on it some days ago but didn't found the root cause. Will dig more on it next week.

**Comment by fabriziomello** [comment] 2024-07-29 13:59
The PR #7161 will fix it.

**Comment by jledentu** [comment] 2024-08-05 09:13
Thanks, I confirm that the 2.16.0 version does not have any error

**Closed** 2024-08-05 12:23 UTC
Labels: bug, time_bucket_gapfill

**Comment by henry701** [comment] 2024-11-14 17:21
> Note that the bug doesn't occur if I disable optimizations:
> 
> SET LOCAL timescaledb.enable_optimizations TO true;

For the ones who can't update their TimescaleDB, it worked for me without disabling all optimizations, by disabling this specific group instead:

`SET timescaledb.enable_chunkwise_aggregation to FALSE;`

**Comment by qeternity** [comment] 2025-05-02 20:37
This is still an issue in 2.19.0
