### ISSUE TITLE
Porting maxDataPoints from Graphite

### ISSUE THREAD

**Issue by Glandos** [timescale/timescaledb#822] opened 2018-10-29 16:49 UTC
When querying Graphite, there is a super useful (in my opinion) feature: `maxDataPoints`. This drastically reduces computation on both server and client (in my case, this is Grafana) when the client only asks for the max resolution of the screen.
Is there any way to do it in the current release of TimescaleDB? Is it planned?

**Comment by dianasaur323** [comment] 2018-10-31 18:38
Hey @svenklemm - is this similar to what min time interval does? or slightly different?

**Comment by svenklemm** [comment] 2018-11-03 14:10
Hi @Glandos you can achieve something similar with grafana and the postgres datasource by using the $__interval variable for your time grouping interval. This variable will get adjusted according to your selected timerange. You can set a lower minimum for that variable with min time interval.

**Comment by Glandos** [comment] 2018-11-06 09:51
The `$__interval` variable is only replaced by the min time interval, defined in the data source options or in the panel preferences. In my case, I have:
```json
{
  "from": "1541372400000",
  "to": "1541977199999",
  "queries": [
    {
      "refId": "A",
      "intervalMs": 300000,
      "maxDataPoints": 1680,
      "datasourceId": 1,
      "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",5m),\n  avg(temperature) AS \"temperature\"\nFROM temperatures\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1",
      "format": "time_series"
    }
  ]
}
```
But the `maxDataPoints` is ignored. If I set the interval to 5s, I get 25000 points. If I set it to 5m, I get only 420 points. I would like to have **at most** 1680 points (my screen available space): if less, then return all points, if more, group points using the given function (in this case `avg`).

I don't know if it's something that should be done in Grafana, TimescaleDB or both.

**Comment by svenklemm** [comment] 2020-10-13 12:53
Duplicate of #479

**Closed by svenklemm** 2020-10-13 12:53 UTC
Labels: community-request, enhancement
