### ISSUE TITLE
[Bug]: Restore failing and unable to insert data

### ISSUE THREAD

**Issue by smcbhj** [timescale/timescaledb#4166] opened 2022-03-14 14:37 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Restore

### What happened?

Hello,
we're tyring to restore a database.
we're using pg_dump.exe with custom format option and pg_restore.exe for restoration.

we're using a constraint and an index on our hypertable like the following before calling 
CREATE TABLE IF NOT EXISTS public."DoubleStream2" ("TimeStamp" TIMESTAMP NOT NULL, "ChannelId" INT NOT NULL, "Sample" DOUBLE PRECISION NULL, UNIQUE("TimeStamp", "ChannelId"));
SELECT create_hypertable("public."DoubleStream2"", "TimeStamp", if_not_exists => true);// this is not the real command it's only for demo purpose
CREATE UNIQUE INDEX IF NOT EXISTS "DoubleStream2_TimeStamp_ChannelId_idx" ON public."DoubleStream2" ("TimeStamp" ASC, "ChannelId");
the issue is during resotre these constraints cannot be restored 
![image](https://user-images.githubusercontent.com/101571925/158190422-7d3f28e9-5449-4cb0-8291-e0f9e1b1888d.png)

we're unable to insert data to the table even manually 
![image](https://user-images.githubusercontent.com/101571925/158190561-fa2018c7-bca6-45ad-81df-411540881c52.png)

we're stuck at this point and can't figure out what we missed or what we have to do .

thanks

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

14

### What operating system did you use?

Windows 10 x64

### What installation method did you use?

Not applicable

### What platform did you run on?

Not applicable

**Comment by smcbhj** [comment] 2022-03-15 15:04
> 

we did follow it and use the timescaledb_pre_restore and timescaledb_post_restore but it failed like shown in the powershell screenshot

**Comment by nikkhils** [comment] 2022-03-16 09:23
@smcbhj sorry I missed that earlier. 

Can you please share details on how/when the UNIQUE constraint was added to the `DoubleStream2` table? 

I am trying to reproduce this locally and I added an additional unique key constraint on the hypertable after creating it and before inserting data (I also tried a variation where I create a hypertable, insert data and then add a unique constraint later). Then I added some data and took a dump and restore following our documentation. So that seems to work ok enough. It will be great if we can get a reproducible scenario.

**Comment by smcbhj** [comment] 2022-03-16 10:01
we're using NpgsqlCommand to create the hypertable and the constraint, the resulting query from the command is 
CREATE TABLE IF NOT EXISTS public."DoubleStream2" ("TimeStamp" TIMESTAMP NOT NULL, "ChannelId" INT NOT NULL, "Sample" DOUBLE PRECISION NULL, UNIQUE("TimeStamp", "ChannelId"));
SELECT create_hypertable("public."DoubleStream2"", "TimeStamp", if_not_exists => true);// there's qutoes issue when i extracted this command

**Comment by nikkhils** [comment] 2022-03-17 13:02
@smcbhj your steps are not targeting the proper database. As per the documentation, you will need to tweak your commands to the below:

```
dropdb --username postgres --force --if-exists "JobTest001"
createdb --username postgres  "JobTest001"
createdb --username postgres  --dbname "JobTest001" --command "CREATE EXTENSION IF NOT EXISTS timescaledb"
psql --username postgres  --dbname "JobTest001" --command "SELECT timescaledb_pre_restore()"
pg_restore --username postgres  --dbname "JobTest001" /path/to/dumpfile
psql --username postgres  --dbname "JobTest001" --command "SELECT timescaledb_post_restore()"
```

Basically, you had forgotten to provide the `--dbname` option to the rest of the commands because of which the extension had not been created in the "JobTest001"  at all.

**Comment by nikkhils** [comment] 2022-03-17 13:07
I am closing this for now. Please open another issue if you have other issues here.

**Closed by nikkhils** 2022-03-17 13:07 UTC
Labels: bug, backup-and-restore
