### ISSUE TITLE
[Bug]: Insertion is interrupted by an error: cannot allocate memory for output buffer

### ISSUE THREAD

**Issue by ivashkevichdn** [timescale/timescaledb#5034] opened 2022-11-28 15:22 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Distributed hypertable, Multi-node

### What happened?

Encountered an error:

`ERROR: [dn1]: cannot allocate memory for output buffer`

after upgrading Timescale DB from 2.7.2 to 2.8.1.
This error occurs when writing to a distributed hyper table. If the size of one transaction in the total_bytes chunk < 2 GB, then the transaction is completed successfully. If exceeded, it is interrupted by an error:

`ERROR: [dn1]: cannot allocate memory for output buffer`

After rolling back TimescaleDB to version 2.7.2, this error is not observed.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.6

### What operating system did you use?

Ubuntu 20.04 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
2022-11-28 14:36:55.631 UTC [1366403] user@test_db WARNING:  only one data node was assigned to the hypertable
2022-11-28 14:36:55.631 UTC [1366403] user@test_db DETAIL:  A distributed hypertable should have at least two data nodes for best performance.
2022-11-28 14:36:55.631 UTC [1366403] user@test_db HINT:  Grant USAGE on data nodes and attach them to the hypertable.
2022-11-28 14:41:48.985 UTC [1366441] user@test_db ERROR:  [dn1]: cannot allocate memory for output buffer
	
2022-11-28 14:41:48.985 UTC [1366441] user@test_db STATEMENT:  INSERT INTO test_distributed_hypertable 
	SELECT '2050-01-01'::date,series,0,0,0,0,0,0,0,0,0,0,0,0,0
	FROM generate_series(1, 20000000, 1) series
2022-11-28 14:41:49.213 UTC [1366327] user@test_db LOG:  could not receive data from client: Connection reset by peer
2022-11-28 14:41:49.213 UTC [1366441] user@test_db LOG:  could not receive data from client: Connection reset by peer
2022-11-28 14:41:49.215 UTC [1366328] user@test_db LOG:  could not receive data from client: Connection reset by peer
2022-11-28 14:46:48.579 UTC [1366871] user@test_db ERROR:  [dn1]: cannot allocate memory for output buffer
	
2022-11-28 14:46:48.579 UTC [1366871] user@test_db STATEMENT:  INSERT INTO test_distributed_hypertable 
	SELECT '2050-01-01'::date,series,0,0,0,0,0,0,0,0,0,0,0,0,0
	FROM generate_series(1, 20000000, 1) series
2022-11-28 14:46:48.839 UTC [1366868] user@test_db LOG:  could not receive data from client: Connection reset by peer
2022-11-28 14:46:48.839 UTC [1366869] user@test_db LOG:  could not receive data from client: Connection reset by peer
2022-11-28 14:46:48.839 UTC [1366871] user@test_db LOG:  could not receive data from client: Connection reset by peer
```

### How can we reproduce the bug?

```bash
CREATE TABLE test_distributed_hypertable (
	create_date date NOT NULL,
	product_id int8 NOT NULL,
	size_id int8 NOT NULL,
	warehouse_id int8 NOT NULL,
	quantity int4 NOT NULL,
	diff_quantity int4 NOT NULL,
	orders int4 NOT NULL,
	incomes  int4 NOT NULL,
	"returns" int4 NOT NULL,
	proceeds float8 NOT NULL,
	price float8 NOT NULL,
	old_price float8 NOT NULL,
	discount int4 NOT NULL DEFAULT 0,
	basic_discount int4 NOT NULL DEFAULT 0,
	promo_discount int4 NOT NULL DEFAULT 0,
	CONSTRAINT test_distributed_hypertable_pk PRIMARY KEY (product_id, size_id, warehouse_id, create_date)
);
SELECT create_distributed_hypertable('test_distributed_hypertable', 'create_date', chunk_time_interval => '1d'::interval, data_nodes => '{ "dn1"}');


INSERT INTO test_distributed_hypertable 
SELECT '2050-01-01'::date,series,0,0,0,0,0,0,0,0,0,0,0,0,0
FROM generate_series(1, 20000000, 1) series;
```

**Comment by akuzm** [comment] 2022-11-28 15:32
This doesn't reproduce on main for me. Probably same as #4576, should be fixed in 2.9.0 which is planned for release in a couple of weeks.

**Comment by akuzm** [comment] 2022-11-28 15:41
Or this one: https://github.com/timescale/timescaledb/pull/4931 It says "compressed" but it has a small fix related to uncompressed distributed hypertables as well. Anyway, please check this on 2.9.0 when it's out.

**Comment by rrz** [comment] 2023-02-21 11:31
Same bug occured for me, using tsdb 2.9.2

**Comment by jnidzwetzki** [comment] 2023-02-27 10:33
Hello @rrz,

I tried to reproduce the problem in my local environment using PostgreSQL 14. Unfortunately, I was not able to reproduce this behavior so far. Could you share some additional information about your setup (i.e., the PostgreSQL version used and the number of data nodes)? In addition, might it be possible to share the table schema and query that is causing the error? This would help me a lot in reproducing the problem.

**Comment by rrz** [comment] 2023-02-27 10:49
Hello @jnidzwetzki,
I use postgresql 13 on centos 8 with timescaleDB 2.9.2 in 3 data nodes
What I am trying to do is moving zabbix trends from postgresql partitions to tsdb.
So, I have, for example, table `trends_2022_06` which contains about 36 Gb data, and I have `trends` table in same database, this `trends` table is hypertable for tsdb. And all I'm trying to do is select from `trends_2022_06` and insert into `trends`. And that's when I get this error, even though I'm limiting the select query by clock so it not get whole 36Gb data all at once. And I successfully can insert this if I limit the `select` very much, about 3 day chunk
And this error I get:
`ERROR: [zbx-data-01]: cannot allocate memory for output buffer`
where `zbx-data-01` is data node to which is writing data.
chunks for trends is 30 days.
No other logs in postgres.

**Comment by jnidzwetzki** [comment] 2023-02-27 14:44
Hello @rrz,

Thanks for all the information. Is the table `trends_2022_06` located on the data node or on the access node? I would like to reproduce the problem. Could you share the commands that you used to create the partitioned table, the commands to create the distributed hypertable, and the actual command which causes the problem?

**Comment by jnidzwetzki** [comment] 2023-02-28 11:42
Hello @ivashkevichdn,

I have re-run the steps you provided in my local environment. Unfortunately, I cannot reproduce the error in my environment so far. In my environment, inserting the data works as expected. I used TimescaleDB 2.9.2 and 2.10.0 on PostgreSQL 14.2 for the tests.

```sql
test2=# INSERT INTO test_distributed_hypertable 
SELECT '2050-01-01'::date,series,0,0,0,0,0,0,0,0,0,0,0,0,0
FROM generate_series(1, 20000000, 1) series;
INSERT 0 20000000

test2=# truncate test_distributed_hypertable;
TRUNCATE TABLE

test2=# INSERT INTO test_distributed_hypertable
SELECT '2050-01-01'::date,series,0,0,0,0,0,0,0,0,0,0,0,0,0
FROM generate_series(1, 30000000, 1) series;
INSERT 0 30000000

test2=# SELECT count(*) FROM test_distributed_hypertable;
  count   
----------
 30000000
(1 row)
```

I am using the default PostgreSQL configuration with the following custom settings:

```
# Add settings for extensions here
shared_preload_libraries = 'timescaledb'

max_locks_per_transaction = 500
max_prepared_transactions = 100
```

How does your PostgreSQL configuration look like? Have you adjusted any other values? If so, could you share them with us so I can set them in my environment as well?

**Comment by ivashkevichdn** [comment] 2023-03-18 00:27
Hello @niedzwiedzki,

I conducted a series of tests on 2 instances of the TimescaleDB multi-node, built from scratch.

1. on 2 docker containers with the image `timeline/timescaledb:2.10.1-pg14`
2. on 2 VDS servers on `Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-135-generic x86_64)` + `Postgresql 14.7` + `TimescaleDB 2.10.1` with installation according to [instructions](https://docs.timescale.com/install/latest/self-hosted/installation-linux/#installing-self-hosted-timescaledb-on-debian-based-systems). To configure PostgreSQL, I used `timescaledb-tune` on 2 servers

For a multi-node cluster, the configuration was based on a minimal set of settings. And for the setup I used the documentation: [setup-password-authentication](https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-auth/#setting-up-password-authentication ) , [multi-node-configuration](https://docs.timescale.com/timescaledb/latest/how-to-guides/multinode-timescaledb/multinode-config/#multi-node-configuration).

Almost identical `postgresql.conf` parameters were used for the two versions.

It was noticed that in the 1st version of the assembly (in Docker containers) this problem has not been reproduced. But on the 2nd option (from 2 VDS servers), he constantly fell into error
`ERROR: [dn1]: failed to allocate memory for output buffer`

What the PostgreSQL configuration says does not affect the error reproduction. We can assume this is due to the Ubuntu 20.04 OS and/or the TimescaleDB build for this OS.

**Comment by ivashkevichdn** [comment] 2023-03-18 22:30
Hello @Niedzwiedzki,

Tell me, what information should I give you? But I assure you that this does not affect the `PostgreSQL` configuration in any way, as I wrote to you earlier. I assume that this error manifests itself when building a timescaledb deb package for `Ubuntu 20.04`. In other operating systems, I have not checked. I think I'll check `Ubuntu 22.04` later.

**Comment by ivashkevichdn** [comment] 2023-03-20 19:23
Hello @Niedzwiedzki

After conducting 2 more additional tests:

1. compiled from source `TimescalDB 2.10.1` for `PostgreSQL 14` under `Ubuntu 20.04 LTS`
2. compiled from source `TimescalDB 2.10.1` for `PostgreSQL 14` under `Ubuntu 22.04 LTS`

In both variants, the PostgreSQL configuration was identical and configured for a multi-node cluster.

The test showed that in option 1, `INSERT` filed an error `ERROR: [dn1]: failed to allocate memory for output buffer`
in the second option, the test was successful.

We conclude that this bug manifests itself on `Ubuntu 20.04 LTS`.

**Comment by ivashkevichdn** [comment] 2023-03-21 11:46
Hi @lkshminarayanan,

Thanks for the reply, but I don't have enough memory. I didn't notice anything missing from the resources.
Please note that on the same machine I built a cluster on Docker containers and built it natively - [described](https://github.com/timescale/timescaledb/issues/5034#issuecomment-1474541673).

I'm very surprised you don't reproduce the issue!

I just don't know how to solve this issue anymore and how exactly to show the community to reproduce my issue.

**Comment by lkshminarayanan** [comment] 2023-03-22 11:44
Hi @ivashkevichdn,

> Thanks for the reply, but I don't have enough memory.

You meant to say you **do** have enough memory right?
> Please note that on the same machine I built a cluster on Docker containers and built it natively - [described](https://github.com/timescale/timescaledb/issues/5034#issuecomment-1474541673).

Okay.
> I just don't know how to solve this issue anymore and how exactly to show the community to reproduce my issue.

No need to worry. I'll investigate the code to check what could have triggered such an error. 
Btw, you have reported two errors : `ERROR: [dn1]: failed to allocate memory for output buffer` and `ERROR: [dn1]: cannot allocate memory for output buffer`. Are you getting different errors under different scenarios?

**Comment by ivashkevichdn** [comment] 2023-03-22 12:38
Hi @lkshminarayanan,

> You meant to say you do have enough memory right?

Sorry. Yes, there is enough memory on the server.

>Btw, you have reported two errors : `ERROR: [dn1]: failed to allocate memory for output buffer` and `ERROR: [dn1]: cannot allocate memory for output buffer`. Are you getting different errors under different scenarios?

At the moment I am getting this error:

```
test_db=# INSERT INTO test_distributed_hypertable 
SELECT '2050-01-01'::date,series,0,0,0,0,0,0,0,0,0,0,0,0,0
FROM generate_series(1, 15000000, 1) series;
ERROR:  [dn1]: cannot allocate memory for output buffer
test_db=# 
```
TimescaleDB 2.10.1. compiled from sources.

`ERROR: [dn1]: failed to allocate memory for output buffer`
I got this error when `TimescaleDB` was installed from the deb package.
I believe these errors occur for the same reason.

Later I will try to reproduce this problem on an image from [Ubuntu 20.04](https://releases.ubuntu.com/focal/)   
Since we previously used the `Ubuntu 20.04` image from **Hetzner Cloud**

**Comment by ivashkevichdn** [comment] 2023-03-22 18:47
Hello, @lakshminarayanan,

I tried to reproduce this problem on a **VDS** with resources 4 times less than before (2 CPU, 2 GB of RAM, 25 GB SSD) on [Ubuntu 20.04 LTS](https://releases.ubuntu.com/focal/).

The test result showed that it passes successfully, without any problems.
Which suggests that this issue manifests itself in installed images from **Hetzner Cloud** or when fine-tuning the OS.

Tell me, what should I pay attention to in order to identify this issue, what could it be related to?

Thank you for your help!

**Comment by lkshminarayanan** [comment] 2023-03-23 12:30
Hi @ivashkevichdn,

I am glad you were able to try this out in standard Ubuntu images without running into the error!

Issue #4611 has been fixed since [2.8.0](https://github.com/timescale/timescaledb/blob/72c0f5b25e569015aacb98cc1be3169a1720116d/CHANGELOG.md?plain=1#L305). So, this is not that. 
It could be a similar, related bug but if that is the case, it should manifest itself in other platforms/setups as well. But we are able to run it without any issues in the standard images. I also tried inserting large number of rows(~300M) to check for any memory leaks but I didn't find anything so far. So, I'm still not sure if this is a bug.

This error is thrown by the postgres code at [fe-misc.c:340](https://github.com/postgres/postgres/blob/adedf54e659ea37316a21c8d5a7aa8f711213d1c/src/interfaces/libpq/fe-misc.c#L340-L341). It occurs when a `realloc` call fails. This mainly happens if you do not have enough memory in the system. But if that is not the case, I'm not sure what else could have been the issue. 

Another weird thing is, I'm unable to find the source of the `failed to allocate memory for output buffer`. Its neither in TimescaleDB nor in Postgres source code. I have checked old/new versions but I can't find the source which returns this error.  So, I'm not sure how to proceed with this further.

**Comment by ivashkevichdn** [comment] 2023-03-23 14:24
Hello, @lakshminarayanan,

> Issue https://github.com/timescale/timescaledb/pull/4611 has been fixed since [2.8.0](https://github.com/timescale/timescaledb/blob/72c0f5b25e569015aacb98cc1be3169a1720116d/CHANGELOG.md?plain=1#L305). So, this is not that.

I follow the logic. If I do not observe this issue in <= `2.7.2`, and after upgrading to version >=`2.8.1`, I observe this issue.
However, in `2.8.0`. there was a issue [Bg #4728](https://github.com/timescale/timescaledb/issues/4728 ), which prevented us from using this version. And we rolled back to version `2.7.2`, which we are currently working on because of an error `cannot allocate memory for output buffer`.
I assumed that fixing the bug https://github.com/timescale/timescaledb/pull/4611 led to my unspecified problem!?

>This error is thrown by the postgres code at [fe-misc.c:340](https://github.com/postgres/postgres/blob/adedf54e659ea37316a21c8d5a7aa8f711213d1c/src/interfaces/libpq/fe-misc.c#L340-L341). It occurs when a realloc call fails. This mainly happens if you do not have enough memory in the system. But if that is not the case, I'm not sure what else could have been the issue.

Can there be a reason for limitations in the operating system kernel or network driver?

>Another weird thing is, I'm unable to find the source of the failed to allocate memory for output buffer. Its neither in TimescaleDB nor in Postgres source code. I have checked old/new versions but I can't find the source which returns this error. So, I'm not sure how to proceed with this further.

Perhaps, unwittingly, I will deceive you. And I got this error from **DBeaver** by reformulating the error `ERROR:  [dn1]: cannot allocate memory for output buffer`. Since I work in this Database Tool

Thank you for helping with the solution of the issue!

**Comment by lkshminarayanan** [comment] 2023-03-25 09:29
> I assumed that fixing the bug https://github.com/timescale/timescaledb/pull/4611 led to my unspecified problem!?

It is possible but without reproducing it, I'm unable to confirm if that's the case. Next time you hit the issue with the Hetzner cloud image, can you check the memory consumption of the postgres backend and let us know if you notice anything weird? 

> Can there be a reason for limitations in the operating system kernel or network driver?

One other possible reason could be that the system has enough memory but it is fragmented a lot such that there is no contiguous memory available to realloc. But if you are able to reproduce this in a fresh system then there is very low chances of memory fragmentation. I do not know any other limitations that could cause this issue. 

> Perhaps, unwittingly, I will deceive you. And I got this error from DBeaver by reformulating the error ERROR:  [dn1]: cannot allocate memory for output buffer. Since I work in this Database Tool
>
>Thank you for helping with the solution of the issue!

That's okay! You're welcome :)

**Comment by lkshminarayanan** [comment] 2023-04-03 08:56
Closing this for now. Please let us know if you need more help with this.

**Closed by lkshminarayanan** 2023-04-03 08:56 UTC
Labels: bug
