### ISSUE TITLE
[Bug]: TOAST table size larger after compression

### ISSUE THREAD

**Issue by GStechschulte** [timescale/timescaledb#6536] opened 2024-01-18 06:43 UTC
### What type of bug is this?

Performance issue, Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

Problem: After compression, almost all of the data is moved to TOAST resulting in slow queries. 

timescaledb = 2.13.0 
PostgreSQL =  16.1

Unfortunately, I cannot share the data. However, I will attempt to be specific in the use case.

I have a main hypertable of the form:

```sql
CREATE TABLE data (
	kks_uid INTEGER  NOT NULL,
	time    TIMESTAMPTZ NOT NULL,
	measurement NUMERIC NOT NULL,
	FOREIGN KEY(kks_uid) REFERENCES parent(kks_uid),
	PRIMARY KEY(kks_uid, time)
);

SELECT create_hypertable('data', by_range('time', INTERVAL '6 days'));

ALTER TABLE data
SET
  (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'kks_uid',
    timescaledb.compress_orderby = 'time desc'
  );

SELECT add_compression_policy('data', INTERVAL '1d');
```

where the chunk time interval was set based on the following calculation:

$$(8 \text{GB RAM} * 0.25)*1000 = 2000 \text{MB}$$

$$2000 \text{MB} / 350 \text{MB daily average size} \approx 6 \text{days}$$

In the `parent` table, there are 75,000 unique ids. Between 6 to 10 million rows of data are inserted into this hypertable throughout the day. However, the number of measurements taken in a day is not uniform across all sensors, i.e. sensor id = 10 may take 100,000 measurements, while sensor id = 15 may take 1,000 measurements.

Below is the before and after compression sizes of the hypertable:

|compression|table_gb|toast_gb|index_gb|total_gb|
|---|---|---|---|---|
|before|157|0|142|299|
|after|0.915|25.598|0.089|26.602|

There is good compression here, however at the cost of the majority of the data now residing in TOAST. When I attempt to query the compressed data, it takes a significantly longer time to query.

Below are the explain logs for a query before and after compression:

```sql
SELECT time_bucket('1s', d.time) as time_interval,
  avg(d.measurement) as avg_measurement
FROM data d
LEFT JOIN attr a
USING (kks_uid)
WHERE a.description_short = '<some text value>'
GROUP BY time_interval
```

Explain before compression:

```
|Node|
|---|
||1.|Aggregate|
||2.|Gather Merge|
||3.|Aggregate|
||4.|Sort|
||5.|Nested Loop Inner Join|
||6.|Seq Scan on attr as a<br><br>- **Filter**: ((description_short)::text = 'Ha3 Allgem Isogyr, BlindleistungReg Stellwert'::text)|
||7.|Append|
||8.|Index Scan using 184_368_data_v2_pkey on _hyper_4_184_chunk as d_1<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||9.|Index Scan using 185_370_data_v2_pkey on _hyper_4_185_chunk as d_2<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||10.|Index Scan using 186_372_data_v2_pkey on _hyper_4_186_chunk as d_3<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||11.|Index Scan using 187_374_data_v2_pkey on _hyper_4_187_chunk as d_4<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|

... (index scans)

||31.|Bitmap Heap Scan on _hyper_4_207_chunk as d_24<br><br>- **Recheck Cond**: (kks_uid = a.kks_uid)|
||32.|Bitmap Index Scan using 207_414_data_v2_pkey<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||33.|Index Scan using 208_416_data_v2_pkey on _hyper_4_208_chunk as d_25<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||34.|Index Scan using 209_418_data_v2_pkey on _hyper_4_209_chunk as d_26<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||35.|Bitmap Heap Scan on _hyper_4_210_chunk as d_27<br><br>- **Recheck Cond**: (kks_uid = a.kks_uid)|
||36.|Bitmap Index Scan using 210_420_data_v2_pkey<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||37.|Index Scan using 211_422_data_v2_pkey on _hyper_4_211_chunk as d_28<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||38.|Index Scan using 212_424_data_v2_pkey on _hyper_4_212_chunk as d_29<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||39.|Index Scan using 213_426_data_v2_pkey on _hyper_4_213_chunk as d_30<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||40.|Index Scan using 214_428_data_v2_pkey on _hyper_4_214_chunk as d_31<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||41.|Index Scan using 215_430_data_v2_pkey on _hyper_4_215_chunk as d_32<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||42.|Index Scan using 216_432_data_v2_pkey on _hyper_4_216_chunk as d_33<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||43.|Index Scan using 217_434_data_v2_pkey on _hyper_4_217_chunk as d_34<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||44.|Bitmap Heap Scan on _hyper_4_218_chunk as d_35<br><br>- **Recheck Cond**: (kks_uid = a.kks_uid)|
||45.|Bitmap Index Scan using 218_436_data_v2_pkey<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||46.|Bitmap Heap Scan on _hyper_4_219_chunk as d_36<br><br>- **Recheck Cond**: (kks_uid = a.kks_uid)|
||47.|Bitmap Index Scan using 219_438_data_v2_pkey<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||48.|Bitmap Heap Scan on _hyper_4_220_chunk as d_37<br><br>- **Recheck Cond**: (kks_uid = a.kks_uid)|
||49.|Bitmap Index Scan using 220_440_data_v2_pkey<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
||50.|Bitmap Heap Scan on _hyper_4_221_chunk as d_38<br><br>- **Recheck Cond**: (kks_uid = a.kks_uid)|
Cond**: (kks_uid = a.kks_uid)|

... (combination of bitmap heap and index scans)

||341.|Bitmap Index Scan using 549_915_data_v2_pkey<br><br>- **Index Cond**: (kks_uid = a.kks_uid)|
```

Explain after compression:

```
|Node|
|---|
||1.|Aggregate|
||2.|Gather Merge|
||3.|Aggregate|
||4.|Sort|
||5.|Hash Inner Join<br><br>- **Hash Cond**: (d_27.id = a.id)|
||6.|Append|
||7.|Custom Scan on _hyper_4_210_chunk as d_27|
||8.|Seq Scan on compress_hyper_5_576_chunk as compress_hyper_5_576_chunk|
||9.|Custom Scan on _hyper_4_195_chunk as d_12|
||10.|Seq Scan on compress_hyper_5_561_chunk as compress_hyper_5_561_chunk|
||11.|Custom Scan on _hyper_4_214_chunk as d_31|
||12.|Seq Scan on compress_hyper_5_580_chunk as compress_hyper_5_580_chunk|

... (custom and sequential scans for all of the compressed chunks)

||369.|Custom Scan on _hyper_4_208_chunk as d_25|
||370.|Seq Scan on compress_hyper_5_574_chunk as compress_hyper_5_574_chunk|
||371.|Custom Scan on _hyper_4_494_chunk as d_151|
||372.|Seq Scan on compress_hyper_5_700_chunk as compress_hyper_5_700_chunk|
||373.|Hash|
||374.|Index Scan using descr_name on parent as a|
```

The uncompressed data query uses a combination of index scans, and bitmap heap and index scans. However, the compressed data query uses mainly a custom sequential scan.

I am thinking a lot of the data is going to TOAST because of the high cardinality of the data. A chunk consists of 6 days and in those six days some sensors are taking many more measurements than others. Since I segment by `kks_uid`, some ids [compressed columnar batches](https://www.timescale.com/blog/building-columnar-compression-in-a-row-oriented-database/) (arrays) will have significantly more data in them. And with a NUMERIC data type, this may mean a high cardinality.

I also noticed in the blog [Compression Faceoff](https://www.timescale.com/blog/postgres-toast-vs-timescale-compression/) that in both tables comparing Postgres native TOAST and timescale's compression, the TOAST size (18 GB) is equal to the table size (18 GB). But nothing was said in that comparison how timescale compressed data being moved to TOAST could affect reads.

Further in that blog, it was discussed how timescale's compression works. The point this issue is interested in is the following:

> After Timescale compression, if the size of the compressed row exceeds the `TOAST_TUPLE_THRESHOLD`(2 kB), that row is relocated to a secondary storage location (the toast table), and a pointer is established within the chunk to reference this data.

Which seems to be what is happening in my use-case (and in the blog compression comparison tables). And as I have stated, I think this is because of high cardinality.

But I am really surprised how almost all of the data is moved to TOAST?

Thanks for your time! Cheers!

### TimescaleDB version affected

2.13.0

### PostgreSQL version used

16.1

### What operating system did you use?

Mac OS 14.2.1 (M2 Pro)

### What installation method did you use?

Homebrew

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_See above for explain logs_

**Comment by nikkhils** [comment] 2024-01-18 07:43
@GStechschulte this is working as intended. 

During compression, we take upto  1000 rows in one batch and compress them and store them together. Given the data layout mentioned by you, most of the batches will have many rows in them and hence such resultant large batch row will be TOASTED out into the corresponding toast table.

Additional Index information gets lost currently when we use  compression. So, if queries need data from compressed chunks then that will be slower. We are working on adding indexes on compressed chunks in future releases (timeline not yet available).

If your queries need to frequently access data from compressed chunks then you need to reconsider the compression strategy and compress data later as it ages out from the query usage requirements.

**Comment by akuzm** [comment] 2024-01-18 10:40
The fact  that everything is in TOAST tables is expected, as Nikhil mentioned, and isn't a problem by itself. The reason you're seeing worse plans seems to be that the entire compressed table is read out for a hash join. And before it only read the ids where the description matched. Can you try to rewrite it as something like:
```
SELECT time_bucket('1s', d.time) as time_interval,
  avg(d.measurement) as avg_measurement
FROM data d
WHERE kks_uid = ANY((select array_agg(kks_uid) from a where a.description_short = '<some text value>'))
GROUP BY time_interval
```
Basically it rewrites the join as an IN query, that might force Postgres to use a more efficient query plan. Does this help your query?
Please run `explain (analyze, buffers, verbose, format json)` for it, and attach the resulting json so that we can check it. There are visualizers for json explain, it will be easier to read.

By the way, the problem you're experiencing might be similar to this one: https://github.com/timescale/timescaledb/issues/6424

**Comment by GStechschulte** [comment] 2024-01-18 12:31
@nikkhils thank you for the quick answer. I think I understand this, but just to clarify: 

In my use case, with the chunk time interval set to 6 days, say there are 1,000,000 records inserted per day for a total of 6,000,000 records.  The compression policy will consolidate the records within this chunk into a single row with an array-like structure. Since my chunk contains 6,000,000 records, there may be up to 6,000,000 / 1,000 = 6,000 rows (or batches as you call it); each storing potentially thousands of values per arrayed column. When the size of one of the 6,000 rows exceeds 2kB, that row is reallocated to the TOAST table. 

Regarding indexes, I thought that currently timescale drops indexes and then adds indexes based on the columns in `segmentby`? 

Thanks for the information and help. Much appreciated 👍🏼

**Comment by GStechschulte** [comment] 2024-01-18 13:28
@akuzm Thanks for the query. Although I had to remove the `array_agg` function since I was getting the following error

```
ERROR:  operator does not exist: integer = integer[]
```

However, it doesn't seem to help. The query planner looks the same --> [query_planner_compressed_chunks.csv](https://github.com/timescale/timescaledb/files/13977059/query_planner_compressed_chunks.csv)

Thanks for your time and help!

**Comment by akuzm** [comment] 2024-01-18 13:32
It doesn't work the way it should without `array_agg`. The point is to transform a join to a scalar array operation. Maybe it should be `kks_uid = ANY((select array_agg(kks_uid) from a where a.description_short = '<some text value>')::integer[])`, not sure.

I think I managed to find the reason for this problem, so hopefully in the next release it will be fixed and you'll get the proper index scans for `kks_uid` segmentby column on compressed chunks as well.

**Comment by GStechschulte** [comment] 2024-01-18 13:54
@akuzm ahh yes. Apologies. Indeed, transforming the join to a scalar array operation changes the query plan. 

Updated query plan --> [Uploading query_planner_compressed_chunks.csv]()

Wow, great news. Looking forward to the next release. Thanks for all your help 👍🏼

**Closed** 2024-01-23 09:18 UTC
Labels: bug
