### ISSUE TITLE
[Bug]: Fetching latest row by time on a hypertable where inserts are done in a compressed chunk - results in scanning all chunks

### ISSUE THREAD

**Issue by hardikm10** [timescale/timescaledb#5521] opened 2023-04-04 06:28 UTC
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Compression, Query executor

### What happened?

On a hypertable that has compression enabled, if an insert has been done into a compressed chunk - the query "select * from hypertable order by time desc limit 1" touches all the chunks which it wasn't doing before the insert, thus seems like an unexpected behavoir. Also, the compressed chunks are decompressed too which may take a toll on query performance.

Recompressing the chunk again OR running the compression policy, both resolves the issue which is interesting to note.

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

PostgreSQL 15.2

### What operating system did you use?

Timescale Cloud

### What installation method did you use?

Other

### What platform did you run on?

Timescale Cloud

### Relevant log output and stack trace

```bash
-- output as expected, test 1
explain analyze select * from sensor_data order by time desc limit 1;
                                                                                     QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.29..0.32 rows=1 width=28) (actual time=0.012..0.012 rows=1 loops=1)
   ->  Custom Scan (ChunkAppend) on sensor_data  (cost=0.29..2242.42 rows=81055 width=28) (actual time=0.011..0.011 rows=1 loops=1)
         Order: sensor_data."time" DESC
         ->  Index Scan using _hyper_18_5030_chunk_sensor_data_time_idx on _hyper_18_5030_chunk  (cost=0.29..2242.42 rows=81055 width=28) (actual time=0.010..0.011 rows=1 loops=1)
         ->  Index Scan using _hyper_18_5029_chunk_sensor_data_time_idx on _hyper_18_5029_chunk  (cost=0.42..2978.27 rows=107590 width=28) (never executed)
         ->  Index Scan using _hyper_18_5028_chunk_sensor_data_time_idx on _hyper_18_5028_chunk  (cost=0.42..2978.27 rows=107590 width=28) (never executed)
         ->  Index Scan using _hyper_18_5027_chunk_sensor_data_time_idx on _hyper_18_5027_chunk  (cost=0.29..2015.04 rows=72790 width=28) (never executed)
 Planning Time: 0.501 ms
 Execution Time: 0.033 ms
(9 rows)


-- output as expected, test 2
explain analyze select * from sensor_data order by time desc limit 1;
                                                                                     QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.29..0.32 rows=1 width=28) (actual time=0.015..0.017 rows=1 loops=1)
   ->  Custom Scan (ChunkAppend) on sensor_data  (cost=0.29..2242.42 rows=81055 width=28) (actual time=0.015..0.016 rows=1 loops=1)
         Order: sensor_data."time" DESC
         ->  Index Scan using _hyper_18_5030_chunk_sensor_data_time_idx on _hyper_18_5030_chunk  (cost=0.29..2242.42 rows=81055 width=28) (actual time=0.014..0.014 rows=1 loops=1)
         ->  Index Scan using _hyper_18_5029_chunk_sensor_data_time_idx on _hyper_18_5029_chunk  (cost=0.42..2978.27 rows=107590 width=28) (never executed)
         ->  Index Scan using _hyper_18_5028_chunk_sensor_data_time_idx on _hyper_18_5028_chunk  (cost=0.42..2978.27 rows=107590 width=28) (never executed)
         ->  Custom Scan (DecompressChunk) on _hyper_18_5027_chunk  (cost=0.08..4535.46 rows=450000 width=28) (never executed)
               ->  Sort  (cost=0.00..0.00 rows=0 width=0) (never executed)
                     Sort Key: compress_hyper_19_5031_chunk._ts_meta_sequence_num
                     ->  Seq Scan on compress_hyper_19_5031_chunk  (cost=0.00..14.50 rows=450 width=152) (never executed)
 Planning Time: 0.815 ms
 Execution Time: 0.066 ms
(12 rows)

-- output NOT as expected, it's touching a row across all of the chunks AND the compressed chunks appears to be fully decompressed., test 3
explain analyze select * from sensor_data order by time desc limit 1;
                                                                                     QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=1881.69..1881.71 rows=1 width=28) (actual time=23.671..23.675 rows=1 loops=1)
   ->  Merge Append  (cost=1881.69..23947.98 rows=814435 width=28) (actual time=23.670..23.673 rows=1 loops=1)
         Sort Key: _hyper_18_5030_chunk."time" DESC
         ->  Index Scan using _hyper_18_5030_chunk_sensor_data_time_idx on _hyper_18_5030_chunk  (cost=0.29..2242.42 rows=81055 width=28) (actual time=0.010..0.010 rows=1 loops=1)
         ->  Index Scan using _hyper_18_5029_chunk_sensor_data_time_idx on _hyper_18_5029_chunk  (cost=0.42..2978.27 rows=107590 width=28) (actual time=0.010..0.011 rows=1 loops=1)
         ->  Index Scan using _hyper_18_5028_chunk_sensor_data_time_idx on _hyper_18_5028_chunk  (cost=0.42..2978.27 rows=107590 width=28) (actual time=0.010..0.010 rows=1 loops=1)
         ->  Sort  (cost=2264.50..3389.50 rows=450000 width=28) (actual time=23.626..23.626 rows=1 loops=1)
               Sort Key: _hyper_18_5027_chunk."time" DESC
               Sort Method: top-N heapsort  Memory: 25kB
               ->  Custom Scan (DecompressChunk) on _hyper_18_5027_chunk  (cost=0.03..14.50 rows=450000 width=28) (actual time=0.094..12.203 rows=68200 loops=1)
                     ->  Seq Scan on compress_hyper_19_5031_chunk  (cost=0.00..14.50 rows=450 width=148) (actual time=0.006..0.020 rows=69 loops=1)
         ->  Sort  (cost=1525.00..1695.50 rows=68200 width=28) (actual time=0.011..0.012 rows=1 loops=1)
               Sort Key: _hyper_18_5027_chunk."time" DESC
               Sort Method: quicksort  Memory: 25kB
               ->  Seq Scan on _hyper_18_5027_chunk  (cost=0.00..1184.00 rows=68200 width=28) (actual time=0.006..0.006 rows=1 loops=1)
 Planning Time: 0.447 ms
 Execution Time: 23.715 ms
(17 rows)

-- output as expected, test 4
explain analyze select * from sensor_data order by time desc limit 1;
                                                                                     QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.29..0.32 rows=1 width=28) (actual time=0.010..0.011 rows=1 loops=1)
   ->  Custom Scan (ChunkAppend) on sensor_data  (cost=0.29..2109.29 rows=75900 width=28) (actual time=0.009..0.010 rows=1 loops=1)
         Order: sensor_data."time" DESC
         ->  Index Scan using _hyper_18_5030_chunk_sensor_data_time_idx on _hyper_18_5030_chunk  (cost=0.29..2109.29 rows=75900 width=28) (actual time=0.009..0.009 rows=1 loops=1)
         ->  Index Scan using _hyper_18_5029_chunk_sensor_data_time_idx on _hyper_18_5029_chunk  (cost=0.42..2802.32 rows=100800 width=28) (never executed)
         ->  Index Scan using _hyper_18_5028_chunk_sensor_data_time_idx on _hyper_18_5028_chunk  (cost=0.42..2802.32 rows=100800 width=28) (never executed)
         ->  Custom Scan (DecompressChunk) on _hyper_18_5027_chunk  (cost=0.07..694.97 rows=69000 width=28) (never executed)
               ->  Sort  (cost=0.00..0.00 rows=0 width=0) (never executed)
                     Sort Key: compress_hyper_19_5032_chunk._ts_meta_sequence_num
                     ->  Seq Scan on compress_hyper_19_5032_chunk  (cost=0.00..2.69 rows=69 width=152) (never executed)
 Planning Time: 1.030 ms
 Execution Time: 0.043 ms
(12 rows)
```

### How can we reproduce the bug?

```bash
drop table sensor_data;

create table sensor_data(
time timestamptz not null,
sensor_id integer not null,
cpu double precision null,
temperature double precision null );

select from create_hypertable('sensor_data','time');

INSERT INTO sensor_data
SELECT
time + (INTERVAL '1 minute' * random()) AS time,
sensor_id,
random() AS cpu,
random()* 100 AS temperature
FROM
generate_series(now() - INTERVAL '1 months', now() - INTERVAL '1 week', INTERVAL '10 minute') AS g1(time),
generate_series(1, 100, 1 ) AS g2(sensor_id)
ORDER BY
time;

\d+ sensor_data


SELECT c.chunk_name,c.range_start,c.range_end,c.is_compressed,pg_size_pretty(d.total_bytes) FROM public.chunks_detailed_size('public.sensor_data') d, timescaledb_information.chunks c WHERE d.chunk_name=c.chunk_name order by c.range_start;

alter table sensor_data set (timescaledb.compress, timescaledb.compress_orderby = 'time DESC');

-- output as expected, test 1
explain analyze select * from sensor_data order by time desc limit 1;

-- compressing the oldest chunk
select compress_chunk(i) from show_chunks('sensor_data', older_than => INTERVAL '3 weeks') i \gset

-- output as expected, test 2
explain analyze select * from sensor_data order by time desc limit 1;

-- inserting one record into the compressed chunk
INSERT INTO sensor_data VALUES (now() - INTERVAL '4 weeks', 1, 0.5, 50);

-- output NOT as expected, it's touching a row across all of the chunks AND the compressed chunks appears to be fully decompressed., test 3
explain analyze select * from sensor_data order by time desc limit 1;

-- recompress the chunk to get the expected output OR run CALL run_job(compression_job_id);
CALL recompress_chunk(':compress_chunk');

-- output as expected, test 4
explain analyze select * from sensor_data order by time desc limit 1;
```

**Comment by konskov** [comment] 2023-04-04 07:25
Thank you for the detailed reproduction information @hardikm10, I was able to reproduce this exact behavior.

**Comment by kgyrtkirk** [comment] 2023-04-13 12:50
notes:
* the chunk in test#3 is `partial` ; meaning it has compressed and non-compressed pieces as well
* a `topNkey` scan is being done on the compressed chunk


possible option could be:
## A) target `time` sort with limit
* in case there are no segmentby keys in the orderby/group/etc
* request for: `order by time desc` of the compressed chunk with a limit of `L`

this could maximize the overhead to scan only `1000L` rows instead of the whole partial chunk

I think this could be allowed - in general if the primary sort key is `time` (and other keys are only non-segmentby columns) 


## B `ChunkAppend` is not kicking in for this `Merge Append`
* because it contains a chunk which is dirty - I'm not sure if that restriction is neccessary - since because of `Merge Append` the `time` order is already ensured with `Sort` operators 
* this could help to not even start reading the  `IndexScan`-s ; there might be more than a few

## C) time ordered reading of compressed rows
#5530

**Comment by lkshminarayanan** [comment] 2023-09-01 07:33
Fixed in recent versions.

**Closed by lkshminarayanan** 2023-09-01 07:33 UTC
Labels: bug, performance, compression
