### ISSUE TITLE
tableoid not set correctly for queries on distributed hypertables

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#2528] opened 2020-10-12 05:00 UTC
Tableoid for queries on distributed hypertables is set to hypertable instead of chunk when timescaledb.enable_per_data_node_queries is true
```
dev=# select tableoid::regclass,* from metrics_dist where device_id = 1;
   tableoid   |          time          | device_id | value
--------------+------------------------+-----------+-------
 metrics_dist | 2000-01-01 00:00:00+01 |         1 |   0.5
(1 row)
dev=# set timescaledb.enable_per_data_node_queries to false;
SET
dev=# select tableoid::regclass,* from metrics_dist where device_id = 1;
                   tableoid                   |          time          | device_id | value
----------------------------------------------+------------------------+-----------+-------
 _timescaledb_internal._dist_hyper_9_14_chunk | 2000-01-01 00:00:00+01 |         1 |   0.5
(1 row)
```

**Comment by erimatnor** [comment] 2020-10-13 08:53
Could you provide some more information and a way to reproduce this issue?

**Comment by svenklemm** [comment] 2020-10-13 11:02
tableoid is a system column that identifies the relation a tuple is originating from. For a distributed hypertable this is set to the hypertable which is wrong since hypertable has no tuples.
To reproduce:
```
SELECT tableoid::regclass, * FROM dist_insert LIMIT 10;
  tableoid   |              inserted               | partkey |       value
-------------+-------------------------------------+---------+--------------------
 dist_insert | Wed Apr 17 16:03:48.482009 2019 PDT | 0       |  0.143692847820045
 dist_insert | Wed Apr 17 05:25:54.923609 2019 PDT | 0       |  0.919203089383576
 dist_insert | Tue Apr 16 16:51:13.461209 2019 PDT | 3       |  0.501142786979077
 dist_insert | Tue Apr 16 19:10:08.123609 2019 PDT | 3       |  0.977845790681446
 dist_insert | Sun Apr 14 14:47:26.776409 2019 PDT | 7       |  0.361208168566694
 dist_insert | Thu Feb 06 12:56:44.776409 2020 PST | 0       |  0.482509741016958
 dist_insert | Mon Feb 10 13:44:08.891609 2020 PST | 0       |  0.617650506760175
 dist_insert | Wed Feb 12 01:13:09.304409 2020 PST | 3       |  0.780974726880007
 dist_insert | Mon Feb 10 09:18:49.518809 2020 PST | 3       | 0.0343540287821931
 dist_insert | Tue Feb 11 00:15:07.902809 2020 PST | 7       |   0.72528391897669
(10 rows)
```

**Comment by erimatnor** [comment] 2020-11-26 10:47
Some context. When `timescaledb.enable_per_data_node_queries=true`, the access node performs a "data node scan" instead of a chunk-by-chunk scan. This is a lot more efficient since there is only one remote query/scan per data node instead of one remote query/scan per chunk. However, for a data node scan the information about which chunk a tuple comes from is lost and it is not trivially added back. Conceptually, you are just scanning a data node, so there is no single notion of a chunk being scanned. Therefore, the solution initially implemented was to use the tableoid of the hypertable instead since conceptually this is a scan of the larger hypertable. (Following the hypertable abstraction, we often want to maintain the notion of a large continuous table.)

Now, there are other ways this could be handled (listing the most prominent ways here):

1. Raise an error when tableoid is specified in the query and we are doing a data node scan.
2. Try to reverse map a received tuple to the local chunk OID on the AN. We could, for instance, try to return the internal `chunk_id` (not OID) as part of the tuple returned from the DN and then map it back to the local OID on the AN. This requires multiple levels of mappings (from DN `chunk_id` to AN chunk_id, and then then to AN OID). It is also non-trivial to get the DN's `chunk_id` included in the returned result, since that ID isn't stored in the chunk itself.
3. Keep as is and document. 

If people feel strongly that this is a bug, then I would probably go with (1) initially. While (2) is theoretically possible, it seems like a  lot of work for little gain and would probably also impose a performance hit.

**Comment by k-rus** [comment] 2020-12-08 16:00
@pmwkaa @erimatnor Is it correct to close the issue? It is not fixed, but the bug is replaced with an error message.

**Comment by k-rus** [comment] 2020-12-11 10:58
The issue is not resolved, but the bug is fixed with returning error. So it is not a bug any more. However, proper `tableoid` needs to be fixed eventually, or a decision on new design around `tableoid` be made.

**Comment by nikkhils** [comment] 2022-03-18 13:15
We now error out if a systemcol is referred from a distributed table. Closing this now.

```
db_dist_query=# select xmin from hyper limit 1;
ERROR:  system columns are not accessible on distributed hypertables with current settings
HINT:  Set timescaledb.enable_per_data_node_queries=false to query system columns.
```

**Closed by nikkhils** 2022-03-18 13:15 UTC
Labels: bug, multinode, distributed-hypertable
