### ISSUE TITLE
[Flaky test] Lingering job in bgw_db_scheduler_fixed

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#4859] opened 2022-10-20 11:05 UTC
### Which test is flaky?

bgw_db_scheduler_fixed

### Since when has the test been flaky?

October 20, 2022

### Link to the failed test run

https://github.com/timescale/timescaledb/actions/runs/3287871530/jobs/5417535202
https://github.com/timescale/timescaledb/actions/runs/3289398600/jobs/5420879404
https://github.com/timescale/timescaledb/actions/runs/3295874767/jobs/5434885747

### Log output

```bash
diff -u /__w/timescaledb/timescaledb/tsl/test/expected/bgw_db_scheduler_fixed.out /__w/timescaledb/timescaledb/build/tsl/test/results/bgw_db_scheduler_fixed.out
--- /__w/timescaledb/timescaledb/tsl/test/expected/bgw_db_scheduler_fixed.out	2022-10-20 08:09:14.342490485 +0000
+++ /__w/timescaledb/timescaledb/build/tsl/test/results/bgw_db_scheduler_fixed.out	2022-10-20 08:12:32.282002979 +0000
@@ -252,9 +252,10 @@
 
 RESET client_min_messages;
 SELECT application_name FROM pg_stat_activity WHERE application_name LIKE 'User-Defined Action%';
- application_name 
-------------------
-(0 rows)
+      application_name      
+----------------------------
+ User-Defined Action [1001]
+(1 row)
 
 --
 -- Test running a normal job
```

**Comment by mkindahl** [comment] 2022-10-20 12:42
https://github.com/timescale/timescaledb/actions/runs/3289466699/jobs/5421034736

```
diff -u /__w/timescaledb/timescaledb/tsl/test/expected/bgw_db_scheduler_fixed.out /__w/timescaledb/timescaledb/build/tsl/test/results/bgw_db_scheduler_fixed.out
--- /__w/timescaledb/timescaledb/tsl/test/expected/bgw_db_scheduler_fixed.out	2022-10-20 12:13:57.417784366 +0000
+++ /__w/timescaledb/timescaledb/build/tsl/test/results/bgw_db_scheduler_fixed.out	2022-10-20 12:17:17.251884475 +0000
@@ -1754,7 +1754,7 @@
    1027 | Fri Dec 31 16:00:00 1999 PST     | Fri Dec 31 16:00:00 1999 PST     | Sat Jan 15 16:00:00 2000 PST     | Fri Dec 31 16:00:00 1999 PST
    1028 | Fri Dec 31 16:00:00.005 1999 PST | Fri Dec 31 16:00:00.005 1999 PST | Fri Jan 21 16:00:00.005 2000 PST | Fri Dec 31 16:00:00.005 1999 PST
    1029 | Fri Dec 31 16:00:00.025 1999 PST | Fri Dec 31 16:00:00.025 1999 PST | Mon Jul 31 16:00:00.01 2000 PDT  | Fri Dec 31 16:00:00.025 1999 PST
-   1030 | Fri Dec 31 16:00:00.025 1999 PST | Fri Dec 31 16:00:00.025 1999 PST | Mon Jul 31 16:00:00.01 2000 PDT  | Fri Dec 31 16:00:00.025 1999 PST
+   1030 | Fri Dec 31 16:00:00.025 1999 PST | Fri Dec 31 16:00:00.05 1999 PST  | Mon Jul 31 16:00:00.01 2000 PDT  | Fri Dec 31 16:00:00.05 1999 PST
    1031 | Fri Dec 31 16:00:00.025 1999 PST | Fri Dec 31 16:00:00.025 1999 PST | Sat Jan 15 16:00:00.015 2000 PST | Fri Dec 31 16:00:00.025 1999 PST
 (6 rows)
```

**Comment by konskov** [comment] 2022-10-21 10:16
it seems to me that this only fails on 32-bit Linux. I also haven't been able to reproduce it locally so far.

**Comment by konskov** [comment] 2022-11-02 11:46
note, https://github.com/timescale/timescaledb/commit/20cdd9ca3ed0c2d62779c4fc61d278a489b4460a has a fix for this flaky test?

**Comment by mkindahl** [comment] 2022-11-04 15:51
> note, [20cdd9c](https://github.com/timescale/timescaledb/commit/20cdd9ca3ed0c2d62779c4fc61d278a489b4460a) has a fix for this flaky test?

Seems like that. Closing. Will reopen if it surfaces again.

**Comment by mkindahl** [comment] 2022-11-09 07:28
Another failure: https://github.com/timescale/timescaledb/actions/runs/3426036399/jobs/5707418509

**Comment by konskov** [comment] 2022-11-10 08:07
another one: https://github.com/timescale/timescaledb/actions/runs/3431413972/jobs/5719521375

**Comment by konskov** [comment] 2022-11-11 08:25
looks like this happens daily now: https://github.com/timescale/timescaledb/actions/runs/3440015152/jobs/5737978936

**Closed** 2022-11-14 12:23 UTC
Labels: flaky-test
