### ISSUE TITLE
Performance: bigint range comparison not pruning chunks

### ISSUE THREAD

**Issue by geoffreybennett** [timescale/timescaledb#1678] opened 2020-02-06 11:45 UTC
**Relevant system information:**
 - OS: CentOS 7
 - PostgreSQL version: 11.6
 - TimescaleDB version: 1.6.0
 - Installation method: yum

**Describe the bug**
The query performance using a bigint range comparison operator is 3x slower than the equivalent query using a scalar comparison operator.

**To Reproduce**
1. Create a hypertable containing a lot of data:
```
# \d ip_port_data
                   Table "public.ip_port_data"
        Column        |  Type   | Collation | Nullable | Default 
----------------------+---------+-----------+----------+---------
 ip_port_snmp_port_id | integer |           | not null | 
 time                 | bigint  |           | not null | 
 bytes_in             | bigint  |           | not null | 
 bytes_out            | bigint  |           | not null | 
Indexes:
    "ip_port_data_ip_port_snmp_port_id_time" UNIQUE, btree (ip_port_snmp_port_id, "time")
    "ip_port_data_timeCheck constraints:
    "ip_port_data_bytes_in_check" CHECK (bytes_in >= 0)
    "ip_port_data_bytes_out_check" CHECK (bytes_out >= 0)
Foreign-key constraints:
    "ip_port_data_ip_port_snmp_port_id_fkey" FOREIGN KEY (ip_port_snmp_port_id) REFERENCES ip_port_snmp_port(id)
Triggers:
    ts_insert_blocker BEFORE INSERT ON ip_port_data FOR EACH ROW EXECUTE PROCEDURE _timescaledb_internal.insert_blocker()
" btree ("time")
```
2. Query the table using a range comparison:
```
# explain analyze select count(*) from ip_port_data where time <@ '[1580342400,)'::int8range;
```

**Expected behavior**
Good performance, with the chunks that cannot match not appearing in the query plan, like this equivalent query:
```
# explain analyze select count(*) from ip_port_data where time >= 1580342400;
                                                                           QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=59826.48..59826.49 rows=1 width=8) (actual time=536.406..536.406 rows=1 loops=1)
   ->  Gather  (cost=59826.26..59826.47 rows=2 width=8) (actual time=536.264..543.096 rows=3 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Partial Aggregate  (cost=58826.26..58826.27 rows=1 width=8) (actual time=525.496..525.497 rows=1 loops=3)
               ->  Parallel Append  (cost=0.00..54948.88 rows=1550955 width=0) (actual time=0.027..417.329 rows=1240743 loops=3)
                     ->  Parallel Seq Scan on _hyper_232_240_chunk  (cost=0.00..44196.26 rows=1466020 width=0) (actual time=0.023..264.368 rows=1172816 loops=3)
                           Filter: ("time" >= 1580342400)
                     ->  Parallel Seq Scan on _hyper_232_241_chunk  (cost=0.00..2997.85 rows=119908 width=0) (actual time=0.023..22.342 rows=101890 loops=2)
                           Filter: ("time" >= 1580342400)
 Planning Time: 0.500 ms
 Execution Time: 543.152 ms
(12 rows)
```

**Actual behavior**
Bad performance, as every chunk is checked for values that cannot be present:
```
# explain analyze select count(*) from ip_port_data where time <@ '[1580342400,)'::int8range;
                                                                              QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=152747.21..152747.22 rows=1 width=8) (actual time=1446.470..1446.471 rows=1 loops=1)
   ->  Gather  (cost=152746.99..152747.20 rows=2 width=8) (actual time=1445.512..1450.557 rows=3 loops=1)
         Workers Planned: 2
         Workers Launched: 2
         ->  Partial Aggregate  (cost=151746.99..151747.00 rows=1 width=8) (actual time=1435.421..1435.421 rows=1 loops=3)
               ->  Parallel Append  (cost=0.08..117300.83 rows=13778463 width=0) (actual time=891.805..1333.005 rows=1240760 loops=3)
                     ->  Custom Scan (DecompressChunk) on _hyper_232_239_chunk  (cost=0.08..190.74 rows=2274000 width=0) (actual time=313.688..313.689 rows=0 loops=1)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
                           Rows Removed by Filter: 3497266
                           ->  Parallel Seq Scan on compress_hyper_233_249_chunk  (cost=0.00..190.74 rows=2274 width=4) (actual time=0.024..3.244 rows=3866 loops=1)
                     ->  Custom Scan (DecompressChunk) on _hyper_232_232_chunk  (cost=0.08..122.72 rows=1472000 width=0) (actual time=196.587..196.587 rows=0 loops=1)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
                           Rows Removed by Filter: 2251989
                           ->  Parallel Seq Scan on compress_hyper_233_242_chunk  (cost=0.00..122.72 rows=1472 width=4) (actual time=0.026..2.296 rows=2502 loops=1)
                     ->  Custom Scan (DecompressChunk) on _hyper_232_233_chunk  (cost=0.06..162.98 rows=2598000 width=0) (actual time=358.550..358.550 rows=0 loops=1)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
                           Rows Removed by Filter: 4045797
                           ->  Parallel Seq Scan on compress_hyper_233_243_chunk  (cost=0.00..162.98 rows=2598 width=4) (actual time=0.028..3.289 rows=4417 loops=1)
                     ->  Custom Scan (DecompressChunk) on _hyper_232_236_chunk  (cost=0.06..142.52 rows=2452000 width=0) (actual time=405.467..405.467 rows=0 loops=1)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
                           Rows Removed by Filter: 4095091
                           ->  Parallel Seq Scan on compress_hyper_233_246_chunk  (cost=0.00..142.52 rows=2452 width=4) (actual time=0.018..6.239 rows=4168 loops=1)
                     ->  Custom Scan (DecompressChunk) on _hyper_232_234_chunk  (cost=0.06..151.39 rows=2639000 width=0) (actual time=344.760..344.761 rows=0 loops=1)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
                           Rows Removed by Filter: 4110064
                           ->  Parallel Seq Scan on compress_hyper_233_244_chunk  (cost=0.00..151.39 rows=2639 width=4) (actual time=0.025..3.060 rows=4486 loops=1)
                     ->  Custom Scan (DecompressChunk) on _hyper_232_235_chunk  (cost=0.06..147.52 rows=2652000 width=0) (actual time=439.407..439.407 rows=0 loops=1)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
                           Rows Removed by Filter: 4130782
                           ->  Parallel Seq Scan on compress_hyper_233_245_chunk  (cost=0.00..147.52 rows=2652 width=4) (actual time=0.026..3.359 rows=4509 loops=1)
                     ->  Custom Scan (DecompressChunk) on _hyper_232_238_chunk  (cost=0.06..148.85 rows=2685000 width=0) (actual time=344.013..344.013 rows=0 loops=1)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
                           Rows Removed by Filter: 4183066
                           ->  Parallel Seq Scan on compress_hyper_233_248_chunk  (cost=0.00..148.85 rows=2685 width=4) (actual time=0.021..2.751 rows=4565 loops=1)
                     ->  Custom Scan (DecompressChunk) on _hyper_232_237_chunk  (cost=0.06..147.69 rows=2669000 width=0) (actual time=134.211..134.211 rows=0 loops=3)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
                           Rows Removed by Filter: 1385429
                           ->  Parallel Seq Scan on compress_hyper_233_247_chunk  (cost=0.00..147.69 rows=2669 width=4) (actual time=0.022..0.996 rows=1513 loops=3)
                     ->  Parallel Seq Scan on _hyper_232_240_chunk  (cost=0.00..44196.26 rows=7330 width=0) (actual time=0.020..380.647 rows=1759224 loops=2)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
                     ->  Parallel Seq Scan on _hyper_232_241_chunk  (cost=0.00..2997.85 rows=599 width=0) (actual time=0.016..41.197 rows=203831 loops=1)
                           Filter: ("time" <@ '[1580342400,)'::int8range)
 Planning Time: 1.143 ms
 Execution Time: 1450.763 ms
(44 rows)
```

**Additional context**
Issue #239 implies that this should have been working since Sep/2017: "A few weeks ago, optimizations were introduced such that queries with RANGE-based criteria would apply to appropriate chunks"

**Comment by svenklemm** [comment] 2020-02-14 07:42
Optimizations for range-types were never added, the referenced ticket is about ranges in the WHERE clause but not range-types

**Comment by svenklemm** [comment] 2020-10-13 12:37
Duplicate of #239

**Closed by svenklemm** 2020-10-13 12:37 UTC
Labels: performance
