### ISSUE TITLE
[Bug]: Fix segfault in ts_chunk_constraints_insert_metadata

### ISSUE THREAD

**Issue by kgyrtkirk** [timescale/timescaledb#5263] opened 2023-01-31 22:41 UTC
### What type of bug is this?

Crash

### What subsystems and features are affected?

Access node

### What happened?

in case num_dimensions is 0; the constraints are not able to initialize properly - which could lead to a segmentation fault

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.6

### What operating system did you use?

Linux

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
.
```

**Comment by mkindahl** [comment] 2023-02-06 12:24
@kgyrtkirk I see that there are no reproduction case. It would be good to have some way to reproduce the problem. Information from customers suggest that it can be related to running `pg_dump` on one version and `pg_restore` on a different version. Have you tested that?

**Comment by kgyrtkirk** [comment] 2023-02-06 12:35
of course I've tested that... https://github.com/timescale/timescaledb/pull/5264#issuecomment-1412419764

I don't know how you would reproduce an issue like this - I've used a docker multi stage build to simulate the process

**Comment by svenklemm** [comment] 2024-05-12 17:06
Closing since this is old ticket with no reproduction case

**Closed by svenklemm** 2024-05-12 17:06 UTC
Labels: bug
