### ISSUE TITLE
Help: Setting up log_statement for postgresql

### ISSUE THREAD

**Issue by bh4r4th** [timescale/timescaledb#1862] opened 2020-04-28 06:39 UTC
Hi Everyone, 
I am trying to set `log_statement=all` from docker-compose file as:
`command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]`

But this is throwing an error. 

I tried to get into a running container and tried setting up manually as:
1. by running as `sudo postgres -c log_statement=all` which prompting for password which is not matching with the password passed for postgresql while spinning up container.
2. tried without sudo; but it didn't work either.

What is the better way to set `log_statement` so that I can see logs along with container logs by simply running:
`docker logs -f container-name`

**docker image I'm using:** `timescale/timescaledb:1.6.1-pg11-bitnami`

**Comment by svenklemm** [comment] 2020-10-13 08:52
The following should work in sql session:
```
alter system set log_statement to "all";
```

**Comment by svenklemm** [comment] 2020-10-13 08:53
Closing this since it seems to be answered. Feel free to reopen if the issue is still relevant.

**Closed by svenklemm** 2020-10-13 08:53 UTC
Labels: question
