### ISSUE TITLE
Error creating continuous aggregate view with time_bucket origin/offset parameter

### ISSUE THREAD

**Issue by grafolean** [timescale/timescaledb#2265] opened 2020-08-26 16:44 UTC
**Relevant system information:**
 - OS: Ubuntu
 - PostgreSQL version (output of `postgres --version`): 12.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.1
 - Installation method: Docker (timescale/timescaledb:latest-pg12)

**Describe the bug**
I am trying to create a [continuous aggregate view](https://docs.timescale.com/latest/using-timescaledb/continuous-aggregates#create) using [time_bucket](https://docs.timescale.com/latest/api#time_bucket) with `origin` parameter set, but I am getting error. It works without `origin` or `offset`.

**To Reproduce**
1. Try to create a continuous aggregate view on a table using `origin` parameter of `time_bucket`:
```
# CREATE VIEW test_hourly WITH (timescaledb.continuous) AS SELECT TIME_BUCKET('1 hours'::interval, ts::timestamp, '1970-01-01'::timestamp) AS period, AVG(value), MIN(value), MAX(value) FROM measurements GROUP BY period;
```
2. See error:
```
ERROR:  no valid bucketing function found for continuous aggregate query
```

3. Observe that it works when `origin` is not specified:
```
# CREATE VIEW test_hourly WITH (timescaledb.continuous) AS SELECT TIME_BUCKET('1 hours'::interval, ts::timestamp) AS period, AVG(value), MIN(value), MAX(value) FROM measurements GROUP BY period;
CREATE VIEW
```

**Expected behavior**
Parameter `origin` should be allowed (and obeyed).

**Actual behavior**
Creating a continuous aggregate view fails.

**Screenshots**
/

**Additional context**
- same behaviour can be observed with `offset` (so it can't be used as a workaround)
- (off topic) it would probably be a good idea to document the default value ([2000-01-03](https://github.com/timescale/timescaledb/blob/c90397fd6a0cfb5cc6487207424eeac5e6920c52/src/time_bucket.c#L100)) of `origin` in [time_bucket](https://docs.timescale.com/latest/api#time_bucket) docs

**Comment by fredericgermain** [comment] 2020-10-01 19:51
I upvote this.
It'd be nice to have aggregation by day not aligned at midnight UTC.

**Comment by alefebvre-berner** [comment] 2020-10-02 14:54
I also upvote this. It would be very helpfull to me.
Also please consider having the offset being pass as a column of the table as the timestamp is, not only a fixed value.

**Comment by DavidPavlicek** [comment] 2020-10-13 09:35
This is a major feature... definitely needs to be implemented... +1

**Comment by erimatnor** [comment] 2021-02-23 15:44
Related to https://github.com/timescale/timescaledb/issues/414

**Comment by mabhijithn** [comment] 2022-06-16 14:20
I am not sure this is related to #414. Even if I use `time_bucket_ng`, I cannot create materialized view for a continuous aggregate if I have to use `origin` parameter. Please do point what I am doing wrong. `time_bucket` also does not work. Though, outside `MATERIALIZED VIEW`, I am able to use `time_bucket` individually with `origin` and `offsets`.

```
CREATE MATERIALIZED VIEW onehour_candle 
WITH (timescaledb.continuous) AS 
SELECT symbol, 
timescaledb_experimental.time_bucket_ng('1 day', time, origin => TIMESTAMP '2022-01-03') AS date,
FIRST(open, time) as open,
MAX(high) as high,
MIN(low) as low,
LAST(close, time) as close
FROM stockdata
GROUP BY symbol,date;
ERROR:  continuous aggregate view must include a valid time bucket function
```

**Comment by afiskon** [comment] 2022-06-24 15:38
> Please do point what I am doing wrong

The problem is that named arguments are currently not supported when creating a CAGG. Just don't specify the name of the argument.

**Comment by mabhijithn** [comment] 2022-06-24 15:49
I apologize. I should have been more clear. I am unable to create an `MATERIALIZED VIEW`  continuous aggregate using just `time_bucket`  and having an origin parameter. For example, I get error for the command as shown below:
```
CREATE MATERIALIZED VIEW onehour_candle 
WITH (timescaledb.continuous) AS 
SELECT symbol, 
time_bucket('1 hour', time, TIMESTAMP '2022-01-03') AS date,
FIRST(open, time) as open,
MAX(high) as high,
MIN(low) as low,
LAST(close, time) as close
FROM stockdata
GROUP BY symbol,date;
ERROR:  continuous aggregate view must include a valid time bucket function
```
@afiskon Is it possible to have a continuous aggregate with `ORIGIN` parameter? Is so how will I provide the origin timestamp?

**Comment by mabhijithn** [comment] 2022-06-24 16:03
Unfortunately, no. I get the same error as given below. I also tried `TIMESTAMPTZ` instead of `TIMESTAMP` (since my `time` column contains timestamp)

```
CREATE MATERIALIZED VIEW onehour_candle_new 
WITH (timescaledb.continuous) AS 
SELECT symbol, 
timescaledb_experimental.time_bucket_ng('1 day', time, TIMESTAMP '2022-01-03') AS date,
FIRST(open, time) as open,
MAX(high) as high,
MIN(low) as low,
LAST(close, time) as close
FROM stockdata
GROUP BY symbol,date;
ERROR:  continuous aggregate view must include a valid time bucket function
```

**Comment by konskov** [comment] 2022-06-24 16:25
If your time field is `timestamp`, the above should work. 
If your time field is `timestamptz`, then you must specify the timezone too as an argument, like this: 
`timescaledb_experimental.time_bucket_ng('1 day', time, '2022-01-03', 'Europe/Moscow') AS date`
as is also noted in https://github.com/timescale/timescaledb/issues/414#issuecomment-1063049999 and the [related documentation](https://docs.timescale.com/api/latest/hyperfunctions/time_bucket_ng/#timescaledb-experimental-time-bucket-ng)

**Comment by FlorianWendelborn** [comment] 2022-10-03 19:47
> ERROR:  continuous aggregate view must include a valid time bucket function  
> — @mabhijithn

For me, this was fixed by using `GROUP BY 1, 2` instead of `GROUP BY "time", "shortId"`

**Comment by theendlessriver13** [comment] 2023-01-21 15:47
For my use case this is also an issue. With the following table:

```sql
CREATE TABLE temperatures (
    time TIMESTAMP WITH TIME ZONE PRIMARY KEY,
    temperature NUMERIC
);
SELECT create_hypertable('temperatures', 'time');
```
And some data which is **right** labelled meaning at the **end** of the interval! -> `15:00` is the interval from `14:50` to `15:00`!

```sql
INSERT INTO temperatures(time, temperature) VALUES
('2022-01-01 14:50', 10.0),
('2022-01-01 15:00', 5.0),
('2022-01-01 15:10', 10.0),
('2022-01-01 15:20', 20.0),
('2022-01-01 16:00', 16.0);
```
When using this in a regular query I can get there with specifying an `offset` to get the averaging correct and then subtracting it again, to go back to the full hour. Exactly as described in the [docs](https://docs.timescale.com/api/latest/hyperfunctions/time_bucket/#sample-usage).
```sql
SELECT
    time_bucket('1 hour', time, '+1 second'::INTERVAL) + '-1 second'::INTERVAL AS hour,
    avg(temperature) AS temp_mean
FROM temperatures
GROUP BY hour;
```
```console
          hour          |      temp_mean      
------------------------+---------------------
 2022-01-01 15:00:01+00 | 15.3333333333333333
 2022-01-01 14:00:01+00 |  7.5000000000000000
(2 rows)
```

However, this **cannot** be transferred to continuous aggregates. When trying:

```sql
CREATE MATERIALIZED VIEW hourly_average
WITH (timescaledb.continuous) AS 
    SELECT
        time_bucket('1 hour', time, '+1 second'::INTERVAL) + '-1 second'::INTERVAL AS hour,
        avg(temperature) AS temp_mean
    FROM temperatures
    GROUP BY hour;
```

This results in `ERROR:  continuous aggregate view must include a valid time bucket function`.

Things I tried:
1. removing the `+ '-1 second'::INTERVAL` part -> same error!
1. also removing the `offset` parameter -> works, but not the desired result!
1. adding back the `+ '-1 second'::INTERVAL` part -> back to the same error!
1. trying this to get at least the side of the label right, knowing that the averaging is incorrect. However this **does not** work if `time` is of type `TIMESTAMPTZ`, only for `TIMESTAMP` - why is this? I have no idea...
    ```sql
    CREATE MATERIALIZED VIEW hourly_average
    WITH (timescaledb.continuous) AS 
        SELECT
            time_bucket('1 hour', time)  + '1 hour'::INTERVAL AS hour,
            avg(temperature) AS temp_mean
        FROM temperatures
        GROUP BY time_bucket('1 hour', time);
    ```
**NOTE:**
The above only works when specifying `GROUP BY time_bucket('1 hour', time)`. You cannot use `GROUP BY hour`, since, yet again, we get the `ERROR:  continuous aggregate view must include a valid time bucket function`...

Any ideas for a workaround or maybe when this feature, that works perfectly fine for `time_bucket` in regular queries, will be implemented for `MATERIALIZED VIEW`?

**Comment by theendlessriver13** [comment] 2023-01-21 16:19
The error message is also not quite right in the context. When looking at the full function signature of `time_bucket`
```sql
Schema              | public
Name                | time_bucket
Result data type    | timestamp with time zone
Argument data types | bucket_width interval, ts timestamp with time zone, timezone text, origin timestamp with time zone DEFAULT NULL::timestamp with time zone, "offset" interval DEFAULT NULL::interval
Type                | func
```
calling this of course succeeds, hence this _is_ a "valid time bucket function".
```sql
SELECT time_bucket('1 hour'::INTERVAL, '2022-01-10 15:30'::TIMESTAMPTZ, 'UTC', NULL, NULL);
```

But in the context of a materialized view this function is not valid anymore? How come?

**Comment by fcovatti** [comment] 2023-03-08 15:52
@jkittner when I tried similar workaround I get the following error
`make sure all functions in the continuous aggregate definition have IMMUTABLE volatility. Note that functions or expressions may be IMMUTABLE for one data type, but STABLE or VOLATILE for another
`

The support to offset functionality to me would be very interesting to have on the continuous aggregates.

**Comment by jkittner** [comment] 2023-03-09 14:26
@fcovatti, you probably have `TIMESTAMPTZ` as a column data type. This doesn't work. For some reason only `TIMESTAMP` works (that may be on accident?).

I'm still hoping that this will be implemented some day. That would make working with inconsistent labeling across different time zones so much easier...

**Comment by searchingforcode** [comment] 2023-03-16 23:09
> @fcovatti, you probably have `TIMESTAMPTZ` as a column data type. This doesn't work. For some reason only `TIMESTAMP` works (that may be on accident?).
> 
> I'm still hoping that this will be implemented some day. That would make working with inconsistent labeling across different time zones so much easier...
When we will get a update?

**Comment by Petwag** [comment] 2024-01-05 14:20
Any advancement on that ticket?

**Comment by vonnue-yehya** [comment] 2024-02-21 05:51
Any updates on this ? I am trying to pass in the offset parameter to the `time_bucket` function when used as a cagg, looks like this is not allowed right now.

**Closed** 2024-04-05 08:30 UTC
Labels: continuous_aggregate, time_bucket, feature-request
