### ISSUE TITLE
Timescaledb dump

### ISSUE THREAD

**Issue by Kumar6295** [timescale/timescaledb#2566] opened 2020-10-19 06:51 UTC
**When we try to dump(Backup) database,below errors showing.
 is it harmful to database/data or not?
How we can get database dump without below error with all the data?**

  pg_dump: NOTICE: there are circular foreign-key constraints on this table:
pg_dump:   hypertable
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump: NOTICE: there are circular foreign-key constraints on this table:
pg_dump:   chunk
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.

 **pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.**

**What is the reason this errors/warning are happening?**

**Comment by Kumar6295** [comment] 2020-10-19 06:52
**Why this errors are happening?**

**Comment by svenklemm** [comment] 2020-10-19 10:07
These are only warnings/hints and can safely be ignored.

**Comment by svenklemm** [comment] 2020-10-19 10:10
Duplicate of #1581

**Closed by svenklemm** 2020-10-19 10:10 UTC
