### ISSUE TITLE
Add Builds / Release files for Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#1857] opened 2020-04-27 12:58 UTC
**Relevant system information:**
 - OS: Ubuntu 20.04
 - Installation method: Apt

**Describe the bug**
There is no release file for Ubuntu 20.04 Focal Fossa, meaning the usual apt install instructions fail:

```
Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal InRelease [265 kB]

Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-updates InRelease

Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu focal-backports InRelease

Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease

Ign:5 http://ppa.launchpad.net/timescale/timescaledb-ppa/ubuntu focal InRelease

Hit:6 http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease

Err:7 http://ppa.launchpad.net/timescale/timescaledb-ppa/ubuntu focal Release

  404  Not Found [IP: 91.189.95.83 80]

Reading package lists... Done

E: The repository 'http://ppa.launchpad.net/timescale/timescaledb-ppa/ubuntu focal Release' does not have a Release file.

N: Updating from such a repository can't be done securely, and is therefore disabled by default.

N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**To Reproduce**
1. Follow the Ubuntu instructions on 20.04

**Expected behavior**
Install as normal

**Actual behavior**
Fails, due to missing release file

**Comment by RobAtticus** [comment] 2020-05-05 14:19
These should now be available.

**Comment by DanielFerreiraJorge** [comment] 2020-05-08 00:03
Still not available... thanks

**Comment by wmay** [comment] 2020-05-08 00:15
Right here: https://launchpad.net/~timescale/+archive/ubuntu/timescaledb-ppa?field.series_filter=focal

**Comment by svenklemm** [comment] 2020-10-14 08:09
Closing this since this should be fixed. Feel free to reopen if the issue is still relevant.

**Closed by svenklemm** 2020-10-14 08:09 UTC
Labels: build

**Comment by NeroVanbiervliet** [comment] 2020-10-29 16:16
Still/again seems to be unavailable

**Comment by RobAtticus** [comment] 2020-10-29 16:30
@NeroVanbiervliet That is the repository for Debian packages, not Ubuntu.

Ubuntu uses this PPA:
https://launchpad.net/~timescale/+archive/ubuntu/timescaledb-ppa?field.series_filter=focal

Added like this:
```
sudo add-apt-repository ppa:timescale/timescaledb-ppa
sudo apt-get update
```

**Comment by NeroVanbiervliet** [comment] 2020-10-29 16:37
@RobAtticus My mistake, I was reading the wrong docs. Thanks a lot!
