### ISSUE TITLE
Unable to run timescaledb on Mac Majove with PG 12.2

### ISSUE THREAD

**Issue by pranasblk** [timescale/timescaledb#1722] opened 2020-03-05 22:33 UTC
$   timescaledb-tune --quiet --yes
exit: unknown major PG version: PostgreSQL 12.2

**Comment by pranasblk** [comment] 2020-03-05 23:07
$ /usr/local/bin/timescaledb_move.sh
Moving files into place...
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Success.
$ uname -a
Darwin xxx.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

**Comment by feikesteenbergen** [comment] 2020-03-06 08:31
You can also explicitly set the version:
```console
timescaledb-tune -pg-version 11
```

**Comment by mfreed** [comment] 2020-03-06 22:13
TimescaleDB has not yet released support for PG12.  Are there any issues left?

**Comment by svenklemm** [comment] 2020-10-14 08:41
Closing this since it should be resolved now. Feel free to reopen if the issue is still relevant.

**Closed by svenklemm** 2020-10-14 08:41 UTC
Labels: question
