### ISSUE TITLE
Sometimes join condition on hyper table seems dropped

### ISSUE THREAD

**Issue by GaryZengTurbo** [timescale/timescaledb#2888] opened 2021-02-01 00:01 UTC
**Relevant system information:**
 - OS: [CentOS Linux release 7.9.2009]
- PostgreSQL version :[PostgreSQL 12.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit]
- TimescaleDB version : [17.4]
- Installation method: [Installation method: Docker image tagged timescale/timescaledb-postgis:1.7.4-pg12]

**Describe the bug**
The join condition on hyper table seems dropped.
`FROM entity e
  join metric m on 
  m.entity_oid = e.oid
    AND m.entity_hash = e.hash`
The **m.entity_hash = e.hash** condition is dropped.

**To Reproduce**
1. Plain Postgres table
```
CREATE TABLE extractor.entity (
 	"oid" int8 NOT NULL,
 	hash int8 NOT NULL,
 	"type" extractor.entity_type NOT NULL,
 	"name" text NOT NULL,
 	environment extractor.environment_type NULL,
 	state extractor.entity_state NULL,
 	attrs jsonb NULL,
 	"scope" _int8 NOT NULL,
 	first_seen timestamptz NOT NULL,
 	last_seen timestamptz NOT NULL
);
CREATE UNIQUE INDEX "entity_entityByOid" ON extractor.entity USING btree (oid, hash);
CREATE INDEX "entity_entityByScopeOid" ON extractor.entity USING gin (scope);

CREATE TABLE extractor."scope" (
 	seed_oid int8 NOT NULL,
 	scoped_oid int8 NOT NULL,
 	scoped_type extractor.entity_type NOT NULL,
 	"start" timestamptz NOT NULL,
 	finish timestamptz NOT NULL,
 	CONSTRAINT scope_pkey PRIMARY KEY (seed_oid, scoped_oid, start)
);
CREATE INDEX scope_scoped_type ON extractor.scope USING btree (scoped_type);
CREATE INDEX scope_seed_type_start ON extractor.scope USING btree (seed_oid, scoped_type, start);
```
2. Hyper Table
```
CREATE TABLE extractor.metric (
 	"time" timestamptz NOT NULL,
 	entity_oid int8 NOT NULL,
 	entity_hash int8 NOT NULL,
 	"type" extractor.metric_type NOT NULL,
 	"current" float8 NULL,
 	capacity float8 NULL,
 	utilization float8 NULL,
 	consumed float8 NULL,
 	provider_oid int8 NULL,
 	"key" text NULL
);
CREATE INDEX metric_idx2 ON extractor.metric USING btree (entity_oid, type, "time" DESC);
CREATE INDEX metric_index ON extractor.metric USING btree (entity_oid, entity_hash, type, "time" DESC);
CREATE INDEX metric_time ON extractor.metric USING brin ("time");
-- Table Triggers
create trigger ts_insert_blocker before
insert
    on
    extractor.metric for each row execute function _timescaledb_internal.insert_blocker();
```
3. Query 1
```
SELECT
    COUNT(*)
  FROM entity e
  join metric m on 
  --m.entity_oid = e.oid
  --  AND 
  m.entity_hash = e.hash
  join scope s
    on e.oid = s.seed_oid AND
        m.time BETWEEN s.start AND s.finish
  WHERE
    -- fixed conditions
    m.type = 'STORAGE_AMOUNT'
    AND e.type = 'STORAGE'
    AND s.scoped_type IN ('STORAGE_CLUSTER', 'GROUP')
    -- conditions involving dashboard vars
    AND m."time" BETWEEN '2020-12-20T19:07:51.313Z' AND '2021-01-28T19:07:51.313Z'
    AND ('2020-12-20T19:07:51.313Z', '2021-01-28T19:07:51.313Z') OVERLAPS (first_seen, last_seen)
    AND CASE
      WHEN ARRAY['0']::text[] = ARRAY[ '284868676493926' ] THEN true
      ELSE ARRAY[s.scoped_oid] && ARRAY['284868676493926']::bigint[]
    END
```
4. Query 2
```
SELECT
    COUNT(*)
  FROM entity e
  join metric m on 
  m.entity_oid = e.oid
    AND m.entity_hash = e.hash
  join scope s
    on e.oid = s.seed_oid AND
        m.time BETWEEN s.start AND s.finish
  WHERE
    -- fixed conditions
    m.type = 'STORAGE_AMOUNT'
    AND e.type = 'STORAGE'
    AND s.scoped_type IN ('STORAGE_CLUSTER', 'GROUP')
    -- conditions involving dashboard vars
    AND m."time" BETWEEN '2020-12-20T19:07:51.313Z' AND '2021-01-28T19:07:51.313Z'
    AND ('2020-12-20T19:07:51.313Z', '2021-01-28T19:07:51.313Z') OVERLAPS (first_seen, last_seen)
    AND CASE
      WHEN ARRAY['0']::text[] = ARRAY[ '284868676493926' ] THEN true
      ELSE ARRAY[s.scoped_oid] && ARRAY['284868676493926']::bigint[]
    END
```
5. Data is too large to attach here.

**Expected behavior**
Query 2 return less or same count as in Query 1.
Since the only difference is query 2 has an additional join condition "m.entity_oid = e.oid".

**Actual behavior**
Query 1: count: 1030
Query 2: count: 3093

**Additional context**
From the explain, we think the second condition  `m.entity_hash = e.hash` was dropped in Query 2.
 ```
Gather  (cost=1001.64..125227.00 rows=2 width=24) (actual time=64828.112..122273.867 rows=3093 loops=1)
  Workers Planned: 2
  Workers Launched: 2
  ->  Nested Loop  (cost=1.64..124226.80 rows=1 width=24) (actual time=65685.204..122028.995 rows=1031 loops=3)
        ->  Nested Loop  (cost=1.08..124194.97 rows=19 width=32) (actual time=0.388..1646.157 rows=207776 loops=3)
              ->  Parallel Seq Scan on entity e  (cost=0.00..11283.75 rows=506 width=16) (actual time=0.071..74.299 rows=403 loops=3)
                    Filter: ("overlaps"('2020-12-20 14:07:51.313-05'::timestamp with time zone, '2021-01-28 14:07:51.313-05'::timestamp with time zone, first_seen, last_seen) AND (type = 'STORAGE'::entity_type))
                    Rows Removed by Filter: 47691
              ->  Append  (cost=1.08..83.14 rows=14000 width=24) (actual time=0.121..3.424 rows=516 loops=1208)
                    ->  Custom Scan (DecompressChunk) on _hyper_1_25_chunk m  (cost=1.08..1.08 rows=1000 width=24) (actual time=0.114..0.242 rows=41 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 123
                          ->  Index Scan using compress_hyper_5_28_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_28_chunk  (cost=0.29..1.08 rows=1 width=92) (actual time=0.027..0.046 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_12_chunk m_1  (cost=1.08..1.08 rows=1000 width=24) (actual time=0.123..0.313 rows=48 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 144
                          ->  Index Scan using compress_hyper_5_16_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_16_chunk  (cost=0.29..1.08 rows=1 width=92) (actual time=0.021..0.024 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_17_chunk m_2  (cost=1.08..1.08 rows=1000 width=24) (actual time=0.117..0.249 rows=48 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 144
                          ->  Index Scan using compress_hyper_5_22_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_22_chunk  (cost=0.29..1.08 rows=1 width=92) (actual time=0.020..0.022 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_15_chunk m_3  (cost=1.08..1.08 rows=1000 width=24) (actual time=0.127..0.242 rows=34 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 102
                          ->  Index Scan using compress_hyper_5_20_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_20_chunk  (cost=0.29..1.08 rows=1 width=92) (actual time=0.020..0.025 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_11_chunk m_4  (cost=1.44..1.44 rows=1000 width=24) (actual time=0.047..0.060 rows=5 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 15
                          ->  Index Scan using compress_hyper_5_14_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_14_chunk  (cost=0.29..1.44 rows=1 width=92) (actual time=0.021..0.022 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_19_chunk m_5  (cost=1.08..1.08 rows=1000 width=24) (actual time=0.187..0.373 rows=48 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 144
                          ->  Index Scan using compress_hyper_5_24_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_24_chunk  (cost=0.29..1.08 rows=1 width=92) (actual time=0.107..0.110 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_21_chunk m_6  (cost=1.08..1.08 rows=1000 width=24) (actual time=0.308..0.437 rows=48 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 144
                          ->  Index Scan using compress_hyper_5_26_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_26_chunk  (cost=0.29..1.08 rows=1 width=92) (actual time=0.020..0.023 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_23_chunk m_7  (cost=1.08..1.08 rows=1000 width=24) (actual time=0.116..0.281 rows=48 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 144
                          ->  Index Scan using compress_hyper_5_27_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_27_chunk  (cost=0.29..1.08 rows=1 width=92) (actual time=0.021..0.023 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_13_chunk m_8  (cost=1.08..1.08 rows=1000 width=24) (actual time=0.110..0.246 rows=41 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 123
                          ->  Index Scan using compress_hyper_5_18_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_18_chunk  (cost=0.29..1.08 rows=1 width=92) (actual time=0.028..0.031 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_7_chunk m_9  (cost=0.62..3.08 rows=5000 width=24) (actual time=0.226..0.681 rows=155 loops=1208)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type) AND (e.oid = entity_oid))
                          Rows Removed by Filter: 845
                          ->  Index Scan using compress_hyper_5_10_chunk__compressed_hypertable_5_entity_oid__ on compress_hyper_5_10_chunk  (cost=0.42..3.08 rows=5 width=92) (actual time=0.037..0.045 rows=1 loops=1208)
                                Index Cond: (entity_oid = e.oid)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                                Rows Removed by Filter: 1
        ->  Index Scan using scope_seed_type_start on scope s  (cost=0.56..1.67 rows=1 width=24) (actual time=0.574..0.574 rows=0 loops=623328)
              Index Cond: ((seed_oid = m.entity_oid) AND (scoped_type = ANY ('{STORAGE_CLUSTER,GROUP}'::entity_type[])) AND (start <= m."time"))
              Filter: ((ARRAY[scoped_oid] && '{284868676493926}'::bigint[]) AND (m."time" <= finish))
              Rows Removed by Filter: 198
Planning Time: 21.885 ms
Execution Time: 122275.098 ms
```

**Comment by gayyappan** [comment] 2021-02-01 14:26
@GaryZengTurbo Could you provide a) create_hypertable stmt and b) the settings used to compress the hypertable? 
 I think this is the same bug as issue 2673.  I need more information to repro the bug and confirm if it has been fixed.

Does the query work as expected if you set enable_nestloop = false work?

**Comment by GaryZengTurbo** [comment] 2021-02-01 20:20
Thanks @gayyappan ,
**create_hypertable stmt and the settings used to compress the hypertable**
```
SELECT create_hypertable('metric', 'time', chunk_time_interval => INTERVAL '2 days');
ALTER TABLE "metric" SET(
  timescaledb.compress,
  timescaledb.compress_segmentby = 'entity_oid, entity_hash, type');
SELECT add_compress_chunks_policy('metric', INTERVAL '2 days');
```
**set enable_nestloop = false**
 yes, the query **work** as expected if I set it. 
```
Hash Join  (cost=125783.63..1902923.18 rows=2 width=24) (actual time=2929.908..48339.363 rows=1030 loops=1)
  Hash Cond: (m_4.entity_oid = s.seed_oid)
  Join Filter: ((m_4."time" >= s.start) AND (m_4."time" <= s.finish))
  Rows Removed by Join Filter: 1545
  ->  Gather  (cost=12291.41..1788378.04 rows=45 width=32) (actual time=145.428..45522.319 rows=144478 loops=1)
        Workers Planned: 2
        Workers Launched: 2
        ->  Parallel Hash Join  (cost=11291.41..1787373.54 rows=19 width=32) (actual time=125.858..34981.972 rows=48159 loops=3)
              Hash Cond: ((m_4.entity_oid = e.oid) AND (m_4.entity_hash = e.hash))
              ->  Parallel Append  (cost=0.07..878301.58 rows=171005832 width=24) (actual time=0.571..33535.972 rows=4827644 loops=3)
                    ->  Custom Scan (DecompressChunk) on _hyper_1_11_chunk m_4  (cost=0.41..7608.74 rows=18449000 width=24) (actual time=0.246..980.318 rows=140339 loops=1)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 2416473
                          ->  Parallel Seq Scan on compress_hyper_5_14_chunk  (cost=0.00..7608.74 rows=18449 width=92) (actual time=0.034..252.674 rows=31364 loops=1)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_7_chunk m_9  (cost=0.07..6183.93 rows=84256000 width=24) (actual time=0.894..12297.980 rows=1450128 loops=3)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 44345626
                          ->  Parallel Seq Scan on compress_hyper_5_10_chunk  (cost=0.00..6183.93 rows=84256 width=92) (actual time=0.046..351.817 rows=47745 loops=3)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                                Rows Removed by Filter: 532
                    ->  Custom Scan (DecompressChunk) on _hyper_1_15_chunk m_3  (cost=0.07..1190.98 rows=17332000 width=24) (actual time=0.403..6949.002 rows=954312 loops=1)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 16432490
                          ->  Parallel Seq Scan on compress_hyper_5_20_chunk  (cost=0.00..1190.98 rows=17332 width=92) (actual time=0.032..125.214 rows=29464 loops=1)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_21_chunk m_6  (cost=0.07..1188.12 rows=17341000 width=24) (actual time=0.408..9694.566 rows=1347264 loops=1)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 23198762
                          ->  Parallel Seq Scan on compress_hyper_5_26_chunk  (cost=0.00..1188.12 rows=17341 width=92) (actual time=0.045..349.015 rows=29480 loops=1)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_12_chunk m_1  (cost=0.07..1187.12 rows=17341000 width=24) (actual time=0.499..3071.280 rows=673632 loops=2)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 11599264
                          ->  Parallel Seq Scan on compress_hyper_5_16_chunk  (cost=0.00..1187.12 rows=17341 width=92) (actual time=0.047..34.913 rows=14740 loops=2)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_25_chunk m  (cost=0.07..1185.09 rows=17339000 width=24) (actual time=0.324..5307.790 rows=1150788 loops=1)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 19815706
                          ->  Parallel Seq Scan on compress_hyper_5_28_chunk  (cost=0.00..1185.09 rows=17339 width=92) (actual time=0.044..56.699 rows=29477 loops=1)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_13_chunk m_8  (cost=0.07..1185.09 rows=17339000 width=24) (actual time=1.566..7014.703 rows=1150788 loops=1)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 19815847
                          ->  Parallel Seq Scan on compress_hyper_5_18_chunk  (cost=0.00..1185.09 rows=17339 width=92) (actual time=0.034..158.280 rows=29477 loops=1)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_23_chunk m_7  (cost=0.07..1183.12 rows=17341000 width=24) (actual time=0.305..9748.412 rows=1347264 loops=1)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 23198618
                          ->  Parallel Seq Scan on compress_hyper_5_27_chunk  (cost=0.00..1183.12 rows=17341 width=92) (actual time=0.026..178.661 rows=29480 loops=1)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_17_chunk m_2  (cost=0.07..1181.12 rows=17341000 width=24) (actual time=0.315..8215.167 rows=1347264 loops=1)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 23198476
                          ->  Parallel Seq Scan on compress_hyper_5_22_chunk  (cost=0.00..1181.12 rows=17341 width=92) (actual time=0.026..232.330 rows=29480 loops=1)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
                    ->  Custom Scan (DecompressChunk) on _hyper_1_19_chunk m_5  (cost=0.07..1179.12 rows=17341000 width=24) (actual time=0.585..6959.688 rows=1347264 loops=1)
                          Filter: (("time" >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND ("time" <= '2021-01-28 14:07:51.313-05'::timestamp with time zone) AND (type = 'STORAGE_AMOUNT'::metric_type))
                          Rows Removed by Filter: 23198944
                          ->  Parallel Seq Scan on compress_hyper_5_24_chunk  (cost=0.00..1179.12 rows=17341 width=92) (actual time=0.057..89.664 rows=29480 loops=1)
                                Filter: ((_ts_meta_max_3 >= '2020-12-20 14:07:51.313-05'::timestamp with time zone) AND (_ts_meta_min_3 <= '2021-01-28 14:07:51.313-05'::timestamp with time zone))
              ->  Parallel Hash  (cost=11283.75..11283.75 rows=506 width=16) (actual time=124.381..124.382 rows=403 loops=3)
                    Buckets: 2048  Batches: 1  Memory Usage: 144kB
                    ->  Parallel Seq Scan on entity e  (cost=0.00..11283.75 rows=506 width=16) (actual time=0.234..123.704 rows=403 loops=3)
                          Filter: ("overlaps"('2020-12-20 14:07:51.313-05'::timestamp with time zone, '2021-01-28 14:07:51.313-05'::timestamp with time zone, first_seen, last_seen) AND (type = 'STORAGE'::entity_type))
                          Rows Removed by Filter: 47691
  ->  Hash  (cost=113258.31..113258.31 rows=18713 width=24) (actual time=2784.077..2784.345 rows=138 loops=1)
        Buckets: 32768  Batches: 1  Memory Usage: 264kB
        ->  Gather  (cost=1000.00..113258.31 rows=18713 width=24) (actual time=1.863..2784.098 rows=138 loops=1)
              Workers Planned: 2
              Workers Launched: 1
              ->  Parallel Seq Scan on scope s  (cost=0.00..110387.01 rows=7797 width=24) (actual time=5.201..2772.209 rows=69 loops=2)
                    Filter: ((scoped_type = ANY ('{STORAGE_CLUSTER,GROUP}'::entity_type[])) AND (ARRAY[scoped_oid] && '{284868676493926}'::bigint[]))
                    Rows Removed by Filter: 3730412
Planning Time: 43.717 ms
Execution Time: 48340.690 ms
```
**I think this is the same bug as issue 2673**
Yes, I think so too. I will close it as duplicate if I could get confirmation from you. Thanks in advance!

**Comment by erimatnor** [comment] 2021-02-09 16:00
Closing as a duplicate of #2673. Please reopen if new information emerges.

**Closed by erimatnor** 2021-02-09 16:00 UTC
Labels: investigate
