### ISSUE TITLE
[Bug]: Segmentation Fault when VACUUM FULL pg_class 

### ISSUE THREAD

**Issue by amalek215** [timescale/timescaledb#3924] opened 2021-12-13 16:40 UTC
### What type of bug is this?

Crash

### What subsystems and features are affected?

Background worker

### What happened?

VACUUM FULL pg_class while another process is modifying table will cause a variety errors ranging from segmentation fault, to pg_class corruption.

Very similar to #3188 except this occurs after the extension is installed

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

14.1

### What operating system did you use?

Red Hat Enterprise Linux 7.9

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Logs for most recent replication of error

2021-12-13 11:17:29.258 EST [24508] CONTEXT:  PL/pgSQL function inline_code_block line 12 at RAISE
2021-12-13 11:18:53.208 EST [26184] ERROR:  cache lookup failed for relation 155205
2021-12-13 11:18:53.208 EST [26184] STATEMENT:  VACUUM FULL pg_class ;
2021-12-13 11:18:56.981 EST [24508] ERROR:  deadlock detected
2021-12-13 11:18:56.981 EST [24508] DETAIL:  Process 24508 waits for RowExclusiveLock on relation 1259 of database 16384; blocked by process 26184.
        Process 26184 waits for ShareLock on transaction 25128; blocked by process 24508.
        Process 24508: CREATE TABLE a24382 (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);
        Process 26184: VACUUM FULL pg_class ;
2021-12-13 11:18:56.981 EST [24508] HINT:  See server log for query details.
2021-12-13 11:18:56.981 EST [24508] STATEMENT:  CREATE TABLE a24382 (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);
2021-12-13 11:18:57.092 EST [26184] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2021-12-13 11:18:57.092 EST [26184] DETAIL:  Key (relname, relnamespace)=(pg_class, 11) already exists.
2021-12-13 11:18:57.092 EST [26184] STATEMENT:  VACUUM FULL pg_class ;
2021-12-13 11:19:01.754 EST [26184] ERROR:  cache lookup failed for relation 171287
2021-12-13 11:19:01.754 EST [26184] STATEMENT:  VACUUM FULL pg_class ;
2021-12-13 11:19:04.592 EST [24508] ERROR:  deadlock detected
2021-12-13 11:19:04.592 EST [24508] DETAIL:  Process 24508 waits for RowExclusiveLock on relation 1259 of database 16384; blocked by process 26184.
        Process 26184 waits for ShareLock on transaction 26880; blocked by process 24508.
        Process 24508: CREATE TABLE a26127 (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);
        Process 26184: VACUUM FULL pg_class ;
2021-12-13 11:19:04.592 EST [24508] HINT:  See server log for query details.
2021-12-13 11:19:04.592 EST [24508] STATEMENT:  CREATE TABLE a26127 (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);
2021-12-13 11:19:06.454 EST [24071] LOG:  server process (PID 26184) was terminated by signal 11: Segmentation fault
2021-12-13 11:19:06.454 EST [24071] DETAIL:  Failed process was running: VACUUM FULL pg_class ;
2021-12-13 11:19:06.454 EST [24071] LOG:  terminating any other active server processes
2021-12-13 11:19:06.455 EST [29849] FATAL:  the database system is in recovery mode

Below is what was being run in psql shell:
(not the session creating the tables)

$ /usr/pgsql-14/bin/psql -d testdb
psql (14.1)
Type "help" for help.

testdb=# VACUUM FULL pg_class ;
VACUUM
testdb=# SELECT  datname, pg_size_pretty( pg_database_size(datname) ) FROM pg_database;
  datname  | pg_size_pretty
-----------+----------------
 postgres  | 8769 kB
 testdb    | 315 MB
 template1 | 8617 kB
 template0 | 8617 kB
(4 rows)

testdb=# VACUUM FULL pg_class ;
ERROR:  cache lookup failed for relation 155205
testdb=# VACUUM FULL pg_class ;
ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(pg_class, 11) already exists.
testdb=# VACUUM FULL pg_class ;
ERROR:  cache lookup failed for relation 171287
testdb=# VACUUM FULL pg_class ;
VACUUM
testdb=# VACUUM FULL pg_class ;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

### How can we reproduce the bug?

1) Create database and install TimescaleDB extension
2) In a psql session connected to that database run:

```
testdb=# SELECT format('CREATE TABLE a%s (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);',i) FROM generate_series(1, 200000) i
\gexec
```

While above is running connect via another psql session connect to same database, wait until pg_class is over 20MB then run `VACUUM FULL pg_class` several times.
```

**Comment by nikkhils** [comment] 2021-12-15 11:35
@mfundul's potential fix seems to remove the crashes/errors.

**Comment by nikkhils** [comment] 2021-12-20 07:07
The reproduction steps mentioned above are always able to reproduce the issue. However, we need to spend time to understand the actual sequence of events which is causing the bug to surface up. 

It also appears that it's somehow being triggered via parallel worker processes in the `cache_invalidate_callback` callback which seems to be doing a lot of cached catalog accesses WHILE the cache is being invalidated. This is, in general, non-standard behavior in cache clearing callbacks.

One option is to NOT to use the cache via `get_relname_relid` and `get_namespace_oid` calls but to directly use `systable_beginscan` and `systable_getnext` calls to get the required information.

**Comment by nikkhils** [comment] 2021-12-20 14:39
https://github.com/timescale/timescaledb/pull/3875 has a version of fix. But that is not what finally needs to be done. Linking here just in case.

**Comment by naav** [comment] 2022-03-07 14:27
I just lost a 26 TB database to this.

**Comment by NunoFilipeSantos** [comment] 2022-03-18 16:00
We're actively looking into this issue.

**Comment by jerryxwu** [comment] 2022-03-30 20:22
Apologize, I accidentally close the issue.

**Closed** 2022-04-01 06:31 UTC
Labels: bug, background-worker, segfault, pg14, RPM, 2.5.1, Core Database Team
