### ISSUE TITLE
Segfault in 1.7.2 on background worker scheduler cache invalidation handling

### ISSUE THREAD

**Issue by cevian** [timescale/timescaledb#2238] opened 2020-08-20 17:39 UTC
Very long stacktrace (many 1000s of lines with recursion in invalidation handling). Posting top and bottom.

```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `postgres: tfuxfphvz9-anum2rdelo: TimescaleDB Background Worker Scheduler      '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055cf11fd670c in LockAcquireExtended (locktag=locktag@entry=0x7ffd0f8cf040, lockmode=lockmode@entry=1, sessionLock=sessionLock@entry=false, dontWait=dontWait@entry=false,
    reportMemoryError=reportMemoryError@entry=true, locallockp=locallockp@entry=0x7ffd0f8cf038) at ./build/../src/backend/storage/lmgr/lock.c:738
#0  0x000055cf11fd670c in LockAcquireExtended (locktag=locktag@entry=0x7ffd0f8cf040, lockmode=lockmode@entry=1, sessionLock=sessionLock@entry=false, dontWait=dontWait@entry=false,
    reportMemoryError=reportMemoryError@entry=true, locallockp=locallockp@entry=0x7ffd0f8cf038) at ./build/../src/backend/storage/lmgr/lock.c:738
#1  0x000055cf11fd4010 in LockRelationOid (relid=2615, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:116
#2  0x000055cf11ceb055 in relation_open (relationId=2615, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#3  0x000055cf11d5435e in table_open (relationId=<optimized out>, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#4  0x000055cf12102c4e in SearchCatCacheMiss (cache=cache@entry=0x55cf1440e780, nkeys=nkeys@entry=1, hashValue=2512250167, hashIndex=3, v1=v1@entry=140637291613642, v2=v2@entry=0, v3=0, v4=0)
    at ./build/../src/backend/utils/cache/catcache.c:1357
#5  0x000055cf12103546 in SearchCatCacheInternal (v4=<optimized out>, v3=0, v2=0, v1=0, nkeys=<optimized out>, cache=0x55cf1440e780) at ./build/../src/backend/utils/cache/catcache.c:1299
#6  SearchCatCache (cache=0x55cf1440e780, v1=v1@entry=35, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1153
#7  0x000055cf12115291 in SearchSysCache (key4=0, key3=0, key2=0, key1=35, cacheId=<optimized out>) at ./build/../src/backend/utils/cache/syscache.c:1244
#8  GetSysCacheOid (cacheId=cacheId@entry=35, oidcol=oidcol@entry=1, key1=key1@entry=140637291613642, key2=key2@entry=0, key3=key3@entry=0, key4=key4@entry=0)
    at ./build/../src/backend/utils/cache/syscache.c:1244
#9  0x000055cf11d91227 in get_namespace_oid (nspname=nspname@entry=0x7fe8abcf0dca "_timescaledb_cache", missing_ok=missing_ok@entry=true) at ./build/../src/backend/catalog/namespace.c:3039
#10 0x00007fe8abccc87b in proxy_table_exists () at /build/timescaledb/src/extension_utils.c:167
#11 extension_current_state () at /build/timescaledb/src/extension_utils.c:167
#12 0x00007fe8abccd157 in extension_update_state () at /build/timescaledb/src/extension.c:270
#13 ts_extension_is_loaded () at /build/timescaledb/src/extension.c:270
#14 0x00007fe8abcb7299 in cache_invalidate_callback (arg=<optimized out>, relid=7069128) at /build/timescaledb/src/cache_invalidate.c:74
#15 0x000055cf121057a7 in LocalExecuteInvalidationMessage (msg=0x7ffd0f8cf410) at ./build/../src/backend/utils/cache/inval.c:595
#16 0x000055cf11fd097b in ReceiveSharedInvalidMessages (invalFunction=invalFunction@entry=0x55cf121056b0 <LocalExecuteInvalidationMessage>,
    resetFunction=resetFunction@entry=0x55cf12104ab0 <InvalidateSystemCaches>) at ./build/../src/backend/storage/ipc/sinval.c:90
#17 0x000055cf12104eb3 in AcceptInvalidationMessages () at ./build/../src/backend/utils/cache/inval.c:683
#18 0x000055cf11fd401a in LockRelationOid (relid=2615, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:136
#19 0x000055cf11ceb055 in relation_open (relationId=2615, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#20 0x000055cf11d5435e in table_open (relationId=<optimized out>, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#21 0x000055cf12102c4e in SearchCatCacheMiss (cache=cache@entry=0x55cf1440e780, nkeys=nkeys@entry=1, hashValue=2512250167, hashIndex=3, v1=v1@entry=140637291613642, v2=v2@entry=0, v3=0, v4=0)
    at ./build/../src/backend/utils/cache/catcache.c:1357
#22 0x000055cf12103546 in SearchCatCacheInternal (v4=<optimized out>, v3=0, v2=0, v1=0, nkeys=<optimized out>, cache=0x55cf1440e780) at ./build/../src/backend/utils/cache/catcache.c:1299
#23 SearchCatCache (cache=0x55cf1440e780, v1=v1@entry=35, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1153
#24 0x000055cf12115291 in SearchSysCache (key4=0, key3=0, key2=0, key1=35, cacheId=<optimized out>) at ./build/../src/backend/utils/cache/syscache.c:1244
#25 GetSysCacheOid (cacheId=cacheId@entry=35, oidcol=oidcol@entry=1, key1=key1@entry=140637291613642, key2=key2@entry=0, key3=key3@entry=0, key4=key4@entry=0)
    at ./build/../src/backend/utils/cache/syscache.c:1244
#26 0x000055cf11d91227 in get_namespace_oid (nspname=nspname@entry=0x7fe8abcf0dca "_timescaledb_cache", missing_ok=missing_ok@entry=true) at ./build/../src/backend/catalog/namespace.c:3039
#27 0x00007fe8abccc87b in proxy_table_exists () at /build/timescaledb/src/extension_utils.c:167
#28 extension_current_state () at /build/timescaledb/src/extension_utils.c:167
#29 0x00007fe8abccd157 in extension_update_state () at /build/timescaledb/src/extension.c:270
#30 ts_extension_is_loaded () at /build/timescaledb/src/extension.c:270
#31 0x00007fe8abcb7299 in cache_invalidate_callback (arg=<optimized out>, relid=7069868) at /build/timescaledb/src/cache_invalidate.c:74
#32 0x000055cf121057a7 in LocalExecuteInvalidationMessage (msg=0x7ffd0f8cf840) at ./build/../src/backend/utils/cache/inval.c:595
#33 0x000055cf11fd097b in ReceiveSharedInvalidMessages (invalFunction=invalFunction@entry=0x55cf121056b0 <LocalExecuteInvalidationMessage>,
    resetFunction=resetFunction@entry=0x55cf12104ab0 <InvalidateSystemCaches>) at ./build/../src/backend/storage/ipc/sinval.c:90
#34 0x000055cf12104eb3 in AcceptInvalidationMessages () at ./build/../src/backend/utils/cache/inval.c:683
#35 0x000055cf11fd401a in LockRelationOid (relid=2615, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:136
#36 0x000055cf11ceb055 in relation_open (relationId=2615, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#37 0x000055cf11d5435e in table_open (relationId=<optimized out>, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#38 0x000055cf12102c4e in SearchCatCacheMiss (cache=cache@entry=0x55cf1440e780, nkeys=nkeys@entry=1, hashValue=2512250167, hashIndex=3, v1=v1@entry=140637291613642, v2=v2@entry=0, v3=0, v4=0)
    at ./build/../src/backend/utils/cache/catcache.c:1357
#39 0x000055cf12103546 in SearchCatCacheInternal (v4=<optimized out>, v3=0, v2=0, v1=0, nkeys=<optimized out>, cache=0x55cf1440e780) at ./build/../src/backend/utils/cache/catcache.c:1299
#40 SearchCatCache (cache=0x55cf1440e780, v1=v1@entry=35, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1153
#41 0x000055cf12115291 in SearchSysCache (key4=0, key3=0, key2=0, key1=35, cacheId=<optimized out>) at ./build/../src/backend/utils/cache/syscache.c:1244
#42 GetSysCacheOid (cacheId=cacheId@entry=35, oidcol=oidcol@entry=1, key1=key1@entry=140637291613642, key2=key2@entry=0, key3=key3@entry=0, key4=key4@entry=0)
    at ./build/../src/backend/utils/cache/syscache.c:1244
#43 0x000055cf11d91227 in get_namespace_oid (nspname=nspname@entry=0x7fe8abcf0dca "_timescaledb_cache", missing_ok=missing_ok@entry=true) at ./build/../src/backend/catalog/namespace.c:3039
#44 0x00007fe8abccc87b in proxy_table_exists () at /build/timescaledb/src/extension_utils.c:167
```

```
#132864 0x000055cf11d91227 in get_namespace_oid (nspname=nspname@entry=0x7fe8abcf0dca "_timescaledb_cache", missing_ok=missing_ok@entry=true) at ./build/../src/backend/catalog/namespace.c:3039
#132865 0x00007fe8abccc87b in proxy_table_exists () at /build/timescaledb/src/extension_utils.c:167
#132866 extension_current_state () at /build/timescaledb/src/extension_utils.c:167
#132867 0x00007fe8abccd0af in extension_update_state () at /build/timescaledb/src/extension.c:223
#132868 ts_extension_invalidate (relid=relid@entry=7921806) at /build/timescaledb/src/extension.c:223
#132869 0x00007fe8abcb7290 in cache_invalidate_callback (arg=<optimized out>, relid=7921806) at /build/timescaledb/src/cache_invalidate.c:68
#132870 0x000055cf121057a7 in LocalExecuteInvalidationMessage (msg=0x7ffd100cc910) at ./build/../src/backend/utils/cache/inval.c:595
#132871 0x000055cf11fd0a13 in ReceiveSharedInvalidMessages (invalFunction=invalFunction@entry=0x55cf121056b0 <LocalExecuteInvalidationMessage>,
    resetFunction=resetFunction@entry=0x55cf12104ab0 <InvalidateSystemCaches>) at ./build/../src/backend/storage/ipc/sinval.c:120
#132872 0x000055cf12104eb3 in AcceptInvalidationMessages () at ./build/../src/backend/utils/cache/inval.c:683
#132873 0x000055cf11fd401a in LockRelationOid (relid=2615, lockmode=1) at ./build/../src/backend/storage/lmgr/lmgr.c:136
#132874 0x000055cf11ceb055 in relation_open (relationId=2615, lockmode=lockmode@entry=1) at ./build/../src/backend/access/common/relation.c:56
#132875 0x000055cf11d5435e in table_open (relationId=<optimized out>, lockmode=lockmode@entry=1) at ./build/../src/backend/access/table/table.c:43
#132876 0x000055cf12102c4e in SearchCatCacheMiss (cache=cache@entry=0x55cf1440e780, nkeys=nkeys@entry=1, hashValue=2512250167, hashIndex=3, v1=v1@entry=140637291613642, v2=v2@entry=0, v3=0, v4=0)
    at ./build/../src/backend/utils/cache/catcache.c:1357
#132877 0x000055cf12103546 in SearchCatCacheInternal (v4=<optimized out>, v3=0, v2=0, v1=0, nkeys=<optimized out>, cache=0x55cf1440e780) at ./build/../src/backend/utils/cache/catcache.c:1299
#132878 SearchCatCache (cache=0x55cf1440e780, v1=v1@entry=35, v2=v2@entry=0, v3=v3@entry=0, v4=v4@entry=0) at ./build/../src/backend/utils/cache/catcache.c:1153
#132879 0x000055cf12115291 in SearchSysCache (key4=0, key3=0, key2=0, key1=35, cacheId=<optimized out>) at ./build/../src/backend/utils/cache/syscache.c:1244
#132880 GetSysCacheOid (cacheId=cacheId@entry=35, oidcol=oidcol@entry=1, key1=key1@entry=140637291613642, key2=key2@entry=0, key3=key3@entry=0, key4=key4@entry=0)
    at ./build/../src/backend/utils/cache/syscache.c:1244
#132881 0x000055cf11d91227 in get_namespace_oid (nspname=nspname@entry=0x7fe8abcf0dca "_timescaledb_cache", missing_ok=missing_ok@entry=true) at ./build/../src/backend/catalog/namespace.c:3039
#132882 0x00007fe8abccc87b in proxy_table_exists () at /build/timescaledb/src/extension_utils.c:167
#132883 extension_current_state () at /build/timescaledb/src/extension_utils.c:167
#132884 0x00007fe8abccd157 in extension_update_state () at /build/timescaledb/src/extension.c:270
#132885 ts_extension_is_loaded () at /build/timescaledb/src/extension.c:270
#132886 0x00007fe8abcb76f7 in ts_catalog_get () at /build/timescaledb/src/catalog.c:449
#132887 0x00007fe8abce3ed5 in ts_bgw_job_get_all (alloc_size=alloc_size@entry=240, mctx=mctx@entry=0x55cf14383ec0) at /build/timescaledb/src/bgw/job.c:224
#132888 0x00007fe8abce64d8 in ts_update_scheduled_jobs_list (cur_jobs_list=0x7fe702000eb8, mctx=mctx@entry=0x55cf14383ec0) at /build/timescaledb/src/bgw/scheduler.c:405
#132889 0x00007fe8abce6a7e in ts_bgw_scheduler_process (run_for_interval_ms=run_for_interval_ms@entry=-1, bgw_register=bgw_register@entry=0x0) at /build/timescaledb/src/bgw/scheduler.c:723
#132890 0x00007fe8abce6bb9 in ts_bgw_scheduler_main (fcinfo=fcinfo@entry=0x7ffd100cce60) at /build/timescaledb/src/bgw/scheduler.c:809
#132891 0x000055cf12121ec1 in DirectFunctionCall1Coll (func=0x7fe8abce6b80 <ts_bgw_scheduler_main>, collation=collation@entry=0, arg1=arg1@entry=0) at ./build/../src/backend/utils/fmgr/fmgr.c:803
#132892 0x00007fe9b50063a8 in ts_bgw_db_scheduler_entrypoint (fcinfo=<optimized out>) at /build/timescaledb/src/loader/bgw_launcher.c:954
#132893 0x000055cf11f6515e in StartBackgroundWorker () at ./build/../src/backend/postmaster/bgworker.c:834
#132894 0x000055cf11f724a8 in do_start_bgworker (rw=<optimized out>) at ./build/../src/backend/postmaster/postmaster.c:5781
#132895 maybe_start_bgworkers () at ./build/../src/backend/postmaster/postmaster.c:6007
#132896 0x000055cf11f72e4b in sigusr1_handler (postgres_signal_arg=<optimized out>) at ./build/../src/backend/postmaster/postmaster.c:5178
#132897 <signal handler called>
#132898 0x00007fe9b7e0bff7 in select () from /lib/x86_64-linux-gnu/libc.so.6
#132899 0x000055cf11f735a6 in ServerLoop () at ./build/../src/backend/postmaster/postmaster.c:1668
#132900 0x000055cf11f7512f in PostmasterMain (argc=17, argv=0x55cf14383c20) at ./build/../src/backend/postmaster/postmaster.c:1377
#132901 0x000055cf11cdeeed in main (argc=17, argv=0x55cf14383c20) at ./build/../src/backend/main/main.c:228
```

**Comment by fvannee** [comment] 2020-08-20 19:47
This is duplicate of #2200 right?

**Comment by mkindahl** [comment] 2020-08-21 05:37
> This is duplicate of #2200 right?

Yes, it is a duplicate. Closing.

**Closed by mkindahl** 2020-08-21 05:37 UTC
Labels: bug, severity-p2
