### ISSUE TITLE
Multinode ON CONFLICT DO NOTHING fails

### ISSUE THREAD

**Issue by markatosi** [timescale/timescaledb#2886] opened 2021-01-30 00:30 UTC
**Relevant system information:**
 - OS: Ubuntu 20.04 LTS
 - PostgreSQL version 12.5
 - TimescaleDB version 2.0.1
 - Installation method: apt install

**Describe the bug**
When attempting to insert a row into a distributed hyper table using on collect do nothing the following error occurs
If the ON CONFLICT instruction is omitted the row is inserted

**To Reproduce**

create table public.test (
	agent_id int8 not null,
	site_id int4 not null,
	date_visit date not null,
	client_name text null,
	constraint test_pkey primary key (site_id, date_visit, agent_id)
);
select create_distributed_hypertable('test', 'date_visit','site_id', '2', chunk_time_interval => interval '1 day');

insert into test(site_id,agent_id,date_visit)
values(-1,-1,'2021-01-27') on conflict(site_id,date_visit,agent_id) do nothing;

**Expected behavior**
I expect the insert to not error out when using an on conflict instruction

**Actual behavior**
Error: [XX000] ERROR: could not find arbiter index for hypertable index "test_pkey" on chunk "_dist_hyper_11_43_chunk

**Comment by markatosi** [comment] 2021-01-30 05:35
So removing the target conditions allows the row to be inserted and prevents duplicate rows from being inserted but this is not helpful for "on conflict do update" scenario. That results in the error: [XX000] ERROR: unexpected ON CONFLICT specification: 2

**Comment by mkindahl** [comment] 2021-02-05 12:49
@markatosi Thank you for an excellent bug report. There were no issues to reproduce the bug.

**Comment by nikkhils** [comment] 2021-02-22 09:20
Hi @markatosi 

There are two issues here:

### ON CONFLICT DO NOTHING support

As you also confirmed, use of `ON CONFLICT DO NOTHING` without specifying any inference columns works as expected.
I will submit a patch to give a more useful HINT when inference columns are specified. So the output will now be:

~~~sql
\set VERBOSITY default
INSERT INTO disttable VALUES ('2017-09-02 06:09', 6)
ON CONFLICT(time,device) DO NOTHING;
ERROR:  could not find arbiter index for hypertable index "disttable_pkey" on chunk "_dist_hyper_1_9_chunk"
HINT:  omit the index inference specification for distributed hypertable in the ON CONFLICT (...) clause
~~~

### ON CONFLICT DO UPDATE support

This is  not supported yet and I agree with you that the error is very esoteric. So for now, I will submit a patch to provide a better error message:

~~~sql
INSERT INTO disttable (time, device) VALUES ('2017-09-09 08:13', 7)
 ON CONFLICT (time) DO UPDATE SET temp = 3.2;
ERROR:  ON CONFLICT DO UPDATE functionality not supported currently on distributed hypertable
~~~

Providing full support for the DO UPDATE case will take a bit more work and that will be tracked under #2963

**Comment by aljazerzen** [comment] 2021-02-22 12:16
Duplicate of #1813

**Closed** 2021-02-23 18:48 UTC
Labels: bug, multinode
