### ISSUE TITLE
[Flaky test] Replication slot active in dist_move_chunk

### ISSUE THREAD

**Issue by mkindahl** [timescale/timescaledb#4976] opened 2022-11-15 07:46 UTC
### Which test is flaky?

dist_move_chunk

### Since when has the test been flaky?

November 15, 2022

### Link to the failed test run

https://github.com/timescale/timescaledb/actions/runs/3468343243/jobs/5794069491

### Log output

```bash
diff -u /__w/timescaledb/timescaledb/tsl/test/expected/dist_move_chunk.out /__w/timescaledb/timescaledb/build/tsl/test/results/dist_move_chunk.out
--- /__w/timescaledb/timescaledb/tsl/test/expected/dist_move_chunk.out	2022-11-15 07:30:58.326609335 +0000
+++ /__w/timescaledb/timescaledb/build/tsl/test/results/dist_move_chunk.out	2022-11-15 07:38:13.271474262 +0000
@@ -567,51 +567,4 @@
 \set ON_ERROR_STOP 1
 -- Now copy chunk from data node 2 to data node 3
 CALL timescaledb_experimental.move_chunk(operation_id => 'id123', chunk=>'_timescaledb_internal._dist_hyper_3_12_chunk', source_node=> :'DATA_NODE_2', destination_node => :'DATA_NODE_3');
-\c :DATA_NODE_3 :ROLE_CLUSTER_SUPERUSER;
--- Validate chunk on data node 3
   .
   .
   .
+ERROR:  [db_dist_move_chunk_2]: replication slot "id123" is active for PID 20841
```

**Comment by akuzm** [comment] 2023-01-20 12:00
duplicate of https://github.com/timescale/timescaledb/issues/5087 ?

**Closed by akuzm** 2023-01-20 12:00 UTC
Labels: flaky-test
