### ISSUE TITLE
[Bug]: Cannot create stacked continuous aggregate - 1 month on top of 1 day

### ISSUE THREAD

**Issue by ivanzamanov** [timescale/timescaledb#5168] opened 2023-01-10 09:08 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Unable to create 1-month bucketed continuous CAgg on top of a 1-day bucketed CAgg.

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

14

### What operating system did you use?

Fedora CoreOS 37.20221225.2.2, Docker image latest-pg14

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
DROP SCHEMA
CREATE SCHEMA
CREATE TABLE
   create_hypertable
-----------------------
 (282,candles,ticks,t)
(1 row)

 set_chunk_time_interval
-------------------------

(1 row)

ALTER TABLE
 add_compression_policy
------------------------
                   1232
(1 row)

CREATE MATERIALIZED VIEW
ERROR:  cannot create continuous aggregate with incompatible bucket width
DETAIL:  Time bucket width of "candles.month" [1 mon] should be multiple of the time bucket width of "candles.day" [1 day].
```

### How can we reproduce the bug?

```bash
The following minimal example reproduces:


DROP SCHEMA IF EXISTS candles CASCADE;
CREATE SCHEMA candles;

CREATE TABLE candles.ticks (
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
  symbol CHAR(8) NOT NULL,
  quote DECIMAL NOT NULL
);

SELECT create_hypertable('candles.ticks', 'timestamp', 'symbol', 100);
SELECT set_chunk_time_interval('candles.ticks', INTERVAL '24 hours');
ALTER TABLE candles.ticks SET (timescaledb.compress, timescaledb.compress_segmentby = 'symbol');
SELECT add_compression_policy('candles.ticks', INTERVAL '1 month');

-- candles: 1 day
CREATE MATERIALIZED VIEW candles.day
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 day', timestamp) as start_time,
    symbol,
    FIRST(quote, timestamp) as quote
FROM candles.ticks GROUP BY start_time, symbol
WITH NO DATA;

-- candles: 1 month
CREATE MATERIALIZED VIEW candles.month
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 month', start_time) as start_time,
    symbol,
    FIRST(quote, start_time) as quote
FROM candles.day GROUP BY time_bucket('1 month', start_time), symbol
WITH NO DATA;
```
```

**Comment by fabriziomello** [comment] 2023-01-10 13:28
Thanks for reporting @ivanzamanov. We're working on a fix for it. Closing because it's duplicate of #5158

**Closed by fabriziomello** 2023-01-10 13:28 UTC
Labels: bug
