### ISSUE TITLE
[Bug]: time_bucket_gapfill returns incorrect data for monthly bucket with different timezone

### ISSUE THREAD

**Issue by yadhupk** [timescale/timescaledb#6170] opened 2023-10-08 01:37 UTC
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Gapfill

### What happened?

Time_bucket_gapfill gives 2 values for a month one with null values and one with data when a different timezone is used. Please refer to the screenshot. Have attached steps to reproduce this issue. 

location | month | temp
----------+------------------------+-------
basement | 2023-05-28 23:00:00+00 |
basement | 2023-05-31 22:00:00+00 | 136.5

![image](https://github.com/timescale/timescaledb/assets/133657286/4f714a5b-7fae-43be-b466-d7979fdca80e)
[Repro_Steps_02102023.txt](https://github.com/timescale/timescaledb/files/12839547/Repro_Steps_02102023.txt)

### TimescaleDB version affected

2.11.2

### PostgreSQL version used

15.4

### What operating system did you use?

Windows 11

### What installation method did you use?

Not applicable

### What platform did you run on?

Amazon Web Services (AWS)

### How can we reproduce the bug?

```bash
Please refer the attachment to reproduce the issue.
```
steps:
```
INSERT INTO conditions
  VALUES
    (NOW(), 'office', 70.0),
    (NOW(), 'basement', 66.5),
    (NOW(), 'garage', 77.0);
​
insert into conditions values(NOW()-interval '4 months', 'basement', 66.5);

insert into conditions values( '2023-06-25 08:00:00','basement', 70);

SELECT location, time_bucket_gapfill('1 month', time, 'Europe/Berlin') as month, sum(temperature) as temp
FROM conditions
WHERE time >= '2023-01-01T00:00:00.000+01:00'::timestamptz AND "time" <= '2023-12-31T23:59:59.999+01:00'::timestamptz and location='basement'
GROUP BY month,location order by 2;
```

**Comment by konskov** [comment] 2023-10-09 06:51
hi @yadhupk, I believe this issue is another instance of https://github.com/timescale/timescaledb/issues/5334.

**Comment by konskov** [comment] 2023-10-09 07:27
I'll go ahead and close this one since it's a duplicate of #5334.

**Closed by konskov** 2023-10-09 07:27 UTC
Labels: bug, duplicate, Team: Core Database, time_bucket_gapfill
