### ISSUE TITLE
temporary disable chunk

### ISSUE THREAD

**Issue by LuboVarga** [timescale/timescaledb#581] opened 2018-07-02 09:03 UTC
Is there any possibility to temporary disable specific chunk? In conventional partitioning there is detach partition possibility.

My use case is to try my application out if it would sustain dropping last chunk. Just to simulate that it is dropped and when application does not work correctly, just re-enable given chunk, instead of reimporting it from backup.

**Comment by RobAtticus** [comment] 2018-07-06 15:40
You could try doing this as part of a transaction which you rollback instead of committing.

**Comment by mfreed** [comment] 2018-07-22 00:58
The short answer is that I'm not aware of any easy way to currently implement this functionality.

**Comment by AndyMender** [comment] 2018-07-22 07:15
The solution proposed by @RobAtticus was suggested to me by a senior colleague as well.

**Comment by dianasaur323** [comment] 2019-07-16 20:34
Given that there is a workaround for this for now, I'm marking this as a question instead of an enhancement

**Comment by svenklemm** [comment] 2020-10-19 01:40
Duplicate of #1560

**Closed by svenklemm** 2020-10-19 01:40 UTC
Labels: question
