### ISSUE TITLE
PostgreSQL 13 support

### ISSUE THREAD

**Issue by jprecuch** [timescale/timescaledb#2721] opened 2020-12-08 10:05 UTC
**Relevant system information:**
 Hi TimescaleDB team. Are there already plans for supporting PostgreSQL 13 version? I couldn't find any note for that yet. 
Any progress or timeline for that? 

**Describe the request**
Add support for Postgresql 13 for timescaledb extension

**Comment by erimatnor** [comment] 2020-12-08 10:12
Yes, PostgreSQL 13 is being worked on (there's already a draft PR). Targeted for end of January (tentative).

Closing since duplicate of https://github.com/timescale/timescaledb/issues/2434

**Closed by erimatnor** 2020-12-08 10:12 UTC

**Comment by NunoFilipeSantos** [comment] 2020-12-29 17:13
You can follow our planned efforts regarding PG13 here: https://github.com/timescale/timescaledb/issues/2779
