### ISSUE TITLE
Query planner using sequential scan instead of index scan on compressed chunks

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb#2744] opened 2020-12-14 15:22 UTC
**Relevant system information:**
 - OS: Debian 9
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 12.4 (Debian 12.4-1.pgdg90+1)
 - TimescaleDB version (output of `\dx` in `psql`): timescaledb | 2.0.0-rc4
 - Installation method: apt from packagecloud.io

**Describe the bug**
When performing a query using a disjunction on a column's value, the query planner uses sequential scans instead of index scans on compressed chunks. This causes the query to take an excessively long time and eventually time out due to `statement_timeout`.

**To Reproduce**
```
# explain select avg("scur") from haproxy where tag_id=1012530943038336713 and time > now() - interval '4 hours';
                                                                             QUERY PLAN                                                                              
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=839.33..839.34 rows=1 width=32)
   ->  Custom Scan (ChunkAppend) on haproxy  (cost=2.51..581.11 rows=103288 width=8)
         Chunks excluded during startup: 98
         ->  Index Scan using _dist_hyper_6_214_chunk_haproxy_tag_id_time_idx on _dist_hyper_6_214_chunk  (cost=0.43..49.69 rows=43 width=8)
               Index Cond: ((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
         ->  Custom Scan (DecompressChunk) on _dist_hyper_6_207_chunk  (cost=2.51..2.51 rows=1000 width=8)
               Filter: ("time" > (now() - '04:00:00'::interval))
               ->  Index Scan using compress_hyper_8_419_chunk__compressed_hypertable_8_tag_id__ts_ on compress_hyper_8_419_chunk  (cost=0.29..2.51 rows=1 width=36)
                     Index Cond: (tag_id = '1012530943038336713'::bigint)
         ->  Custom Scan (DecompressChunk) on _dist_hyper_6_211_chunk  (cost=2.51..2.51 rows=1000 width=8)
               Filter: ("time" > (now() - '04:00:00'::interval))
               ->  Index Scan using compress_hyper_8_427_chunk__compressed_hypertable_8_tag_id__ts_ on compress_hyper_8_427_chunk  (cost=0.29..2.51 rows=1 width=36)
                     Index Cond: (tag_id = '1012530943038336713'::bigint)
         ->  Custom Scan (DecompressChunk) on _dist_hyper_6_209_chunk  (cost=2.51..2.51 rows=1000 width=8)
               Filter: ("time" > (now() - '04:00:00'::interval))
               ->  Index Scan using compress_hyper_8_423_chunk__compressed_hypertable_8_tag_id__ts_ on compress_hyper_8_423_chunk  (cost=0.29..2.51 rows=1 width=36)
                     Index Cond: (tag_id = '1012530943038336713'::bigint)
         ->  Index Scan using _dist_hyper_6_213_chunk_haproxy_tag_id_time_idx on _dist_hyper_6_213_chunk  (cost=0.44..277.03 rows=245 width=8)
               Index Cond: ((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval)))

# explain select avg("scur") from haproxy where tag_id=8083010360917350495 and time > now() - interval '4 hours';
                                                                             QUERY PLAN                                                                              
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=840.45..840.46 rows=1 width=32)
   ->  Custom Scan (ChunkAppend) on haproxy  (cost=2.51..582.23 rows=103289 width=8)
         Chunks excluded during startup: 98
         ->  Index Scan using _dist_hyper_6_214_chunk_haproxy_tag_id_time_idx on _dist_hyper_6_214_chunk  (cost=0.43..50.81 rows=44 width=8)
               Index Cond: ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
         ->  Custom Scan (DecompressChunk) on _dist_hyper_6_207_chunk  (cost=2.51..2.51 rows=1000 width=8)
               Filter: ("time" > (now() - '04:00:00'::interval))
               ->  Index Scan using compress_hyper_8_419_chunk__compressed_hypertable_8_tag_id__ts_ on compress_hyper_8_419_chunk  (cost=0.29..2.51 rows=1 width=36)
                     Index Cond: (tag_id = '8083010360917350495'::bigint)
         ->  Custom Scan (DecompressChunk) on _dist_hyper_6_211_chunk  (cost=2.51..2.51 rows=1000 width=8)
               Filter: ("time" > (now() - '04:00:00'::interval))
               ->  Index Scan using compress_hyper_8_427_chunk__compressed_hypertable_8_tag_id__ts_ on compress_hyper_8_427_chunk  (cost=0.29..2.51 rows=1 width=36)
                     Index Cond: (tag_id = '8083010360917350495'::bigint)
         ->  Custom Scan (DecompressChunk) on _dist_hyper_6_209_chunk  (cost=2.51..2.51 rows=1000 width=8)
               Filter: ("time" > (now() - '04:00:00'::interval))
               ->  Index Scan using compress_hyper_8_423_chunk__compressed_hypertable_8_tag_id__ts_ on compress_hyper_8_423_chunk  (cost=0.29..2.51 rows=1 width=36)
                     Index Cond: (tag_id = '8083010360917350495'::bigint)
         ->  Index Scan using _dist_hyper_6_213_chunk_haproxy_tag_id_time_idx on _dist_hyper_6_213_chunk  (cost=0.44..277.03 rows=245 width=8)
               Index Cond: ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval)))

# explain select avg("scur") from haproxy where (tag_id=1012530943038336713 or tag_id=8083010360917350495) and time > now() - interval '4 hours';
                                                                                                           QUERY PLAN                                                                                                           
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Finalize Aggregate  (cost=11907539.79..11907539.80 rows=1 width=32)
   ->  Gather  (cost=11907539.57..11907539.78 rows=2 width=32)
         Workers Planned: 2
         ->  Partial Aggregate  (cost=11906539.57..11906539.58 rows=1 width=32)
               ->  Parallel Custom Scan (ChunkAppend) on haproxy  (cost=10.42..988735.37 rows=4367121679 width=8)
                     Chunks excluded during startup: 196
                     ->  Parallel Bitmap Heap Scan on _dist_hyper_6_213_chunk  (cost=10.42..554.07 rows=288 width=8)
                           Recheck Cond: (((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval))) OR ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval))))
                           Filter: ("time" > (now() - '04:00:00'::interval))
                           ->  BitmapOr  (cost=10.42..10.42 rows=490 width=0)
                                 ->  Bitmap Index Scan on _dist_hyper_6_213_chunk_haproxy_tag_id_time_idx  (cost=0.00..5.09 rows=245 width=0)
                                       Index Cond: ((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
                                 ->  Bitmap Index Scan on _dist_hyper_6_213_chunk_haproxy_tag_id_time_idx  (cost=0.00..5.09 rows=245 width=0)
                                       Index Cond: ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
                     ->  Parallel Bitmap Heap Scan on _dist_hyper_6_212_chunk  (cost=10.38..549.59 rows=286 width=8)
                           Recheck Cond: (((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval))) OR ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval))))
                           Filter: ("time" > (now() - '04:00:00'::interval))
                           ->  BitmapOr  (cost=10.38..10.38 rows=486 width=0)
                                 ->  Bitmap Index Scan on _dist_hyper_6_212_chunk_haproxy_tag_id_time_idx  (cost=0.00..5.07 rows=243 width=0)
                                       Index Cond: ((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
                                 ->  Bitmap Index Scan on _dist_hyper_6_212_chunk_haproxy_tag_id_time_idx  (cost=0.00..5.07 rows=243 width=0)
                                       Index Cond: ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
                     ->  Parallel Bitmap Heap Scan on _dist_hyper_6_214_chunk  (cost=4.01..103.87 rows=53 width=8)
                           Recheck Cond: (((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval))) OR ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval))))
                           Filter: ("time" > (now() - '04:00:00'::interval))
                           ->  BitmapOr  (cost=4.01..4.01 rows=90 width=0)
                                 ->  Bitmap Index Scan on _dist_hyper_6_214_chunk_haproxy_tag_id_time_idx  (cost=0.00..1.98 rows=45 width=0)
                                       Index Cond: ((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
                                 ->  Bitmap Index Scan on _dist_hyper_6_214_chunk_haproxy_tag_id_time_idx  (cost=0.00..1.98 rows=45 width=0)
                                       Index Cond: ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
                     ->  Parallel Bitmap Heap Scan on _dist_hyper_6_215_chunk  (cost=3.99..101.63 rows=52 width=8)
                           Recheck Cond: (((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval))) OR ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval))))
                           Filter: ("time" > (now() - '04:00:00'::interval))
                           ->  BitmapOr  (cost=3.99..3.99 rows=88 width=0)
                                 ->  Bitmap Index Scan on _dist_hyper_6_215_chunk_haproxy_tag_id_time_idx  (cost=0.00..1.97 rows=44 width=0)
                                       Index Cond: ((tag_id = '1012530943038336713'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
                                 ->  Bitmap Index Scan on _dist_hyper_6_215_chunk_haproxy_tag_id_time_idx  (cost=0.00..1.97 rows=44 width=0)
                                       Index Cond: ((tag_id = '8083010360917350495'::bigint) AND ("time" > (now() - '04:00:00'::interval)))
                     ->  Custom Scan (DecompressChunk) on _dist_hyper_6_208_chunk  (cost=0.23..4988.74 rows=21974000 width=8)
                           Filter: (((tag_id = '1012530943038336713'::bigint) OR (tag_id = '8083010360917350495'::bigint)) AND ("time" > (now() - '04:00:00'::interval)))
                           ->  Parallel Seq Scan on compress_hyper_8_422_chunk  (cost=0.00..4988.74 rows=21974 width=36)
                     ->  Custom Scan (DecompressChunk) on _dist_hyper_6_210_chunk  (cost=0.23..4960.65 rows=21865000 width=8)
                           Filter: (((tag_id = '1012530943038336713'::bigint) OR (tag_id = '8083010360917350495'::bigint)) AND ("time" > (now() - '04:00:00'::interval)))
                           ->  Parallel Seq Scan on compress_hyper_8_426_chunk  (cost=0.00..4960.65 rows=21865 width=36)
                     ->  Custom Scan (DecompressChunk) on _dist_hyper_6_209_chunk  (cost=0.23..4988.29 rows=22029000 width=8)
                           Filter: (((tag_id = '1012530943038336713'::bigint) OR (tag_id = '8083010360917350495'::bigint)) AND ("time" > (now() - '04:00:00'::interval)))
                           ->  Parallel Seq Scan on compress_hyper_8_423_chunk  (cost=0.00..4988.29 rows=22029 width=36)
                     ->  Custom Scan (DecompressChunk) on _dist_hyper_6_211_chunk  (cost=0.23..4963.26 rows=21926000 width=8)
                           Filter: (((tag_id = '1012530943038336713'::bigint) OR (tag_id = '8083010360917350495'::bigint)) AND ("time" > (now() - '04:00:00'::interval)))
                           ->  Parallel Seq Scan on compress_hyper_8_427_chunk  (cost=0.00..4963.26 rows=21926 width=36)
                     ->  Custom Scan (DecompressChunk) on _dist_hyper_6_206_chunk  (cost=0.23..4928.95 rows=21795000 width=8)
                           Filter: (((tag_id = '1012530943038336713'::bigint) OR (tag_id = '8083010360917350495'::bigint)) AND ("time" > (now() - '04:00:00'::interval)))
                           ->  Parallel Seq Scan on compress_hyper_8_418_chunk  (cost=0.00..4928.95 rows=21795 width=36)
                     ->  Custom Scan (DecompressChunk) on _dist_hyper_6_207_chunk  (cost=0.23..4933.66 rows=21866000 width=8)
                           Filter: (((tag_id = '1012530943038336713'::bigint) OR (tag_id = '8083010360917350495'::bigint)) AND ("time" > (now() - '04:00:00'::interval)))
                           ->  Parallel Seq Scan on compress_hyper_8_419_chunk  (cost=0.00..4933.66 rows=21866 width=36)
 JIT:
   Functions: 58
   Options: Inlining true, Optimization true, Expressions true, Deforming true

```

**Expected behavior**
The last query should be using index scans for all chunks.

**Actual behavior**
The last query uses index scans only for uncompressed chunks.

**Additional context**
Another thing I noticed is that the last query (using the disjunction), is reading chunks that the first 2 queries are not. For example `_dist_hyper_6_206_chunk` and `_dist_hyper_6_212_chunk`.

Note that for the purposes of being able to obtain the query plan, these queries were executed on the data node of a multi-node cluster.

**Comment by erimatnor** [comment] 2020-12-18 09:30
Possible duplicate of #2722

**Comment by gayyappan** [comment] 2020-12-24 17:08
@phemmer Could you add the definition for the table  (\d <table_name> ) and the settings used for compression (timescaledb_information.compression_settings)

**Comment by phemmer** [comment] 2020-12-24 17:13
```
# \d haproxy
                             Table "public.haproxy"
       Column        |           Type           | Collation | Nullable | Default 
---------------------+--------------------------+-----------+----------+---------
 time                | timestamp with time zone |           | not null | 
 tag_id              | bigint                   |           |          | 
 bout                | bigint                   |           |          | 
 ereq                | bigint                   |           |          | 
 mode                | text                     |           |          | 
 dcon                | bigint                   |           |          | 
 scur                | bigint                   |           |          | 
 stot                | bigint                   |           |          | 
 dreq                | bigint                   |           |          | 
 conn_rate           | bigint                   |           |          | 
 rate_max            | bigint                   |           |          | 
 http_response.5xx   | bigint                   |           |          | 
 comp_rsp            | bigint                   |           |          | 
 intercepted         | bigint                   |           |          | 
 slim                | bigint                   |           |          | 
 status              | text                     |           |          | 
 http_response.3xx   | bigint                   |           |          | 
 req_tot             | bigint                   |           |          | 
 comp_out            | bigint                   |           |          | 
 bin                 | bigint                   |           |          | 
 rate_lim            | bigint                   |           |          | 
 comp_in             | bigint                   |           |          | 
 comp_byp            | bigint                   |           |          | 
 dresp               | bigint                   |           |          | 
 sid                 | bigint                   |           |          | 
 http_response.4xx   | bigint                   |           |          | 
 req_rate            | bigint                   |           |          | 
 iid                 | bigint                   |           |          | 
 rate                | bigint                   |           |          | 
 http_response.2xx   | bigint                   |           |          | 
 http_response.other | bigint                   |           |          | 
 req_rate_max        | bigint                   |           |          | 
 conn_tot            | bigint                   |           |          | 
 dses                | bigint                   |           |          | 
 smax                | bigint                   |           |          | 
 pid                 | bigint                   |           |          | 
 http_response.1xx   | bigint                   |           |          | 
 conn_rate_max       | bigint                   |           |          | 
 srv_abort           | bigint                   |           |          | 
 rtime               | bigint                   |           |          | 
 econ                | bigint                   |           |          | 
 chkdown             | bigint                   |           |          | 
 backup_servers      | bigint                   |           |          | 
 cli_abort           | bigint                   |           |          | 
 lastsess            | bigint                   |           |          | 
 ctime               | bigint                   |           |          | 
 qmax                | bigint                   |           |          | 
 active_servers      | bigint                   |           |          | 
 eresp               | bigint                   |           |          | 
 wretr               | bigint                   |           |          | 
 ttime               | bigint                   |           |          | 
 qcur                | bigint                   |           |          | 
 weight              | bigint                   |           |          | 
 lastchg             | bigint                   |           |          | 
 qtime               | bigint                   |           |          | 
 wredis              | bigint                   |           |          | 
 lbtot               | bigint                   |           |          | 
 downtime            | bigint                   |           |          | 
 check_health        | bigint                   |           |          | 
 cookie              | text                     |           |          | 
 chkfail             | bigint                   |           |          | 
 check_duration      | bigint                   |           |          | 
 check_status        | text                     |           |          | 
 check_fall          | bigint                   |           |          | 
 last_chk            | text                     |           |          | 
 check_rise          | bigint                   |           |          | 
 addr                | text                     |           |          | 
 check_code          | bigint                   |           |          | 
 agent_health        | bigint                   |           |          | 
 agent_duration      | bigint                   |           |          | 
 agent_rise          | bigint                   |           |          | 
 agent_status        | text                     |           |          | 
 agent_fall          | bigint                   |           |          | 
 agent_code          | bigint                   |           |          | 
 last_agt            | text                     |           |          | 
 cache_hits          | bigint                   |           |          | 
 wrew                | bigint                   |           |          | 
 cache_lookups       | bigint                   |           |          | 
 reuse               | bigint                   |           |          | 
 qtime_max           | bigint                   |           |          | 
 connect             | bigint                   |           |          | 
 rtime_max           | bigint                   |           |          | 
 ttime_max           | bigint                   |           |          | 
 ctime_max           | bigint                   |           |          | 
 qlimit              | bigint                   |           |          | 
 srv_icur            | bigint                   |           |          | 
 eint                | bigint                   |           |          | 
 idle_conn_cur       | bigint                   |           |          | 
 need_conn_est       | bigint                   |           |          | 
 safe_conn_cur       | bigint                   |           |          | 
 used_conn_cur       | bigint                   |           |          | 
Indexes:
    "haproxy_tag_id_time_idx" btree (tag_id, "time" DESC)
    "haproxy_time_idx" btree ("time" DESC)
Triggers:
    ts_insert_blocker BEFORE INSERT ON haproxy FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker()
Number of child tables: 690 (Use \d+ to list them.)

# select * from timescaledb_information.compression_settings where hypertable_name='haproxy';
 hypertable_schema | hypertable_name | attname | segmentby_column_index | orderby_column_index | orderby_asc | orderby_nullsfirst 
-------------------+-----------------+---------+------------------------+----------------------+-------------+--------------------
 public            | haproxy         | tag_id  |                      1 |                      |             | 
 public            | haproxy         | time    |                        |                    1 | f           | t
(2 rows)
```

**Comment by svenklemm** [comment] 2021-04-11 00:07
The cause might be your use of OR in the WHERE clause. Did you try replacing it with IN or = ANY
```
explain select avg("scur") from haproxy where tag_id IN(1012530943038336713,8083010360917350495) and time > now() - interval '4 hours';
explain select avg("scur") from haproxy where tag_id = ANY(ARRAY[1012530943038336713,8083010360917350495]) and time > now() - interval '4 hours';
```

**Comment by NunoFilipeSantos** [comment] 2021-10-01 11:28
@phemmer let us know if @svenklemm's suggestion worked. If it didn't feel free to reopen the issue.

**Closed by NunoFilipeSantos** 2021-10-01 11:28 UTC
Labels: bug, need-more-info, investigate
