### ISSUE TITLE
Telegraf plugin `tags_as_foreignkeys` & `table_template` incompatibility

### ISSUE THREAD

**Issue by pphysch** [timescale/timescaledb#1706] opened 2020-02-21 23:31 UTC
I'm not sure where is most appropriate to submit this.

**Platform:**

- CentOS 7 (kernel 3.10.0-1062.12.1.el7.x86_64)
- PostgreSQL 11.7
- TimescaleDB 1.6.0
- Telegraf 1.13.0 (`telegraf-1.13.0~with~pg-1.x86_64.rpm`)

# Problem

In the TimescaleDB/Postgres section of the Telegraf configuration file, the default `table_template` option is
```
table_template = "CREATE TABLE IF NOT EXISTS {TABLE}({COLUMNS}); SELECT create_hypertable({TABLELITERAL},'time',chunk_time_interval := '1 week'::interval,if_not_exists := true);
```
which works great for automatic schema setup and hypertable creation.

However, when enabling the `tags_as_foreignkeys` option (default false), Telegraf crashes because it is applying `table_template` to the tag-metadata table(s) as well, which do not have a `'time'` column and fail at `create_hypertable()`.

# Workaround

Append to `table_template` as follows:
```
table_template = "CREATE TABLE IF NOT EXISTS {TABLE}({COLUMNS}); SELECT create_hypertable({TABLELITERAL},'time',chunk_time_interval := '1 week'::interval,if_not_exists := true) FROM pg_attribute WHERE attrelid={TABLELITERAL}::regclass AND attname='time';"
```
so that hypertable creation is only attempted if there is a `'time'` column in the table.

**Comment by bboule** [comment] 2020-02-25 17:09
@blagojts  is this something you could take a look at?

**Comment by svenklemm** [comment] 2020-10-14 08:48
Closing this since this seems to be an issue with the telegraf plugin. Feel free to reopen if you think the issue is still relevant.

**Closed by svenklemm** 2020-10-14 08:48 UTC
Labels: Telegraf, bug
