### ISSUE TITLE
[Enhancement]: Propagate vaccum / analyze calls to compressed chunks

### ISSUE THREAD

**Issue by jnidzwetzki** [timescale/timescaledb#5431] opened 2023-03-13 09:09 UTC
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Compression

### What does the enhancement do?

**Context:** At the moment, we disable autovaccum for uncompressed chunks. This will be changed in https://github.com/timescale/timescaledb/pull/5118 .  After this PR is merged, autovacuum on a hypertable will be propagated to the uncompressed area of compressed chunks and clean up dead tuples. 

However, vacuum calls (and analyze calls) are not propagated to the compressed area of a compressed chunk (i.e., to the compressed hypertable). This should be changed to clean up dead tuples in the compressed area of the chunk as well.

**Comment by shhnwz** [comment] 2023-04-04 09:56
### Quick Analysis after the merge of #5118:

- [ ] **VACUUM ALL** is including compressed and uncompressed chunks .

```
postgres=# select show_chunks('metrics_compressed');
-[ RECORD 1 ]-----------------
show_chunks | _hyper_2_4_chunk
-[ RECORD 2 ]-----------------
show_chunks | _hyper_2_5_chunk
-[ RECORD 3 ]-----------------
show_chunks | _hyper_2_6_chunk

postgres=# select * from hypertable where table_name = 'metrics_compressed';
-[ RECORD 1 ]------------+-------------------------
id                       | 2
schema_name              | public
table_name               | metrics_compressed
associated_schema_name   | _timescaledb_internal
associated_table_prefix  | _hyper_2
num_dimensions           | 1
chunk_sizing_func_schema | _timescaledb_internal
chunk_sizing_func_name   | calculate_chunk_interval
chunk_target_size        | 0
compression_state        | 1
compressed_hypertable_id | 3
replication_factor       | 

postgres=# select * from chunk where hypertable_id = 3;
-[ RECORD 1 ]-------+-------------------------
id                  | 7
hypertable_id       | 3
schema_name         | _timescaledb_internal
table_name          | compress_hyper_3_7_chunk
compressed_chunk_id | 
dropped             | f
status              | 0
osm_chunk           | f
-[ RECORD 2 ]-------+-------------------------
id                  | 8
hypertable_id       | 3
schema_name         | _timescaledb_internal
table_name          | compress_hyper_3_8_chunk
compressed_chunk_id | 
dropped             | f
status              | 0
osm_chunk           | f
-[ RECORD 3 ]-------+-------------------------
id                  | 9
hypertable_id       | 3
schema_name         | _timescaledb_internal
table_name          | compress_hyper_3_9_chunk
compressed_chunk_id | 
dropped             | f
status              | 0
osm_chunk           | f


postgres=# select oid from pg_class where relname = '_hyper_2_4_chunk';
-[ RECORD 1 ]
oid | 17145

postgres=# select oid from pg_class where relname = 'compress_hyper_3_7_chunk';
-[ RECORD 1 ]
oid | 17170

postgres=# vacuum;
WARNING:  relid 2619
WARNING:  relid 1247
WARNING:  relid 3118
WARNING:  relid 1260
WARNING:  relid 3429
WARNING:  relid 1418
WARNING:  relid 6100
WARNING:  relid 1249
WARNING:  relid 1255
WARNING:  relid 1259
WARNING:  relid 2604
WARNING:  relid 2606
WARNING:  relid 2611
WARNING:  relid 2610
WARNING:  relid 2617
WARNING:  relid 2753
WARNING:  relid 2616
WARNING:  relid 2601
WARNING:  relid 2602
WARNING:  relid 2603
WARNING:  relid 2612
WARNING:  relid 2995
WARNING:  relid 2600
WARNING:  relid 3381
WARNING:  relid 2618
WARNING:  relid 2620
WARNING:  relid 3466
WARNING:  relid 2609
WARNING:  relid 2605
WARNING:  relid 3501
WARNING:  relid 2615
WARNING:  relid 2607
WARNING:  relid 2608
WARNING:  relid 1262
WARNING:  relid 2964
WARNING:  relid 1213
WARNING:  relid 1261
WARNING:  relid 1214
WARNING:  relid 2396
WARNING:  relid 3602
WARNING:  relid 3603
WARNING:  relid 3600
WARNING:  relid 3601
WARNING:  relid 3764
WARNING:  relid 3079
WARNING:  relid 2328
WARNING:  relid 1417
WARNING:  relid 3256
WARNING:  relid 6000
WARNING:  relid 826
WARNING:  relid 3394
WARNING:  relid 3596
WARNING:  relid 3592
WARNING:  relid 3456
WARNING:  relid 3350
WARNING:  relid 3541
WARNING:  relid 3576
WARNING:  relid 2224
WARNING:  relid 6104
WARNING:  relid 6106
WARNING:  relid 6102
WARNING:  relid 2613
WARNING:  relid 12836
WARNING:  relid 12831
WARNING:  relid 12826
WARNING:  relid 12841
WARNING:  relid 16417
WARNING:  relid 16438
WARNING:  relid 16451
WARNING:  relid 16465
WARNING:  relid 16483
WARNING:  relid 16496
WARNING:  relid 16511
WARNING:  relid 16535
WARNING:  relid 16552
WARNING:  relid 16568
WARNING:  relid 16626
WARNING:  relid 16633
WARNING:  relid 16660
WARNING:  relid 16672
WARNING:  relid 16682
WARNING:  relid 16692
WARNING:  relid 16696
WARNING:  relid 16705
WARNING:  relid 16712
WARNING:  relid 16731
WARNING:  relid 16746
WARNING:  relid 16756
WARNING:  relid 16767
WARNING:  relid 16779
WARNING:  relid 16582
WARNING:  relid 16599
WARNING:  relid 16611
WARNING:  relid 16795
WARNING:  relid 16800
WARNING:  relid 16803
WARNING:  relid 16806
WARNING:  relid 17139
WARNING:  relid 17163
WARNING:  relid 17170
WARNING:  relid 17157
WARNING:  relid 17180
WARNING:  relid 17151
WARNING:  relid 17190
WARNING:  relid 17145
VACUUM
```

- [ ] VACUUM metrics_compressed;

**Comment by shhnwz** [comment] 2023-04-05 05:53
Closing this as duplicate of https://github.com/timescale/timescaledb/pull/5510

**Closed by shhnwz** 2023-04-05 05:53 UTC
Labels: duplicate, compression, enhancement
