### ISSUE TITLE
SELECT TIME_BUCKET with ORDER BY fails if using interval in WHERE

### ISSUE THREAD

**Issue by Kilill** [timescale/timescaledb#1399] opened 2019-08-14 21:26 UTC
the following select pass : 
```
SELECT TIME_BUCKET('5 minute', thetime) AS time5min,
        avg(temp)
  FROM temp
  WHERE thetime >  timestamp '2019-08-13 19:17:34' - interval '10 minutes'
  GROUP BY time5min 
  limit 10;
```
```
          time5min        |       avg        
------------------------+------------------
 2019-08-13 19:15:00+00 | 15.4827272241766
 2019-08-13 19:05:00+00 | 15.5005000591278
 2019-08-13 19:10:00+00 |  15.194000005722
(3 rows)
```

adding an ORDER BY clause fails:
```
SELECT TIME_BUCKET('5 minute', thetime) AS time5min,
        avg(temp)
  FROM temp
  WHERE thetime >  timestamp '2019-08-13 19:15' - interval '10 minutes'
  GROUP BY time5min order by time5min
  limit 100;

`ERROR:  invalid child of constraint-aware append: 10`
```
removing the timestamp and interval makes i work though:

```
SELECT TIME_BUCKET('5 minute', thetime) AS time5min,
        avg(temp)
  FROM temp
  WHERE thetime >  '2019-08-13 19:07:34' and thetime <'2019-08-13 19:17:34'
  GROUP BY time5min  order by time5min
  limit 100;

       time5min        |       avg        
------------------------+------------------
 2019-08-13 19:05:00+00 | 15.3890001296997
 2019-08-13 19:10:00+00 |  15.194000005722
 2019-08-13 19:15:00+00 | 15.5189999580383
(3 rows)

```
OS: ubuntu 16.04 LTS
Postgres: 11.5-1
Timescaledb: 1.4.1

**Comment by dianasaur323** [comment] 2019-08-15 17:52
@svenklemm can you take a look at this to see if you would classify it as a bug?

**Comment by treystout** [comment] 2019-08-23 18:11
getting the same issue on 1.3.0

## WORKS
```sql
SELECT                                                                                                                          
  time_bucket('1h', occurrence_time) AS occurrence_time,                                                                      
  avg(COALESCE((payload->'pump_intake_monitor')::float, 0)) AS intake_pressure                                                
FROM                                                                                                                            
  well_occurrences                                                                                                            
WHERE                                                                                                                           
  well_map_id = (SELECT well_map_id FROM history_well WHERE well_id=21574)                                                    
  AND                                                                                                                         
  occurrence_time BETWEEN '2019-08-07T00:00:00' AND '2019-08-23T00:00:00'                                                     
GROUP BY                                                                                                                        
  1                                                                                                                           
ORDER BY                                                                                                                        
  1 ASC;
```

## DOESN'T WORK (notice timestamp cast in WHERE clause)

```sql
SELECT                                                                                                                          
  time_bucket('1h', occurrence_time) AS occurrence_time,                                                                      
  avg(COALESCE((payload->'pump_intake_monitor')::float, 0)) AS intake_pressure                                                
FROM                                                                                                                            
  well_occurrences                                                                                                            
WHERE                                                                                                                           
  well_map_id = (SELECT well_map_id FROM history_well WHERE well_id=21574)                                                    
  AND                                                                                                                         
  occurrence_time BETWEEN '2019-08-07T00:00:00' AND '2019-08-23T00:00:00'::timestamp                                          
GROUP BY                                                                                                                        
  1                                                                                                                           
ORDER BY                                                                                                                        
  1 ASC;
```
```
ERROR:  XX000: invalid child of constraint-aware append: 10
LOCATION:  constraint_aware_append_plan_create, constraint_aware_append.c:500
```

**Comment by svenklemm** [comment] 2019-09-09 08:50
@Kilill @treystout can you provide a minimal sql script that demonstrates the problem in an otherwise empty table, i tried to reproduce the error but I couldnt

**Comment by treystout** [comment] 2019-09-09 21:06
Hmm, I can't reproduce either with a clean hypertable.

```SQL
localhost shistorian@shistorian=# \d bug;
                         Table "public.bug"
 Column  |           Type           | Collation | Nullable | Default 
---------+--------------------------+-----------+----------+---------
 d       | timestamp with time zone |           | not null | 
 payload | jsonb                    |           |          | 
Indexes:
    "bug_d_idx" btree (d DESC)
Triggers:
    ts_insert_blocker BEFORE INSERT ON bug FOR EACH ROW EXECUTE PROCEDURE _timescaledb_internal.insert_blocker()
Number of child tables: 1 (Use \d+ to list them.)



localhost shistorian@shistorian=# select * from bug;
               d               |  payload   
-------------------------------+------------
 2019-09-09 21:02:21.230958+00 | {"foo": 1}
 2019-09-09 21:02:28.158739+00 | {"foo": 5}
(2 rows)



localhost shistorian@shistorian=# SELECT
  time_bucket('1d', d) AS bucket,
  avg(coalesce((payload->'foo')::float, 0)) AS average
FROM
  bug
WHERE
  d BETWEEN
    '2019-01-01T00:00:00'::timestamp - interval '1day'
    AND
    '2020-01-01T00:00:00'::timestamp - interval '1day'
GROUP BY
  bucket
ORDER BY
  bucket ASC;
         bucket         | average 
------------------------+---------
 2019-09-09 00:00:00+00 |       3
(1 row)
```

I tried to make the query as similar to the original reported issue as possible (using time_bucket, coalescing values in an aggregate function, accessing a jsonb key), none of it reproduces. Yet I still see the same bug in the original db. Any ideas on what else could throw that planner error? `constraint_aware_append_plan_create, constraint_aware_append.c:500`

**Comment by nlhnt** [comment] 2019-10-03 10:36
I am getting the same issue, used to work before, now it fails for unknown reason.
Here's the view.
`CREATE OR REPLACE VIEW "public"."fev_last_fifteen_min_stats" AS 
 SELECT time_bucket('00:15:00'::interval, fev."timestamp") AS "timestamp",
    fev."time",
    to_char(fev."timestamp", 'HH12:MI:SS'::text) AS time_clock,
    fev.phi,
    fev.rssi,
    fev.doa,
    fev.mac_address
   FROM fev
  WHERE ((fev."timestamp" > (now() - '00:15:00'::interval)) AND (fev.phi IS NOT NULL) AND (fev.rssi IS NOT NULL))
  ORDER BY (time_bucket('00:15:00'::interval, fev."timestamp"));`

**Comment by Kilill** [comment] 2019-10-04 16:06
Sorry for late update, but:
This happened as a result of an Ubuntu upgrade to timescaledb, and i'm an idiot for not realizing that the upgrade ofc does not upgrade the databases where timescaledb is added as an extension.
After properly upgrading the extension on the database in question it works like a charm again.

**Comment by nlhnt** [comment] 2019-10-17 08:26
> 
> 
> Sorry for late update, but:
> This happened as a result of an Ubuntu upgrade to timescaledb, and i'm an idiot for not realizing that the upgrade ofc does not upgrade the databases where timescaledb is added as an extension.
> After properly upgrading the extension on the database in question it works like a charm again.

Could you elaborate?
I am using TimeScaleDB in a docker contianer and the problem exists there, don't know why?

**Comment by bboule** [comment] 2019-10-18 15:06
@nlhnt what version are you using?  Are you using something in the 1.4 branch and still seeing this issue?

**Comment by megalodn** [comment] 2019-10-19 09:55
I am using 1.4 on windows and have the same issue but only when I make an offset on the time_bucket. Without the offset it works fine. What is even more weird: Within the same DB but on other tables I can use the identical query with an offset.

**Comment by Kilill** [comment] 2019-11-03 11:13
@nlhnt According to https://docs.timescale.com/latest/using-timescaledb/update-db You need to do an `ALTER EXTENSION timescaledb UPDATE;`
On each database that has timescaldb as an extension, when upgrading the timscaledb extension

**Comment by svenklemm** [comment] 2020-08-18 09:43
closing since this seems to be resolved in recent versions, feel free to reopen if it still happens with recent versions

**Closed by svenklemm** 2020-08-18 09:43 UTC
Labels: need-more-info
