### ISSUE TITLE
Continuous aggregate: time_bucket with offset leads to error

### ISSUE THREAD

**Issue by Andi2405** [timescale/timescaledb#2970] opened 2021-02-21 20:54 UTC
**Relevant system information:**
 - OS: CentOS 8
 - PostgreSQL version: 12.0
 - TimescaleDB version: 2.0.2

**Describe the bug**
When using the `time_bucket` function with the `offset` parameter I am running into the error: 

>  continuous aggregate view must include a valid time bucket function

When running the query directly that I want to set as a **continuous aggregate**, everything works fine. When removing the `offset` parameter, everything works fine as well.

**To Reproduce**
Given a hypertable named `measurement` with three columns: `timestamp`, `sensor_uuid` and `value`

The following works:

```
CREATE MATERIALIZED VIEW measurement_minutly ("timestamp", sensor_uuid, avg, sum, min, max, count) WITH (timescaledb.continuous) AS
    SELECT time_bucket('1 minute', "timestamp") AS minutly, sensor_uuid, AVG(value), SUM(value), MIN(value), MAX(value), COUNT(value) 
    FROM measurement GROUP BY minutly, sensor_uuid 
WITH DATA;
```

But this does not:

```
CREATE MATERIALIZED VIEW measurement_minutly ("timestamp", sensor_uuid, avg, sum, min, max, count) WITH (timescaledb.continuous) AS
    SELECT time_bucket('1 minute', "timestamp", INTERVAL '-30 seconds') AS minutly, sensor_uuid, AVG(value), SUM(value), MIN(value), MAX(value), COUNT(value) 
    FROM measurement GROUP BY minutly, sensor_uuid 
WITH DATA;
```

As far as I read and understand the notes in the docs this should work, right?

**Comment by gayyappan** [comment] 2021-02-22 14:16
time_bucket with offset is not supported with continuous aggregates.

**Comment by Andi2405** [comment] 2021-02-22 21:51
This should either be implemented or added (as a note) to https://docs.timescale.com/latest/api#continuous_aggregate-create_view

**Comment by erimatnor** [comment] 2021-02-23 15:43
Closing since duplicate of https://github.com/timescale/timescaledb/issues/2265

**Closed by erimatnor** 2021-02-23 15:43 UTC
