### ISSUE TITLE
[Bug]: Occasional background worker crash

### ISSUE THREAD

**Issue by joeyberkovitz** [timescale/timescaledb#4175] opened 2022-03-16 12:54 UTC
### What type of bug is this?

Crash

### What subsystems and features are affected?

Background worker

### What happened?

The TimescaleDB background worker crashes occasionally, potentially related to connecting with pgAdmin. After this point, the database needs to be restarted to allow background tasks to run on schedule.

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

13.6

### What operating system did you use?

Ubuntu 20.04 x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
2022-03-16 04:21:36.184 UTC [45626] ERROR:  tuple concurrently updated
2022-03-16 04:21:36.189 UTC [45615] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 45626) exited with exit code 1
```

### How can we reproduce the bug?

```bash
Crash is intermittent, not yet sure what causes it
```

**Comment by nikkhils** [comment] 2022-03-17 13:05
@joeyberkovitz there's very little to go by for now. It will be great if you can provide a reproducible test  case for this.

**Comment by mkindahl** [comment] 2022-05-04 08:06
@joeyberkovitz The error message is usually caused by a race condition in updating internal tables. What kind of job were you executing? Is it a custom job, or one of the pre-provided policies?

**Comment by mkindahl** [comment] 2022-05-04 08:10
@joeyberkovitz We had a [problem in the `decompress_backfill` earlier](https://github.com/timescale/timescaledb-extras/pull/24). What version of that function are you using?

**Comment by mkindahl** [comment] 2022-05-05 06:46
@joeyberkovitz It is dealing with a locking issue causing a deadlock, not with that particular error as such. However, the error you have is related to concurrent updates so it could be related.

**Comment by mkindahl** [comment] 2022-05-18 16:26
@joeyberkovitz See #4293. The problem probably occurs because `decompress_backfill` uses `alter_job` internally.

**Comment by joeyberkovitz** [comment] 2022-05-18 17:01
Thanks. This sounds like it'll also require the same fix as in 4293? If so, I guess we can merge the two issues.

**Comment by mkindahl** [comment] 2022-05-20 20:14
Duplicate of #4293. Closing.

**Closed by mkindahl** 2022-05-20 20:14 UTC
Labels: bug, bgw
