### ISSUE TITLE
[Bug]: Refreshing Continuous Aggregate with NULL End Offset can Result in Watermark in the Future

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#4239] opened 2022-04-15 20:22 UTC
### What type of bug is this?

Other

### What subsystems and features are affected?

Continuous aggregate

### What happened?

When creating a continuous aggregate with data, (or performing a refresh with a NULL end offset). Depending on the size of the time_bucket, that can result in a watermark in the future.

This results in incorrect (or at last unexpected) realtime aggregation, since any data ingested between the refresh and when the next time_bucket boundary gets crossed will not be will not be accounted for when querying with realtime aggregation.

This is particularly apparent with longer buckets.

Perhaps this is just a docs bug and we can explain this more clearly. But the behavior of the watermarks here doesn't feel quite right, though not doing it this way might result in wrong data the other way, having some things duplicated. It seems like freshly creating a cagg with data or doing a NULL end offset refresh shouldn't invalidate realtime aggreagation results until the next bucket boundary is passed.

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

14.2

### What operating system did you use?

Timescale Docker image

### What installation method did you use?

Docker

### What platform did you run on?

Not applicable

### How can we reproduce the bug?
NB: Due to the rolling nature of time_buckets and the nature of the NULL end offset, this may be somewhat temporal in nature. For completeness sake, these tests were all run on April 15, 2022. I'm not super clear how that might affect the watermark - If your test returns some date other than April 17, 2022, that may be why, and you may need to account for that.

```bash

In a fresh database:



create table test 
(a timestamp, b int);

select create_hypertable ('test', 'a');

insert into test VALUES
('2022-04-05'::timestamp, 1),
('2022-04-15'::timestamp, 2);


create materialized view testview WITH (timescaledb.continuous) AS
select time_bucket('10 days', a) as bucket,
sum(b) as val
from test
group by 1
WITH NO DATA;

CALL refresh_continuous_aggregate('testview', NULL, NULL);
SELECT _timescaledb_internal.to_timestamp(_timescaledb_internal.cagg_watermark(2));
```
The Select results in a date in the future:

`2022-04-17 00:00:00+00`
```

**Comment by mfundul** [comment] 2022-04-15 20:25
Duplicate of https://github.com/timescale/timescaledb/issues/3877 ?

**Comment by tylerfontaine** [comment] 2022-04-15 20:30
Oh, very likely yes. I did some searching but didn't see that one.

**Comment by horzsolt** [comment] 2022-04-26 10:01
Closing as  duplicate of https://github.com/timescale/timescaledb/issues/3877

**Closed** 2022-04-26 10:01 UTC
Labels: bug
