### ISSUE TITLE
Server segfaults during COPY command of csv data

### ISSUE THREAD

**Issue by naveenrpendli** [timescale/timescaledb#1158] opened 2019-04-11 18:54 UTC
**Relevant system information:**
 - OS: CentOS7
 - PostgreSQL version 10.7
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
 - Installation method: yum install

**Describe the bug**
server closed the connection unexpectedly                          
        This probably means the server terminated abnormally       
        before or while processing the request.                    
The connection to the server was lost. Attempting reset: Failed
**To Reproduce**
1. Go to 'psql(Shell)'
2. try to import data from the CSV file
3. execute the script

**Expected behavior**

I expect the data to be imported into the table.
**Actual behavior**
A clear and concise description of what _actually_ happened.

**Comment by mfreed** [comment] 2019-04-12 02:33
Hi @naveenrpendli It sounded like there might have been some crash.

Can you please update the above to include (a) what version of TimescaleDB you are running, (b) any relevant information from the Postgres logs.  Can't do much with just the above.  Thanks!

**Comment by naveenrpendli** [comment] 2019-04-12 03:56
![Capture](https://user-images.githubusercontent.com/25126027/56011374-f1a89b80-5cac-11e9-9513-de407b8c977b.PNG)
I think the version is 0.5.0

**Comment by mfreed** [comment] 2019-04-12 14:25
@naveenrpendli I'd need the actual postgres logs where error messages are being printed.

That said, version 0.5 was released 1.5 years ago.  I would strongly recommend upgrading to the lastest (e.g., 1.2.2).  Thanks.

**Comment by naveenrpendli** [comment] 2019-04-12 19:30
![error1](https://user-images.githubusercontent.com/25126027/56061449-10e80d00-5d2f-11e9-9bce-e9d44306d132.PNG)
![error](https://user-images.githubusercontent.com/25126027/56061451-12b1d080-5d2f-11e9-88c7-f5809c78e6d4.PNG)
![verison](https://user-images.githubusercontent.com/25126027/56061584-6d4b2c80-5d2f-11e9-977d-ed37867ade56.PNG)
Timescaredb version : 1.2.2


Please help me with the issue.

**Comment by naveenrpendli** [comment] 2019-04-12 20:05
Also I'm seeing that my server was tuned for version 0.5.0, how do I change it to the recent version ?, My db has the 1.2.2 and the postgresql.conf shows the different version.

**Comment by RobAtticus** [comment] 2019-04-12 20:10
@naveenrpendli The 0.5.0 you see is the version of `timescaledb-tune` that was run, which is on a separate versioning from TimescaleDB. 0.5.0 is the latest in that regard, so you are up to date there.

**Comment by naveenrpendli** [comment] 2019-04-16 15:08
Thanks for confirming that then the issue was with the timescale and I'm still waiting for your response. I'm using pgsql-10 and I have attached all the errors that I have got. I have tried the same operation from the command line and the GUI (pgadmin) as well.

**Comment by mfreed** [comment] 2019-04-17 02:14
Hi @naveenrpendli please supply the contents of your postgres *logs*, not the stdout.  

For CentOS/RHEL, I think you'll typically fine the postgres logs somewhere like`/var/lib/pgsql/data/pg_log/` or `/var/lib/pgsql/<version>/data/pg_log/`.  Do you see something there?

**Comment by naveenrpendli** [comment] 2019-04-17 15:41
[log_timescale_12th.txt](https://github.com/timescale/timescaledb/files/3090356/log_timescale_12th.txt)
[10th.txt](https://github.com/timescale/timescaledb/files/3090412/10th.txt)


We have tried to do the same on 2 databases and the results are attached as requested form logs.

**Comment by naveenrpendli** [comment] 2019-04-23 19:51
> Hi @naveenrpendli please supply the contents of your postgres _logs_, not the stdout.
> 
> For CentOS/RHEL, I think you'll typically fine the postgres logs somewhere like`/var/lib/pgsql/data/pg_log/` or `/var/lib/pgsql/<version>/data/pg_log/`. Do you see something there?

I have attached the information that was from the logs and waiting for your response. This is the first time I was working with timescale db. Please let me know if you still need more info from me. If the issue I reported was a known issue/bug please direct me to the solution.

**Comment by mfreed** [comment] 2019-04-26 23:40
@naveenrpendli Sorry for the delay.  It appears to get a crash while COPYing the CSV.  Can you please post the contents of .csv file and the table schema into which you are copying?   

Feel free to also reach out on Slack or email the information to support (at) timescale.com, if you prefer to keep this information out of the public github issue.

**Comment by mfreed** [comment] 2019-07-10 18:44
Hi @naveenrpendli Following up for more information?

**Comment by naveenrpendli** [comment] 2019-07-24 17:25
I have provided all the info from the logs and may I know what info you are looking for ?

**Comment by mfreed** [comment] 2019-08-22 00:54
^
@naveenrpendli It appears to get a crash while COPYing the CSV. Can you please post the contents of .csv file and the table schema into which you are copying?  Wonder if the CSV has some strange characters that are causing the issue; hard to understand with this information.

**Comment by mfreed** [comment] 2019-10-28 01:19
Hi @naveenrpendli Following up once more to try to get the CSV.  Otherwise, I'll close out the issue, and we can re-open once have more information.  Thanks.

**Comment by cevian** [comment] 2019-11-20 16:22
Can't reproduce. Closing for now. Can reopen once we get more info.

**Closed by cevian** 2019-11-20 16:22 UTC
Labels: bug, need-more-info
