### ISSUE TITLE
[Bug]: superuser required for restoring

### ISSUE THREAD

**Issue by jgpruitt** [timescale/timescaledb#4291] opened 2022-05-02 13:45 UTC
### What type of bug is this?

Other

### What subsystems and features are affected?

Restore

### What happened?

`timescaledb_pre_restore()` and `timescaledb_post_restore()` both alter the database to set a GUC. This requires superuser privileges, yet the functions are not security definer functions. Thus, restoring requires superuser privileges. Is this by design? We would like promscale users to be able to restore without superuser privileges.

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

14.2

### What operating system did you use?

docker

### What installation method did you use?

Docker

### What platform did you run on?

Other

### How can we reproduce the bug?

```bash
create extension timescaledb;
create user bob;
set role bob;
select timescaledb_pre_restore();
ERROR:  permission denied to set parameter "timescaledb.restoring"
CONTEXT:  SQL statement "ALTER DATABASE db SET timescaledb.restoring ='on'"
```
```

**Comment by mkindahl** [comment] 2022-05-03 10:43
This is a duplicate of #2686

**Closed by mkindahl** 2022-05-03 10:43 UTC
Labels: bug, backup-and-restore, feature-request, low-hanging-fruit
