### ISSUE TITLE
Hierarchical continuous aggregates for price charts

### ISSUE THREAD

**Issue by MarcSky** [timescale/timescaledb#5171] opened 2023-01-10 21:55 UTC
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Hi all!!! I am new to timescaledb and decided to try its functionality. I liked the idea of continuous aggregates and decided to try to build charts for stocks.

I found a topic on the website called **"Hierarchical continuous aggregates"** that says you can overlay a table with continuous aggregates data in layers. I want to try to get 3 minute charts from 1 minute charts, but when I try to run a SQL query I get an **error**.

```
create table ts_trades
(
    ticker varchar(100),
    price_usd       numeric(50, 18) default 0                                not null,
    amount       numeric(50, 18) default 0                                not null,
    timestamp    timestamp without time zone default (now() at time zone 'utc')
);
select create_hypertable('ts_trades', 'timestamp',
                         if_not_exists => true, chunk_time_interval => interval '24 hours');

CREATE MATERIALIZED VIEW price_candles_1min
    WITH (timescaledb.continuous) AS
SELECT time_bucket('1 minute', timestamp) AS time,
       ticker,
       max(price_usd)                    AS high,
       first(price_usd, timestamp)       AS open,
       last(price_usd, timestamp)        AS close,
       min(price_usd)                    AS low,
       sum(amount)                      as volume
FROM ts_trades
GROUP BY time, ticker
WITH NO DATA;

CREATE MATERIALIZED VIEW price_candles_3min
    WITH (timescaledb.continuous) AS
SELECT time_bucket('3 minute', time) AS time2,
       ticker,
       max(high)                     AS high,
       first(open, time)             AS open,
       last(close, time)             AS close,
       min(low)                      AS low,
       sum(volume)                   as volume
FROM price_candles_1min
GROUP BY time2, ticker
WITH NO DATA;
```

My error -  **pq: time bucket function must reference a hypertable dimension column**

Can anyone tell me what I'm doing wrong and how to correct the error. Thank you!

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

15

### What operating system did you use?

Mac OS X 10.5 ARM

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Run my SQL code above.
```

**Comment by fabriziomello** [comment] 2023-01-11 13:22
@MarcSky thanks for reaching out. It was already fixed by #5133.

But there are an workaround to make this work until next release. In the original hypertable place the time dimension column ("timestamp") at the same order you do the time bucket in caggs (in this case as the 1st column), for example:
```sql
create table ts_trades
(
    timestamp    timestamp without time zone default (now() at time zone 'utc'),
    ticker varchar(100),
    price_usd       numeric(50, 18) default 0                                not null,
    amount       numeric(50, 18) default 0                                not null
);
```

**Comment by fabriziomello** [comment] 2023-01-12 16:39
@MarcSky did the workaround worked? If yes we can close this issue!

**Closed** 2023-01-12 19:48 UTC
Labels: bug, need-more-info

**Comment by MarcSky** [comment] 2023-01-14 09:07
@fabriziomello Hi, I noticed a not very handy thing. In the first example table **price_candles_1min** has bucket **AS time**, and in the second table **AS time2**, is there any way to bring time to the same view. The solution of just naming everything **TIME** doesn't help ....
Thank you.

**Comment by fabriziomello** [comment] 2023-01-16 00:34
> @fabriziomello Hi, I noticed a not very handy thing. In the first example table **price_candles_1min** has bucket **AS time**, and in the second table **AS time2**, is there any way to bring time to the same view. The solution of just naming everything **TIME** doesn't help .... Error: `pq: continuous aggregate view must include a valid time bucket function` Thank you.

Hmmm... seems it is another bug, can u please open a new issue and I can have a look on it this week!

**Comment by fabriziomello** [comment] 2023-01-16 14:11
@MarcSky having a look more carefully in your example for now there are an workaround for it (using the same column name in all caggs). Instead of using the column name in the GROUP BY change it for numbering, see the example:
```sql
create table ts_trades
(
    ticker varchar(100),
    price_usd       numeric(50, 18) default 0                                not null,
    amount       numeric(50, 18) default 0                                not null,
    timestamp    timestamp without time zone default (now() at time zone 'utc')
);
select create_hypertable('ts_trades', 'timestamp',
                         if_not_exists => true, chunk_time_interval => interval '24 hours');

CREATE MATERIALIZED VIEW price_candles_1min
    WITH (timescaledb.continuous) AS
SELECT time_bucket('1 minute', timestamp) AS time,
       ticker,
       max(price_usd)                    AS high,
       first(price_usd, timestamp)       AS open,
       last(price_usd, timestamp)        AS close,
       min(price_usd)                    AS low,
       sum(amount)                      as volume
FROM ts_trades
GROUP BY 1, 2
WITH NO DATA;

CREATE MATERIALIZED VIEW price_candles_3min
    WITH (timescaledb.continuous) AS
SELECT time_bucket('3 minute', time) AS time,
       ticker,
       max(high)                     AS high,
       first(open, time)             AS open,
       last(close, time)             AS close,
       min(low)                      AS low,
       sum(volume)                   as volume
FROM price_candles_1min
GROUP BY 1, 2
WITH NO DATA;
```

Thanks for reporting this because seems it is a very old bug (perhaps since 2.0 when the new Continuous Aggregats was introduced -- much before I joined Timescale... hehehe). I'll work on a fix for it.

**Comment by fabriziomello** [comment] 2023-01-16 14:29
@MarcSky FYI I've created an issue to fix it - https://github.com/timescale/timescaledb/issues/5185

**Comment by fabriziomello** [comment] 2023-01-16 18:13
@MarcSky actually there's no problem, the problem is in the GROUP BY clause you're using the alias name you used for the time bucket function expression and this name is the same used in the source of the continuous aggregate (in this case a cagg but the same occurs if it is over a raw hypertable) so for the GROUP BY clause Postgres is trying to use the column from the previous cagg and doing that actually you're not grouping by the time bucket function and instead by the previous cagg column. I agree that the error message is not helping too much, but will see if we can improve it.

But let me elaborate and demonstrate this Postgres behavior:

1. Given the following vanilla Postgres table:
```sql
CREATE TABLE conditions (
  time TIMESTAMPTZ NOT NULL,
  temperature NUMERIC
);

INSERT INTO conditions
SELECT *, 10
FROM generate_series('2023-01-15 00:00:00-03'::timestamptz, '2023-01-15 12:00:00-03'::timestamptz, '1 hour'::interval);
```

3. Just querying the data for reference
```sql
SELECT * FROM conditions;
          time          | temperature 
------------------------+-------------
 2023-01-15 00:00:00-03 |          10
 2023-01-15 01:00:00-03 |          10
 2023-01-15 02:00:00-03 |          10
 2023-01-15 03:00:00-03 |          10
 2023-01-15 04:00:00-03 |          10
 2023-01-15 05:00:00-03 |          10
 2023-01-15 06:00:00-03 |          10
 2023-01-15 07:00:00-03 |          10
 2023-01-15 08:00:00-03 |          10
 2023-01-15 09:00:00-03 |          10
 2023-01-15 10:00:00-03 |          10
 2023-01-15 11:00:00-03 |          10
 2023-01-15 12:00:00-03 |          10
(13 rows)
```

4. Using the `time` name in GROUP BY clause make Postgres group by data by the `conditions.time` column and not by the  `time_bucket` function expression producing wrong results:
```sql
SELECT
  time_bucket(INTERVAL '1 day', "time") AS "time",
  SUM(temperature) AS temperature
FROM conditions
GROUP BY "time";
          time          | temperature 
------------------------+-------------
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
 2023-01-14 21:00:00-03 |          10
(13 rows)
```

5. To make this GROUP BY work you have three options
* Use another alias for the `time_bucket` function expression
```sql
SELECT
  time_bucket(INTERVAL '1 day', "time") AS "bucket",
  SUM(temperature) AS temperature
FROM conditions
GROUP BY "bucket";
         bucket         | temperature 
------------------------+-------------
 2023-01-14 21:00:00-03 |         130
(1 row)
```
* Place the entire function expression to the GROUP BY clause
```sql
SELECT
  time_bucket(INTERVAL '1 day', "time") AS "time",
  SUM(temperature) AS temperature
FROM conditions
GROUP BY time_bucket(INTERVAL '1 day', "time");
          time          | temperature 
------------------------+-------------
 2023-01-14 21:00:00-03 |         130
(1 row)
```
* Or alternatively use the number of the function expression in the targetlist for the GROUP BY clause
```sql
SELECT
  time_bucket(INTERVAL '1 day', "time") AS "time",
  SUM(temperature) AS temperature
FROM conditions
GROUP BY 1;
          time          | temperature 
------------------------+-------------
 2023-01-14 21:00:00-03 |         130
(1 row)
```

Hope everything is more clear now.

**Comment by jonatas** [comment] 2023-01-17 00:31
Hi @fabriziomello, I tried something [very similar](https://gist.github.com/jonatas/aba38052ec25671a66cd53962e0d4057), and it didn't work in the third level when I try to create a continuous aggregate.  Not sure if we should reopen this or if this is a different issue 🤔

**Comment by fabriziomello** [comment] 2023-01-17 13:45
> Hi @fabriziomello, I tried something [very similar](https://gist.github.com/jonatas/aba38052ec25671a66cd53962e0d4057), and it didn't work in the third level when I try to create a continuous aggregate. Not sure if we should reopen this or if this is a different issue thinking

The problem you're facing is the same I mentioned in [my previous comment](https://github.com/timescale/timescaledb/issues/5171#issuecomment-1378746349). You should place the time dimension of the raw hypertable and time bucket for all caggs in the same order in the query projection (i.e. 1st place). For example:
```sql
CREATE MATERIALIZED VIEW candlestick_1m
WITH (timescaledb.continuous) AS
SELECT time_bucket('1m', time),
       "ticks"."symbol",
       toolkit_experimental.candlestick_agg(time, price, volume) as candlestick
FROM "ticks"
GROUP BY 1, 2
ORDER BY 1
WITH NO DATA;

CREATE MATERIALIZED VIEW candlestick_1h
WITH (timescaledb.continuous) AS
SELECT time_bucket('1 hour', "time_bucket"),
       symbol,
       toolkit_experimental.rollup(candlestick) as candlestick 
FROM "candlestick_1m"
GROUP BY 1, 2
WITH NO DATA;

CREATE MATERIALIZED VIEW candlestick_1d
WITH (timescaledb.continuous) AS
SELECT time_bucket('1 day', "time_bucket"),
       symbol,
       toolkit_experimental.rollup(candlestick) as candlestick
FROM "candlestick_1h"
GROUP BY 1, 2
WITH NO DATA;
```

**Comment by jonatas** [comment] 2023-01-17 19:18
Oh, man! Thanks for your patience! I missed the order of the elements! I haven't thought that the order could impact 😄

**Comment by jonatas** [comment] 2024-11-22 14:26
Hi @Keveen-ghori , seems they are in the same query order: May this name gives a different AST node that is not detectable 🤔 

```sql

	    md.timestamp,
-- second

	    "timestamp",
```    

can you try to rename both to something that is not a reserved keyword?
