### ISSUE TITLE
ERROR:  cache lookup failed for function 1

### ISSUE THREAD

**Issue by Pravin-kumbhar** [timescale/timescaledb#1495] opened 2019-10-24 10:02 UTC
i am trying to extend postgresql database with timescaledb using the command
create extension timescaledb;

but it gives the error is: ERROR:  cache lookup failed for function 1

**Comment by cevian** [comment] 2019-10-24 16:18
This is a duplicate of #1494. Let's use that as the tracking issue.

**Closed by cevian** 2019-10-24 16:18 UTC
