### ISSUE TITLE
[Bug]: Cannot download timescale plugin for windows

### ISSUE THREAD

**Issue by dgleba** [timescale/timescaledb#5513] opened 2023-03-30 20:58 UTC
### What type of bug is this?

Other

### What subsystems and features are affected?

Other

### What happened?

I try to download the plugin for postgres 15 for windows.
![image](https://user-images.githubusercontent.com/4622715/228962397-a55d20f0-035f-4728-8162-310eb75411ba.png)

error in chrome:
![2023-03-30 16_50_58-Downloads](https://user-images.githubusercontent.com/4622715/228962498-d1719be3-d815-45a7-bfd8-066eef9ebee9.png)

error in edge:

![2023-03-30 16_50_37-Timescale Documentation _ Install TimescaleDB on Windows - Personal - Microsoft​](https://user-images.githubusercontent.com/4622715/228962615-59944fad-02b8-4810-87ed-f596e8d6d7f6.png)

### TimescaleDB version affected

can't install

### PostgreSQL version used

15.2

### What operating system did you use?

Windows server 2019

### What installation method did you use?

Other

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
Try to download the plugin.
```

**Comment by lkshminarayanan** [comment] 2023-03-31 15:26
Hi @dgleba! 

Thank you for reporting this! We are aware of this issue and are trying to get this fixed.

**Comment by lkshminarayanan** [comment] 2023-03-31 15:27
Duplicate of #5491.

**Closed by lkshminarayanan** 2023-03-31 15:27 UTC
Labels: bug
