### ISSUE TITLE
Bug / Documentation Omission on pg_backup / pg_restore for Hypertables when source and destination table spaces differ

### ISSUE THREAD

**Issue by FireAndIce68** [timescale/timescaledb#1548] opened 2019-11-26 04:53 UTC
**Relevant system information:**
 - OS: Ubuntu 18.0 and , Windows 10 x64
 - PostgreSQL version 10, 11.6
 - TimescaleDB 1.3 - 1-5
 - Installation method: apt / msi

**Describe the bug**
When backing up and restoring the a Timescale database from one server to another where the destination server does not have the same table spaces as the source server the primary keys and indexes on the base table "disappear". While data can be selected from the base table where clauses on the time fields do not return any data.

This failure is silent. Either the documentation should be updated to reflect this restriction or Timescale should support a pg_restore to a database with different table space names

**To Reproduce**
1. pg_dump from a source server where the Timescaled tables / indexes are on a designated table space and and pg_restore to a server where that table space does not exist.

**Expected behavior**
The documentation to state this restriction / the pg-restore to at-least explicitly fail or preferably work.

**Actual behavior**
Indexes and primary keys disappeared on the base table (they still existed on the hyper_chunks)

**Screenshots**

Actual

![image](https://user-images.githubusercontent.com/28450043/69600437-4a009380-1019-11ea-92c6-9563ad7956bb.png)

Expected

![image](https://user-images.githubusercontent.com/28450043/69600463-600e5400-1019-11ea-97c0-035f812cbdba.png)

**Comment by erimatnor** [comment] 2020-01-15 13:02
@FireAndIce68 can you elaborate on the failure being silent? 

Usually, `pg_restore` warns or raises an error when objects cannot be recreated due to missing tablespace.

Can you provide a way to reproduce this particular problem?

**Comment by mfreed** [comment] 2020-11-08 03:32
Hi @FireAndIce68 Wanted to follow up to see if you have any more information?  (Otherwise, I might close this out for now.)

**Comment by FireAndIce68** [comment] 2020-11-08 16:43
You can close this issue. I suspect it was a red-herring and the underlying issue was restoring with jobs > 1 for a directory based restore.

**Closed** 2020-11-09 04:49 UTC
Labels: bug, documentation, need-more-info
