### ISSUE TITLE
timescaledb.compress unrecognized parameter namespace "timescaledb"

### ISSUE THREAD

**Issue by mattberns** [timescale/timescaledb#1985] opened 2020-06-11 22:42 UTC
**Relevant system information:**
 - Azure PostgreSQL (managed service)
 - Postgresql version 11

**Describe the bug**
Attempted to compress and received an unrecognized parameter namespace "timescaledb" error

**To Reproduce**
1. Created a table "ts.the_table", empty per instructions
2. Called `SELECT create_hyptertable('ts.the_table', 'time');`
3. Called `ALTER TABLE ts.the_table SET (timescaledb.compress); `
4. ERROR:  unrecognized parameter namespace "timescaledb"

**Expected behavior**
Compression!

**Actual behavior**
Error!

**Comment by mfreed** [comment] 2020-06-11 23:48
@mattberns I think the error is related to schema scoping.

That said, the managed service on Azure only runs the Apache 2 version of TimescaleDB, not the fully Community version.  Compression is only available in the latter:

https://www.timescale.com/products/features

If you are interested in a managed service with compression, recommend checking out Timescale Cloud (where you can also create databases running on Azure):

https://www.timescale.com/cloud/

**Comment by svenklemm** [comment] 2020-10-13 08:41
Closing this since it seems to be resolved. Feel free to reopen if the issue is still relevant.

**Closed by svenklemm** 2020-10-13 08:41 UTC
Labels: investigate

**Comment by buff** [comment] 2024-02-09 15:48
I am trying this on timescale cloud and getting the same error. How do I enable compression??
