### ISSUE TITLE
CMake error when building on MacOS

### ISSUE THREAD

**Issue by dsempel** [timescale/timescaledb#2743] opened 2020-12-14 14:19 UTC
I'm trying to build timescaledb from source, but keep running into in error when running bootstrap. Unable to find anything on this error. Anybody has any idea?

MacOS: 11.0.1
CMake: 3.19.1

```
$((1.7.4)) timescaledb $ ./bootstrap 
Build system already initialized in ./build
Do you want to remove it (this is IMMEDIATE and PERMANENT), y/n? y
-- The C compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- TimescaleDB version 1.7.4. Can be updated from version 1.7.3
-- Build type is Release
-- Install method is 'source'
CMake Error at CMakeLists.txt:121 (message):
  The compiler AppleClang does not support -fvisibility=hidden
```

**Comment by jpayne** [comment] 2020-12-15 01:37
I picked tonight to dive into TimescaleDB, and unfortunately I'm running into the exact same problem.

MacOS 11.0.1
CMake  3.19.1

**Comment by mkindahl** [comment] 2020-12-18 12:27
This is triggered because the compiler does not support the flag `-fvisibility`. What is the compiler that you're using? It seems to be using the compiler at `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc` so if you could run something like

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc --version
```

To figure out the compiler version, that would be helpful. It seems like CMake claims it is a Apple version of CLang compiler, but that might not be correct.

**Comment by dsempel** [comment] 2020-12-18 12:45
Here you go:
```
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by mkindahl** [comment] 2020-12-18 14:12
Strange. According to the documentation for the [CLang 12](https://clang.llvm.org/docs/ClangCommandLineReference.html) the option `-fvisibility=hidden` should be supported. Can you try the flag `-fvisibility=hidden` and see if that works directly?

**Comment by mkindahl** [comment] 2021-02-09 07:59
We have tested this here with the following result:

```
% clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
%  clang -fvisibility=hidden -o helloworld helloworld.c
%
```

Closing issue since it is not reproducible.

**Closed by mkindahl** 2021-02-09 07:59 UTC
Labels: build

**Comment by gelisam** [comment] 2022-03-01 14:13
Note that the error message `The compiler AppleClang does not support -fvisibility=hidden` can be reported when the underlying problem is more fundamental, because this just check just happens to be the first one performed.

When I try to compile that version of timescaledb, I get the same error message, plus a very useful message pointing me to the logs:

MacOS: 12.2.1
CMake: 3.19.1
clang: 12.0.0
timescaledb commit: tag 1.7.4

```
$ ./bootstrap
Build system already initialized in ./build
Do you want to remove it (this is IMMEDIATE and PERMANENT), y/n? y
-- The C compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- TimescaleDB version 1.7.4. Can be updated from version 1.7.3
-- Build type is Release
-- Install method is 'source'
CMake Error at CMakeLists.txt:121 (message):
  The compiler AppleClang does not support -fvisibility=hidden


-- Configuring incomplete, errors occurred!
See also "[...]/timescaledb/build/CMakeFiles/CMakeOutput.log".
See also "[...]/timescaledb/build/CMakeFiles/CMakeError.log".
```

The file `CMakeError.log` makes it very clear that the problem is with `-lSystem`, not with `-fvisibility=hidden`:

```
$ cat build/CMakeFiles/CMakeError.log
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
Build flags:
Id flags:

The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Determining if the -fvisibility=hidden option is supported for C language failed with the following output:
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

From [what I've found online](https://github.com/ponylang/ponyc/issues/3684#issuecomment-743979518) and confirmed by manually invoking `ld -lSystem` on a toy `.o` file, the solution to this `-lSystem` error is that I have to add `-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib` to my `ld` invocation. I am still trying to figure out how to tell CMake to add that flag.

**Comment by gelisam** [comment] 2022-03-01 16:41
I bumped a bunch of versions and that did the trick for me. 

MacOS: 12.2.1
CMake: 3.22.2
clang: 13.0.0
timescaledb commit: tag 2.2.1

I still see one `-lSystem` error at the top of `CMakeError.log`, but that no longer causes the `-fvisibility=hidden` error down the line.

```
$ head -n 20 build/CMakeFiles/CMakeError.log
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
Build flags:
Id flags:

The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Performing C SOURCE FILE Test CC_SUPPORTS_NO_FORMAT_TRUNCATION failed with the following output:
Change Dir: /Users/gelisam/working/c/timescaledb/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/gmake -f Makefile cmTC_40df7/fast && /usr/local/bin/gmake  -f CMakeFiles/cmTC_40df7.dir/build.make CMakeFiles/cmTC_40df7.dir/build
gmake[1]: Entering directory '/Users/gelisam/working/c/timescaledb/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_40df7.dir/src.c.o
/Library/Developer/CommandLineTools/usr/bin/cc -DCC_SUPPORTS_NO_FORMAT_TRUNCATION  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk   -Wno-format-truncation -MD -MT CMakeFiles/cmTC_40df7.dir/src.c.o -MF CMakeFiles/cmTC_40df7.dir/src.c.o.d -o CMakeFiles/cmTC_40df7.dir/src.c.o -c /Users/gelisam/working/c/timescaledb/build/CMakeFiles/CMakeTmp/src.c
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
```
