### ISSUE TITLE
Bug pg_restore from directory based backup with high concurrency fails.

### ISSUE THREAD

**Issue by FireAndIce68** [timescale/timescaledb#1584] opened 2019-12-13 05:26 UTC
**Relevant system information:**
 - OS: Ununtu 18.04 (source) Windows 10 Destination.
 - PostgreSQL version 11.6
 - TimescaleDB 1.5.1
 - Installation method: apt / zip

**Describe the bug**
When restoring from a **directory based** (Fd) backup with a high number of worker threads (j =10) the restore encounters a chunk_constraint_dimension_slice_id_fkey foreign key exception. The trace below shows the dimension table restore only completes after the chunk_constraint table. 

We have encountered this issue often (but not always) when doing linux-> linux or linux-> windows restores but this is the first time we have found a definitive reason. 

The consequence of this is that the database appears restored but while you can select data from the tables you cannot filter by the time fields. 

To work around restore with j = 1

--Restore log
pg_restore: processing data for table "_timescaledb_internal._hyper_129_732_chunk"
pg_restore: finished item 870106 TABLE DATA dimension
pg_restore: launching item 873754 TABLE DATA _hyper_129_708_chunk
pg_restore: processing data for table "_timescaledb_internal._hyper_129_708_chunk"
pg_restore: [archiver (db)] Error while PROCESSING TOC:
**pg_restore: [archiver (db)] Error from TOC entry 870112; 0 1911460 TABLE DATA chunk_constraint ava_postgres**
**pg_restore: [archiver (db)] COPY failed for table "chunk_constraint": ERROR:  insert or update on table "chunk_constraint" violates foreign key constraint "chunk_constraint_dimension_slice_id_fkey"
DETAIL:  Key (dimension_slice_id)=(1242) is not present in table "dimension_slice".**
pg_restore: finished item 870112 TABLE DATA chunk_constraint
pg_restore: launching item 873691 TABLE DATA _hyper_127_645_chunk
pg_restore: processing data for table "_timescaledb_internal._hyper_127_645_chunk"
**pg_restore: finished item 870108 TABLE DATA dimension_slice**
pg_restore: launching item 873689 TABLE DATA _hyper_127_643_chunk
pg_restore: processing data for table "_timescaledb_internal._hyper_127_643_chunk"
pg_restore: finished item 873980 TABLE DATA _hyper_142_1201_chunk

**To Reproduce**
Failure is not always deterministic but backing up a large timescale database with several time-scaled tables using the directory format and restoring with a large number of jobs -j 10 often produces the error. 

**Expected behavior**
A clean restore of the database.

**Actual behavior**
The consequence of this is that the database appears restored but while you can select data from the tables you cannot filter by the time fields.

**Comment by mfreed** [comment] 2019-12-13 05:53
Hi @FireAndIce68 Thank you for the report.  Can you confirm that you are following the directions here:  https://docs.timescale.com/latest/using-timescaledb/backup

And namely, that you execute `pg_restore` after calling:

```
CREATE DATABASE tutorial;
\c tutorial --connect to the db where we'll perform the restore
CREATE EXTENSION timescaledb;
SELECT timescaledb_pre_restore();
```

**Comment by FireAndIce68** [comment] 2019-12-18 05:48
Yes I can confirm that I am using the directions on your web site.

**Comment by netman1ac** [comment] 2020-02-28 12:21
Same here.
OS: Debian GNU/Linux 10
postgresql-10           10.12-2.pgdg100+1
timescaledb-1.3.1-postgresql-10         1.3.1~debian10

/usr/bin/pg_restore -h 127.0.0.1 -p 5432 -U postgres -j 10 -d postgres -v /opt/backup/

`2020-02-28 14:45:14.019 MSK [7061] postgres@postgres ERROR:  insert or update on table "chunk_constraint" violates foreign key constraint "chunk_constraint_dimension_slice_id_fkey"
2020-02-28 14:45:14.019 MSK [7061] postgres@postgres DETAIL:  Key (dimension_slice_id)=(3719) is not present in table "dimension_slice".
2020-02-28 14:45:14.019 MSK [7061] postgres@postgres STATEMENT:  COPY _timescaledb_catalog.chunk_constraint (chunk_id, dimension_slice_id, constraint_name, hypertable_constraint_name) FROM stdin;

2020-02-28 14:46:16.557 MSK [5946] LOG:  server process (PID 7054) was terminated by signal 9: Killed`

**Comment by ryan-berger** [comment] 2020-05-21 00:24
@gayyappan Any update on this? I am having the same issue

**Comment by svenklemm** [comment] 2020-10-19 01:42
Duplicate of #698

**Closed by svenklemm** 2020-10-19 01:42 UTC
Labels: bug, investigate
