### ISSUE TITLE
drop_chunks() Fails against hypertable with cagg defined with no ignore_invalidation_older set

### ISSUE THREAD

**Issue by tylerfontaine** [timescale/timescaledb#1921] opened 2020-05-19 23:08 UTC
**Relevant system information:**
 - OS: Centos 7
 - PostgreSQL version (output of `postgres --version`):  PostgreSQL 11.8 on x86_64-pc-linux-gnu
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.1
 - Installation method: [e.g., "using Docker", "apt install", "source"] Yum

**Describe the bug**
Calling `SELECT count(*)
FROM drop_chunks(INTERVAL ‘3 days’, ‘some_hypertable’, cascade_to_materializations => FALSE);` against a hypertable that has a cagg defined against it with no `ignore_invalidation_older_than` set.

It works as expected if `cascade_to_materializations` is TRUE

This is problematic, because `ignore_invalidation_older_than` is not required to create a cagg, and it is non-intuitive that this should fail if not cascading to the materalization.

**To Reproduce**
1. Create a hypertable.
2. Create a cagg on that hypertable, do NOT set `ignore_invalidation_older_than` on the cagg.
3. Execute a drop_chunks against the hypertable, setting `cascade_to_materializations` to FALSE in the call : `drop_chunks(INTERVAL ‘3 days’, ‘some_hypertable’, cascade_to_materializations => FALSE);`
4. See error: `ERROR:  older_than must be greater than the timescaledb.ignore_invalidation_older_than parameter of public.some_cagg`

**Expected behavior**
The expected chunks would be dropped from the hypertable.

**Actual behavior**
The call fails with the following error: `ERROR:  older_than must be greater than the timescaledb.ignore_invalidation_older_than parameter of public.some_cagg`

**Comment by erimatnor** [comment] 2020-08-31 08:59
The described behavior is by design. The user experience is, admittedly, not great, however. Therefore, we have decided to change this behavior as part of a larger refactor of continuous aggregates in version 2.0. Closing this issue for this reason.

**Closed by erimatnor** 2020-08-31 08:59 UTC
Labels: continuous-aggs, severity-p3, ui/ux
