### ISSUE TITLE
[Bug]: Copy fetcher creates NULL values

### ISSUE THREAD

**Issue by nikolaps** [timescale/timescaledb#5323] opened 2023-02-14 13:30 UTC
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Distributed hypertable

### What happened?

We have a hypertable  with all fields NOT NULL constraint:
```
ticks=# \d schema.table_name
                            Table "schema.table_name"
    Column     |            Type             | Collation | Nullable | Default
---------------+-----------------------------+-----------+----------+---------
 col01         | integer                     |           | not null |
 col02         | integer                     |           | not null |
 col03         | character(1)                |           | not null |
 col04         | double precision            |           | not null |
 col05         | double precision            |           | not null |
 col06         | integer                     |           | not null |
 col07         | timestamp without time zone |           | not null |
 col08         | timestamp without time zone |           | not null |
 sol09         | integer                     |           |          |
Indexes:
    "table_name_col01_idx" btree (col01)
    "table_name_col07_idx" btree (col07 DESC)
Triggers:
    ts_insert_blocker BEFORE INSERT ON schema.table_name FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker()
Number of child tables: 9138 (Use \d+ to list them.)
```
However, with certain timestamp condition interval in where clause the query returns one row with all NULLs:

```
select count(col01), count(*)
 from schema.table_name
where col07 > '2023-01-24 14:31:08.009484'
and col07 <= '2023-01-24 14:31:10.009484'
 and col01 = 618;
 count | count
-------+-------
  9999 | 10000
(1 row)
```
and
```
select count(*)
from schema.table_name where col01 is null;
 count
-------
     0
(1 row)
```
![photo_2023-02-13_15-31-36](https://user-images.githubusercontent.com/44470692/218751743-ccbeadfe-e1e2-4fd4-bef6-e6ea858cfc1d.jpg)

col07 is the field we use as chunk partition key, If I change the interval (enlarge or shrink, whatever) - the null row disappears

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

14.1

### What operating system did you use?

AlmaLinux release 8.7

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
I don't think this is possible, since data populated this table is sensitive.
```

**Comment by kgyrtkirk** [comment] 2023-02-22 15:15
* can we have an `explain analyze` for the problematic query? (I guess it will be the usual; but we never know)
```
select count(col01), count(*)
 from schema.table_name
where col07 > '2023-01-24 14:31:08.009484'
and col07 <= '2023-01-24 14:31:10.009484'
 and col01 = 618;
```
  I suspect that this might be connected to the append

* is there anything suspicious in the logs?

**Comment by nikolaps** [comment] 2023-02-22 15:26
1. explain analyze
select *
where col07 > '2023-01-24 14:31:08.009484'
and col07 <= '2023-01-24 14:31:10.009484'
and col01 = 618;
                                                               QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------
 Custom Scan (DataNodeScan) on table_name  (cost=100.00..10314286.33 rows=9456 width=56) (actual time=12.240..12.767 rows=10000 loops=1)
 Planning Time: 1.418 ms
 Execution Time: 13.930 ms
(3 rows)

**Comment by kgyrtkirk** [comment] 2023-02-22 16:30
* I've tried to reproduce it - so far without success
* could you try making the same query on the data nodes? see if the query returns the incorrect result on just one of them
* that explain is a bit odd - I wonder why there aren't any more nodes there? like `Aggregate` or `Append`?
  * if you do more explains please also add `verbose`

**Comment by nikolaps** [comment] 2023-02-22 16:53
On access node:

```
explain analyze verbose
 select count(col01), count(*)
 from schema.table_name
 where col07 > '2023-01-24 14:31:08.009484'
   and col07 <= '2023-01-24 14:31:10.009484'
   and col01 = 618;

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|QUERY PLAN                                                                                                                                                                                                                                                                                                                                                                                       |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|Custom Scan (DataNodeScan) on okex.okex_book  (cost=100.00..10314286.33 rows=9456 width=56) (actual time=8.828..9.180 rows=10000 loops=1)                                                                                                                                                                                                                                                        |
|  Output: table_name.col01, table_name.col02, table_name.col03, table_name.col04, table_name.col05, table_name.col06, table_name.col07, table_name.col08, table_name.col09                                                                                                                                                                                               |
|  Data node: dn1                                                                                                                                                                                                                                                                                                                                                                                 |
|  Fetcher Type: COPY                                                                                                                                                                                                                                                                                                                                                                             |
|  Chunks: _dist_hyper_96_176351_chunk                                                                                                                                                                                                                                                                                                                                                            |
|  Remote SQL: SELECT col01,col02,col03,col04,col05,col06,col07,col08,col09 FROM schema.table_name WHERE _timescaledb_internal.chunks_in(schema.table_name.*, ARRAY[110903]) AND ((col07 > '2023-01-24 14:31:08.009484'::timestamp without time zone)) AND ((col07 <= '2023-01-24 14:31:10.009484'::timestamp without time zone)) AND ((col01= 618))|
|Query Identifier: -4776214072007373409                                                                                                                                                                                                                                                                                                                                                           |
|Planning Time: 0.594 ms                                                                                                                                                                                                                                                                                                                                                                          |
|Execution Time: 9.680 ms                                                                                                                                                                                                                                                                                                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

On data node 1 the issue is not reproduced:

```
 select count(col01), count(*)
 from schema.table_name
 where col07 > '2023-01-24 14:31:08.009484'
   and col07 <= '2023-01-24 14:31:10.009484'
   and col01 = 618;
   
 count | count
-------+-------
  9999 | 9999
(1 row)
```

**Comment by jnidzwetzki** [comment] 2023-03-01 15:42
Hello @nikolaps,

I would like to try to reproduce the issue in my local environment. Could you share the `create_distributed_hypertable` command that you have used to create the distributed hypertable? Does the issue also occur in your environment if you remove the `col01 = 618` part of the query? In addition, might it be possible to give a rough estimation of how many rows are stored in this distributed hypertable and how many data nodes you are using?

**Comment by jnidzwetzki** [comment] 2023-03-02 08:33
Hello @nikolaps,

Thanks for getting back to us. Unfortunately, I was not able to reproduce the behavior in my local environment so far. TimescaleDB provides two different fetcher types that determine how the data is transferred. In your query, the `COPY` fetcher is used. Could you switch to the cursor fetcher and re-run the query? This would help me to check which component of the software might be responsible for this behavior.

```sql
set timescaledb.remote_data_fetcher = cursor;
```

Are the `NULL` values still contained in the query result or is the result correct by using the cursor fetcher?

**Comment by nikolaps** [comment] 2023-03-02 14:12
Hi,
If I set timescaledb.remote_data_fetcher = cursor;

**Comment by jnidzwetzki** [comment] 2023-03-03 11:04
Hello @nikolaps,

Thanks for getting back to us. So, the `COPY` fetcher seems to be the component that is responsible for the problem. We made a few changes to the fetcher code in the last versions of TimescaleDB. Could you try if an upgrade to version 2.10.0 solves the problem or if the problem also occurs with this version of TimescaleDB?

**Comment by nikolaps** [comment] 2023-03-03 11:08
Hello,
The issue still persist after upgrade:
```
\dx
                                            List of installed extensions
        Name        | Version |   Schema   |                              Description
--------------------+---------+------------+------------------------------------------------------------------------
 pg_stat_statements | 1.9     | public     | track planning and execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb        | 2.10.0  | public     | Enables scalable inserts and complex queries for time-series data
(3 rows)

select count(col01), count(*)
 from schema.table_name
where col07 > '2023-01-24 14:31:08.009484'
and col07 <= '2023-01-24 14:31:10.009484'
 and col01 = 618;
 count | count
-------+-------
  9999 | 10000
(1 row)
```

**Comment by jnidzwetzki** [comment] 2023-03-03 14:21
Hello @nikolaps,

Thank you for performing the upgrade and testing this again. I was able to create a reproducible test case for this issue. I am using TimescaleDB 2.10.0 with PostgreSQL 14.2 in the following example. 

There seems to be a problem when exactly 9999 results with the `COPY` fetcher are transferred; this explains why the problem disappears as soon as you remove the `col01 = 618` condition from the query.

```sql
create extension timescaledb;
select add_data_node('data_node_1', host => 'localhost', database => 'data_node_1');
create table metric(ts timestamptz NOT NULL, sensor_id int NOT NULL, value float NOT NULL);
select create_distributed_hypertable('metric', 'ts', 'sensor_id');
insert into metric select now() as time, sensor_id, random() as value from generate_series(1, 9999, 1 ) as g1(sensor_id) order by time;

test2=# set timescaledb.remote_data_fetcher = cursor;
SET
test2=# select count(*), count(value) from metric;
 count | count 
-------+-------
  9999 |  9999
(1 row)

test2=# set timescaledb.remote_data_fetcher = copy;
SET
test2=# select count(*), count(value) from metric;
 count | count 
-------+-------
 10000 |  9999
(1 row)
```

Inserting a further value fixes the result:

```sql
test2=# insert into metric values (now(), 10, 10);
INSERT 0 1
test2=# select count(*), count(value) from metric;
 count | count 
-------+-------
 10000 | 10000
(1 row)
```

Running the same query on a debug build triggers an assert:

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f715368e537 in __GI_abort () at abort.c:79
#2  0x000055ad1cfef53c in ExceptionalCondition (conditionName=0x7f713dc8dc76 "fetcher->state.eof", errorType=0x7f713dc8d72f "FailedAssertion", 
    fileName=0x7f713dc8d808 "/home/jan/timescaledb/tsl/src/remote/copy_fetcher.c", lineNumber=494) at assert.c:69
#3  0x00007f713dc5e2a9 in copy_fetcher_complete (fetcher=0x55ad1f070770) at /home/jan/timescaledb/tsl/src/remote/copy_fetcher.c:494
#4  0x00007f713dc5e3da in copy_fetcher_fetch_data (df=0x55ad1f070770) at /home/jan/timescaledb/tsl/src/remote/copy_fetcher.c:535
#5  0x00007f713dc5e441 in copy_fetcher_store_tuple (df=0x55ad1f070770, row=0, slot=0x55ad1f020d58) at /home/jan/timescaledb/tsl/src/remote/copy_fetcher.c:547
#6  0x00007f713dc5e58d in copy_fetcher_store_next_tuple (df=0x55ad1f070770, slot=0x55ad1f020d58) at /home/jan/timescaledb/tsl/src/remote/copy_fetcher.c:569
#7  0x00007f713dc2adbb in fdw_scan_iterate (ss=0x55ad1f020aa8, fsstate=0x55ad1f020bc0) at /home/jan/timescaledb/tsl/src/fdw/scan_exec.c:333
#8  0x00007f713dc368fd in data_node_scan_next (node=0x55ad1f020aa8) at /home/jan/timescaledb/tsl/src/fdw/data_node_scan_exec.c:66
#9  0x000055ad1cc0c0c8 in ExecScanFetch (node=0x55ad1f020aa8, accessMtd=0x7f713dc368ac <data_node_scan_next>, recheckMtd=0x7f713dc36913 <data_node_scan_recheck>)
    at execScan.c:133
#10 0x000055ad1cc0c169 in ExecScan (node=0x55ad1f020aa8, accessMtd=0x7f713dc368ac <data_node_scan_next>, recheckMtd=0x7f713dc36913 <data_node_scan_recheck>)
    at execScan.c:199
#11 0x00007f713dc36998 in data_node_scan_exec (node=0x55ad1f020aa8) at /home/jan/timescaledb/tsl/src/fdw/data_node_scan_exec.c:97
#12 0x000055ad1cc25846 in ExecCustomScan (pstate=0x55ad1f020aa8) at nodeCustom.c:115
#13 0x000055ad1cc0828e in ExecProcNodeFirst (node=0x55ad1f020aa8) at execProcnode.c:463
#14 0x000055ad1cc1778e in ExecProcNode (node=0x55ad1f020aa8) at ../../../src/include/executor/executor.h:257
#15 0x000055ad1cc17c95 in fetch_input_tuple (aggstate=0x55ad1f020450) at nodeAgg.c:581
#16 0x000055ad1cc1aefc in agg_retrieve_direct (aggstate=0x55ad1f020450) at nodeAgg.c:2364
#17 0x000055ad1cc1aad4 in ExecAgg (pstate=0x55ad1f020450) at nodeAgg.c:2179
#18 0x000055ad1cc0828e in ExecProcNodeFirst (node=0x55ad1f020450) at execProcnode.c:463
#19 0x000055ad1cbfc88e in ExecProcNode (node=0x55ad1f020450) at ../../../src/include/executor/executor.h:257
#20 0x000055ad1cbff27c in ExecutePlan (estate=0x55ad1f020200, planstate=0x55ad1f020450, use_parallel_mode=false, operation=CMD_SELECT, sendTuples=true, 
    numberTuples=0, direction=ForwardScanDirection, dest=0x55ad1f02d960, execute_once=true) at execMain.c:1551
#21 0x000055ad1cbfcf35 in standard_ExecutorRun (queryDesc=0x55ad1f041000, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:361
#22 0x000055ad1cbfcd48 in ExecutorRun (queryDesc=0x55ad1f041000, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:305
#23 0x000055ad1ce5336b in PortalRunSelect (portal=0x55ad1ef6b850, forward=true, count=0, dest=0x55ad1f02d960) at pquery.c:921
#24 0x000055ad1ce5301c in PortalRun (portal=0x55ad1ef6b850, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x55ad1f02d960, altdest=0x55ad1f02d960, 
    qc=0x7ffe8c5ac3c0) at pquery.c:765
#25 0x000055ad1ce4c917 in exec_simple_query (query_string=0x55ad1eefe3f0 "SELECT count(*), count(value) from metric;") at postgres.c:1214
#26 0x000055ad1ce51126 in PostgresMain (argc=1, argv=0x7ffe8c5ac650, dbname=0x55ad1ef2f240 "test2", username=0x55ad1ef2f220 "jan") at postgres.c:4486
#27 0x000055ad1cd87c6d in BackendRun (port=0x55ad1ef2b860) at postmaster.c:4530
#28 0x000055ad1cd8759f in BackendStartup (port=0x55ad1ef2b860) at postmaster.c:4252
#29 0x000055ad1cd83781 in ServerLoop () at postmaster.c:1745
#30 0x000055ad1cd82fce in PostmasterMain (argc=3, argv=0x55ad1eef7a60) at postmaster.c:1417
#31 0x000055ad1cc80cce in main (argc=3, argv=0x55ad1eef7a60) at main.c:209
```

**Closed** 2023-03-09 13:29 UTC
Labels: bug, distributed-hypertable
