### ISSUE TITLE
Backfilled data outside of refresh_lag not calculated in caggs

### ISSUE THREAD

**Issue by slasktrat** [timescale/timescaledb#2285] opened 2020-08-31 07:19 UTC
**Relevant system information:**
 - OS: Debian 10
 - PostgreSQL version: 12.3
 - TimescaleDB version: 1.7.2
 - Installation method: apt install

**Describe the bug**
First of all, it might be that I have misunderstood something fundamentally and this is a user error from my end, but I have not found any documentation that explains the behaviour we experience, so it appears to me as a bug.

We have a solution where we have hundreds of nodes (not postgresql) collecting data. These nodes have extremely limited bandwidth and often unstable internet connection, so they forward the data (aggregated to minute resolution) to a master server (postgresql/timescaledb) every two hours/when they get connection. So the hypertable table is backfilled regulary, especially in the range now - 2 hours. 

The problem is that if I set a refresh lag to lower than 2 hours the graphs are looking weird (using grafana as frontend) meaning that the continuous aggregation view(s) are missing a lot of data (in a cyclic pattern). If I drop and recreate the cagg, the graph is looking as expected and all data is calculated. I have done a lot of testing over time in this regard and the results are always the same. If I set refresh lag to > 2 hours the graphs are looking as expected, so I _can_ use that as a "solution", but I'm afraid then we are still missing data (from the nodes that are offline and backwrite more than 2 hours when they get online), just not that easy to spot.

Below is screenshots of three different graphs which is rendered using three different caggs. All created using _WITH (timescaledb.continuous, timescaledb.refresh_lag = '1 hour', timescaledb.max_interval_per_job='2 days', timescaledb.refresh_interval='10 minutes', timescaledb.materialized_only=false) AS_. The difference between the top screenshots and the bottom screenshots (of each graph) is solely that they are rendered before and after drop and recreate of each cagg. All query parameters are the same. (ignore the spikes, that is because some older nodes log data with hour resolution)

![image](https://user-images.githubusercontent.com/11269880/91689112-be95cf00-eb63-11ea-9c26-c428a312b21b.png)
![image](https://user-images.githubusercontent.com/11269880/91689198-e38a4200-eb63-11ea-952d-2b310bac4d22.png)
  
  
![image](https://user-images.githubusercontent.com/11269880/91689731-fea98180-eb64-11ea-87aa-b6e7a2440da4.png)
![image](https://user-images.githubusercontent.com/11269880/91689749-0701bc80-eb65-11ea-8888-e24fd2b101ca.png)
  
  
![image](https://user-images.githubusercontent.com/11269880/91689781-141eab80-eb65-11ea-9047-accd6bd85877.png)
![image](https://user-images.githubusercontent.com/11269880/91689814-21d43100-eb65-11ea-9a2e-89d63d351621.png)

**Comment by erimatnor** [comment] 2020-08-31 09:11
Hi @slasktrat, I think this is what is happening: If you set `refresh_lag` to less than two hours, you will materialize a time interval that has not yet received all data. That not-yet-filled interval will remain that way until the materializer runs again and recomputes it to fill in missing data. What's your `refresh_interval` set to for the continuous aggregate? Did you try to wait until the next refresh interval to see if the missing data is filled in?

The reason why you are seeing the correct data with a `refresh_lag` greater than two hours is because that time period will then be a "real-time" query (i.e., the data is queried directly from the underlying hypertable), so it is always up-to-date to the instant.

I think the important question we'd like answered here is whether the "missing data" will eventually be materialized. If that doesn't happen, there might be a bug.

**Comment by slasktrat** [comment] 2020-08-31 11:54
Hi @erimatnor, thanks for your reply.

I understand that if refresh_lag is set to e.g. 1 hour un-materialized data older than 1 hour would not be retreived in the query until after the next refresh. But as mentioned all these caggs have refresh_lag = '1 hour' and refresh_interval='10 minutes' and as you can see in the graphs they display 12 hours of data. 

So the whole problem is that the "missing data" seems never to be materialized. I would expect the materialized view to be updated after 10 minutes, and therefore each screenshot pair to be equal up to now - 10 minutes, but they are not. :-/

**Comment by slasktrat** [comment] 2020-09-02 08:18
Is this a bug we can expect to be fixed in the not too distant future, or should we find an alternative to continuous aggregations? Or maybe you have a tip on some workaround we can try?

**Comment by erimatnor** [comment] 2020-09-07 12:04
@slasktrat The documentation says that a continuous aggregate lags behind `bucket_width + refresh_lag`: https://docs.timescale.com/latest/api#continuous_aggregate-create_view-with-optional

Could this extra bucket explain the behavior? Otherwise, it does seem to be a bug in the materialization process.

On a related note, the whole continuous aggregate feature will see a major overhaul in the upcoming 2.0 release. This might fix some of your problems as the materialization process will be simplified. You can also manually refresh given regions. If you are willing, and interested, you could try the new functionality to see if it solves your problem. We'd appreciate your feedback on the changes we're making.

**Comment by slasktrat** [comment] 2020-09-07 13:45
Thanks for the notice, but I would anyway expect the calculation to correct itself when time exceeds bucket_width + refresh_lag. Agreed? My problem is that the missing data never "recovers", even after several days with both bucket_width and refresh_lag set to 1 hour.

I've also tried running REFRESH MATERIALIZED VIEW .. manually, but no difference.

But as mentioned dropping + recreating the continuous aggregation "fixes" the calculation and gives the expected result (up till current time, new data after recreate will still suffer the same behaviour).

How stable is the 2.0 release? Right now we don't have a test environment with timescaledb, only prod. And is there any breaking changes that would make the grafana integration stop working?

**Comment by erimatnor** [comment] 2020-09-07 17:35
@slasktrat we don't want you to run pre-releases on prod, and 2.0 will be a pretty big change. So, if you don't have a test environment you should probably wait. In the meantime, do you have steps to reproduce the behavior you are seeing so that we can examine the behavior more closely?

Btw, if you are interested in pre-releases or betas, it might be useful to join our support Slack (if you haven't already). I can ping you there about upcoming 2.0 testing.

**Comment by erimatnor** [comment] 2020-10-07 14:57
@slasktrat We have a couple of ideas of what could be wrong here. Do you have backfill (even if just a single point) that regularly happens further back than `max_interval_per_job` (i.e., further back than 2 days)?

One thing you can test is to set a large value for `max_interval_per_job` so that everything is materialized in one run of the background job (this might mean it takes a longer time, tough, depending on how far back the backfill goes).

**Comment by gayyappan** [comment] 2020-10-07 15:07
@slasktrat  You do say that you get backfill data for the "2 hour range". This generates "invalidations" : i.e. the range in the cagg is not up to date with the underlying data. For this use case, I would set refresh_lag = 2 hours or more and enable real time aggregation.In general you want to materialize up to a point which is not constantly modified (by setting refresh_lag) and use real time aggregation to get the data for the remaining part (materialized_only = false).

Note that any backfill (say from 2 days ago) invalidates data in the continuous aggregate. It is no longer in sync with the hypertable. This would mean a refresh job has to run before data is back in sync. The continuous_aggregate_stats table would show what was the last updated data point and when did the last refresh job run.

**Comment by mfreed** [comment] 2020-10-18 14:42
On a related note, @slasktrat , the 2.0 release candidates are available in both source & binary packaged form, and support ugprades from 1.x.  So if you have a backup/copy of the database that you are willing to upgrade to 2.0 and try with that, it would be great.  As @erimatnor mentioned, we significantly revamped how continuous aggregates are supported/refreshed in 2.0.

**Comment by slasktrat** [comment] 2020-10-19 05:08
Thanks a lot for following this up, @erimatnor, @gayyappan and @mfreed. Sorry for my late reply, but I've been overloaded on other projects lately. I will try and do some more testing in this matter as soon as possible.

@erimatnor, it depends a bit how you define "regularly". In these charts the max_interval_per_job was set to  '2 days'. We regulary (as in all the time) backfill the last 3 hours, but backfilling more than 3 hours back will only happen if a node has been offline. That is not rare, and probably happens several times a day, but in random interval. I need to double-check, but when you mention it I think actually setting a large value for max_interval_per_job did seem to give better results.

@gayyappan, the reason why we ideally wanted to use a smaller value for refresh_lag and refresh_interval is because performance is more important in our scenario than 100% "data integrity" for the latest hour(s).

**Comment by slasktrat** [comment] 2020-10-26 10:30
Ok, so I created two identical cags. The only difference is timescaledb.refresh_lag, both have timescaledb.max_interval_per_job='2 days', timescaledb.refresh_interval='10 minutes', timescaledb.materialized_only=false. 
![image](https://user-images.githubusercontent.com/11269880/97158896-5a197980-177a-11eb-8b26-54720822a8df.png)

I tried to adjust max_interval_per_job to '30 days' on the cag with 60 minutes refresh_lag, but no difference :-/

Haven't been able to test with 2.0 yet, unfortunately

**Comment by slasktrat** [comment] 2020-10-28 12:23
Update: Actually, I checked the charts now and they are now ~identical. So it seems adjusting max_interval_per_job to '30 days' actually did resolve the issue any how, it just took longer time than I had expected before I could see the effect.

**Comment by k-rus** [comment] 2020-10-29 07:46
Great that it works now!
BTW do you have a drop chunk policy or do you run `drop_chunks`?

**Comment by slasktrat** [comment] 2020-10-29 08:24
I do not have a drop chunk policy, but the cag view is created with WHERE time > now() - INTERVAL '2 days' on the select.

**Comment by erimatnor** [comment] 2020-12-30 12:15
Closing since a workaround was found for 1.7. Please open a new issue if this problem reoccurs in 2.0.

**Closed by erimatnor** 2020-12-30 12:15 UTC
Labels: bug, continuous-aggs, severity-p2
