### ISSUE TITLE
Version detection is broken when there is just major.minor

### ISSUE THREAD

**Issue by devereaux** [timescale/timescaledb#424] opened 2018-02-12 01:26 UTC
bootstrap can't work with a version like:
PostgreSQL 10.2 (Debian 10.2-1.pgdg90+1)

To fix that, the CMakeLists.txt regex should read instead:

 95 if (NOT ${PG_VERSION_STRING} MATCHES "^PostgreSQL[ ]+([0-9]+)\\.([0-9]+) (\(.*\))$")     
 96   message(FATAL_ERROR "Could not parse PostgreSQL version ${PG_VERSION}")
 97 endif ()

**Comment by RobAtticus** [comment] 2018-02-12 02:50
Someone contributed a PR to fix this / issues like it:
https://github.com/timescale/timescaledb/pull/423

The issue is actually the part after the minor version, the `(Debian...` portion that is breaking the regex.

**Comment by mfreed** [comment] 2018-02-15 21:57
A fix for this has been merged in PR #https://github.com/timescale/timescaledb/pull/428.  This will be in v0.9.0, which will be released shortly.

**Comment by mfreed** [comment] 2018-03-06 21:48
@devereaux 0.9.0 was released yesterday, which should fix this.  Please let me know if you continue to see this issue, or please otherwise close the issue?  Thanks!

https://github.com/timescale/timescaledb/releases/tag/0.9.0

**Closed** 2018-03-14 20:48 UTC
Labels: bug
