### ISSUE TITLE
Make on EnterpriseDB 11.2.9 failed

### ISSUE THREAD

**Issue by zhuodao** [timescale/timescaledb#1276] opened 2019-06-06 04:22 UTC
**Relevant system information:**
 - OS: centos 7.2
 - PostgreSQL version (output of `postgres --version`): EnterpriseDB 11.2.9
 - TimescaleDB version (output of `\dx` in `psql`): 1.3.0
 - Installation method: source

**Describe the bug**
I have a EnterpriseDB 11.2.9 binary and I want to make install timescaledb for a extension. But it returns error like this:
error: too few arguments to function 'index_create'

**To Reproduce**
1. Download the source code and unzip it.
2. export PG_CONFIG
3. run ./bootstrap -DAPACHE_ONLY=1
4. See error:
CMake Error at CMakeLists.txt:155 (message):
  Could not parse PostgreSQL version EnterpriseDB 11.2.9
5. update the CMakeLists.txt:155 
if (NOT ${PG_VERSION_STRING} MATCHES "^EnterpriseDB[ ]+([0-9]+)\\.([0-9]+)(\\.([0-9]+))*")
6. run ./bootstrap -DAPACHE_ONLY=1 again
7. See error:
 error: too few arguments to function 'index_create'

Is the timescaledb not compatible with EnterpriseDB 11.2.9 ？ Is there a plan to compatible with EnterpriseDB 11.2.9 ? If not, what can I do with my EnterpriseDB 11.2.9.

**Comment by mfreed** [comment] 2019-06-06 04:56
Hi @21090310 we don't internally build/test against EnterpriseDB, nor do we have any immediate plans on our roadmap.  

We certainly do support Postgres 11.2, so this perhaps is due to differences between EDB 11.2.9 and Postgres 11.2: https://postgresrocks.enterprisedb.com/t5/EDB-Technical-Updates-and-Alerts/Technical-Update-EDB-Postgres-Advanced-Server-Database-Server-11/ta-p/3083

Would certainly welcome PRs / help from the community for patches to support EDB versions!

**Comment by k-rus** [comment] 2020-07-16 09:00
@zhuodao EnterpriseDB installation of PostgreSQL were missing some packages, which was resolved in later version of EDB. Also some issues related to Windows installation of TimescaleDB were resolved in later versions. Can you test if you can install newer version of TimescaleDB on newer version of EBD PG?

**Comment by svenklemm** [comment] 2020-10-13 08:54
Closing this since it should be resolved. Feel free to reopen if the issue is still relevant.

**Closed by svenklemm** 2020-10-13 08:54 UTC
Labels: Windows, build
