### ISSUE TITLE
Multiple decompressing the same chunk at the same time leads to deadlock

### ISSUE THREAD

**Issue by WalkerWalker** [timescale/timescaledb#5069] opened 2022-12-09 13:41 UTC
### What type of bug is this?

Locking issue

### What subsystems and features are affected?

Compression

### What happened?

I found a similar issue https://github.com/timescale/timescaledb/issues/4605 but they are not exactly the same.  When multiple decompressing command of the same chunk are running across several sessions/connections,  deadlock was detected with the error message 

```
ERROR:  deadlock detected
DETAIL:  Process 3067 waits for AccessExclusiveLock on relation 8974318 of database 16384; blocked by process 3750.
Process 3750 waits for ExclusiveLock on relation 8974314 of database 16384; blocked by process 3067.
HINT:  See server log for query details.
SQL state: 40P01
``` 

The reproduce code larged adopted from the issue https://github.com/timescale/timescaledb/issues/4605 with minor modifications in the end,  changing from decompressing and query to two decompressing.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

12

### What operating system did you use?

Debian 11

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
drop table sensor_data cascade;

create table sensor_data(
time timestamptz not null,
person_id integer not null,
sensor_id integer not null,
cpu double precision null,
temperature double precision null,
PRIMARY KEY (time, person_id, sensor_id)); 

select from create_hypertable('sensor_data','time');

-- this should create four chunks 
INSERT INTO sensor_data
SELECT
time + (INTERVAL '1 minute' * random()) AS time,
person_id,
sensor_id,
random() AS cpu,
random()* 100 AS temperature
FROM
generate_series(now() - INTERVAL '1 months', now() - INTERVAL '1 week', INTERVAL '10 minute') AS g1(time),
generate_series(1, 10, 1 ) AS g2(person_id),
generate_series(1, 10, 1 ) AS g3(sensor_id)
ORDER BY
time;

-- make a particular chunk heavy, run the below query 5-6 times
INSERT INTO sensor_data
SELECT
time + (INTERVAL '1 minute' * random()) AS time,
person_id,
sensor_id,
random() AS cpu,
random()* 100 AS temperature
FROM
generate_series('2022-07-14 00:00:00+00', '2022-07-21 00:00:00+00', INTERVAL '1 minute') AS g1(time),
generate_series(1, 10, 1 ) AS g2(person_id),
generate_series(1, 10, 1 ) AS g3(sensor_id)
ORDER BY
time
on conflict do nothing;

--view chunk's status, all chunks are decompressed
SELECT c.chunk_name,c.range_start,c.range_end,c.is_compressed,pg_size_pretty(d.total_bytes) FROM public.chunks_detailed_size('public.sensor_data') d, timescaledb_information.chunks c WHERE d.chunk_name=c.chunk_name order by c.range_start;


--enabling compression and compressing all the chunks
alter table sensor_data set 
(timescaledb.compress, 
 timescaledb.compress_segmentby = 'person_id, sensor_id',
 timescaledb.compress_orderby = 'time DESC');

select add_compression_policy('sensor_data','8 days'::INTERVAL);

--view chunk's status, all chunks are now compressed except the last chunk
SELECT c.chunk_name,c.range_start,c.range_end,c.is_compressed,pg_size_pretty(d.total_bytes) FROM public.chunks_detailed_size('public.sensor_data') d, timescaledb_information.chunks c WHERE d.chunk_name=c.chunk_name order by c.range_start;


```
Now creating multiple connections/sessions using psql and pgadmin:

Session 1
```
SELECT tableoid::regclass FROM sensor_data
  WHERE time < '2022-07-20' AND time > '2022-07-15'
  GROUP BY tableoid;

select decompress_chunk('_timescaledb_internal._hyper_23_354_chunk', True);
```

Session 2 exactly the same
```
SELECT tableoid::regclass FROM sensor_data
  WHERE time < '2022-07-20' AND time > '2022-07-15'
  GROUP BY tableoid;

select decompress_chunk('_timescaledb_internal._hyper_23_354_chunk', True);
```

The deadlock will be triggered

```
timescaledb_1           | 2022-12-12 22:21:50.921 CET [3706] ERROR:  deadlock detected
timescaledb_1           | 2022-12-12 22:21:50.921 CET [3706] DETAIL:  Process 3706 waits for AccessExclusiveLock on relation 8974318 of database 16384; blocked by process 3067.
timescaledb_1           | 	Process 3067 waits for ExclusiveLock on relation 8974314 of database 16384; blocked by process 3706.
timescaledb_1           | 	Process 3706: SELECT tableoid::regclass FROM sensor_data
timescaledb_1           | 	  WHERE time < '2022-07-20' AND time > '2022-07-15'
timescaledb_1           | 	  GROUP BY tableoid;
timescaledb_1           | 	
timescaledb_1           | 	select decompress_chunk('_timescaledb_internal._hyper_23_354_chunk', True);
timescaledb_1           | 	Process 3067: SELECT tableoid::regclass FROM sensor_data
timescaledb_1           | 	  WHERE time < '2022-07-20' AND time > '2022-07-15'
timescaledb_1           | 	  GROUP BY tableoid;
timescaledb_1           | 	
timescaledb_1           | 	select decompress_chunk('_timescaledb_internal._hyper_23_354_chunk', True);
```

Context

```
SELECT * FROM pg_class where oid = 8974314 or oid = 8974318;
```

returns

oid | relname | relnamespace | reltype | reloftype | relowner | relam | relfilenode | reltablespace | relpages | reltuples | relallvisible | reltoastrelid | relhasindex | relisshared | relpersistence | relkind | relnatts | relchecks | relhasrules | relhastriggers | relhassubclass | relrowsecurity | relforcerowsecurity | relispopulated | relreplident | relispartition | relrewrite | relfrozenxid | relminmxid | relacl | reloptions | relpartbound
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
8974318 | 354_151_sensor_data_pkey | 17544 | 0 | 0 | 10 | 403 | 10331856 | 0 | 31008 | 8.06E+06 | 0 | 0 | FALSE | FALSE | p | i | 3 | 0 | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | n | FALSE | 0 | 0 | 0 |   |   |  
8974314 | _hyper_23_354_chunk | 17544 | 8974316 | 0 | 10 | 2 | 10331846 | 0 | 177883 | 8.06E+06 | 177883 | 0 | TRUE | FALSE | p | r | 5 | 1 | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | d | FALSE | 0 | 36474466 | 15055049 |   | {autovacuum_enabled=true} |

**Comment by jnidzwetzki** [comment] 2022-12-09 15:02
Hello @WalkerWalker,

Thanks for reaching out. I am trying to reproduce the problem you reported. You mentioned that the problem occurs when you decompress chunks. In the example given, you call `compress_chunk`, which compresses a chunk. Does the problem also occur when you are decompressing the chunks?

The error message refers to a relation with the ID 8387502. I am interested in the name of this relation. Could you execute the following statement and send us the results for further investigation?

```sql
SELECT * FROM pg_class where oid = 8387502;
```

**Comment by WalkerWalker** [comment] 2022-12-10 19:29
sorry.  I typed in `compress_chunk` but it was actually `decompress_chunk`. I will update the reproduce code. 

Relation with ID 8387502 is `_hyper_14_256_chunk` The result of the following query is

```
SELECT * FROM pg_class where oid = 8387502;
```
8387502 | _hyper_14_256_chunk | 17544 | 8387504 | 0 | 10 | 2 | 8542540 | 0 | 44471 | 6.05E+06 | 0 | 0 | TRUE | FALSE | p | r | 4 | 1 | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | d | FALSE | 0 | 35158420 | 14280574 |   | {autovacuum_enabled=false}
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by WalkerWalker** [comment] 2022-12-10 20:30
Another error log from timescaledb I encounter when running two decompression is the following
```
timescaledb_1           | 2022-12-10 21:23:50.481 CET [16925] ERROR:  deadlock detected
timescaledb_1           | 2022-12-10 21:23:50.481 CET [16925] DETAIL:  Process 16925 waits for AccessExclusiveLock on relation 8252957 of database 16384; blocked by process 17648.
timescaledb_1           | 	Process 17648 waits for ExclusiveLock on relation 8252950 of database 16384; blocked by process 16925.
timescaledb_1           | 	Process 16925: 
timescaledb_1           | 	            SELECT decompress_chunk('_timescaledb_internal._hyper_11_197_chunk', True);
timescaledb_1           | 	            
timescaledb_1           | 	Process 17648: 
timescaledb_1           | 	            SELECT decompress_chunk('_timescaledb_internal._hyper_11_197_chunk', True);
timescaledb_1           | 	            
timescaledb_1           | 2022-12-10 21:23:50.481 CET [16925] HINT:  See server log for query details.
timescaledb_1           | 2022-12-10 21:23:50.481 CET [16925] STATEMENT:  
timescaledb_1           | 	            SELECT decompress_chunk('_timescaledb_internal._hyper_11_197_chunk', True);
```

and the relation information when running `SELECT * FROM pg_class where oid = 8252957;`

8252957 | 197_106_data_store_mmt_ppg_pkey | 17544 | 0 | 0 | 10 | 403 | 8616020 | 0 | 37778 | 2.43E+06 | 0 | 0 | FALSE | FALSE | p | i | 5 | 0 | FALSE | FALSE | FALSE | FALSE | FALSE | TRUE | n | FALSE | 0 | 0 | 0 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by WalkerWalker** [comment] 2022-12-10 20:35
running the following gives me both 2.8.1
```
SELECT default_version, installed_version FROM pg_available_extensions
where name = 'timescaledb';
```

**Comment by jnidzwetzki** [comment] 2022-12-12 09:22
Hello @WalkerWalker,

Thank you for getting back to us. I tried to reproduce the issue in my local environment with the steps mentioned above. Unfortunately, I was not able to reproduce the behavior so far. When I run the decompression of the same chunk in two different sessions, no deadlock occurs:

```sql
--- Session 1
issue5069=# select decompress_chunk('_timescaledb_internal._hyper_3_11_chunk', True);

            decompress_chunk             
-----------------------------------------
 _timescaledb_internal._hyper_3_11_chunk
(1 row)


--- Session 2
issue5069=# select decompress_chunk('_timescaledb_internal._hyper_3_11_chunk', True);
--- Blocks until the decompression is done, then:
ERROR:  chunk "_hyper_3_11_chunk" is already decompressed
```

The second error message you received refers to the key `197_106_data_store_mmt_ppg_pkey`. However, this key is not created in the steps above. Can you reproduce the behavior in a new database using only the above steps, or is there something else that needs to be done?

**Comment by WalkerWalker** [comment] 2022-12-12 21:59
Sorry I also just noticed that only doing the `decompress_chunk` in mutiple sessions will not create a deadlock.  I accidentally put `query chunks with criteria` and the `decompress those chunk` in the same session and multiple of these sessions lead me to the deadlock. The error message didn't reflect that and I didn't notice that the session contains more than just the decompression.

Now I have reproduce the deadlock and updated the steps above.  Sorry for the incorrect steps before.  It will be nice if you can confirm that you can reproduce it. Yet I am not so sure anymore whether it's a bug.  I guess the behaviour is ok. I will leave to you to decide whether it's a bug or not.

**Comment by jnidzwetzki** [comment] 2022-12-13 08:14
Hello @WalkerWalker,

Thanks for the updated steps to reproduce the issue. If you open two transactions, read tuples from chunk A in both transactions, and execute `decompress_chunk(A)` in both transactions, there is a high probability that a deadlock will occur. 

The `SELECT` requests a lock (`AccessShareLock`) on the read chunks. The `decompress_chunk` operation attempts to delete the compressed version of the chunk when decompression is complete. This operation has to wait because of the `AccessShareLock` of the other transaction on this chunk. If both transactions try to execute a `decompress_chunk` on the same chunk, a deadlock will occur.

I recommend to run `compress_chunk` / `decompress_chunk` always in a fresh transaction. Then these operations should be performed without risking a deadlock.

**Comment by WalkerWalker** [comment] 2022-12-13 08:37
yup.  I did exactly what you suggested.  Using a fresh session for `decompress_chunk` and there is no deadlock anymore. Thanks for the help!

Btw, using `show_chunks` to get the chunks and then decompress is actually totally fine.  Running multiple sessions of the following query do not lead to decompression. 
```
SELECT decompress_chunk(i)
    FROM show_chunks('sensor_data', older_than => DATE '2022-07-21', newer_than => DATE '2022-07-14') i;
```

Reason why I didn't use `show_chunks` is because [it only returns full chunks within the time range](https://github.com/timescale/timescaledb/issues/5081).  `SELECT tableoid::regclass FROM sensor_data group by tableiod` serves me the purpose of finding all related chunks to be decompressed.

**Comment by jnidzwetzki** [comment] 2022-12-13 13:47
Hello @WalkerWalker,

Thank you for confirming that using a new transaction for compression/decompression helps to solve the deadlocks you experienced. And thank you for opening the feature suggestion.

Do you need any additional help with this issue or can we close it?

**Comment by WalkerWalker** [comment] 2022-12-13 14:16
For me, it can be closed :)
Thank you!

**Closed** 2022-12-13 15:37 UTC
Labels: bug, compression, locking
