### ISSUE TITLE
Problem to use function with "ON CONFLICT" clause on multinode

### ISSUE THREAD

**Issue by gomex** [timescale/timescaledb#1813] opened 2020-04-13 14:46 UTC
**Relevant system information:**
 - OS: **Ubuntu 18.04**
 - PostgreSQL version (output of `postgres --version`): **11.5**
 - TimescaleDB version (output of `\dx` in `psql`): **2.0.0-beta4**
 - Installation method:  **using Docker**

**Describe the bug**
I created this timescaledb cluster:

```
database=# SELECT * FROM timescaledb_information.data_node;
 node_name | owner |                          options                          | node_up | num_dist_tables | num_dist_chunks | total_dist_size
-----------+-------+-----------------------------------------------------------+---------+-----------------+-----------------+-----------------
 node2 |    10 | {host=node2.company.com,port=35000,dbname=database} | t       |               6 |               1 | 29 MB
 node1 |    10 | {host=node1.company.com,port=35000,dbname=database} | t       |               6 |               3 | 26 MB
(2 rows)
```

I created the tables and hypertables:

```
database=# SELECT * FROM timescaledb_information.hypertable;
 table_schema |               table_name               | table_owner | num_dimensions | num_chunks | table_size | index_size | toast_size | total_size | distributed
--------------+----------------------------------------+-------------+----------------+------------+------------+------------+------------+------------+-------------
 public       | table1                            | postgres    |              1 |          1 | 8192 bytes | 16 kB      |            | 24 kB      | t
 public       | table2                               | postgres    |              1 |          1 | 14 MB      | 12 MB      | 8192 bytes | 25 MB      | t
 public       | table3       | postgres    |              1 |          0 |            |            |            |            | t
(3 rows)
``` 

I created this function:

```
CREATE OR REPLACE FUNCTION testing_function_on_multi_node() RETURNS VOID AS $$
BEGIN
WITH raw AS (
    SELECT time_bucket('1 minute', time) AS time, server_address, COUNT(1) AS total FROM table2 AS dns WHERE dns.id > (SELECT last_id FROM table1 WHERE name = 'table3') GROUP BY
 time, server_address
)
INSERT INTO table3 (time,server_address,total) 
SELECT time, server_address, total FROM raw
ON CONFLICT (
    time, server_address
  ) DO UPDATE SET
    total = table3.total + EXCLUDED.total
;
END; $$
LANGUAGE PLPGSQL;
```

I tried to run it and I got this error:

```
database=# select testing_function_on_multi_node();
ERROR:  unexpected ON CONFLICT specification: 2
CONTEXT:  SQL statement "WITH raw AS (
    SELECT time_bucket('1 minute', time) AS time, server_address, COUNT(1) AS total FROM table2 AS dns WHERE dns.id > (SELECT last_id FROM table1 WHERE name = 'table3') GROUP BY
 time, server_address
)
INSERT INTO table3 (time,server_address,total) 
SELECT time, server_address, total FROM raw
ON CONFLICT (
    time, server_address
  ) DO UPDATE SET
    total = table3.total + EXCLUDED.total"
PL/pgSQL function testing_function_on_multi_node() line 3 at SQL statement
```

**To Reproduce**
1. Create a function with "ON CONFLICT" clause on access node of multinode timescaledb
2. Execute the function
3. See error

**Expected behavior**
Insert the data into table3

**Actual behavior**
unexpected ON CONFLICT specification: 2

**Comment by gomex** [comment] 2020-04-13 14:49
Function without ON CONFLICT clause works fine.

**Comment by gomex** [comment] 2020-06-12 02:27
hi, is there anything that I can do to help with this issue?

**Comment by aljazerzen** [comment] 2021-01-27 15:26
I have a smaller reproduction example:
```
CREATE TABLE my_table (
    id              BIGINT            NOT NULL,
    time            TIMESTAMP         NOT NULL,
    value           DOUBLE PRECISION  NULL,
    UNIQUE (time, id)
);
SELECT create_distributed_hypertable('my_table', 'time');
```

When trying to insert or overwriting a data point:
```
INSERT INTO my_table 
VALUES (15, '2021-01-26 17:43:29.518009'::timestamp,16.6) 
ON CONFLICT (time, id) DO UPDATE SET value = 16.6;
> [XX000] ERROR: unexpected ON CONFLICT specification: 2
```

If I use `DO NOTHING`:
```
INSERT INTO my_table 
VALUES (15, '2021-01-26 17:43:29.518009'::timestamp,16.6) 
ON CONFLICT (time, id) DO NOTHING;
> [XX000] ERROR: could not find arbiter index for hypertable index "my_table_time_id_key" on chunk "_dist_hyper_5_4_chunk"
```

If I add space partition 'id', the error persists. As @gomex mentioned, this query works with non-distributed hyper tables. 

If anyone can give me a pointer where to start looking for the error, I'd be happy to help.

**Comment by ezean21** [comment] 2021-02-22 18:36
Hi, is there any workaround? Thanks :)

**Comment by aljazerzen** [comment] 2021-02-22 18:39
In my case, statement without referencing the index
```
INSERT INTO my_table VALUES (...) ON CONFLICT DO NOTHING;
```
does work.

**Comment by ezean21** [comment] 2021-02-22 18:56
yes, but the raw will not be updated lol

**Comment by aljazerzen** [comment] 2021-02-22 19:10
Raw? You mean existing row?

Well, you could always make a delete and then insert. But that would have to be in a transaction to be entirely equivalent.

**Comment by nikkhils** [comment] 2021-02-25 11:26
@ezean21 @aljazerzen 

As part of #2886 I have pushed proper error messages. "ON CONFLICT DO UPDATE" functionality is an enhancement in multinode environments and will be added in the coming days.

**Comment by nikkhils** [comment] 2021-10-04 13:12
Closing this one since #2963 is tracking this enhancement.

**Closed by nikkhils** 2021-10-04 13:12 UTC
Labels: bug, multinode, 2.0-proposed
