### ISSUE TITLE
[Bug]: VACUUM FULL on a hypertable blocking public.chunks_detailed_size function on a different hypertable

### ISSUE THREAD

**Issue by mwarejohn** [timescale/timescaledb#5073] opened 2022-12-10 07:03 UTC
### What type of bug is this?

Locking issue

### What subsystems and features are affected?

Command processing, Query executor

### What happened?

`VACUUM FULL` executed against a hypertable or chunks in that hypertable (e.g hypertable_xxx) blocks `chunks_detailed_size()` function executed against a different hypertable (e.g hypertable_yyy).
The expectation is that `VACUUM FULL` operation should not block function `chunks_detailed_size()`.

In the sample scripts below, session 2 is blocked by session 1.

**Script1 - psql session1**

```sql
VACUUM FULL hypertable_xxx;

```

**Script2 - psql session2**
```sql
SELECT * FROM public.chunks_detailed_size('hypertable_yyy') limit 10;
```

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

12.12

### What operating system did you use?

x86_64-pc-linux-gnu, compiled by gcc, a 9b6f1cff78 p ce8d8b4729, 64-bit

### What installation method did you use?

Other, Not applicable

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### Relevant log output and stack trace

```bash
The issue is reproducible following the steps highlighted below.
```

### How can we reproduce the bug?

```bash
Prepare two hypertables to use in this test.

**Hypertable 1:** To be used with `chunks_detailed_size()` function . It will take you approximately 10 seconds to generate test data.


create table table_test1 (id bigint not null, time timestamptz not null, cpu double precision);

select create_hypertable('table_test1','time',create_default_indexes => False, chunk_time_interval => INTERVAL '1 day');

insert into table_test1 
    (select  round(random() * 2 + 1), 
    generate_series('2022-10-01','2022-10-03',INTERVAL '20 millisecond'),
    round(random()*10));


**Hypertable 2:** To `VACUUM FULL` the entire hypertable or one chunk of this hypertable. It will take you approximately 5 minutes to generate test data.

```sql
create table table_test2 (id bigint not null, time timestamptz not null, cpu double precision);

select create_hypertable('table_test2','time',create_default_indexes => False, chunk_time_interval => INTERVAL '1 day');

insert into table_test2 
    (select  round(random() * 2 + 1), 
    generate_series('2022-10-01','2022-10-03',INTERVAL '1 millisecond'),
    round(random()*10));

```
If you intend to vacuum a single chunk, list the chunks in `table_test2` and pick one chunk to vacuum. Use one of the two chunks with approx 4GB in size. Else proceed to `VACUUM FULL table_test2`

```sql
SELECT
c.chunk_name,
c.range_start,
c.range_end,
c.is_compressed,
pg_size_pretty(d.total_bytes)
FROM public.chunks_detailed_size('table_test2') d, timescaledb_information.chunks c
WHERE c.chunk_name=d.chunk_name;

```
Open three psql sessions and prepare the following statements to execute in parallel.

**psql session 1:** vacuum full one chunk from `table_test2` or the entire hypertable as follows.

```sql
vacuum full _timescaledb_internal._hyper_xx_xxx_chunk;
or
vacuum full table_test2;
```

**psql session 2:** Use `table_test1` to check detailed chunk size as follows.

```sql
SELECT * FROM public.chunks_detailed_size('table_test1') limit 10;
```

**psql session 3:** Check for blocking sessions as follows.
```sql
SELECT blocked_locks.pid     AS blocked_pid,
         blocked_activity.usename  AS blocked_user,
         blocking_locks.pid     AS blocking_pid,
         blocking_activity.usename AS blocking_user,
         blocked_activity.query    AS blocked_statement,
         blocking_activity.query   AS current_statement_in_blocking_process,
         blocked_activity.application_name AS blocked_application,
         blocking_activity.application_name AS blocking_application
   FROM  pg_catalog.pg_locks         blocked_locks
    JOIN pg_catalog.pg_stat_activity blocked_activity  ON blocked_activity.pid = blocked_locks.pid
    JOIN pg_catalog.pg_locks         blocking_locks
        ON blocking_locks.locktype = blocked_locks.locktype
        AND blocking_locks.DATABASE IS NOT DISTINCT FROM blocked_locks.DATABASE
        AND blocking_locks.relation IS NOT DISTINCT FROM blocked_locks.relation
        AND blocking_locks.page IS NOT DISTINCT FROM blocked_locks.page
        AND blocking_locks.tuple IS NOT DISTINCT FROM blocked_locks.tuple
        AND blocking_locks.virtualxid IS NOT DISTINCT FROM blocked_locks.virtualxid
        AND blocking_locks.transactionid IS NOT DISTINCT FROM blocked_locks.transactionid
        AND blocking_locks.classid IS NOT DISTINCT FROM blocked_locks.classid
        AND blocking_locks.objid IS NOT DISTINCT FROM blocked_locks.objid
        AND blocking_locks.objsubid IS NOT DISTINCT FROM blocked_locks.objsubid
        AND blocking_locks.pid != blocked_locks.pid

    JOIN pg_catalog.pg_stat_activity blocking_activity ON blocking_activity.pid = blocking_locks.pid
   WHERE NOT blocked_locks.GRANTED;
```
Execute the three scripts simultaneously.
The blocking session script shows that `VACUUM FULL` statement is blocking `public.chunks_detailed_size()` function.
```

**Comment by sb230132** [comment] 2022-12-12 04:14
Hi @mwarejohn 
Iam able to reproduce the problem. However this issue seems to be fixed in latest 2.9.0. Let me try to find which PR has fixed this issue.

**Comment by mwarejohn** [comment] 2022-12-13 14:28
Thank you @sb230132

**Comment by akuzm** [comment] 2023-01-25 11:07
Can confirm it's fixed, doesn't seem to reproduce in `main`.

**Closed by akuzm** 2023-01-25 11:07 UTC
Labels: bug, locking, MST, Timescale Cloud
