### ISSUE TITLE
Assertion failure in ts_bgw_job_find_with_lock in CI

### ISSUE THREAD

**Issue by svenklemm** [timescale/timescaledb#5030] opened 2022-11-26 12:08 UTC
Link to run: https://github.com/timescale/timescaledb/actions/runs/3551362759/jobs/5965472875

Stacktrace:
```
#0  0x00007fbb411cfa7c in pthread_kill () from /home/sven/share/libc.so.6
No symbol table info available.
#1  0x00007fbb4117b476 in raise () from /home/sven/share/libc.so.6
No symbol table info available.
#2  0x00007fbb411617f3 in abort () from /home/sven/share/libc.so.6
No symbol table info available.
#3  0x000055b46ff2c60b in ExceptionalCondition (conditionName=<optimized out>, errorType=<optimized out>, fileName=<optimized out>, lineNumber=<optimized out>) at assert.c:67
No locals.
#4  0x00007fbb3738bd14 in ts_bgw_job_find_with_lock (bgw_job_id=1008, mctx=0x55b470fc83d0, tuple_lock_mode=2, lock_type=TXN_LOCK, block=true, got_lock=0x7ffef295b23f) at /home/runner/work/timescaledb/timescaledb/src/bgw/job.c:636
        iterator = {ctx = {internal = {tinfo = {scanrel = 0x7fbb374e05d8, slot = 0x0, ituple = 0x0, ituple_desc = 0x7fbb374e44f8, lockresult = TM_Ok, lockfd = {ctid = {ip_blkid = {bi_hi = 0, bi_lo = 0}, ip_posid = 0}, xmax = 0,
                  cmax = 0, traversed = false}, count = 2, mctx = 0x55b470fc83d0}, scan = {index_scan = 0x55b470fc85b0, table_scan = 0x55b470fc85b0}, scan_mcxt = 0x0, registered_snapshot = true, started = false, ended = true},
            table = 53921, index = 54354, tablerel = 0x0, indexrel = 0x0, scankey = 0x7ffef295b088, flags = 0, nkeys = 1, norderbys = 0, limit = 0, want_itup = false, lockmode = 5, result_mctx = 0x55b470fc83d0, tuplock = 0x0,
            scandirection = ForwardScanDirection, snapshot = 0x0, data = 0x0, prescan = 0x0, postscan = 0x0, filter = 0x0, tuple_found = 0x0}, tinfo = 0x0, scankey = {{sk_flags = 0, sk_attno = 1, sk_strategy = 3, sk_subtype = 0,
              sk_collation = 950, sk_func = {fn_addr = 0x55b46fe621b0 <int4eq>, fn_oid = 65, fn_nargs = 2, fn_strict = true, fn_retset = false, fn_stats = 2 '\002', fn_extra = 0x0, fn_mcxt = 0x55b470fc83d0, fn_expr = 0x0},
              sk_argument = 1008}, {sk_flags = 0, sk_attno = 0, sk_strategy = 0, sk_subtype = 0, sk_collation = 0, sk_func = {fn_addr = 0x0, fn_oid = 0, fn_nargs = 0, fn_strict = false, fn_retset = false, fn_stats = 0 '\000',
                fn_extra = 0x0, fn_mcxt = 0x0, fn_expr = 0x0}, sk_argument = 0}, {sk_flags = 0, sk_attno = 0, sk_strategy = 0, sk_subtype = 0, sk_collation = 0, sk_func = {fn_addr = 0x0, fn_oid = 0, fn_nargs = 0, fn_strict = false,
                fn_retset = false, fn_stats = 0 '\000', fn_extra = 0x0, fn_mcxt = 0x0, fn_expr = 0x0}, sk_argument = 0}, {sk_flags = 0, sk_attno = 0, sk_strategy = 0, sk_subtype = 0, sk_collation = 0, sk_func = {fn_addr = 0x0,
                fn_oid = 0, fn_nargs = 0, fn_strict = false, fn_retset = false, fn_stats = 0 '\000', fn_extra = 0x0, fn_mcxt = 0x0, fn_expr = 0x0}, sk_argument = 0}, {sk_flags = 0, sk_attno = 0, sk_strategy = 0, sk_subtype = 0,
              sk_collation = 0, sk_func = {fn_addr = 0x0, fn_oid = 0, fn_nargs = 0, fn_strict = false, fn_retset = false, fn_stats = 0 '\000', fn_extra = 0x0, fn_mcxt = 0x0, fn_expr = 0x0}, sk_argument = 0}}}
        jobs = 0x55b470fc8c48
        job = 0x55b470fc8ca0
        tag = {locktag_field1 = 52277, locktag_field2 = 1008, locktag_field3 = 0, locktag_field4 = 29749, locktag_type = 10 '\n', locktag_lockmethodid = 2 '\002'}
        __func__ = "ts_bgw_job_find_with_lock"
#5  0x00007fbb3738bda6 in ts_bgw_job_get_share_lock (bgw_job_id=1008, mctx=0x55b470fc83d0) at /home/runner/work/timescaledb/timescaledb/src/bgw/job.c:653
        got_lock = true
        job = 0x7ffef295b280
        __func__ = "ts_bgw_job_get_share_lock"
#6  0x00007fbb37393031 in scheduled_bgw_job_transition_state_to (sjob=0x55b470f55098, new_state=JOB_STATE_STARTED) at /home/runner/work/timescaledb/timescaledb/src/bgw/scheduler.c:280
        prev_state = JOB_STATE_SCHEDULED
        job_stat = 0x55b46fee2402 <GetCurrentTimestamp+34>
        owner_uid = 32766
        __func__ = "scheduled_bgw_job_transition_state_to"
#7  0x00007fbb37393a0a in scheduled_ts_bgw_job_start (sjob=0x55b470f55098, bgw_register=0x0) at /home/runner/work/timescaledb/timescaledb/src/bgw/scheduler.c:398
        pid = -225070416
        status = 32766
        __func__ = "scheduled_ts_bgw_job_start"
#8  0x00007fbb37394622 in start_scheduled_jobs (bgw_register=0x0) at /home/runner/work/timescaledb/timescaledb/src/bgw/scheduler.c:588
        sjob = 0x55b470f55098
        lc__state = {l = 0x55b470f543f8, i = 4}
        ordered_scheduled_jobs = 0x55b470f543f8
        lc = 0x55b470f558e8
#9  0x00007fbb373952e9 in ts_bgw_scheduler_process (run_for_interval_ms=-1, bgw_register=0x0) at /home/runner/work/timescaledb/timescaledb/src/bgw/scheduler.c:780
        next_wakeup = 9223372036854775807
        start = 722736963476833
        quit_time = 9223372036854775807
        __func__ = "ts_bgw_scheduler_process"
(More stack frames follow...)
```

**Comment by akuzm** [comment] 2023-01-25 11:31
Still happening:
```
ci_stats=> select count(*), max(job_date) from log where log_contents like '%ts_bgw_job_find_with_lock%';
 count │              max              
───────┼───────────────────────────────
     5 │ 2023-01-23 10:40:45.560063+00
```

**Comment by akuzm** [comment] 2023-01-25 11:43
```
ci_stats=> select count(*), max(job_date), split_part(test.test_name, '-', 1) from log left join test using(job_date) where log_contents like '%ts_bgw_job_find_with_lock%' and test_status != 'ok' and test_status not like '%(ignored)%' group by 3 order by 1 desc;
 count │              max              │            split_part            
───────┼───────────────────────────────┼──────────────────────────────────
     5 │ 2023-01-23 10:40:45.560063+00 │ cagg_invalidation_dist_ht
     5 │ 2023-01-23 10:40:45.560063+00 │ bgw_custom
     3 │ 2023-01-13 15:56:18.275902+00 │ cagg_policy
     3 │ 2023-01-13 15:56:18.275902+00 │ cagg_policy_run
     3 │ 2023-01-13 15:56:18.275902+00 │ cagg_query
     3 │ 2023-01-13 15:56:18.275902+00 │ cagg_refresh
     3 │ 2023-01-13 15:56:18.275902+00 │ cagg_tableam
     3 │ 2023-01-13 15:56:18.275902+00 │ cagg_union_view
     3 │ 2023-01-13 15:56:18.275902+00 │ cagg_usage
     3 │ 2023-01-13 15:56:18.275902+00 │ cagg_watermark
     3 │ 2023-01-23 10:40:45.560063+00 │ cagg_migrate_dist_ht
     3 │ 2023-01-13 15:56:18.275902+00 │ cagg_permissions
     3 │ 2023-01-23 10:40:45.560063+00 │ cagg_migrate
     2 │ 2023-01-13 15:56:18.275902+00 │ cagg_on_cagg_dist_ht
     2 │ 2022-11-26 00:21:08.594705+00 │ cagg_migrate_integer_dist_ht
     2 │ 2022-11-26 00:21:08.594705+00 │ cagg_migrate_integer
     2 │ 2022-11-26 00:21:08.594705+00 │ cagg_migrate_timestamp
.........
```

**Comment by jnidzwetzki** [comment] 2023-06-17 04:43
Failed again in CI: https://github.com/timescale/timescaledb/actions/runs/5284753117/jobs/9562507683

**Comment by mkindahl** [comment] 2024-01-08 12:18
This is related to the observation [here](https://github.com/timescale/timescaledb/issues/4863#issuecomment-1305395425) that can occur because, for some reason, two jobs with the same ID can be added to the table.

**Comment by mkindahl** [comment] 2024-01-08 13:46
This seems to be a duplicate of #5381, so closing in favor of the previous one.

**Closed by mkindahl** 2024-01-08 13:46 UTC
Labels: bug
