### ISSUE TITLE
index of the segmentby column is not used

### ISSUE THREAD

**Issue by vitabaks** [timescale/timescaledb#2722] opened 2020-12-08 10:07 UTC
The problem is that the index of the segmentby column is not used. Instead, the entire chunk is decompressed.

PostgreSQL 11.10
timescaledb 1.7.4

compression options:
```
ALTER TABLE events SET (
  timescaledb.compress,
  timescaledb.compress_orderby = 'id DESC, "timestamp" DESC, "name", "client_id"',
  timescaledb.compress_segmentby = '"group"'
);
```

test query:
```
explain analyze
SELECT * FROM events
WHERE events.group = 'notification'::varchar
AND events.timestamp >= '2020-11-19 20:00:00+03'::timestamptz AND events.timestamp < '2020-11-19 21:00:00+03'::timestamptz
--ORDER BY events.id DESC
LIMIT 10000;
```
execution plan:
```
                                                                                                  QUERY PLAN                                                                                            
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.08..50.92 rows=10000 width=339) (actual time=7788.491..15238.489 rows=3 loops=1)
   ->  Append  (cost=0.08..161160.50 rows=31700000 width=339) (actual time=7788.489..15238.486 rows=3 loops=1)
         ->  Custom Scan (DecompressChunk) on _hyper_1_584238_chunk  (cost=0.08..2660.50 rows=31700000 width=339) (actual time=7788.489..15238.483 rows=3 loops=1)
               Filter: (("timestamp" >= '2020-11-19 20:00:00+03'::timestamp with time zone) AND ("timestamp" < '2020-11-19 21:00:00+03'::timestamp with time zone) AND (("group")::text = 'notification'::text))
               Rows Removed by Filter: 31692576
               ->  Seq Scan on compress_hyper_34_584769_chunk  (cost=0.00..2660.50 rows=31700 width=811) (actual time=0.006..23.113 rows=31700 loops=1)
                     Filter: ((_ts_meta_max_2 >= '2020-11-19 20:00:00+03'::timestamp with time zone) AND (_ts_meta_min_2 < '2020-11-19 21:00:00+03'::timestamp with time zone))
 Planning Time: 0.878 ms
 Execution Time: 15238.680 ms
```

column "group" is of type "character varying"

**Comment by vitabaks** [comment] 2020-12-16 09:11
\d _timescaledb_internal.compress_hyper_34_584769_chunk
```
                  Table "_timescaledb_internal.compress_hyper_34_584769_chunk"
        Column         |                 Type                  | Collation | Nullable | Default
-----------------------+---------------------------------------+-----------+----------+---------
 id                    | _timescaledb_internal.compressed_data |           |          |
 name                  | _timescaledb_internal.compressed_data |           |          |
 group                 | character varying                     |           |          |
 timestamp             | _timescaledb_internal.compressed_data |           |          |
 attributes            | _timescaledb_internal.compressed_data |           |          |
 client_id             | _timescaledb_internal.compressed_data |           |          |
 ip                    | _timescaledb_internal.compressed_data |           |          |
 city_id               | _timescaledb_internal.compressed_data |           |          |
 city_name             | _timescaledb_internal.compressed_data |           |          |
 subdiv_id             | _timescaledb_internal.compressed_data |           |          |
 subdiv_name           | _timescaledb_internal.compressed_data |           |          |
 lat                   | _timescaledb_internal.compressed_data |           |          |
 long                  | _timescaledb_internal.compressed_data |           |          |
 country_code          | _timescaledb_internal.compressed_data |           |          |
 timezone              | _timescaledb_internal.compressed_data |           |          |
 local_timestamp       | _timescaledb_internal.compressed_data |           |          |
 device_type           | _timescaledb_internal.compressed_data |           |          |
 app_version           | _timescaledb_internal.compressed_data |           |          |
 os_version            | _timescaledb_internal.compressed_data |           |          |
 dre_id                | _timescaledb_internal.compressed_data |           |          |
 user_agent            | _timescaledb_internal.compressed_data |           |          |
 os_name               | _timescaledb_internal.compressed_data |           |          |
 app_name              | _timescaledb_internal.compressed_data |           |          |
 _ts_meta_count        | integer                               |           |          |
 _ts_meta_sequence_num | integer                               |           |          |
 _ts_meta_min_1        | bigint                                |           |          |
 _ts_meta_max_1        | bigint                                |           |          |
 _ts_meta_min_3        | character varying                     |           |          |
 _ts_meta_max_3        | character varying                     |           |          |
 _ts_meta_min_2        | timestamp with time zone              |           |          |
 _ts_meta_max_2        | timestamp with time zone              |           |          |
 _ts_meta_min_4        | character varying                     |           |          |
 _ts_meta_max_4        | character varying                     |           |          |
Indexes:
    "compress_hyper_34_584769_chunk__compressed_hypertable_34_group_" btree ("group", _ts_meta_sequence_num)
Inherits: _timescaledb_internal._compressed_hypertable_34
```

**Comment by vitabaks** [comment] 2020-12-16 09:44
In the documentation: https://docs.timescale.com/latest/using-timescaledb/compression#understanding-segmentby
 
> Queries with WHERE clauses that filter by a segmentby column are much more efficient, as decompression can happen after filtering instead of before (thus avoiding the need to decompress filtered-out rows altogether). In fact, for even more efficient access, we build b-tree indexes over each segmentby column.


But it doesn't work for me...

Please help fix the problem.

**Comment by vitabaks** [comment] 2020-12-16 09:49
SET enable_seqscan = OFF;

```
                                                                                                                                                                                                  QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=10002425762.91..10002425787.91 rows=10000 width=217) (actual time=12121.103..12122.584 rows=10000 loops=1)
   Output: _hyper_1_584238_chunk.id, _hyper_1_584238_chunk.city_name, _hyper_1_584238_chunk.attributes, _hyper_1_584238_chunk."group", _hyper_1_584238_chunk."timestamp", _hyper_1_584238_chunk.ip, _hyper_1_584238_chunk.name, _hyper_1_584238_chunk.client_id
   Buffers: shared hit=981980
   ->  Sort  (cost=10002425762.91..10002505012.91 rows=31700000 width=217) (actual time=12121.102..12122.005 rows=10000 loops=1)
         Output: _hyper_1_584238_chunk.id, _hyper_1_584238_chunk.city_name, _hyper_1_584238_chunk.attributes, _hyper_1_584238_chunk."group", _hyper_1_584238_chunk."timestamp", _hyper_1_584238_chunk.ip, _hyper_1_584238_chunk.name, _hyper_1_584238_chunk.client_id
         Sort Key: _hyper_1_584238_chunk.id DESC
         Sort Method: top-N heapsort  Memory: 4322kB
         Buffers: shared hit=981980
         ->  Append  (cost=315457.50..10000161160.50 rows=31700000 width=217) (actual time=3741.072..9694.377 rows=12347017 loops=1)
               Buffers: shared hit=981980
               ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_1_584238_chunk  (cost=315457.50..10000002660.50 rows=31700000 width=217) (actual time=3741.071..8982.165 rows=12347017 loops=1)
                     Output: _hyper_1_584238_chunk.id, _hyper_1_584238_chunk.city_name, _hyper_1_584238_chunk.attributes, _hyper_1_584238_chunk."group", _hyper_1_584238_chunk."timestamp", _hyper_1_584238_chunk.ip, _hyper_1_584238_chunk.name, _hyper_1_584238_chunk.client_id
                     Filter: ((_hyper_1_584238_chunk."timestamp" >= '2020-11-19 20:00:00+03'::timestamp with time zone) AND (_hyper_1_584238_chunk."timestamp" < '2020-11-19 21:00:00+03'::timestamp with time zone) AND ((_hyper_1_584238_chunk."group")::text = 'operationState'::text))
                     Rows Removed by Filter: 19345562
                     Buffers: shared hit=981980
                     ->  Seq Scan on _timescaledb_internal.compress_hyper_34_584769_chunk  (cost=10000000000.00..10000002660.50 rows=31700 width=331) (actual time=0.006..17.928 rows=31700 loops=1)
                           Output: compress_hyper_34_584769_chunk._ts_meta_count, compress_hyper_34_584769_chunk.id, compress_hyper_34_584769_chunk.name, compress_hyper_34_584769_chunk."group", compress_hyper_34_584769_chunk."timestamp", compress_hyper_34_584769_chunk.attributes, compress_hyper_34_584769_chunk.client_id, compress_hyper_34_584769_chunk.ip, compress_hyper_34_584769_chunk.city_name
                           Filter: ((compress_hyper_34_584769_chunk._ts_meta_max_2 >= '2020-11-19 20:00:00+03'::timestamp with time zone) AND (compress_hyper_34_584769_chunk._ts_meta_min_2 < '2020-11-19 21:00:00+03'::timestamp with time zone))
                           Buffers: shared hit=2185
 Planning Time: 10.266 ms
 Execution Time: 12123.818 ms

**Comment by vitabaks** [comment] 2020-12-16 10:09
The "group" filter does not go down to the compress_hyper_34_584769_chunk level (_ts_meta_max_2, _ts_meta_min_2 only), and is applied at the DecompressChunk level.

**Comment by svenklemm** [comment] 2021-01-31 14:41
@vitabaks  The problem is the datatype of your segment_by column. Since the default datatype is text your query constraints have casts to text preventing pushdown. Can you reproduce this when using text instead of varchar.
Using text instead of varchar is considered best practice and varchar should be avoided as you might run into other issues related to this.

**Comment by vitabaks** [comment] 2021-02-01 09:06
@svenklemm 
Thank you for the answer. 

> Can you reproduce this when using text instead of varchar.

Yes, we'll check. I will write here what the result will be.

**Comment by alexsanjoseph** [comment] 2021-04-02 20:25
> Using text instead of varchar is considered best practice and varchar should be avoided as you might run into other issues related to this.

Thanks @svenklemm - Can confirm that this problem goes away when you use `TEXT` instead of `VARCHAR`. Maybe makes sense to mention this somewhere in the docs?

**Comment by svenklemm** [comment] 2021-04-10 23:56
Closing this since it seems to be resolved.

**Closed by svenklemm** 2021-04-10 23:56 UTC
Labels: bug, investigate
