### ISSUE TITLE
Error install timescale with .rpm file

### ISSUE THREAD

**Issue by quocnguyenq** [timescale/timescaledb#505] opened 2018-04-19 09:07 UTC
Hello

Follow https://docs.timescale.com/v0.9/getting-started/installation/linux/installation-yum
I download timescaledb-0.9.1-postgresql-9.6-0.x86_64.rpm already for postgres 9.6
Then run: rpm -ivh timescaledb-0.9.1-postgresql-9.6-0.x86_64.rpm
But system show:
  error: Failed dependencies:
        postgresql96 is needed by timescaledb-0.9.1-0.el7.centos.x86_64
        postgresql96-devel is needed by timescaledb-0.9.1-0.el7.centos.x86_64
        postgresql96-server is needed by timescaledb-0.9.1-0.el7.centos.x86_64

My redhat: Red Hat Enterprise Linux Server 7.3 (Maipo)
I don't know why, pls help!!

**Comment by RobAtticus** [comment] 2018-04-19 14:45
Did you follow the install instructions here for setting up postgres?:
https://wiki.postgresql.org/wiki/YUM_Installation

**Comment by RobAtticus** [comment] 2018-05-25 16:58
Going to close this for now, please feel free to reopen if the problem is still there.

**Closed by RobAtticus** 2018-05-25 16:58 UTC
Labels: need-more-info
