### ISSUE TITLE
[Bug]: cannot restore materialized view using pg_restore

### ISSUE THREAD

**Issue by theendlessriver13** [timescale/timescaledb#4256] opened 2022-04-20 17:07 UTC
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Backup

### What happened?

`pg_restore` cannot restore a materialized view from a custom format dump
```
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 263; 1259 17589 VIEW t_view postgres
pg_restore: error: could not execute query: ERROR:  column "_materialized_hypertable_2.date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2:  SELECT _materialized_hypertable_2.date,
```
I'd expect it to be able to restore the materialized view (definition) and refresh it upon full restore

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

14.2

### What operating system did you use?

ubuntu 20.04 inside Virtualbox on Windows 10

### What installation method did you use?

Docker

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
Log output from running the script below:
Besides the usual annyoing warnings and notices when creating backups, the errors appear:
-----

ce0f09fa098922ec6d56e580e901e96e0d60fddc0d5ed3c308efd3d35d0a71f9
CREATE DATABASE
CREATE TABLE
 create_hypertable 
-------------------
 (1,public,t,t)
(1 row)

INSERT 0 6
NOTICE:  refreshing continuous aggregate "t_view"
HINT:  Use WITH NO DATA if you do not want to refresh the continuous aggregate on creation.
CREATE MATERIALIZED VIEW
pg_dump: warning: there are circular foreign-key constraints on this table:
pg_dump:   hypertable
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump: warning: there are circular foreign-key constraints on this table:
pg_dump:   chunk
pg_dump: You might not be able to restore the dump without using --disable-triggers or temporarily dropping the constraints.
pg_dump: Consider using a full dump instead of a --data-only dump to avoid this problem.
pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
pg_dump: NOTICE:  hypertable data are in the chunks, no data will be copied
DETAIL:  Data for hypertables are stored in the chunks of a hypertable so COPY TO of a hypertable will not copy any data.
HINT:  Use "COPY (SELECT * FROM <hypertable>) TO ..." to copy all data in hypertable, or copy each chunk individually.
DROP DATABASE
CREATE DATABASE
 timescaledb_pre_restore 
-------------------------
 t
(1 row)

pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 264; 1259 17595 VIEW t_view postgres
pg_restore: error: could not execute query: ERROR:  column "_materialized_hypertable_2.date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 2:  SELECT _materialized_hypertable_2.date,
                ^
Command was: CREATE VIEW public.t_view AS
 SELECT _materialized_hypertable_2.date,
    _timescaledb_internal.finalize_agg('pg_catalog.avg(double precision)'::text, NULL::name, NULL::name, '{{pg_catalog,float8}}'::name[], _materialized_hypertable_2.agg_2_2, NULL::double precision) AS value
   FROM _timescaledb_internal._materialized_hypertable_2
  WHERE (_materialized_hypertable_2.time_partition_col < COALESCE(_timescaledb_internal.to_timestamp_without_timezone(_timescaledb_internal.cagg_watermark(2)), '-infinity'::timestamp without time zone))
  GROUP BY _materialized_hypertable_2.time_partition_col
UNION ALL
 SELECT (public.time_bucket('01:00:00'::interval, t.date) + '01:00:00'::interval) AS date,
    avg(t.val) AS value
   FROM public.t
  WHERE (t.date >= COALESCE(_timescaledb_internal.to_timestamp_without_timezone(_timescaledb_internal.cagg_watermark(2)), '-infinity'::timestamp without time zone))
  GROUP BY (public.time_bucket('01:00:00'::interval, t.date));


pg_restore: error: could not execute query: ERROR:  relation "public.t_view" does not exist
Command was: ALTER TABLE public.t_view OWNER TO postgres;

pg_restore: warning: errors ignored on restore: 2
 timescaledb_post_restore 
--------------------------
 t
(1 row)

ERROR:  duplicate key value violates unique constraint "continuous_agg_user_view_schema_user_view_name_key"
DETAIL:  Key (user_view_schema, user_view_name)=(public, t_view) already exists.
timescaledb
timescaledb
```

### How can we reproduce the bug?

```bash
## This can be executed inside docker:
1. setup the container and wait for the db service to be ready
1. create a custom database `t`
1. create a table t with a `TIMESTAMP` column and make it a hypertable
1. insert some data into the table `t`
1. create a materialized view `t_view` from the hypertable `t`
1. create a backup following the [docs](https://docs.timescale.com/timescaledb/latest/how-to-guides/backup-and-restore/pg-dump-and-restore/)
1. drop and recreate the database `t`
1. run the timescaledb_pre_restore
1. try restoring from the previously created backup **error appears**
1. run the timescaledb_post_restore
1. try creating the materialized view manually -> We are stuck in a state where the view does not exist but also cannot be created.

docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=test timescale/timescaledb-ha:pg14-latest
sleep 10
docker exec -i -e PGPASSWORD=test timescaledb psql -d postgres -c "CREATE DATABASE t"
docker exec -i -e PGPASSWORD=test timescaledb psql -d t -c "CREATE TABLE t (date TIMESTAMP PRIMARY KEY, val DOUBLE PRECISION)"
docker exec -i -e PGPASSWORD=test timescaledb psql -d t -c "SELECT create_hypertable('t', 'date', chunk_time_interval => INTERVAL '1 year')"
docker exec -i -e PGPASSWORD=test timescaledb psql -d t -c "INSERT INTO t VALUES ('2022-01-01 00:00:00', 1), ('2022-01-01 00:30:00', 2), ('2022-01-01 01:00:00', 3), ('2022-01-01 01:30:00', 4), ('2022-01-01 02:00:00', 5), ('2022-01-01 02:30:00', 6)"
docker exec -i -e PGPASSWORD=test timescaledb psql -d t -c "CREATE MATERIALIZED VIEW t_view(date, value) WITH (timescaledb.continuous) AS SELECT time_bucket('1hour', date) + '1hour', AVG(val) FROM t GROUP BY time_bucket('1hour', date)"
docker exec -i -e PGPASSWORD=test timescaledb pg_dump -Fc t -f db.dump
docker exec -i -e PGPASSWORD=test timescaledb psql -d postgres -c "DROP DATABASE t"
docker exec -i -e PGPASSWORD=test timescaledb psql -d postgres -c "CREATE DATABASE t"
docker exec -i -e PGPASSWORD=test timescaledb psql -d t -c "SELECT timescaledb_pre_restore()"
docker exec -i -e PGPASSWORD=test timescaledb pg_restore -Fc -d t db.dump
docker exec -i -e PGPASSWORD=test timescaledb psql -d t -c "SELECT timescaledb_post_restore()"
docker exec -i -e PGPASSWORD=test timescaledb psql -d t -c "CREATE MATERIALIZED VIEW t_view(date, value) WITH (timescaledb.continuous) AS SELECT time_bucket('1hour', date) + '1hour', AVG(val) FROM t GROUP BY time_bucket('1hour', date)"
docker stop timescaledb && docker rm timescaledb
```

**Comment by konskov** [comment] 2022-04-21 07:16
Hi @theendlessriver13 thanks for reporting this issue. 

It looks like this is a duplicate of #4233.
(Notice the `time_bucket('1hour', date) + '1hour'` in the materialized view definition)

**Closed by konskov** 2022-04-21 07:16 UTC
Labels: bug
