### ISSUE TITLE
timescaledb fresh install fails

### ISSUE THREAD

**Issue by kvaikla** [timescale/timescaledb#3514] opened 2021-08-24 09:10 UTC
Hi, 
Seems, that something is wrong in SHAREDIR/extension/
OS:RH 7.9
Pg:12.5

Steps what has been done:
yum install timescaledb-2-postgresql-12-2.3.1-0.el7.x86_64
timescaledb-tune -conf-path=/pgdata/pgsql/12/data/postgresql.conf

```
dusagedata=# create extension timescaledb ;
ERROR:  extension "timescaledb" has no installation script nor update path for version "2.4.1"

dusagedata=# select * from pg_available_extensions where name='timescaledb';
    name     | default_version | installed_version |                              comment
-------------+-----------------+-------------------+-------------------------------------------------------------------
 timescaledb | 2.4.1           |                   | Enables scalable inserts and complex queries for time-series data
(1 row)

dusagedata=# create extension timescaledb version '2.3.1';
ERROR:  could not load library "/usr/pgsql-12/lib/timescaledb-2.3.1.so": /usr/pgsql-12/lib/timescaledb-2.3.1.so: undefined symbol: pull_varnos_new
```
```
$ ls /usr/pgsql-12/share/extension/timescale*
/usr/pgsql-12/share/extension/timescaledb--1.1.0--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--1.5.1--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.0.0-rc3--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.1.1--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--1.6.0--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.0.0-rc4--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.2.0--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--1.6.1--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.0.1--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.2.1--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--1.7.0--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.0.2--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.2.2--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--1.7.1--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.1.0--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.3.0--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--1.7.2--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.1.1--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.3.1--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--1.7.3--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.2.0--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.3.2--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--1.7.4--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.2.1--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.4.0--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--1.7.5--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.3.0--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.4.1--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--2.0.0--2.3.1.sql      /usr/pgsql-12/share/extension/timescaledb--2.3.1--2.3.0.sql
/usr/pgsql-12/share/extension/timescaledb--1.4.2--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--2.0.0-rc1--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--2.3.1.sql
/usr/pgsql-12/share/extension/timescaledb--1.5.0--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb--2.0.0-rc2--2.3.1.sql  /usr/pgsql-12/share/extension/timescaledb.control

$ cat /usr/pgsql-12/share/extension/timescaledb.control
# timescaledb extension
comment = 'Enables scalable inserts and complex queries for time-series data'
default_version = '2.4.1'
module_pathname = '$libdir/timescaledb-2.4.1'
#extension cannot be relocatable once installed because it uses multiple schemas and that is forbidden by PG.
#(though this extension is relocatable during installation).
relocatable = false

$ ls /usr/pgsql-12/lib/times*
/usr/pgsql-12/lib/timescaledb-2.3.1.so  /usr/pgsql-12/lib/timescaledb.so  /usr/pgsql-12/lib/timescaledb-tsl-2.3.1.so
```

Did I mess something up?

br
Kaido

**Comment by mfundul** [comment] 2021-08-24 09:55
Since you're not installing the latest available version but version 2.3.1 then you should run the command:
```
CREATE EXTENSION timescaledb WITH VERSION "2.3.1";
```

**Comment by kvaikla** [comment] 2021-08-24 09:56
Like I wrote
```
dusagedata=# create extension timescaledb version '2.3.1';
ERROR:  could not load library "/usr/pgsql-12/lib/timescaledb-2.3.1.so": /usr/pgsql-12/lib/timescaledb-2.3.1.so: undefined symbol: pull_varnos_new
```

**Comment by mfundul** [comment] 2021-08-24 09:57
Maybe duplicate of https://github.com/timescale/timescaledb/issues/3482

**Comment by kvaikla** [comment] 2021-08-24 10:05
if so then what could be a solution?

**Comment by mfundul** [comment] 2021-08-24 10:19
A solution seems to be to upgrade PG to >= 12.6

**Comment by kvaikla** [comment] 2021-08-24 10:53
Ok, but i think, pg patch level "control" is too much.  Furtheremore, if doc says:  "TimescaleDB requires PostgreSQL 12 or 13"

**Comment by NunoFilipeSantos** [comment] 2021-08-24 14:09
@kvaikla please upgrade to TimescaleDB 2.4.1 where we have fixed this issue.

**Closed by NunoFilipeSantos** 2021-08-24 14:09 UTC
Labels: bug
