### ISSUE TITLE
[Bug]: Continuous aggregate policy refresh throws error

### ISSUE THREAD

**Issue by csharpdev09** [timescale/timescaledb#4128] opened 2022-02-25 06:52 UTC
### What type of bug is this?

Crash, Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

During Timescale continuous aggregate policy refresh on a defined interval, it throws the below-mentioned errors.

2022-02-24 14:01:13.663 [23576] LOG: refreshing continuous aggregate "aggregate_policy" in window
2022-02-24 14:01:13.669 [23576] LOG: job 1012 threw an error
2022-02-24 14:01:13.669 [23576] ERROR: portal snapshots (0) did not account for all active snapshots (1)
2022-02-24 14:01:13.673 [24936] LOG: background worker "Refresh Continuous Aggregate Policy [1012]" (PID 23576) exited with exit code 1

### TimescaleDB version affected

Tried on both 2.5.0 & 2.6.0

### PostgreSQL version used

13.6

### What operating system did you use?

Windows 10

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
2022-02-24 14:01:13.663 [23576] LOG: refreshing continuous aggregate "aggregate_policy" in window
2022-02-24 14:01:13.669 [23576] LOG: job 1012 threw an error
2022-02-24 14:01:13.669 [23576] ERROR: portal snapshots (0) did not account for all active snapshots (1)
2022-02-24 14:01:13.673 [24936] LOG: background worker "Refresh Continuous Aggregate Policy [1012]" (PID 23576) exited with exit code 1
```

### How can we reproduce the bug?

```bash
Create a Refresh Continuous Aggregate Policy
During refresh it throws the above error in logs
```

**Comment by horzsolt** [comment] 2022-02-25 08:46
@csharpdev09 thanks for submitting this issue, can you please provide the following information for us to be able to reproduce your bug:

- create table statement of the hypertable
- create statement of the continuous aggregate
- create command of the refresh policy 
thank you

**Comment by csharpdev09** [comment] 2022-02-28 08:36
Thank you for your reply, following are the command to reproduce the bug.

Please let me know if anything else is requried.

`

CREATE TABLE IF NOT EXISTS sensor_data(
	sensor_id uuid NOT NULL,
	time_index timestamp with time zone NOT NULL,
	data_value real,
	PRIMARY KEY (sensor_id, time_index));
	
SELECT create_hypertable('sensor_data', 'time_index', chunk_time_interval => interval '1 day', if_not_exists => TRUE);

CREATE MATERIALIZED VIEW sensor_data_summary_daily
WITH (timescaledb.continuous, timescaledb.create_group_indexes = true) AS
SELECT	time_bucket('24 Hours',time_index) AS time_index_start,
	AVG(data_value) AS avg_value
	FROM sensor_data 
	GROUP BY time_index_start WITH NO DATA;
	
SELECT add_continuous_aggregate_policy('sensor_data_summary_daily',
									   start_offset => INTERVAL '7 days',
									   end_offset   => INTERVAL '60 minutes',
									   schedule_interval => INTERVAL '30 minutes'); 

`

**Comment by erimatnor** [comment] 2022-02-28 14:44
@csharpdev09  I ran your commands to reproduce the bug and did not experience an error. Your commands don't include adding any data, which makes me think that having data is important to reproduce the bug. However, adding some sample data still doesn't reproduce the error.

I did notice some oddness in the log output you posted:

```
2022-02-24 14:01:13.663 [23576] LOG: refreshing continuous aggregate "aggregate_policy" in window
```

That line should typically print the refresh window's start and end.

**Comment by csharpdev09** [comment] 2022-02-28 16:23
@erimatnor Thanks for your reply, May i know in which version you tried to replicate this?

For me above mentioned errors are thrown in the logs right after executing the above statements, and it keeps on printing the same logs on each refresh interval.

```
2022-02-28 13:54:36.921 IST [20592] LOG:  refreshing continuous aggregate "sensor_data_summary_daily" in window [ 2022-02-22 05:30:00+05:30, 2022-02-28 05:30:00+05:30 ]
2022-02-28 13:54:36.927 IST [20592] LOG:  job 1014 threw an error
2022-02-28 13:54:36.927 IST [20592] ERROR:  portal snapshots (0) did not account for all active snapshots (1)
2022-02-28 13:54:36.931 IST [19660] LOG:  background worker "Refresh Continuous Aggregate Policy [1014]" (PID 20592) exited with exit code 1
```

Right now I am on PG 13.6 and Timescale 2.6.0

Please let me know what else is required from my side to replicate this error?

**Comment by erimatnor** [comment] 2022-04-28 06:11
@csharpdev09 I ran again on 2.6.0 with your exact commands. This is what I see in the logs:

```
2022-04-28 08:08:53.147 CEST [281214] LOG:  00000: statement: SELECT add_continuous_aggregate_policy('sensor_data_summary_daily',
        start_offset => INTERVAL '7 days',
        end_offset => INTERVAL '60 minutes',
        schedule_interval => INTERVAL '30 minutes');
2022-04-28 08:08:53.147 CEST [281214] LOCATION:  exec_simple_query, postgres.c:1014
2022-04-28 08:08:53.880 CEST [281362] LOG:  00000: refreshing continuous aggregate "sensor_data_summary_daily" in window [ 2022-04-22 02:00:00+02, 2022-04-28 02:00:00+02 ]
```

So, I am unfortunately not able to reproduce this issue. Maybe you have a difference in your setup, some memory limit that the job hits or something similar?

**Comment by NunoFilipeSantos** [comment] 2022-06-23 11:12
Hi @csharpdev09 ! 👋 We're closing this issue for now, feel free to reopen it if you can provide more information. Thank you! 😃

**Closed by NunoFilipeSantos** 2022-06-23 11:12 UTC
Labels: bug, need-more-info, Core Database Team, 2.6.0
