### ISSUE TITLE
COPY FROM with serial datatype segfaults and restarts the timescaledb 

### ISSUE THREAD

**Issue by dhodyn** [timescale/timescaledb#1892] opened 2020-05-13 14:21 UTC
Relevant system information:

OS: Fedora 31
PostgreSQL version (output of postgres --version): 12.2
TimescaleDB version (output of \dx in psql): 1.7.0
Installation method: using Docker

Describe the bug
if the copy to is inserting a 'bad' record into the hypertable, the database is terminating all the connections and restarting

**To Reproduce**
```
create table regulartable (time timestamptz, id bigserial, value numeric);
create table hypertable (time timestamptz, id bigserial, value numeric);
select create_hypertable('hypertable', 'time');

```
```
create a datafile as /csv/data.csv
2020-05-13 22:00:00.000000,,1

```
```
copy regulartable(time, id, value) from '/csv/data.csv' csv;
copy hypertable(time, id, value) from '/csv/data.csv' csv;
```

since the column id is serial, it is not expecting a null value in the input csv. 
```
For regular table, error is returned as
2020-05-13 14:10:16.497 UTC [69] ERROR:  null value in column "id" violates not-null constraint
2020-05-13 14:10:16.497 UTC [69] DETAIL:  Failing row contains (2020-05-13 22:00:00+08, null, 1).
2020-05-13 14:10:16.497 UTC [69] CONTEXT:  COPY regulartable, line 1: "2020-05-13 22:00:00.000000,,1"

for hypertable,
2020-05-13 14:10:16.497 UTC [69] ERROR:  null value in column "id" violates not-null constraint
2020-05-13 14:10:16.497 UTC [69] DETAIL:  Failing row contains (2020-05-13 22:00:00+08, null, 1).
2020-05-13 14:10:16.497 UTC [69] CONTEXT:  COPY regulartable, line 1: "2020-05-13 22:00:00.000000,,1"
```

**Expected behavior**
same error as regular table

**Actual behavior**
segfault

**Screenshots**

**Additional context**
Please close the bug if it is duplicate of 
https://github.com/timescale/timescaledb/issues/1840

**Comment by svenklemm** [comment] 2020-05-17 18:00
Thanks for the report this is indeed duplicate of #1840 and already fixed on master

**Closed by svenklemm** 2020-05-17 18:00 UTC
Labels: bug
