### ISSUE TITLE
pg_restore error chunk_index... when trying to backup/restore from one 2.2.0 instance to another

### ISSUE THREAD

**Issue by tluchowski** [timescale/timescaledb#3154] opened 2021-04-23 23:13 UTC
Hi,

I'm running Postgresql 12 + Timescale extension 2.2.0 on two separate hosts.

I'm taking the backup as follows (on a host with Postgresql 12, it was running Timescale 1.7.1, but recently was upgraded to 1.7.5, then to 2.2.0):
pg_dump -j2 -U postgres -Fd -Z9 -f mydatabase.pgbak mydatabase

And trying to restore it on another host (Postgresql 12) as follows.

Unfortunately this fails, errors can be seen below.

```
psql -X
postgres=# create database mydatabase;
CREATE DATABASE
postgres=# \c mydatabase;
You are now connected to database "mydatabase" as user "postgres".
mydatabase=# CREATE EXTENSION timescaledb
mydatabase-# ;
WARNING:
WELCOME TO
 _____ _                               _     ____________
|_   _(_)                             | |    |  _  \ ___ \
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ /
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 2.2.0
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/getting-started
 2. API reference documentation: https://docs.timescale.com/api
 3. How TimescaleDB is designed: https://docs.timescale.com/introduction/architecture

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescaledb.com/using-timescaledb/telemetry.

CREATE EXTENSION
mydatabase=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.2.0   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)

mydatabase=# SELECT timescaledb_pre_restore();
 timescaledb_pre_restore
-------------------------
 t
(1 row)

mydatabase=# \! pg_restore -j 4 -Fd -d mydatabase mydatabase.pgbak
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3937; 0 17063 TABLE DATA chunk_index postgres
pg_restore: error: COPY failed for table "chunk_index": ERROR:  insert or update on table "chunk_index" violates foreign key constraint "chunk_index_chunk_id_fkey"
DETAIL:  Key (chunk_id)=(165) is not present in table "chunk".
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3935; 0 17045 TABLE DATA chunk_constraint postgres
pg_restore: error: COPY failed for table "chunk_constraint": ERROR:  insert or update on table "chunk_constraint" violates foreign key constraint "chunk_constraint_chunk_id_fkey"
DETAIL:  Key (chunk_id)=(200) is not present in table "chunk".
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 3933; 0 17024 TABLE DATA chunk postgres
pg_restore: error: COPY failed for table "chunk": ERROR:  insert or update on table "chunk" violates foreign key constraint "chunk_hypertable_id_fkey"
DETAIL:  Key (hypertable_id)=(3) is not present in table "hypertable".
pg_restore: from TOC entry 3931; 0 17008 TABLE DATA dimension_slice postgres
pg_restore: error: COPY failed for table "dimension_slice": ERROR:  insert or update on table "dimension_slice" violates foreign key constraint "dimension_slice_dimension_id_fkey"
DETAIL:  Key (dimension_id)=(3) is not present in table "dimension".
```

**Comment by tluchowski** [comment] 2021-04-23 23:40
Just found this: https://github.com/timescale/timescaledb/issues/698

Docs really need to be enhanced to make it clear that pg_dump will fail if -j is used!

I was closely following https://docs.timescale.com/latest/using-timescaledb/backup and there was no mention of this at all

**Comment by mkindahl** [comment] 2021-04-27 09:56
@tluchowski Thank you for the bug report. Did some minor edit on the original report to make it easier to read.

**Comment by mkindahl** [comment] 2021-04-27 09:59
Closing the issue since it is a duplicate of #698. Please reopen if you think it is not accurate.

**Closed by mkindahl** 2021-04-27 09:59 UTC
Labels: community-request, enhancement
