### ISSUE TITLE
[Bug]: Very slow continuous aggregate 

### ISSUE THREAD

**Issue by jbx1** [timescale/timescaledb#4444] opened 2022-06-14 22:01 UTC
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I am using the latest postgresql 14.3 with timescale 2.7.0 from the timescaledb docker image. 

I am performing a load test of 50 million rows inserted into a hypertable in approximately chronological order, with some concurrency. Each batch of 1000 rows is inserted within the same hour chronologically, with some workers potentially inserting into the next hour concurrently. The hypertable was created using defaults, on the `time` field (with the default chunk time interval of 7 days). The data spans about 7 months. 

I also have a continuous aggregate that aggregates the data daily (time bucket of 1 day). 

The continuous aggregate was created before the data was inserted. After all data was inserted, very simply queries like: 
```
select * from daily_vew limit 1;
...
Time: 39429.423 ms (00:39.429)
```
Take a very long time. 

Other queries on the continuous aggregate take a long time too. 

When I dropped the materialized view of the continuous aggregate, and recreated it on the same exact hypertable of 50 million rows. The same exact query:

```
select * from daily_vew limit 1;
...
Time: 15.829 ms
Took just 15ms!
```

For some reason I get such a bad performance on the continuous aggregate the first time round, then after I drop it and recreate it, with the data already there, the continuous aggregate is fast.

### TimescaleDB version affected

2.7.0

### PostgreSQL version used

14.3

### What operating system did you use?

Ubuntu 18.04.4 LTS

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

1. Download the latest timescaledb docker image with postgresql 14.3 and timescaledb 2.7.0, and start the image: 

`docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg14`

2. Log into the running container and run timescaledb-tune. 

3. Create a database called `test` and create the timescaledb extension within the created database. 

4. Create and run the following Python script (change the IP address and credentials accordingly if necessary):

```python
from datetime import datetime, timedelta
import pandas as pd
import sys

import numpy as np
import psycopg2
from pgcopy import CopyManager

CONNECTION = "postgres://postgres:password@127.0.0.1:5432/test"
START_TIME = pd.to_datetime('2022-01-01 00:00:00.000')

def generate_customer_ids(size):
    customer_ids = []
    for x in range(size):
        customer_ids.append(str(uuid.uuid4()))
    return customer_ids

CUSTOMER_IDS = generate_customer_ids(100000);

def sample_date_time(start, delta, n):
    end = start + delta
    return pd.date_range(start, end, periods=n)

def insert(n):
    conn = psycopg2.connect(CONNECTION)
    cursor = conn.cursor()

    cols = ['time', 'customer_id', 'op_id', 'type', 'amount', "return", "win",
            "loss", "bonus", "incoming", "outgoing"]

    samples = 1000
    types = ["A", "B", "C", "D", "E", "F", "G"]

    #make 10 batches all insert into the same period
    start = START_TIME + timedelta(hours=n // 10)
    delta = timedelta(hours=1)

    df = pd.DataFrame()
    df["time"] = sample_date_time(start, delta, samples)
    df["customer_id"] = np.random.choice(CUSTOMER_IDS, samples)
    df["op_id"] = np.random.randint(1, 1000, samples)
    df["type"] = np.random.choice(types, samples)
    df["amount"] = np.random.uniform(5.5, 2500.30, samples)
    df["return"] = np.random.uniform(5.5, 2500.30, samples)
    df["win"] = np.random.uniform(5.5, 2500.30, samples)
    df["loss"] = np.random.uniform(5.5, 2500.30, samples)
    df["bonus"] = np.random.uniform(5.5, 2500.30, samples)
    df["incoming"] = np.random.uniform(5.5, 2500.30, samples)
    df["outgoing"] = np.random.uniform(5.5, 2500.30, samples)
    list = df.values.tolist()

    start = timer()
    mgr = CopyManager(conn, 'data', cols)
    mgr.copy(list)
    end = timer()

    # commit after all data is inserted
    conn.commit()
    cursor.close()


def data_tests():
    with multiprocessing.Pool() as pool:
       insert_tasks = pool.map_async(insert, range(50000), 1)
       insert_tasks.wait()


def main():
    conn = psycopg2.connect(CONNECTION)
    cursor = conn.cursor()

    query_create_data_table = """CREATE TABLE IF NOT EXISTS data (
                                    time timestamp not null,
                                    customer_id varchar(255) not null,
                                    op_id int not null,
                                    type varchar(255) not null,
                                    amount double precision,
                                    return double precision,
                                    win double precision,
                                    loss double precision,
                                    bonus double precision,
                                    incoming double precision,
                                    outgoing double precision
                                    );"""


    query_create_hypertable = "SELECT create_hypertable('data', 'time', if_not_exists => TRUE);"

    query_create_main_idx = """CREATE INDEX IF NOT EXISTS data_time_customer_id_type_idx
        on data (customer_id asc, type asc, time desc);"""

    query_create_continuous_aggregate = """CREATE MATERIALIZED VIEW IF NOT EXISTS daily_view
                                            WITH (timescaledb.continuous)
                                            AS
                                            SELECT
                                               time_bucket('1 day', time) as bucket,
                                               type,
                                               customer_id,
                                               sum(amount) as sum_amount,
                                               count(amount) as amount,
                                               min(amount) as min_amount,
                                               max(amount) as max_amount,
                                               avg(amount) as avg_amount
                                            FROM data
                                            GROUP BY bucket, type, customer_id
                                            WITH NO DATA;"""

    cursor.execute(query_create_data_table)
    conn.commit()
    cursor.execute(query_create_hypertable)
    cursor.execute(query_create_main_idx)
    cursor.execute(query_create_continuous_aggregate)
    conn.commit()
    cursor.close()

    data_tests()


if __name__ == "__main__":
    main()
```
```

**Comment by jbx1** [comment] 2022-06-15 17:25
@horzsolt The script is created with NO DATA because in my tests I was sometimes creating it after the data was inserted, and refreshing manually to see what was happening. (Also, when creating the aggregate with NO DATA, timescale was displaying warnings to use NO DATA.)

In the above case the continuous aggregate is created before any data is inserted. According to the documentation "The WITH NO DATA option allows the continuous aggregate to be created instantly, so you don't have to wait for the data to be aggregated. Data begins to populate only when the policy begins to run. This means that only data newer than the start_offset time begins to populate the continuous aggregate."

Given the hypertable is empty when I create the continuous aggregate, I can't see how this would have any effect at all. 

But I will try it again and let you know.

**Comment by jbx1** [comment] 2022-06-15 18:35
@horzsolt Changed it to create the materialized view without the NO DATA option as follows. Dropped both the materialized view and the hypertable and recreated them before inserting the data (50 million rows). 

Still the same very bad performance. Doing a `select * from daily_view limit 1` took over 46 seconds.

```
Time: 46715.162 ms (00:46.715)
```



```
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
from psycopg2.extensions import ISOLATION_LEVEL_DEFAULT
```

```
query_create_continuous_aggregate = """CREATE MATERIALIZED VIEW IF NOT EXISTS daily_view
                                            WITH (timescaledb.continuous)
                                            AS
                                            SELECT
                                               time_bucket('1 day', time) as bucket,
                                               type,
                                               customer_id,
                                               sum(amount) as sum_amount,
                                               count(amount) as amount,
                                               min(amount) as min_amount,
                                               max(amount) as max_amount,
                                               avg(amount) as avg_amount
                                            FROM data
                                            GROUP BY bucket, wager_type, customer_id;"""

    conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    cursor.execute(query_create_data_table)
    cursor.execute(query_create_hypertable)
    cursor.execute(query_create_main_idx)
    cursor.execute(query_create_continuous_aggregate)
    cursor.close()

    conn.set_isolation_level(ISOLATION_LEVEL_DEFAULT)
   
    data_tests()
```

**Comment by konskov** [comment] 2022-06-17 06:33
Hi @jbx1, could you please provide the following information: 

* output of `explain select * from daily_view limit 1;` for both cases, slow and fast
* when you say you drop and recreate the materialized view with the data already there, I understand that you mean you skipped the `WITH NO DATA` option when recreating the view, is that correct?
* could you run `VACUUM ANALYZE data;` and see if that improves performance?

Thanks!

**Comment by konskov** [comment] 2022-06-17 07:00
If you look at the output of explain, in the slow case you will notice that the data comes from the table data, and not the materialized view itself. 
![Screenshot 2022-06-17 at 9 56 00 AM](https://user-images.githubusercontent.com/44239391/174242836-b2e34df7-3ccd-45de-918a-07fa6b1f25fc.png)

In the fast case, you can see the data comes from the materialized view itself:
![Screenshot 2022-06-17 at 9 57 43 AM](https://user-images.githubusercontent.com/44239391/174243068-cf3736e2-0614-43ef-aaf4-645292b8113b.png)

The fact that you do not see any change in query performance when skipping the `WITH NO DATA` option is not unexpected. It is because the materialized view is, as you have said, created before inserting data into the table named `data`. So while the creation of the view happens instantaneously, there is no data in the table `data` at that point so the materialized view does not contain any data, and will not contain any until you refresh it (or drop and recreate it after populating the table).   

You can also take a look at [this issue](https://github.com/timescale/timescaledb/issues/4216) which is related, I believe there is no unexpected behavior here.

**Comment by jbx1** [comment] 2022-06-17 07:46
@konskov replies below:

- output of explain select * from daily_view limit 1; for both cases, slow and fast

I presume you regenerated it and don't need it. 

- when you say you drop and recreate the materialized view with the data already there, I understand that you mean you skipped the WITH NO DATA option when recreating the view, is that correct?

Yes of course it was created with data. 

- could you run VACUUM ANALYZE data; and see if that improves performance?

No it does not. I had also tried `VACUUM FULL ANALYZE`.

My issue has **nothing to do** with the WITH NO DATA option. That was brought up by @horzsolt as a possible cause, which we excluded by the second test. 

Looking at the issue you linked, could it be that the reason has to do with future dated timestamps? My test is starting from 1st January 2022, and continues generating records with timestamps up to July?

**Comment by konskov** [comment] 2022-06-17 11:35
Apologies if I closed the issue prematurely, I probably misunderstood the issue you are facing.

From my understanding, you were wondering why there is such a difference in performance.
(*For some reason I get such a bad performance on the continuous aggregate the first time round, then after I drop it and recreate it, with the data already there, the continuous aggregate is fast*)

The explanation is that the data comes from the table and not from the materialized view. (As to why the data comes from the original hypertable, data : this is because of real-time aggregation, which is enabled by default, if you don’t explicitly specify the option `materialized_only = true` to disable it).
In the script you provided, I see that in both cases (with data / with no data) the materialized view is created before calling `data_tests()` so before populating the table.
If you would do the creation of the materialized view, with data, after the population of the data table, then I believe you would get good query performance straight away (no need to drop/recreate the view). I haven’t tested it yet though - could you please try it and get back to us? Also please provide the output of explain, just to make sure it is not different for you.
I linked the issue to reference https://github.com/timescale/timescaledb/issues/4216#issuecomment-1090176836 specifically, about how you can tell where the result comes from.

If that is not what you were asking, please feel free to reopen the issue and we can try to look into it

**Comment by jbx1** [comment] 2022-06-17 13:18
@konskov OK, can you please reopen the issue because I don't have any permissions to reopen it?

I will rerun the tests again without the continuous aggregate and create it after all the data is inserted, to confirm it is fast (pretty sure it will be). Of course, in my use case I want to have the continuous aggregate there before, so that the aggregate information is generated automatically as the data comes in.

**Comment by konskov** [comment] 2022-06-17 15:47
> so that the aggregate information is generated automatically as the data comes in

What do you mean by this, what would you like to achieve?
Real-time aggregation does not mean that the materialized view is getting refreshed. It means that when you query the materialized view, the pre-aggregated data that’s already in the materialized view will be combined with recent data from the original hypertable, which hasn’t been aggregated yet, to return an up-to-date result.
If you want the data to be in the materialized view itself, then you will have to refresh the view. The view can be refreshed in one of two ways:
1. manually, by calling `refresh_continuous_aggregate` or
2. by setting up a policy with `add_continuous_aggregate_policy` that will run in the background on a given schedule and automatically refresh the materialized view.

You can read more about how continuous aggregates work in our [documentation](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/about-continuous-aggregates/#function-support), [blog](https://www.timescale.com/blog/achieving-the-best-of-both-worlds-ensuring-up-to-date-results-with-real-time-aggregation/), and get more help on our community slack and forum

**Comment by jbx1** [comment] 2022-06-20 16:02
@konskov ok yes this is an important detail I was somehow missing even though I was aware of the refresh policy

What I want to achieve of course is that I query the continuous aggregate materialized view and have at least equivalent or faster response time than the actual hypertable. 

I added the following refresh policy. I know this might not be realistic due to the very short schedule_interval and the fact that 6 months of data are being inserted at once, but I want to simulate load as much as possible. 

```
query_create_refresh_policy = """SELECT add_continuous_aggregate_policy('daily_view',
                                            start_offset => NULL,
                                            end_offset => INTERVAL '1 day',
                                            schedule_interval => INTERVAL '1 minutes');"""

cursor.execute(query_create_refresh_policy)
```

So while the script is inserting I would expect the continuous aggregate materialized view to refresh. 

The situation is now much better, although there are still some strange things I wish to understand why. 

`select * from daily_view limit 1` now returns in 58ms, which is great. 

However: 

`select max(time) from data` returns in 39ms, while 
`select max(bucket) from daily_view` returns in  8765.727 ms (00:08.766). 

Even after calling `refresh_continuous_aggregate` manually, in case the slowness was because it had to aggregate recent records, it still took 8 seconds. 

Similarly, calling `select count(*) from daily_view` took 8 seconds too: Time: 8115.530 ms (00:08.116)
while calling `select count(*) from data` (50 million rows) took 2 seconds: Time: 2336.688 ms (00:02.337)

When I do `explain`, it seems that the materialized view is being used, but there is a sequential scan. 
When I do an `explain` on the last two queries on the main hypertable, in both cases there are index scans being used. 

What could be the reason for the continuous aggregate materialized view not using the right indices?

**Comment by konskov** [comment] 2022-06-21 11:17
Real-time aggregation provides a full overview on the data including non-materialized data as well, but it can come with a trade-off, the cost of using union. So depending on your use case, you can consider turning real-time aggregates on/off, getting some queries from the materialized view or some from the original hypertable etc. 
You do not need to create additional indices, they already exist: If you turn off real-time aggregation in this case, you'll notice that the index on time_bucket is being used. 
You can get more help on our community slack and forum if you need it, I believe it's a better platform for this type of questions regarding what options work best depending on the use case.

**Comment by Jimi9** [comment] 2022-11-11 11:14
Greetings all,

I am sorry to include myself in the discussion but I noticed the same problem.

I am basically creating a MATERIALIZED VIEW from a brand new table created earlier (oltp.channel_data_float). 
![table_channel_data_float](https://user-images.githubusercontent.com/117985167/201327502-b2f5d1f4-6241-45a4-91b6-3be20ca33aa8.png)

After the table has been populated I created a VIEW oltp.hourly_average_stats like so:

```
 
CREATE MATERIALIZED VIEW IF NOT EXISTS oltp.hourly_average_stats WITH (timescaledb.continuous)--oltp.
 AS SELECT time_bucket('1 hour',oltp.channel_data_float.time) AS bucket
                 , oltp.channel_data_float.channel_id 
                 , MAX (oltp.channel_data_float.value)
                 , MIN (oltp.channel_data_float.value)
                 , AVG (oltp.channel_data_float.value)
                 
         
         FROM oltp.channel_data_float
 
         
         GROUP BY bucket,oltp.channel_data_float.channel_id;---,oltp.channel_data_float.channel_id
         
 SELECT add_continuous_aggregate_policy('oltp.hourly_average_stats',
      start_offset => INTERVAL '3 hours',
      end_offset => INTERVAL '1 hour',
      schedule_interval => INTERVAL '1 hour');
```

and the output of "explain select * from oltp.hourly_average_stats LIMIT 1;" is:
![explain_view_fast](https://user-images.githubusercontent.com/117985167/201328292-b57337db-8945-4da1-adb8-e675666238e8.png)

In my opinion the chunk sent, according the query plan, are related to the original table oltp.channel_data_float and not to the VIEW just created. Susequently I am not sure why this GroupAggregated is used instead of the HashAggregated containg the Custom scan pointing in the right hypertable.

Thank you very much for your support.

**Comment by konskov** [comment] 2022-11-14 10:23
hi @Jimi9, thanks for reaching out.  Have you also tried asking in our slack/forum? You would probably get a quicker response there. 
I wonder if your refresh policies are working as expected, since you say the aggregate does not follow the policy. Can you check the  cagg_watermark value for the respective materialized hypertable? That should tell you how far materializations have progressed...

**Comment by Jimi9** [comment] 2022-11-15 13:32
Many thanks Konskov.

I am observing also fluctuation on the requested time to retrieve the data from the materialized VIEW (to retrieve the same data the range goes from 15 s to 45-50s in less than 5 minutes of tries).

Here you can see the output of the explain (analyze) query:
![explain_analyze](https://user-images.githubusercontent.com/117985167/201931592-9e515597-c108-4086-8977-40f0ac9f45a8.png)

and here the cagg_watermark value obtained running the command at 2022-11-15 13:31:
![watermark](https://user-images.githubusercontent.com/117985167/201931988-133202c6-d629-42a3-b248-73a7ca272c56.png)

Not sure how to extract some useful information but I wait for your feedback about those.

**Comment by konskov** [comment] 2022-11-15 16:18
@Jimi9 you are using version 2.6.0, there have been several changes to continuous aggregates since, most notably the new cagg format which makes them more performant. Would it be possible for you to retry with the latest version of TimescaleDB and let us know if you still notice the same performance issues?

**Comment by Jimi9** [comment] 2022-11-17 10:42
@konskov I have updated timescaledb version to 2.8.0 and I would say that the performance are slightly better but still seeing a fluctuation in the time per request when requesting 10 charts at the same time. Maybe there is a limit also in the HDD disk used in the database because as I said the server with timescaledb version 2.5.2 BUT equipped with SSD disk didn't show any fluctuation or latency in the response

**Comment by konskov** [comment] 2022-11-18 13:16
@Jimi9, could you try some more combinations: 

* Could you remove the LIMIT clause and look at the output plan? And also the time taken
* Also do `EXPLAIN (ANALYZE, BUFFERS)` that should also show the buffers hit. 
* Try to experiment with both servers/disks and timescaleDB versions to help determine if the timescaleDB version plays a part here..

**Comment by Jimi9** [comment] 2022-11-21 15:18
At the moment I don't have the access to the SSD server but I would like feedback about this two outputs.

I sent the same query "explain (analyze,buffers) select * from oltp.hourly_average_stats;" within 5 minutes and you can see the difference in the execution time.

The first try is here:
![explain_analyze_buffer_HDD](https://user-images.githubusercontent.com/117985167/203091053-5ff5908f-6da6-4c3c-b926-ab4d16dcb1ea.png)

and the second one, (a few minutes later):

![explain_analyze_buffer_2try_HDD](https://user-images.githubusercontent.com/117985167/203091146-df5f5ffb-8185-4edb-8c1e-3daf4882b53e.png)

**Comment by Jimi9** [comment] 2022-11-22 08:36
Here I leave also the output from the SSD server:

![explain_analyze_buffer_SSD](https://user-images.githubusercontent.com/117985167/203265201-f5f72df2-d12f-406d-b0cb-286e31400614.png)

![explain_analyze_buffers_SSD2](https://user-images.githubusercontent.com/117985167/203265237-3e7f0f19-b370-469d-b0c8-b149e7dbe6d3.png)

**Comment by mkindahl** [comment] 2022-11-24 13:42
@Jimi9 From the explain output, it is possible to see that the real-time aggregates are taking a large part of the time. If you disable real-time aggregates, the queries will be on the materialized table only, so you will not get the most recent data, but the query will be fast. You can disable the real-time aggregates using the `materialized_only` parameter when [creating (or altering)](https://docs.timescale.com/timescaledb/latest/how-to-guides/continuous-aggregates/real-time-aggregates/) the continuous aggregate.

**Comment by Jimi9** [comment] 2022-11-24 14:23
Hi mkindahl, yes this answer the question about the slow query but the point is that I need the real-time aggregates because otherwise the materialized view would be no longer necessary.

Basically at the moment you cannot have high performance on real-time aggregate correct? Most likely because I have to analyze a lot of data in those two hours of bucket.

Thanks anyway for the support!!

**Comment by mkindahl** [comment] 2022-11-25 08:11
@Jimi9 Ah, IC.

Well, you can adapt the refresh period to get a smaller range for the real-time aggregate, meaning that there will be more that will be materialized by the continuous aggregate policy and less that the real-time aggregate will have to read. The real-time aggregate has a condition added to ensure that it only reads the data that is not in the materialization table.

Note that this is not only related to the bucket size of the continuous aggregate. You can have a continuous aggregate that materializes buckets in the 15-minute range and then combine them into larger buckets using a view on top of that. It would allow you to, for example, materialize everything except the last 15 minutes and still get 2-hour buckets.

We are also working on #4668, which allow you to combine continuous aggregates and materialize the data in multiple levels. You might be interested in that.

**Comment by mkindahl** [comment] 2022-11-25 08:15
Closing the issue since there are no explicit feature requests or issues to fix at this point, but feel free to open if you think that there is anything left to resolve.

**Closed by mkindahl** 2022-11-25 08:15 UTC
Labels: bug, question, continuous_aggregate

**Comment by tayler-king** [comment] 2023-01-25 14:10
@jbx1 were you able to ever solve this? Running into the exact same issue.

Query on the CAGG will be slow. If I drop the materialised view and recreate the CAGG the queries run just fine again.

My query plan explanations look similar to yours.

**Comment by jbx1** [comment] 2023-01-25 17:23
@tayler-king So, from what I discovered, a slow Continuous Aggregate can be caused by several things. 
The first one I would check:
1. In your query, how much of the data is actually already pre-aggregated, and how much of it is still raw. Timescaledb needs to join both sources together, so if a lot of data still haven't been aggregated (as specified by the `end_offset` and `schedule_interval`), it will be at least as slow as querying the raw data, plus the overheads to combine both together. This might explain why recreating the aggregate again speeds things up, because it would have aggregated more data than originally aggregated in the last scheduled refresh. 

I would also analyse the following:
2. Data cardinality in your Continuous Aggregate. If you are grouping by too many columns, you might get aggregates that are almost as big as the raw data itself, and slow things down. However, I would expect things to be the same even if the aggregate is recreated. 

3. Chunk size. If the chunk_time_interval is too small, it will need to join the results from several chunks, which tends to degrade performance a lot. According to the documentation, the continuous aggregate will use a chunk time interval 10 times the size of the raw hypertable (I don't know if this is configurable). This means that if you have 7 day chunks in your hypertable, your continuous aggregate will have chunks of 70 days, while if your raw table is in 1 hour chunks, the continuous aggregate will  have chunks 10 hour chunks. This can have quite an effect on the performance of the continuous aggregate. 

Good luck.

**Comment by tayler-king** [comment] 2023-01-25 17:28
@jbx1 Unfortunately neither of those apply to my case, but I appreciate the pointers.

I'm still running v2.7 on my development machine so I'll have to upgrade to one of the v2.9.x releases and see if the issue persists.

Funnily enough I haven't managed to replicate it since my original comment.

I've seen the same issue posted very few times on various forums so it seems like this might be quite an isolated issue.

**Comment by jbx1** [comment] 2023-01-25 17:57
@tayler-king As an experiment, when this problem happens, rather than dropping and recreating the continuous aggregate, try calling `refresh_continuous_aggregate` instead, and see if it speeds up. If it does, it would mean it has something to do with the delay in refreshing the continuous aggregate.

**Comment by tayler-king** [comment] 2023-01-25 18:22
@jbx1 Thank you, I'll keep that in mind.

**Comment by tayler-king** [comment] 2023-03-25 17:23
Just wanted to post an update regarding my situation. For legacy reasons I was storing the timestamp fields as unix timestamps (with milliseconds), requiring a custom millisecond fn to be implemented on the hyper tables.

Changing over to a native `TIMESTAMPTZ` has resolved my issue.
