### ISSUE TITLE
Cannot disable compression on distributed hypertable

### ISSUE THREAD

**Issue by phemmer** [timescale/timescaledb#2725] opened 2020-12-09 04:34 UTC
**Relevant system information:**
 - OS: Debian 9
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 12.4 (Debian 12.4-1.pgdg90+1)
 - TimescaleDB version (output of `\dx` in `psql`): timescaledb | 2.0.0-rc4
 - Installation method: apt from packagecloud.io

**Describe the bug**
Compression cannot be disabled on distributed hypertables.

**To Reproduce**
```
create table test (time timestamptz, i int);

select create_distributed_hypertable('test','time');

alter table test set (timescaledb.compress);

alter table test set (timescaledb.compress=false);
```

**Expected behavior**
```
ALTER TABLE
```

**Actual behavior**
```
ERROR:  compressed hypertable not found
DETAIL:  compression was enabled on "test", but its internal compressed hypertable could not be found.
```

**Comment by erimatnor** [comment] 2020-12-09 07:56
Duplicate of https://github.com/timescale/timescaledb/issues/2716 and should be fixed in https://github.com/timescale/timescaledb/pull/2719.

**Closed by erimatnor** 2020-12-09 07:56 UTC
Labels: Compression, multinode
