### ISSUE TITLE
drop_chunks stopped freeing disk space

### ISSUE THREAD

**Issue by netrounds-fredrik** [timescale/timescaledb#1842] opened 2020-04-22 09:18 UTC
**Relevant system information:**
 - OS: timescaledev/timescaledb-ha:pg11-ts1.6 docker image on Linux 4.14
 - PostgreSQL version (output of `postgres --version`): 11.7 (Debian 11.7-2.pgdg100+1)
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.1
 - Installation method: helm/docker

About 8 hours into a load test with an ingestion rate of 15,000 rows/s, the `drop_chunk` suddenly stopped freeing up disk space.

![image](https://user-images.githubusercontent.com/10723697/79962497-66014780-8488-11ea-9b36-2fe5ac242b09.png)

The chunks are marked as dropped in timescaledb_catalog.chunk
```
postgres=# select * from _timescaledb_catalog.chunk order by id;
 id | hypertable_id |      schema_name      |    table_name     | compressed_chunk_id | dropped 
----+---------------+-----------------------+-------------------+---------------------+---------
  1 |             1 | _timescaledb_internal | _hyper_1_1_chunk  |                     | t
  2 |             1 | _timescaledb_internal | _hyper_1_2_chunk  |                     | t
  3 |             2 | _timescaledb_internal | _hyper_2_3_chunk  |                     | f
  4 |             1 | _timescaledb_internal | _hyper_1_4_chunk  |                     | t
  5 |             1 | _timescaledb_internal | _hyper_1_5_chunk  |                     | t
  6 |             1 | _timescaledb_internal | _hyper_1_6_chunk  |                     | t
  7 |             1 | _timescaledb_internal | _hyper_1_7_chunk  |                     | t
  8 |             1 | _timescaledb_internal | _hyper_1_8_chunk  |                     | t
  9 |             1 | _timescaledb_internal | _hyper_1_9_chunk  |                     | t
 10 |             1 | _timescaledb_internal | _hyper_1_10_chunk |                     | t
 11 |             1 | _timescaledb_internal | _hyper_1_11_chunk |                     | t
 12 |             1 | _timescaledb_internal | _hyper_1_12_chunk |                     | t
 13 |             1 | _timescaledb_internal | _hyper_1_13_chunk |                     | t
 14 |             1 | _timescaledb_internal | _hyper_1_14_chunk |                     | t
 15 |             1 | _timescaledb_internal | _hyper_1_15_chunk |                     | t
 16 |             1 | _timescaledb_internal | _hyper_1_16_chunk |                     | t
 17 |             1 | _timescaledb_internal | _hyper_1_17_chunk |                     | t
 18 |             1 | _timescaledb_internal | _hyper_1_18_chunk |                     | t
 19 |             1 | _timescaledb_internal | _hyper_1_19_chunk |                     | t
 20 |             2 | _timescaledb_internal | _hyper_2_20_chunk |                     | f
 21 |             1 | _timescaledb_internal | _hyper_1_21_chunk |                     | t
 22 |             2 | _timescaledb_internal | _hyper_2_22_chunk |                     | f
 23 |             2 | _timescaledb_internal | _hyper_2_23_chunk |                     | f
 24 |             1 | _timescaledb_internal | _hyper_1_24_chunk |                     | t
 25 |             1 | _timescaledb_internal | _hyper_1_25_chunk |                     | f
 26 |             1 | _timescaledb_internal | _hyper_1_26_chunk |                     | f
 27 |             1 | _timescaledb_internal | _hyper_1_27_chunk |                     | f
 28 |             1 | _timescaledb_internal | _hyper_1_28_chunk |                     | f
 29 |             1 | _timescaledb_internal | _hyper_1_29_chunk |                     | f
 30 |             1 | _timescaledb_internal | _hyper_1_30_chunk |                     | f
 31 |             1 | _timescaledb_internal | _hyper_1_31_chunk |                     | f
 32 |             1 | _timescaledb_internal | _hyper_1_32_chunk |                     | f
 33 |             1 | _timescaledb_internal | _hyper_1_33_chunk |                     | f
 34 |             2 | _timescaledb_internal | _hyper_2_34_chunk |                     | f
 35 |             1 | _timescaledb_internal | _hyper_1_35_chunk |                     | f
 36 |             1 | _timescaledb_internal | _hyper_1_36_chunk |                     | f
 37 |             1 | _timescaledb_internal | _hyper_1_37_chunk |                     | f
(37 rows)
```

and chunk tables are removed accordingly
```
postgres=# \dt _timescaledb_internal.
                           List of relations
        Schema         |            Name            | Type  |  Owner   
-----------------------+----------------------------+-------+----------
 _timescaledb_internal | _hyper_1_25_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_26_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_27_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_28_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_29_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_30_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_31_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_32_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_33_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_35_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_36_chunk          | table | postgres
 _timescaledb_internal | _hyper_1_37_chunk          | table | postgres
 _timescaledb_internal | _hyper_2_20_chunk          | table | postgres
 _timescaledb_internal | _hyper_2_22_chunk          | table | postgres
 _timescaledb_internal | _hyper_2_23_chunk          | table | postgres
 _timescaledb_internal | _hyper_2_34_chunk          | table | postgres
 _timescaledb_internal | _hyper_2_3_chunk           | table | postgres
 _timescaledb_internal | _materialized_hypertable_2 | table | postgres
 _timescaledb_internal | bgw_job_stat               | table | postgres
 _timescaledb_internal | bgw_policy_chunk_stats     | table | postgres
(20 rows)
```

however, the calculated total size for the hypertable and the actual disk space used do not decrease.
```
postgres=# select * from timescaledb_information.hypertable;
     table_schema      |         table_name         | table_owner | num_dimensions | num_chunks | table_size | index_size | toast_size | total_size 
-----------------------+----------------------------+-------------+----------------+------------+------------+------------+------------+------------
 public                | metrics                    | postgres    |              1 |         32 | 93 GB      | 33 GB      |            | 125 GB
 _timescaledb_internal | _materialized_hypertable_2 | postgres    |              1 |          5 | 31 GB      | 3500 MB    | 40 kB      | 35 GB
(2 rows)
```

This might be related to https://github.com/timescale/timescaledb/issues/1772.

I will continue to investigate the logs to see if there are any clues to what happened.

Here are my output from `dump_meta_data.sql`:
```
TimescaleDB meta data dump
<exclude_from_test>
Date, git commit, and extension version can change without it being an error.
Adding this tag allows us to run regression tests on this script file.
Wed Apr 22 08:18:47 UTC 2020
Postgres version
                                                     version                                                      
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.7 (Debian 11.7-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)

Build tag
 get_git_commit 
----------------
 1.6.1
(1 row)

                                      List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 1.6.1   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)

</exclude_from_test>
List of tables
             List of relations
 Schema |     Name      | Type  |  Owner   
--------+---------------+-------+----------
 public | metrics       | table | postgres
 public | devices       | table | postgres
(2 rows)

List of hypertables
 id |      schema_name      |         table_name         | associated_schema_name | associated_table_prefix | num_dimensions | chunk_sizing_func_schema |  chunk_sizing_func_name  | chunk_target_size | compressed | compressed_hypertable_id 
----+-----------------------+----------------------------+------------------------+-------------------------+----------------+--------------------------+--------------------------+-------------------+------------+--------------------------
  1 | public                | metrics                    | _timescaledb_internal  | _hyper_1                |              1 | _timescaledb_internal    | calculate_chunk_interval |                 0 | f          |                         
  2 | _timescaledb_internal | _materialized_hypertable_2 | _timescaledb_internal  | _hyper_2                |              1 | _timescaledb_internal    | calculate_chunk_interval |                 0 | f          |                         
(2 rows)

List of chunk indexes
 chunk_id |                           index_name                            | hypertable_id |              hypertable_index_name              
----------+-----------------------------------------------------------------+---------------+-------------------------------------------------
       37 | _hyper_1_37_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       37 | _hyper_1_37_chunk_metrics_time_idx                              |             1 | metrics_time_idx
        3 | _hyper_2_3_chunk__materialized_hypertable_2_bucket_idx          |             2 | _materialized_hypertable_2_bucket_idx
        3 | _hyper_2_3_chunk__materialized_hypertable_2_device_id_bucket_id |             2 | _materialized_hypertable_2_device_id_bucket_idx
       20 | _hyper_2_20_chunk__materialized_hypertable_2_bucket_idx         |             2 | _materialized_hypertable_2_bucket_idx
       20 | _hyper_2_20_chunk__materialized_hypertable_2_device_id_bucket_i |             2 | _materialized_hypertable_2_device_id_bucket_idx
       22 | _hyper_2_22_chunk__materialized_hypertable_2_bucket_idx         |             2 | _materialized_hypertable_2_bucket_idx
       22 | _hyper_2_22_chunk__materialized_hypertable_2_device_id_bucket_i |             2 | _materialized_hypertable_2_device_id_bucket_idx
       23 | _hyper_2_23_chunk__materialized_hypertable_2_bucket_idx         |             2 | _materialized_hypertable_2_bucket_idx
       23 | _hyper_2_23_chunk__materialized_hypertable_2_device_id_bucket_i |             2 | _materialized_hypertable_2_device_id_bucket_idx
       24 | _hyper_1_24_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       24 | _hyper_1_24_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       25 | _hyper_1_25_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       25 | _hyper_1_25_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       26 | _hyper_1_26_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       26 | _hyper_1_26_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       27 | _hyper_1_27_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       27 | _hyper_1_27_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       28 | _hyper_1_28_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       28 | _hyper_1_28_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       29 | _hyper_1_29_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       29 | _hyper_1_29_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       30 | _hyper_1_30_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       30 | _hyper_1_30_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       31 | _hyper_1_31_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       31 | _hyper_1_31_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       32 | _hyper_1_32_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       32 | _hyper_1_32_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       33 | _hyper_1_33_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       33 | _hyper_1_33_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       34 | _hyper_2_34_chunk__materialized_hypertable_2_bucket_idx         |             2 | _materialized_hypertable_2_bucket_idx
       34 | _hyper_2_34_chunk__materialized_hypertable_2_device_id_bucket_i |             2 | _materialized_hypertable_2_device_id_bucket_idx
       35 | _hyper_1_35_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       35 | _hyper_1_35_chunk_metrics_time_idx                              |             1 | metrics_time_idx
       36 | _hyper_1_36_chunk_idx_metrics_device_id                         |             1 | idx_metrics_device_id
       36 | _hyper_1_36_chunk_metrics_time_idx                              |             1 | metrics_time_idx
(36 rows)

Size of hypertables
ERROR:  relation "_timescaledb_internal._hyper_1_21_chunk" does not exist
Chunk sizes:
ERROR:  relation "_timescaledb_internal._hyper_1_1_chunk" does not exist
Hypertable index sizes
                    hypertable                    |                              index_name                               | index_bytes 
--------------------------------------------------+-----------------------------------------------------------------------+-------------
 _timescaledb_internal._materialized_hypertable_2 | _timescaledb_internal._materialized_hypertable_2_bucket_idx           |  1516412928
 _timescaledb_internal._materialized_hypertable_2 | _timescaledb_internal._materialized_hypertable_2_device_id_bucket_idx |  2153259008
 public.metrics                                   | public.idx_metrics_device_id                                          | 16084377600
 public.metrics                                   | public.metrics_time_idx                                               | 19071524864
(4 rows)
```

**Comment by netrounds-fredrik** [comment] 2020-04-28 13:42
Unfortunately (or fortunately, depending on how you see it) I have not been able to reproduce the problem in later test runs, so this might not be very likely to happen.

I see that there has been work in refactoring the handling of dropped chunks in https://github.com/timescale/timescaledb/pull/1843. Do you think that the problems mentioned in that PR could have caused the observed behavior?

**Comment by erimatnor** [comment] 2020-04-29 08:03
@netrounds-fredrik I don't think the refactoring PR you mention (https://github.com/timescale/timescaledb/pull/1843) would explain it because it only affects metadata, which shouldn't account for a lot of diskspace. I think we need more information to know the real cause of this.

**Comment by netrounds-fredrik** [comment] 2020-04-29 10:50
OK, I will post any additional information that I can find if this happens again.

**Comment by onesvat** [comment] 2020-05-01 02:06
I have the exact problem. Even if I dropped the table, it still takes place on server.

**Comment by erimatnor** [comment] 2020-06-01 14:25
Did you try to run vacuum after deleting the data to free up disk space?

**Comment by netrounds-fredrik** [comment] 2020-09-03 20:51
I did not try to run a manual vacuum, however the automatic vacuum should have been running. I did not check that as far as I remember.

But as far as I understand, vacuum should not be needed to free disk space since it's simply dropping entire chunks/partitions.

**Comment by svenklemm** [comment] 2020-10-19 02:41
@netrounds-fredrik can you pinpoint the space usage to specific objects? can you check individual chunk space usage if there are weird outliers?
```
\dt+ _timescaledb_internal.*
\di+ _timescaledb_internal.*
```

**Comment by netrounds-fredrik** [comment] 2020-10-19 06:46
Unfortunately I no longer have a copy of the system where this happened. Maybe @onesvat can help since he saw something similar and says that he has a copy of his system in error state.

**Comment by bijwaard** [comment] 2020-12-10 12:19
Hi all,
I'm trying to use TimescaleDB on a single-board-computer (orangepizero with 4-core with 512MB memory) that does electrical measurements every second to see if this performs better than influxdb. I compiled from git repository and I tuned some postgresql settings to reduce disk/memory usage (see zipfile below). I created the hypertable with time as BIGINT and a chuck_time_interval of 5 microseconds.

The processing and internal memory usage of timescaledb apears approximately a factor 2 better than influxdb but disk storage is a big problem. While influxdb is using 15MB, postgresql is now using 400MB in /var/lib over the course of less than an hour. I ran the  dump_meta_data.sql script to see the hypertable usage, see [timescaledb-config+dump.zip](https://github.com/timescale/timescaledb/files/5672531/timescaledb-config%2Bdump.zip), and don't see any dropped chunks.

Here are the sizes from the dump:
 hypertable  | table_bytes | index_bytes | toast_bytes | total_bytes 
-------------+-------------+-------------+-------------+-------------
 phaselock   |     7569408 |    15138816 |     7569408 |    30277632
 rms_std     |     7561216 |    15122432 |     7561216 |    30244864
 harmonics   |     7512064 |    15024128 |     7512064 |    30048256
 current_rms |     7561216 |    15122432 |     7561216 |    30244864
 freq        |     7536640 |    15073280 |     7536640 |    30146560
 power       |     7471104 |    14942208 |     7471104 |    29884416
 phasor      |     7536640 |    15073280 |     7536640 |    30146560
(7 rows)

Chunk sizes:
Hypertable index sizes
     hypertable     |         index_name          | index_bytes 
--------------------+-----------------------------+-------------
 public.current_rms | public.current_rms_time_idx |    15515648
 public.freq        | public.freq_time_idx        |    15450112
 public.harmonics   | public.harmonics_time_idx   |    15400960
 public.phaselock   | public.phaselock_time_idx   |    15532032
 public.phasor      | public.phasor_time_idx      |    15450112
 public.power       | public.power_time_idx       |    15302656
 public.rms_std     | public.rms_std_time_idx     |    15499264

Before this experiment, I tried to vacuum the database after some measurements and it only grew bigger, above 1GB. Even when I dropped all my tables, the storage was still huge. So, for the experiment above I dropped the database and started fresh.

Kind regards,
Dennis

**Comment by bijwaard** [comment] 2020-12-11 07:56
Dear all,

After half a day, the database grew to 2.3GB, influxdb with the same measurement data is now 36M. I'm ditching the hypertable for now on my embedded device, and see if regular postgresql performs better.

$ sudo du /var/lib/|sort -n|tail -15
26844   /var/lib/influxdb/wal/_internal/monitor
26848   /var/lib/influxdb/wal/_internal
27484   /var/lib/dpkg/info
27564   /var/lib/influxdb/wal
29244   /var/lib/dpkg
36236   /var/lib/influxdb
49160   /var/lib/postgresql/11/main/pg_wal
114616  /var/lib/apt/lists
114660  /var/lib/apt
2223584 /var/lib/postgresql/11/main/base/302849
2247940 /var/lib/postgresql/11/main/base
2303624 /var/lib/postgresql/11/main
2303628 /var/lib/postgresql/11
2303640 /var/lib/postgresql
2487356 /var/lib/

Kind regards,
Dennis

**Comment by bijwaard** [comment] 2020-12-14 12:18
First results with postgresql without timescaledb look promising, I use double precision in seconds for the UTC timestamps and a Python script with psycopg2 to dump into database:
- postgres database
  - 165M diskspace over the weekend,  
  - 7.7 (main)+7.3% (checkpointer) +7.1% (background writer)=21.1% memory usage
  - 1.3% (database user) + 12.1% (Python script) CPU usage
- influxdb database
  - 33M diskspace over the weekend, 
  - 19.4% memory usage
  - 12.6-14.7% (influxd)+9.8% (Python script) CPU usage

Unsure at this point how to further reduce postgresql disk usage, maybe by using different datatype than numeric for the measurements. The combined memory usage seem similar to influxdb and processing performance is much better with influxdb.

**Comment by NunoFilipeSantos** [comment] 2021-10-01 11:38
@bijwaard can you please check against the latest version of Timescale 2.4.2?

**Comment by bijwaard** [comment] 2021-10-01 12:41
Hi Nuno,
I'm[ trying to install timescaledb again](https://docs.timescale.com/timescaledb/latest/how-to-guides/install-timescaledb/self-hosted/debian/installation-apt-debian/#installation-apt-debian), have since moved to debian bullseye on arm64, now the package doesn't want to install for some reason.
```
% sudo sh -c "echo 'deb [signed-by=/usr/share/keyrings/timescale.keyring] https://packagecloud.io/timescale/timescaledb/debian/ $(lsb_release -c -s) main' > /etc/apt/sources.list.d/timescaledb.list"
% wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/timescale.keyring
% sudo apt update

% cat /etc/apt/sources.list.d/timescaledb.list
deb [signed-by=/usr/share/keyrings/timescale.keyring] https://packagecloud.io/timescale/timescaledb/debian/ bullseye main
% sudo apt install  timescaledb-2-postgresql-13
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package timescaledb-2-postgresql-13
```
Kind regards,
Dennis

**Comment by NunoFilipeSantos** [comment] 2021-11-18 14:36
Hi @bijwaard! We're closing this issue. If you can reproduce it on TimescaleDB 2.5.0, feel free to reopen it.

**Closed by NunoFilipeSantos** 2021-11-18 14:36 UTC
Labels: bug, need-more-info, continuous_aggregate, 1.X
