### ISSUE TITLE
[Bug]: <Title> As RAM limitation, if chunk_time_interval 1 hour is okay please?

### ISSUE THREAD

**Issue by yinan8128** [timescale/timescaledb#5509] opened 2023-03-30 09:25 UTC
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Configuration

### What happened?

Hi guys

Now our production RAM is 8GB

As "We recommend setting the chunk_time_interval so that 25% of main memory can store one chunk" in the doc, we need to configure chunk_time_interval to 1 hour to meet it, is it okay please? If configure chunk_time_interval to 1 hour is okay, is there any notices to use other features please? Thanks
https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/about-hypertables/

Thank you

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

14.6

### What operating system did you use?

Centos 7

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

```bash
N.A
```

**Comment by konskov** [comment] 2023-03-30 10:07
hi @yinan8128, thank you for reaching out. 

Whether this value for `chunk_time_interval` is enough would of course depend on how much data you are going to store in one chunk. Regarding chunk size, you may find this blog post useful https://www.timescale.com/blog/timescale-cloud-tips-testing-your-chunk-size/ and the Timescale blog in general. However, as this doesn’t seem to be a bug report but rather a question regarding a specific usecase, I would also recommend asking about this in the community slack or forum which are better platforms for this type of questions and you will get more help there.

**Comment by konskov** [comment] 2023-03-30 10:12
I'll go ahead and close the issue as it's not a bug.

**Closed by konskov** 2023-03-30 10:12 UTC
Labels: question

**Comment by yinan8128** [comment] 2023-03-30 10:16
@konskov 
Thank you for your reply
Yes, we checked https://www.timescale.com/blog/timescale-cloud-tips-testing-your-chunk-size/
Just the samples are chunk by days, so just ask if chunk by hour is okay please?

**Comment by mkindahl** [comment] 2023-03-31 07:11
> @konskov Thank you for your reply Yes, we checked https://www.timescale.com/blog/timescale-cloud-tips-testing-your-chunk-size/ Just the samples are chunk by days, so just ask if chunk by hour is okay please? If has any limitation please?

It is perfectly OK to have a chunk size of 1 hour, but that also means that you will have a lot of chunks over time. With a lot of chunks, you might see an increase in planning time for queries.

**Comment by yinan8128** [comment] 2023-04-03 13:29
@mkindahl @konskov 

Thank you for your reply

We keep 1 month data, so there will be 30*24=720 chunks, is it okay to have 720 partitions please? Thank you

**Comment by mkindahl** [comment] 2023-04-04 06:54
> @mkindahl @konskov
> 
> Thank you for your reply
> 
> We keep 1 month data, so there will be 30*24=720 chunks, is it okay to have 720 chunks please? Thank you

There are no limitations in the software that prevents this, but with that many chunks you should check performance. Here is a simple test I did:

```sql
CREATE TABLE conditions(
    time TIMESTAMP NOT NULL,
    device_id INTEGER,
    temperature FLOAT,
    humidity FLOAT
);

CREATE TABLE devices (
  device_id SERIAL,
  building TEXT
);

SELECT * FROM create_hypertable('conditions', 'time', 'device_id', 12);

SELECT * FROM create_hypertable('conditions', 'time', chunk_time_interval => '1 hour'::interval);

INSERT INTO conditions
SELECT time, (random()*3 + 1)::int, random()*80 - 40, random()*100
FROM generate_series(now() - INTERVAL '2 months', now(), '1 minute') AS time;
```

With this, we have 1416 chunks: 

```sql
mats=# \d conditions
                         Table "public.conditions"
   Column    |            Type             | Collation | Nullable | Default 
-------------+-----------------------------+-----------+----------+---------
 time        | timestamp without time zone |           | not null | 
 device_id   | integer                     |           |          | 
 temperature | double precision            |           |          | 
 humidity    | double precision            |           |          | 
Indexes:
    "conditions_time_idx" btree ("time" DESC)
Triggers:
    ts_insert_blocker BEFORE INSERT ON conditions FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker()
Number of child tables: 1416 (Use \d+ to list them.)
```

Running an analyze on it gives the following. 

```sql
mats=# EXPLAIN ANALYZE SELECT * FROM conditions JOIN devices USING (device_id) WHERE building = 'One' AND time > now() - '1 day'::interval;
                                                                          QUERY PLAN                                                                           
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Join  (cost=33.85..2992.52 rows=112 width=60) (actual time=0.063..0.480 rows=265 loops=1)
   Hash Cond: (conditions.device_id = devices.device_id)
   ->  Custom Scan (ChunkAppend) on conditions  (cost=7.90..2951.41 rows=3745 width=28) (actual time=0.013..0.366 rows=1429 loops=1)
         Chunks excluded during startup: 1391
         ->  Seq Scan on _hyper_4_1480_chunk  (cost=0.00..2.05 rows=9 width=28) (actual time=0.012..0.014 rows=9 loops=1)
               Filter: ("time" > (now() - '1 day'::interval))
               Rows Removed by Filter: 51
         ->  Seq Scan on _hyper_4_1481_chunk  (cost=0.00..2.05 rows=60 width=28) (actual time=0.003..0.014 rows=60 loops=1)
               Filter: ("time" > (now() - '1 day'::interval))
                           .
                           .
                           .
         ->  Seq Scan on _hyper_4_1503_chunk  (cost=0.00..2.05 rows=60 width=28) (actual time=0.002..0.012 rows=60 loops=1)
               Filter: ("time" > (now() - '1 day'::interval))
         ->  Bitmap Heap Scan on _hyper_4_1504_chunk  (cost=7.90..26.35 rows=483 width=28) (actual time=0.008..0.010 rows=40 loops=1)
               Recheck Cond: ("time" > (now() - '1 day'::interval))
               Heap Blocks: exact=1
               ->  Bitmap Index Scan on _hyper_4_1504_chunk_conditions_time_idx  (cost=0.00..7.78 rows=483 width=0) (actual time=0.005..0.005 rows=40 loops=1)
                     Index Cond: ("time" > (now() - '1 day'::interval))
   ->  Hash  (cost=25.88..25.88 rows=6 width=36) (actual time=0.016..0.016 rows=1 loops=1)
         Buckets: 1024  Batches: 1  Memory Usage: 9kB
         ->  Seq Scan on devices  (cost=0.00..25.88 rows=6 width=36) (actual time=0.012..0.012 rows=1 loops=1)
               Filter: (building = 'One'::text)
               Rows Removed by Filter: 2
 Planning Time: 82.701 ms
 Execution Time: 7.921 ms
(65 rows)
```
