### ISSUE TITLE
time_bucket_gapfill issue with time zones

### ISSUE THREAD

**Issue by TorakikiITA** [timescale/timescaledb#2462] opened 2020-09-28 16:03 UTC
OS: Windows Server 2019, Version 1809
PostgreSQL version: 12.4
TimescaleDB version: 1.7.2
Installation method: Installer

**Functions "time_bucket" and "time_bucket_gapfill" don't seem to calculate the correct interval for time zones different than UTC.**

**Steps to reproduce the behavior:**

_1. Create the hypertable_
`CREATE TABLE conditions (
  time timestamptz not null,
  location text not null,
  temperature double precision not null
);`
`SELECT create_hypertable('conditions', 'time');`

_2. Insert samples_
`
INSERT INTO conditions (time, location, temperature)
values
('20200731 22:00', 'Rome', -2)
, ('20200731 23:00', 'Rome', -1)
, ('20200801 00:00', 'Rome', 1)
, ('20200801 01:00', 'Rome', 2)
, ('20200801 02:00', 'Rome', 3)
, ('20200801 03:00', 'Rome', 4)
, ('20200801 04:00', 'Rome', 5)
, ('20200801 05:00', 'Rome', 6)
, ('20200801 06:00', 'Rome', 7)
, ('20200801 07:00', 'Rome', 8)
, ('20200801 08:00', 'Rome', 9)
, ('20200801 09:00', 'Rome', 10)
, ('20200801 10:00', 'Rome', 11)
, ('20200801 11:00', 'Rome', 12)
, ('20200801 12:00', 'Rome', 13)
, ('20200801 13:00', 'Rome', 14)
, ('20200801 14:00', 'Rome', 15)
, ('20200801 15:00', 'Rome', 16)
, ('20200801 16:00', 'Rome', 17)
, ('20200801 17:00', 'Rome', 18)
, ('20200801 18:00', 'Rome', 19)
, ('20200801 19:00', 'Rome', 20)
, ('20200801 20:00', 'Rome', 21)
, ('20200801 21:00', 'Rome', 22)
, ('20200801 22:00', 'Rome', 23)
, ('20200801 23:00', 'Rome', 24)
, ('20200802 00:00', 'Rome', 25)
, ('20200802 01:00', 'Rome', 26)
, ('20200802 02:00', 'Rome', 27)
, ('20200802 03:00', 'Rome', 28);
`

_3. Calculate 1 day aggregates, without changing time zone (so we're working in UTC)_
`
SELECT
    time_bucket_gapfill('1 day', cond.time) as bucket
    , locf(avg(temperature), 0::double precision)
FROM
    conditions cond
WHERE
   cond.time >= '2020-08-01' and cond.time < '2020-09-01'
GROUP BY bucket;
`

_4. Change session time zone_
`
set session time zone 'Europe/Rome';
`

_5. Repeat the SELECT query in point n. 3._
I would expect 31 rows again, 1 for each August day, and each one referring to the 00:00:00+02 time.
Instead, we're getting 32 rows, included a 2020-07-31 row, which is not wanted by the time range of the WHERE clause. Furthermore, each time bucket starts at 02:00:00+02, and not at 00:00:00+02.

**Expected behavior:**
31 rows, one for each day, and each bucket starting at 00:00:00 of the session time zone. The average has to be calculated for the 00-24 day of the session timezone , and not for the UTC day.
1: 2020-08-01 **00**:00:00+02   **10.416** <--- this is the average between the start and end of the Europe/Rome day
etc.

**Actual behavior:**
32 rows:
1: 2020-07-31 **02**:00:00+02    **-1.5**:
This row is not requested by the query, as the WHERE clause is for time >= '2020-08-01'..

2: 2020-08-01 **02**:00:00+02    **12.5**
This row's bucket starts at 2 o'clock and ends at 2 o'clock of the next day (matching UTC's 00:00:00 - 00:00:00 day)

I guess Timescale makes a bit of a mess here, by always judging the start and finish dates to be in UTC timezone, and then eventually translating the result dates to the correct time zone.

**Comment by ryanbooz** [comment] 2020-09-28 20:54
@TorakikiITA - I had added some more information in the Slack chat.

Upon setting your preferred time zone, does this query give you what you expect?

```SQL
select time_bucket_gapfill('24 hours', cond.time::timestamp, '2020-08-01', '2020-09-01') as bucket,
locf(avg(temperature), 0::double precision) 
from conditions cond where cond.time >= '2020-08-01' and cond.time < '2020-09-01' GROUP BY bucket;
```

Notice the case to a `Timestamp` and the addition of the optional `Start` and `End` parameters.

**Comment by TorakikiITA** [comment] 2020-09-29 07:36
@ryanbooz : as I answered in Slack, results are still incorrect. What I'm expecting with Europe/Rome time zone is:
14.5 for 2020-08-01: the average of the values between 2020-08-01 02:00 UTC (included) and 2020-08-02 02:00 UTC (excluded).
27.5 for 2020-08-02: the average of the values between 2020-08-02 02:00 UTC (included) and 2020-08-03 02:00 UTC (excluded).

**Comment by svenklemm** [comment] 2020-10-13 13:11
time_bucket_gapfill calls time_bucket internally so this is more a time_bucket issue

**Comment by svenklemm** [comment] 2020-10-13 16:20
duplicate of #489

**Closed by svenklemm** 2020-10-13 16:20 UTC
