### ISSUE TITLE
Constraint aware append not getting called with some functions? 

### ISSUE THREAD

**Issue by gajus** [timescale/timescaledb#982] opened 2019-01-10 15:24 UTC
**Describe the bug**

```
EXPLAIN ANALYZE
SELECT
  aesqsc2.event_start_time
FROM aggregate_event_seating_quantitative_summary_change aesqsc2
WHERE
  aesqsc2.event_start_time BETWEEN
    '2018-06-04 10:15:00+00'::timestamptz + interval '1 hour' * nextval('materialize_aggregate') AND
    '2018-06-04 10:15:00+00'::timestamptz + interval '1 hour' * nextval('materialize_aggregate') AND
  aesqsc2.materialized_at IS NULL
LIMIT 100;

```

Explain: https://gist.github.com/gajus/0d324c902033262fdd27f20ebc928a77

```
EXPLAIN ANALYZE
SELECT
  aesqsc2.event_start_time
FROM aggregate_event_seating_quantitative_summary_change aesqsc2
WHERE
  aesqsc2.event_start_time BETWEEN
    '2018-06-04 10:15:00+00'::timestamptz + interval '1 hour' * 1 AND
    '2018-06-04 10:15:00+00'::timestamptz + interval '1 hour' * 2 AND
  aesqsc2.materialized_at IS NULL
LIMIT 100;

```

Explain: https://gist.github.com/gajus/8802ec6c7d55c4fc7fc7310f9d198245

**Expected behavior**

Using `nextval('materialize_aggregate')` in the WHERE conditional block advances the nextval on every check and ends up scanning all partitions.

**Actual behavior**

Should treat `nextval()` as static value after query binding initialisation.

**Comment by svenklemm** [comment] 2019-01-12 01:03
@gajus  Closing this since that is working as intended, that function is marked as volatile so postgres will call it every time.

**Comment by davidkohn88** [comment] 2019-01-13 22:11
Going to reopen this as I think the problem here is the lack of constraint aware append, not that it's not being called correctly? I don't know if that's correct though. It certainly doesn't change the value of nextval within the statement right? Or is it supposed to be calling it on every row it scans? that seems odd as that would clearly have different numbers of calls based on whether it chose an index scan or some other method, so I think it should be calling it in the where clause once per statement. Which should mean we can still use a constraint-aware append?

**Comment by davidkohn88** [comment] 2019-01-13 22:12
@svenklemm am I missing something here? or do we not do constraint aware append on volatile functions for some reason? is there a reason we wouldn't do that?

**Comment by svenklemm** [comment] 2019-01-14 09:10
For the example query constraint aware append would not help you. Volatile functions need to be evaluated every time and won't be optimized away. If you want nextval to only evaluate once in a query you can wrap it in a CTE.

**Comment by svenklemm** [comment] 2019-01-14 21:19
@gajus You can use something like the following to only evaluate nextval once:
```
sven=# with rnd AS (SELECT random()) SELECT * FROM foo,rnd;
             time              | device_id |      random
-------------------------------+-----------+-------------------
 2019-01-10 01:05:57.390034+01 |         1 | 0.236815015785396
 2000-01-01 00:00:00+01        |         1 | 0.236815015785396
 2000-02-01 00:00:00+01        |         1 | 0.236815015785396
 2000-03-01 00:00:00+01        |         1 | 0.236815015785396
 2000-04-01 00:00:00+02        |         1 | 0.236815015785396
```

**Closed** 2019-01-16 01:18 UTC
