### ISSUE TITLE
Unable to update hypertable columns

### ISSUE THREAD

**Issue by Kumar6295** [timescale/timescaledb#2540] opened 2020-10-13 07:45 UTC
CREATE TABLE test (
    time timestamptz NOT NULL,
    id character varying(50) NOT NULL,
    name text NOT NULL,
    value double precision
);

SELECT create_hypertable('test', 'time','id',16, chunk_time_interval => interval '1 day');

insert into test values('2020-10-04 00:00:00','1','TEST',100);
insert into test values('2020-10-04 01:00:00','2','VOLUME',100);
insert into test values('2020-10-04 02:59:00','1','TEST',100);
insert into test values('2020-10-04 23:50:00','2','VOLUME',100);

insert into test values('2020-10-05 00:00:00','1','TEST',100);
insert into test values('2020-10-05 01:00:00','2','VOLUME',100);
insert into test values('2020-10-05 02:59:00','1','TEST',100);
insert into test values('2020-10-05 23:50:00','2','VOLUME',100);

**when i try to update id column with new id, it showing below error.How to resolve it?**

**->update test set id='3' where id='1';**
**ERROR:  new row for relation "_hyper_1_1_chunk" violates check constraint "constraint_2"
DETAIL:  Failing row contains (2020-10-04 00:00:00+05:30, 3, TEST, 100).**

**Comment by erimatnor** [comment] 2020-10-13 08:49
@Kumar6295 we currently do not support updates to data that would move the data from one chunk (partition) to another.

Duplicate of this issue: #1052

**Comment by erimatnor** [comment] 2020-10-13 08:50
Closing since duplicate of #1052

**Comment by erimatnor** [comment] 2020-10-13 08:50
Closing since duplicate of #1052

**Closed by erimatnor** 2020-10-13 08:50 UTC
Labels: enhancement
