### ISSUE TITLE
Amazon RDS, GCP Cloud SQL, Azure, Heroku support?

### ISSUE THREAD

**Issue by jqnatividad** [timescale/timescaledb#65] opened 2017-05-26 18:08 UTC
RDS comes with pre-packaged extensions... are there any talks with AWS to include timescale in their supported extensions, given that timescaledb uses the Apache 2.0 license?

**Comment by stalltron** [comment] 2017-05-26 19:19
Hi Joel, thanks for this question. We're connected with the folks at RDS but it's most helpful if they receive outside requests: https://aws.amazon.com/rds/postgresql/faqs/

> Q: What are the extensions supported by RDS for PostgreSQL?
> You can check the list of supported extensions in the Amazon RDS User Guide. To request support for additional extensions, you can send an email to rds-postgres-extensions-request@amazon.com with the extension name and use case.

Would then be useful if you could let us know (privately) their feedback and we can reassess how to expedite the process of becoming an extension. Hope this helps.

**Comment by orlando** [comment] 2017-08-29 20:51
@mfreed do you know if there's an update about this?

**Comment by stalltron** [comment] 2017-09-06 13:34
Hi @orlando they haven't announced a timeline and some of it is out of our control. We'll provide updates as we have them.

**Comment by orlando** [comment] 2017-09-06 15:32
Thanks @stalltron, having that will be a huge win for timescaledb. Last week I tried it with metabase and works OTB (expected since is still postgres) but it was really good to have graphs from a time series database in less than 10 minutes

**Comment by misham** [comment] 2017-11-08 17:20
Is it possible to run TimescaleDB as a "frontend" on a separate machine that connects to an RDS instance?

**Comment by stalltron** [comment] 2017-11-17 01:38
@misham Interesting question.. We can be run on EC2, so the question then becomes can hosted offerings like RDS be run alongside self-managed EC2 instances? I'm not entirely sure, but will look into this...

**Comment by misham** [comment] 2017-11-17 01:54
If you're looking into using RDS as a slave and PG running as master on an EC2 instance, that doesn't work - at least I haven't been able to figure out how to make that work.

I was wondering if it's possible to make TimescaleDB run as a separate service that uses PG as a "backend" and then have the app talk only to TimescaleDB.

**Comment by stalltron** [comment] 2017-11-17 02:08
@misham Ah, ok. Can you share more about the use case you have in mind? I'm not sure I understand "uses PG as a backend," since data stored in TimescaleDB is effectively stored in PostgreSQL. Please email me (andrew@timescale.com) if there's stuff you can't share publicly.

**Comment by TalosThoren** [comment] 2017-12-04 16:23
This is exactly the use case I expect to.

So the idea is you have a clustered TimescaleDB service living in AWS, that's load balanced (I'm new to this and I'm just assuming this can be done) and that that clustered service is configured to point to an RDS endpoint for storage.

I'm a little surprised that this isn't something timescaleDB can't do today out of box. It seemed obvious to me that such a tool would be able to consume arbitrarily defined PostgreSQL backends for storage; is this not the case?

**Comment by orlando** [comment] 2017-12-04 17:04
@TalosThoren TimescaleDB is not a service that sits in front of a database, is a PostgreSQL extension you install. You can do it without problems since you are using EC2, but with managed services like RDS is not possible yet (they need to whitelist the extension first)

**Comment by TalosThoren** [comment] 2017-12-04 18:44
@orlando, that makes perfect sense and explains the limitations preventing this from being deployed in my expected use case. Thank you for clarifying.

**Comment by akulkarni** [comment] 2017-12-04 18:55
Thank you @orlando, that is correct.

@TalosThoren - If you'd like to expedite the AWS whitelisting process, please feel free to follow the instructions at the top of this issue.

Thanks!

**Comment by lambdaq** [comment] 2018-01-25 01:10
Might as well add Aliyun to that list.

They wrote multiple blogs but not supported in official  pg extensions.

https://yq.aliyun.com/articles/241194

https://yq.aliyun.com/articles/73537

**Comment by lambdaq** [comment] 2018-01-25 05:07
Update: I contacted Aliyun (AlibabaCloud) support via ticket system (https://workorder.console.aliyun.com), their response is 

> 以上您建议我们会评估分析一下关于功能需求，但是目前还没有得到评估计划、相关功能是否可以支持及确认支持时间。

Translation: We will evaluate this, but we dont have a plan or confirmation yet.

**Comment by lambdaq** [comment] 2018-01-26 04:59
@orlando 

>  TimescaleDB is not a service that sits in front of a database, is a PostgreSQL extension (ex. PostGIS) you install to add new capabilities to it (http://docs.timescale.com/latest/using-timescaledb/hypertables).

Let's think about this, it's ok to setup a pg isntance on ec2, however, the main problem is the extremely low IOPS. 

What if we can setup a pg master with timescale extension on ec2, but we don't write data to disk, use hosted RDS to do the heavy-lifting for persistency, and for actual read/writes. 

The master pg instance is only for query planing. 

Is this doable?

**Comment by mfreed** [comment] 2018-01-27 14:51
@lambdaq Thanks for reaching out to Aliyun and providing that data.  

I should also add that TimescaleDB currently supports Postgres version 9.6 and 10.  It looks like at least the version of the Aliyun PG instance you are using is 9.4 (which was released in late 2014), but we don't currently have any plans to backport to 9.4.

**Comment by mfreed** [comment] 2018-02-04 19:51
@lambdaq Regarding your postgres broker idea, is there a particular software codebase you are referring to?  Timescale can be utilized with remote storage via FDW, but also does run "inside" a Postgres database instance itself.

That said, I'm not sure I follow/agree with the assumption behind your question, which is that PG databases deployed on EC2 suffer from low IOPS.  This seems mostly due to the *type* of storage selected with EC2:  local SSD, remote SSD, remote HDD, provisioned vs. unprovisioned IOPS, etc.

We've certainly had no problems reaching steady-state traffic rates of 100K+ rows / second on these cloud VMs with the modest provisioning of network-attached SSD.

**Comment by rymoore** [comment] 2018-02-13 12:01
I've contacted AWS RDS multiple times via email to request TimeScale support... no response

**Comment by latortuga** [comment] 2018-04-20 14:01
I've sent requests to Heroku and AWS RDS, please if this is relevant to you, reach out! It takes 5 minutes!

**Comment by latortuga** [comment] 2018-04-28 00:50
There are lots of links up this issue thread.

**Comment by rawberg** [comment] 2018-05-12 04:40
It looks like [Aiven](https://aiven.io/blog/turn-aiven-postgresql-into-time-series-powerhouse-with-timescale/) recently added TimescaleDB support to their cloud managed Postgres option. Not affiliated and haven't tried them yet.

**Comment by craiggenner** [comment] 2018-07-20 22:17
I've raised a ticket with AWS support to request this, and I'll also email the Aurora Postgresql Product manager to follow this up and see what he says.

**Comment by craiggenner** [comment] 2018-07-21 19:59
I've had this response to my ticket

"To request support for additional extensions/plugins, you can send an email to rds-postgres-extensions-request@amazon.com with the extension/plugin name and use case. "

**Comment by Helmi** [comment] 2018-08-31 11:16
sent an email to that AWS account too without a response but that seems to be the way that works. Wonder how this topic hasn't come forward after over a year of "contact" with the AWS RDS team @stalltron @mfreed - are they declining to bring TimescaleDB on or is there just work to be done? Can you give any status update or outlook? Any chance to see timescaleDB on RDS anytime soon?

**Comment by craiggenner** [comment] 2018-09-02 08:42
I met with some members of the RDS team and it would appear its more likely they have so many core features they want to implement first.

But yes don't expect a reply to the email address.

**Comment by jwg2s** [comment] 2018-09-18 18:53
I've also emailed rds-postgres-extensions-request@amazon.com and will bring up with our AWS account rep - would love to see this get supported!

**Comment by ashwinpromethean** [comment] 2018-09-28 16:38
Yes, would like to see this as well. We are sticking to Postgres as of now for over a year (and come back to this page once a month), primarily because timescale isnt supported by RDS.

Hoping for the best.

**Comment by mmouterde** [comment] 2018-10-09 08:47
I met an AWS Account Manager yesterday and he adds us as customer reference to this feature requirement.
No more garanties but that should contribute.

**Comment by austinh** [comment] 2018-11-09 21:47
Any update on this? Would love to help in anyway I can to speed this along. I’ve created tickets at AWS and Heroku for this but no response

**Comment by Sach97** [comment] 2018-11-13 10:00
Digital Ocean has released [Managed Databases](https://try.digitalocean.com/dbaas-beta/). We might have a chance to see a positive response from them.

**Comment by walterwebb** [comment] 2018-11-15 15:40
Your article is very good very practical, I will collect up, hope [you can also pay attention](https://www.clickittech.com/) to my web site, thank you very much!

**Comment by pjebs** [comment] 2018-12-11 23:04
This is probably the reason why AWS isn't supporting this postgres extension for RDS: Amazon Timestream: https://aws.amazon.com/timestream/?hp=r

**Comment by alanhamlett** [comment] 2018-12-16 15:36
> This is probably the reason why AWS isn't supporting this postgres extension for RDS: Amazon Timestream

AWS has other competing products so I'm still hoping to see Timescale supported in RDS PG extensions.

**Comment by mehiel** [comment] 2019-01-21 21:34
AFAICT it simply means that they should pay TimescaleDB to provide their customers the extension in an "as a service" manner. 

That of course is a reasonable decision on TimescaleDB's side as they want to profit as well on that case BUT it will make integrations harder to happen as it'll cost all those service providers more and they'll have to pass the cost to the end customer at the end. On top of that, AWS especially is rumored to not actually play well with others. 

On the other hand there is a lot of discussion in the OSS community for that kind of licensing. Mongo's decision and actual license seems like it backfired in the end (?) (see 
https://www.theregister.co.uk/2019/01/17/red_hat_mongodb/)

It's interesting to see what's going to happen. It's important for all these data related businesses to find a way to profit because the won't survive otherwise (see Riak) and that's a problem for the community that wants to avoid vendor lock-in and trust some stable tech that will not extinguish in the next couple of years.

**Comment by mehiel** [comment] 2019-01-22 18:00
Thanks for the clarifications @mfreed. 

TimescaleDB's decision seems way more balanced and I think they'll be welcomed by both the community and the cloud providers. Time will tell. Keep it up!

**Comment by chickahoona** [comment] 2019-01-22 21:46
First of all I understand that people behind timescale want to make a living and the decision behind TSL and so on, yet afaik that is a deathshot for all dreams of getting Timescale on AWS / GCP / ...
No cloud provider will install it when by any chance a future version might

a) have an addon or whatever bundled with this TSL. It would open the doors for a potential lawsuit and is just not worth the trouble.

b) tomorrow you would decide that only your TSL version would support Postgres 10 (or any other restriction actually), then that would mean that they would not be able to upgrade to Postgres 10 or would have to get a shitstorm from all their customers.

You can argue whatever you like about "It wont happe" or "they can still use the apache 2.0" ...
It just does not matter to them. Also to have this discussion here now does not really matter anymore. The guys behind timescaledb for sure knew all of that when they made the decision and made it anyway, fully accepting this.

So if you want it, you have to host it yourself.

**Comment by windbender** [comment] 2019-01-23 19:13
Yo AWS RDS people, Azure is going to do it.  How about you ?

AZURE:  "
Unplanned → Planned

We’ve been working with TimescaleDB team to enable it in Azure Database for PostgreSQL service. We expect TimescaleDB extension to be available to customers of our service worldwide in 6-8 weeks from now.

Nik on behalf of the Azure Database for PostgreSQL team

  | Azure Database for PostgreSQL Product TeamAdmin, Microsoft Azure 
"

**Comment by mehiel** [comment] 2019-01-24 18:05
Citus acquisition then this ^. 
There is something happening for sure with MS :) Good news!

**Comment by austinh** [comment] 2019-01-24 20:35
They have timescaledb on aurora RDS?

**Comment by pjebs** [comment] 2019-01-24 21:21
@austinh It's supposedly a few weeks away. But I'll believe it when I see it.

**Comment by chanon** [comment] 2019-01-28 07:11
I would really love TimescaleDB to be available on Digital Ocean.

**Comment by JeroneGagliano** [comment] 2019-02-13 15:00
> Any update on this? Would love to help in anyway I can to speed this along. I’ve created tickets at AWS and Heroku for this but no response

I submitted a ticket request for timescale add-on to Heroku as well.

**Comment by pjebs** [comment] 2019-02-14 21:58
I think Digital Ocean will be more receptive from a business perspective. They just launched their managed service and it's a great opportunity to bring in new customers Immediately:https://blog.digitalocean.com/announcing-managed-databases-for-postgresql/

@akulkarni

**Comment by consense** [comment] 2019-02-14 22:01
@pjebs no need to be hopeful as it is already confirmed that the DigitalOcean Managed Database offering contains Timescale as plugin option by default in the status quo as of today.

**Comment by ehamberg** [comment] 2019-02-15 08:51
Live from [DigitalOcean's (limited availability) PostgreSQL offering](https://www.digitalocean.com/docs/databases/):

<img width="1119" alt="screenshot 2019-02-15 at 09 49 44" src="https://user-images.githubusercontent.com/16063/52845316-19dda900-3107-11e9-8490-7f54658546f1.png">

**Comment by edencorbin** [comment] 2019-02-27 05:50
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.FeatureSupport.Extensions.11x

Still not supported at AWS, anybody know when it might be? 

I also don't see it over at Azure:
https://docs.microsoft.com/en-us/azure/postgresql/concepts-extensions

Anything new on MS support?

**Comment by bremnes** [comment] 2019-02-27 08:20
@edencorbin, for Azure follow this [feedback issue](https://feedback.azure.com/forums/597976-azure-database-for-postgresql/suggestions/20055946-timescaledb-extension). They said 6-8 weeks January 23rd. So worst case - if they follow that timeline - we should see it by the end of March.

**Comment by SamWoolerton** [comment] 2019-03-18 21:02
Azure has shipped support!
https://azure.microsoft.com/en-us/blog/power-iot-and-time-series-workloads-with-timescaledb-for-azure-database-for-postgresql/

**Comment by mfreed** [comment] 2019-05-19 14:30
Alibaba has recently posted a bunch of tutorials on how to use TimescaleDB on their cloud:  https://www.alibabacloud.com/blog/postgresql-time-series-database-plug-in-timescaledb-deployment-practices_594814

**Comment by mfreed** [comment] 2019-05-19 14:31
Additionally, this perhaps goes without saying, but a managed version of TimescaleDB is now available on the Timescale Cloud on both AWS and Google Cloud.   It includes all enterprise capabilities and billed at an incremental hourly cost.

https://www.timescale.com/cloud-signup

**Comment by ryanrolds** [comment] 2019-07-01 05:33
Any updated ETA for TimescaleDB on AWS RDS?

**Comment by JeroneGagliano** [comment] 2019-07-01 13:49
I thought timescaleDB was already working on AWS RDS for postgres. There
are installation instructions on timescale's website for postgres 11.

**Comment by ryanrolds** [comment] 2019-07-01 13:53
Do you have a link? I don't see any for AWS RDS, just setting up a cluster outside of RDS.

**Comment by JeroneGagliano** [comment] 2019-07-01 14:10
Maybe I'm misunderstanding it, but these instructions AR for installing
postgres on and AWS AMI and then connecting it to your postgres database?
https://docs.timescale.com/v1.3/getting-started/installation/ami/installation-ubuntu-ami

I have a postgres database setup on RDS and I'm really hoping to use
timescale for my project as well.

**Comment by ryanrolds** [comment] 2019-07-01 14:14
Those instructions appear to be for setting up a PG instantace with Timescale DB on EC2 instances using pre-built images, not using RDS.

**Comment by JeroneGagliano** [comment] 2019-07-01 15:15
Oh, thank you for the clarification. That's a real bummer.

**Comment by dianasaur323** [comment] 2019-07-16 17:51
In case there is any confusion on this front, here's the current state of things as of the time I posted this (that I know of): 
AWS - No support
GCP - No support
Azure - TimescaleDB OSS only
Alibaba - TimescaleDB OSS only
Digital Ocean - TimescaleDB OSS only
Timescale Cloud - TimescaleDB Enterprise

**Comment by Drkstr** [comment] 2019-08-30 02:40
How would you go about connecting to a TimescaleDB running on an EC2 or Lightsail instance from a Lambda function?

**Comment by EralpB** [comment] 2019-09-18 07:37
I sent another request to `rds-postgres-extensions-request@amazon.com` is there anything you want us to include in the request?

**Comment by forzagreen** [comment] 2019-09-18 15:34
AWS are working on their managed timeseries database, [Timestream](https://aws.amazon.com/timestream/), that will be released probably in a few months.
So I don't expect them to accept any timeseries integration with RDS.

**Comment by alex88** [comment] 2019-09-30 16:48
> AWS are working on their managed timeseries database, [Timestream](https://aws.amazon.com/timestream/), that will be released probably in a few months.
> So I don't expect them to accept any timeseries integration with RDS.

earlier this year they've sent me an email when I've asked about timescaledb support saying:

> This is definitely on our 2019 roadmap for RDS Postgres 11

**Comment by throrin19** [comment] 2019-10-30 10:19
Any news about AWS support ?

**Comment by rskumar** [comment] 2019-11-05 22:27
Waiting for OSS version on AWS RDS 
### 🤓

**Comment by punnie** [comment] 2019-11-11 12:51
Regarding AWS, got the following reply after requesting Timescale support to the email address mentioned above:

> "L******, D****" <<l***@amazon.com>>
> This is on our roadmap for 2020.

So it seems that support from RDS was delayed a bit.

**Comment by solars** [comment] 2020-02-14 10:14
any news already?

**Comment by sairam** [comment] 2020-02-14 14:07
@solars, our team started to use https://www.timescale.com/cloud/ in AWS which we tunnel within the VPC. the self serve portal is simple and straight forward.

**Comment by Sytten** [comment] 2020-02-14 14:46
You can even terraform it using the [provider created by aiven](https://github.com/aiven/terraform-provider-aiven). It works great and the pricing is much on par with what RDS offers.

**Comment by throrin19** [comment] 2020-02-14 14:50
In my case I have a specific cloudformation using the latest timescaleDB AMI.

This cloudformation create : 

- 1 HAproxy server
- 1 etcd server
- 3 timescleDB servers with patroni to manage cluster and replication primary/secondary on down

**Comment by solars** [comment] 2020-02-19 13:07
Thanks for the pointers, we have our infrastructure on AWS (EC2 in Germany). The timescale cloud option seems nice, but if I compare costs right now it's much more expensive (we're at the lower side of the offers).

**Comment by sairam** [comment] 2020-02-19 17:18
@solars , one suggestion we got during our onboarding was a possibility to move the complete database infra to avian hosted timescaledb since they support regular database tables as well on the new server instance. 

Cheers,

**Comment by sytabaresa** [comment] 2020-04-14 03:55
Any update about this? :thinking:

**Comment by silentlight** [comment] 2020-04-19 17:53
It's really a bummer that you still cannot use TimescaleDB on RDS :(

**Comment by djrobby** [comment] 2020-05-04 18:09
> It's really a bummer that you still cannot use TimescaleDB on RDS :(

Most likely because such an extension causes direct conflict of interest with AWS’ own https://aws.amazon.com/timestream/

**Comment by kiwicopple** [comment] 2020-06-03 01:08
Not sure where to post this. It looks like this issue is the best fit.

We are discussing Timescale over at Supabase: https://github.com/supabase/postgres/issues/5#issuecomment-636893064
☝️ This repo packages Postgres with other useful extensions. It's unclear whether we can offer this based on the licensing terms. The main reason is that Supabase has a hosted platform ourselves. We only want to package extensions which our customers can use too. 

Is there anyone in the Timescale team that we can chat to about this? I see a number of benefits for Timescale - our images make it extremely easy to get started with Postgres and try out different extensions. We already have Docker, Digital Ocean, AWS, with more platforms on the way.

**Comment by benedictjohannes** [comment] 2020-06-12 16:31
> In case there is any confusion on this front, here's the current state of things as of the time I posted this (that I know of):
> AWS - No support
> GCP - No support
> Azure - TimescaleDB OSS only
> Alibaba - TimescaleDB OSS only
> Digital Ocean - TimescaleDB OSS only
> Timescale Cloud - TimescaleDB Enterprise

I was interested in using TimescaleDB in Alibaba Cloud, which is mentioned as available here. But I don't seem to find it in ApsaraDB PostgreSQL docs. It seems like the article mentioned by another is discussing how to use timescaleDB in a self-managed VM instead of managed PosgreSQL DB like the Apsara. Any thoughts?

**Comment by akulkarni** [comment] 2020-07-24 23:06
Hi @kiwicopple I just saw your comment. Could you email me at ajay (at) timescale.com?

**Comment by akulkarni** [comment] 2020-07-24 23:11
Hi all - Timescale Cloud is now available on AWS, GCP, and Azure in over 75 regions: https://www.timescale.com/cloud

It is the only hosted service where you can get the full TimescaleDB experience: native compression, continuous aggregations, data retention policies, etc. These features aren't available on other hosted services. So even if AWS were to offer TimescaleDB, you wouldn't be getting the key TimescaleDB features.

In particular, most of our users with compression are seeing over 96% storage savings, which often can make Timescale Cloud cheaper than the equivalent on RDS (and others). 

Hope this helps!

**Comment by benedictjohannes** [comment] 2020-07-30 17:58
@akulkarni I really appreciate the hard work that has been put in building this awesome product. I'm inclined on the hosted / managed TimescaleDB service, but one concern is holding me back.
My use case would be a small sized infrequent-insert very-frequent-access IoT sensor reading. For this, I would rather have a low CPU count, small storage but large RAM (due to almost all FLOAT columns). I can imagine other use cases like web scrapping data warehouse that can produce very large (TEXT) data per row that would need large storage (but not large RAM).

Please correct me if I'm wrong: When I'd like to launch hosted TimescaleDB solution, I found that the configuration offered when I see the pricing page is rather limited, and it restrict my option that (I reckon) can result in more deployment cost saving, thus using hosted TimescaleDB might (probably) result in unnecessary cost due to unnecessary resource provisioning.

If full machine type flexibility can be added, it would practically wipe _this_ concern away.

**Comment by akulkarni** [comment] 2020-08-10 22:51
Hi @benedictjohannes - sorry for the delayed response. 

Given your concern for more fine-tuned provisioning, have you considered Timescale Forge? https://www.timescale.com/forge

We recently launched Forge as a second hosted service to complement Timescale Cloud. It allows you to independently scale compute/storage (among other advanced features). (However, unlike Timescale Cloud, it does not let you choose which cloud/region to operate in.)

Let me know if that can do the job. Cheers!

**Comment by akulkarni** [comment] 2020-08-11 04:09
@benedictjohannes Forgot to add: We get great compression for floats, which will also reduce your resource requirements: https://docs.timescale.com/latest/using-timescaledb/compression

**Comment by benedictjohannes** [comment] 2020-08-13 10:17
@akulkarni I've looked on Timescale Forge link. It certainly looks promising, I'll have a closer look. But it would be even better if the cloud service is more flexible. 
Or, maybe timescale can be offered directly as service through the cloud platform (GCP marketplase in my case), maybe like  how Redhat offers RHEL?

**Comment by mkindahl** [comment] 2021-04-27 09:48
Closing this issue since it is not related to the TimescaleDB extension. This issue is added to the internal Forge backlog, which means that it is taken into consideration by the Forge team and might be implemented some time in the future.

**Closed by mkindahl** 2021-04-27 09:48 UTC
Labels: enhancement, feedback-wanted, question

**Comment by douglasg14b** [comment] 2023-12-12 22:06
This issue is old enough to be in kindergarden, is there any news on RDS support or similar?

**Comment by willfarrell** [comment] 2023-12-13 00:35
Not supported on RDS at this time. I mention it to my account manager every chance I can. If everyone does the same, it will happen one day.

**Comment by shayneoneill** [comment] 2025-07-11 04:04
Just checked. Still not an option. We've mentioned it to AWS. (We're quite happy using Timescale, but its nice to have a backup plan if that all-too-common occurence of hosted database-providers collapsing happens, god forbid, its a rough industry.
