### ISSUE TITLE
1.7 rpm package for centos 8

### ISSUE THREAD

**Issue by zdm** [timescale/timescaledb#1845] opened 2020-04-22 20:18 UTC
Hi.
Thank you for release 1.7,
Does mentioned package exists somewhere?

**Comment by svenklemm** [comment] 2020-10-14 08:06
Should be available through the usual channels: https://docs.timescale.com/latest/getting-started/installation/rhel-centos/installation-yum

**Comment by svenklemm** [comment] 2020-10-14 08:07
Closing since this should be fixed. Feel free to reopen if the issue is still relevant.

**Closed by svenklemm** 2020-10-14 08:07 UTC
Labels: question
