### ISSUE TITLE
[Bug]: Planner fails to leverage Chunk partitioning index along VIEW that contains LAG expression

### ISSUE THREAD

**Issue by cdu-genedis** [timescale/timescaledb#6595] opened 2024-02-02 09:11 UTC
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Query planner

### What happened?

When `SELECT`-ing using a `LAG` expression directly into an Hypertable, indexes are leveraged as expected, in particular the one that select the Chunks to span.

When creating a `VIEW` that is absolulety **identical** to that `SELECT` statement, the planner suddenly looses its footing and fails to leverage the same index, in particular in respect with choosing the Chunks to span.

### TimescaleDB version affected

2.13.1

### PostgreSQL version used

16.1

### What operating system did you use?

Docker (timescale/timescaledb-ha:pg16.1-ts2.13.1)

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

[if demanded, I'll try to compile a fully-reproducible test case]

When taping directly into an Hypertable, indexes are leveraged as expected,
in particular the one that select the Chunks to span:

```sql
EXPLAIN ANALYZE
SELECT
    dateheure,
    compteur, extension,
    CASE WHEN delta THEN NULL ELSE valeur END AS valeur,
    CASE WHEN delta THEN
        valeur
    ELSE
        LAG(valeur) OVER (
            PARTITION BY
                source, compteur, extension,
                fluide, grandeur, variante, unite
            ORDER BY
                dateheure DESC
        ) - valeur
    END AS valeur_delta,
    delta
FROM
    communityMultifluidesReleve
WHERE
    compteur = 'CHAUD0000'
    AND extension = '0000'
    AND dateheure >= '2024-01-01T00:00:00+01'
    AND dateheure < '2024-02-01T00:00:00+01'
;
```

```text
 WindowAgg  (cost=34.47..35.48 rows=27 width=88) (actual time=0.264..0.303 rows=31 loops=1)
   ->  Sort  (cost=34.47..34.54 rows=27 width=80) (actual time=0.253..0.256 rows=31 loops=1)
         Sort Key: _hyper_1_38_chunk.source, _hyper_1_38_chunk.fluide, _hyper_1_38_chunk.grandeur, _hyper_1_38_chunk.variante, _hyper_1_38_chunk.unite, _hyper_1_38_chunk.dateheure DESC
         Sort Method: quicksort  Memory: 27kB
         ->  Result  (cost=0.43..33.83 rows=27 width=80) (actual time=0.036..0.158 rows=31 loops=1)
               ->  Append  (cost=0.43..33.56 rows=27 width=79) (actual time=0.035..0.151 rows=31 loops=1)
                     ->  Index Scan using _hyper_1_38_chunk_communitymultifluidesreleve_compteur on _hyper_1_38_chunk  (cost=0.43..18.40 rows=15 width=80) (actual time=0.034..0.084 rows=18 loops=1)
                           Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text) AND (dateheure >= '2023-12-31 23:00:00+00'::timestamp with time zone) AND (dateheure < '2024-01-31 23:00:00+00'::timestamp with time zone))
                     ->  Index Scan using _hyper_1_39_chunk_communitymultifluidesreleve_compteur on _hyper_1_39_chunk  (cost=0.42..15.02 rows=12 width=78) (actual time=0.018..0.063 rows=13 loops=1)
                           Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text) AND (dateheure >= '2023-12-31 23:00:00+00'::timestamp with time zone) AND (dateheure < '2024-01-31 23:00:00+00'::timestamp with time zone))
 Planning Time: 0.816 ms
 Execution Time: 0.359 ms
```

When creating a `VIEW` that is absolulety **identical** to that `SELECT` statement,
the planner suddenly looses its footing and fails to leverage the same indexes,
in particular in respect with choosing the Chunks to span:

 ```sql
CREATE OR REPLACE VIEW
    communityMultifluidesReleve_delta
AS
SELECT
    dateheure,
    compteur, extension,
    CASE WHEN delta THEN NULL ELSE valeur END AS valeur,
    CASE WHEN delta THEN
        valeur
    ELSE
        LAG(valeur) OVER (
            PARTITION BY
                source, compteur, extension,
                fluide, grandeur, variante, unite
            ORDER BY
                dateheure DESC
        ) - valeur
    END AS valeur_delta,
    delta
FROM
    communityMultifluidesReleve
;

EXPLAIN ANALYZE
SELECT
    *
FROM
    communityMultifluidesReleve_delta
WHERE
    compteur = 'CHAUD0000'
    AND extension = '0000'
    AND dateheure >= '2024-01-01T00:00:00+01'
    AND dateheure < '2024-02-01T00:00:00+01'
;
```

```text
 Subquery Scan on communitymultifluidesreleve_delta  (cost=60363.58..62155.35 rows=1 width=87) (actual time=277.225..278.556 rows=31 loops=1)
   Filter: ((communitymultifluidesreleve_delta.dateheure >= '2023-12-31 23:00:00+00'::timestamp with time zone) AND (communitymultifluidesreleve_delta.dateheure < '2024-01-31 23:00:00+00'::timestamp with time zone))
   Rows Removed by Filter: 1098
   ->  WindowAgg  (cost=60363.58..61643.41 rows=34129 width=87) (actual time=277.223..278.456 rows=1129 loops=1)
         ->  Sort  (cost=60363.58..60448.90 rows=34129 width=80) (actual time=277.200..277.309 rows=1129 loops=1)
               Sort Key: _hyper_1_1_chunk.source, _hyper_1_1_chunk.fluide, _hyper_1_1_chunk.grandeur, _hyper_1_1_chunk.variante, _hyper_1_1_chunk.unite, _hyper_1_1_chunk.dateheure DESC
               Sort Method: quicksort  Memory: 163kB
               ->  Append  (cost=1690.33..57793.88 rows=34129 width=80) (actual time=0.049..272.416 rows=1129 loops=1)
                     ->  Custom Scan (DecompressChunk) on _hyper_1_1_chunk  (cost=1690.33..1690.33 rows=1000 width=81) (actual time=0.048..5.993 rows=3 loops=1)
                           ->  Index Scan using compress_hyper_56_137_chunk__compressed_hypertable_56_source_co on compress_hyper_56_137_chunk  (cost=0.42..1690.33 rows=1 width=211) (actual time=0.023..5.964 rows=1 loops=1)
                                 Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text))
                     ->  Custom Scan (DecompressChunk) on _hyper_1_2_chunk  (cost=1690.33..1690.33 rows=1000 width=81) (actual time=0.081..6.752 rows=30 loops=1)
                           ->  Index Scan using compress_hyper_56_138_chunk__compressed_hypertable_56_source_co on compress_hyper_56_138_chunk  (cost=0.42..1690.33 rows=1 width=211) (actual time=0.034..6.697 rows=1 loops=1)
                                 Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text))
[[ ... 30 identical Custom Scan entries redacted out ... ]]
                     ->  Custom Scan (DecompressChunk) on _hyper_1_33_chunk  (cost=1690.33..1690.33 rows=1000 width=81) (actual time=0.119..7.
                     083 rows=30 loops=1)
                           ->  Index Scan using compress_hyper_56_169_chunk__compressed_hypertable_56_source_co on compress_hyper_56_169_chunk  (cost=0.42..1690.33 rows=1 width=211) (actual time=0.066..7.022 rows=1 loops=1)
                                 Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text))
                     ->  Custom Scan (DecompressChunk) on _hyper_1_34_chunk  (cost=1690.33..1690.33 rows=1000 width=81) (actual time=0.105..6.849 rows=30 loops=1)
                           ->  Index Scan using compress_hyper_56_170_chunk__compressed_hypertable_56_source_co on compress_hyper_56_170_chunk  (cost=0.42..1690.33 rows=1 width=211) (actual time=0.054..6.790 rows=1 loops=1)
                                 Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text))
                     ->  Index Scan using _hyper_1_35_chunk_communitymultifluidesreleve_compteur on _hyper_1_35_chunk  (cost=0.43..34.01 rows=29 width=81) (actual time=0.065..0.559 rows=30 loops=1)
                           Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text))
                     ->  Index Scan using _hyper_1_36_chunk_communitymultifluidesreleve_compteur on _hyper_1_36_chunk  (cost=0.43..38.48 rows=33 width=79) (actual time=0.037..0.431 rows=31 loops=1)
                           Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text))
                     ->  Index Scan using _hyper_1_37_chunk_communitymultifluidesreleve_compteur on _hyper_1_37_chunk  (cost=0.43..34.00 rows=29 width=79) (actual time=0.030..0.344 rows=30 loops=1)
                           Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text))
                     ->  Index Scan using _hyper_1_38_chunk_communitymultifluidesreleve_compteur on _hyper_1_38_chunk  (cost=0.43..30.64 rows=26 width=81) (actual time=0.034..0.203 rows=30 loops=1)
                           Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text))
                     ->  Index Scan using _hyper_1_39_chunk_communitymultifluidesreleve_compteur on _hyper_1_39_chunk  (cost=0.42..14.96 rows=12 width=79) (actual time=0.025..0.054 rows=13 loops=1)
                           Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text))
 Planning Time: 7.886 ms
 Execution Time: 279.128 ms
```

I narrowed the issue down to the presence of the `LAG` expression; removing it
allows to recover the expected behavior:

```sql
CREATE OR REPLACE VIEW
    communityMultifluidesReleve_test
AS
SELECT
    dateheure,
    compteur, extension,
    CASE WHEN delta THEN NULL ELSE valeur END AS valeur,
    CASE WHEN delta THEN
        valeur
    ELSE
        NULL
    END AS valeur_delta,
    delta
FROM
    communityMultifluidesReleve
;

EXPLAIN ANALYZE
SELECT
    *
FROM
    communityMultifluidesReleve_test
WHERE
    compteur = 'CHAUD0000'
    AND extension = '0000'
    AND dateheure >= '2024-01-01T00:00:00+01'
    AND dateheure < '2024-02-01T00:00:00+01'
;
```

```text
 Result  (cost=0.43..33.83 rows=27 width=39) (actual time=0.023..0.100 rows=31 loops=1)
   ->  Append  (cost=0.43..33.56 rows=27 width=31) (actual time=0.021..0.093 rows=31 loops=1)
         ->  Index Scan using _hyper_1_38_chunk_communitymultifluidesreleve_compteur on _hyper_1_38_chunk  (cost=0.43..18.40 rows=15 width=31) (actual time=0.020..0.053 rows=18 loops=1)
               Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text) AND (dateheure >= '2023-12-31 23:00:00+00'::timestamp with time zone) AND (dateheure < '2024-01-31 23:00:00+00'::timestamp with time zone))
         ->  Index Scan using _hyper_1_39_chunk_communitymultifluidesreleve_compteur on _hyper_1_39_chunk  (cost=0.42..15.02 rows=12 width=30) (actual time=0.015..0.036 rows=13 loops=1)
               Index Cond: (((compteur)::text = 'CHAUD0000'::text) AND ((extension)::text = '0000'::text) AND (dateheure >= '2023-12-31 23:00:00+00'::timestamp with time zone) AND (dateheure < '2024-01-31 23:00:00+00'::timestamp with time zone))
 Planning Time: 0.455 ms
 Execution Time: 0.136 ms
 ```

Is this something to do with how TimescaleDB affects the planner (and can it be fixed) ?
```

**Comment by fabriziomello** [comment] 2024-02-02 19:03
@cdu-genedis thanks for reaching out. Can u please send the complete reproducible SQL script with hypertable definition and data if necessary??

**Comment by cdu-genedis** [comment] 2024-02-05 08:36
@fabriziomello Please see blow bash script:

```bash
#!/bin/bash
set -e -o pipefail
# AS 'postgres' user

# Database
createdb bug6595

# Schema
psql -f - bug6595 <<EOF
CREATE TABLE IF NOT EXISTS communityMultifluidesReleve (
    dateheure TIMESTAMPTZ NOT NULL,
    source VARCHAR(32) NOT NULL,
    compteur VARCHAR(16) NOT NULL,
    extension VARCHAR(8),
    fluide VARCHAR(8) NOT NULL,
    grandeur VARCHAR(2) NOT NULL,
    variante VARCHAR(4),
    unite VARCHAR(8) NOT NULL,
    valeur DOUBLE PRECISION NOT NULL,
    delta BOOLEAN NOT NULL,
    brute BOOLEAN NOT NULL DEFAULT FALSE,
    _unite VARCHAR(8),
    _valeur DOUBLE PRECISION,
    _delta BOOLEAN
)
;

SELECT create_hypertable(
    'communityMultifluidesReleve',
    by_range('dateheure', '1 month'::INTERVAL),
    if_not_exists => TRUE
)
;

CREATE UNIQUE INDEX IF NOT EXISTS communityMultifluidesReleve_unique
ON communityMultifluidesReleve(
    dateheure DESC, source, compteur, extension, fluide, grandeur, variante
)
NULLS NOT DISTINCT
;

CREATE INDEX IF NOT EXISTS communityMultifluidesReleve_source
ON communityMultifluidesReleve(
    source, dateheure DESC
)
;

CREATE INDEX IF NOT EXISTS communityMultifluidesReleve_compteur
ON communityMultifluidesReleve(
    compteur, extension, dateheure DESC
)
NULLS NOT DISTINCT
;

CREATE OR REPLACE VIEW
    communityMultifluidesReleve_delta
AS SELECT
    dateheure,
    source, compteur, extension,
    fluide, grandeur, variante, unite,
    CASE WHEN delta THEN NULL ELSE valeur END AS valeur,
    CASE WHEN delta THEN
        valeur
    ELSE
        LAG(valeur) OVER (
            PARTITION BY
                source, compteur, extension,
                fluide, grandeur, variante, unite
            ORDER BY
                dateheure DESC
        ) - valeur
    END AS valeur_delta,
    delta,
    brute
FROM
    communityMultifluidesReleve
;
EOF

# Data
start="$(date -d '2021-01-01' +'%s')"
stop="$(date -d '2024-02-01' +'%s')"
ts="${start}"
while true; do
    if [ "${ts}" -ge "${stop}" ]; then
        break
    fi
    psql -f - bug6595 <<EOF
INSERT INTO communityMultifluidesReleve (
    dateheure,
    source, compteur, extension,
    fluide, grandeur, variante, unite,
    valeur, delta, brute
) VALUES (
    '$(date -d "@${ts}" -u -Iseconds)',
    'BUG6595', 'COMPTEUR', NULL,
    'ELEC', 'E', NULL, 'kWh',
    $(( ts / 1000 )).$(( ts % 1000 )), FALSE, TRUE
)
;
EOF
    ts="$((ts + 86400 ))"
done
[ "$(psql -qtAc 'SELECT COUNT(*) FROM communityMultifluidesReleve' bug6595)" == '1126' ]

# Explain analyze (<-> bug)
psql -f - bug6595 <<EOF
EXPLAIN ANALYZE
SELECT
    *
FROM
    communityMultifluidesReleve_delta
WHERE
    dateheure >= '2024-01-01'
    AND dateheure < '2024-02-01'
;

EXPLAIN ANALYZE
SELECT
    dateheure,
    source, compteur, extension,
    fluide, grandeur, variante, unite,
    CASE WHEN delta THEN NULL ELSE valeur END AS valeur,
    CASE WHEN delta THEN
        valeur
    ELSE
        LAG(valeur) OVER (
            PARTITION BY
                source, compteur, extension,
                fluide, grandeur, variante, unite
            ORDER BY
                dateheure DESC
        ) - valeur
    END AS valeur_delta,
    delta,
    brute
FROM
    communityMultifluidesReleve
WHERE
    dateheure >= '2024-01-01'
    AND dateheure < '2024-02-01'
;
EOF
```

Which `EXPLAIN ANALYZE` outputs are:

```text
                                                                                                                   QUERY PLAN

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Subquery Scan on communitymultifluidesreleve_delta  (cost=1113.47..1584.40 rows=45 width=292) (actual time=8.169..9.444 rows=30 loops=1)
   Filter: ((communitymultifluidesreleve_delta.dateheure >= '2024-01-01 00:00:00+00'::timestamp with time zone) AND (communitymultifluidesreleve_delta.dateheure < '2024-02-01 00:00:00+00'::timestamp with time zone))
   Rows Removed by Filter: 1096
   ->  WindowAgg  (cost=1113.47..1449.85 rows=8970 width=292) (actual time=8.167..9.355 rows=1126 loops=1)
         ->  Sort  (cost=1113.47..1135.90 rows=8970 width=284) (actual time=8.141..8.216 rows=1126 loops=1)
               Sort Key: _hyper_1_1_chunk.source, _hyper_1_1_chunk.compteur, _hyper_1_1_chunk.extension, _hyper_1_1_chunk.fluide, _hyper_1_1_chunk.grandeur, _hyper_1_1_chunk.variante, _hyper_1_1_chunk.unite, _hyper_1_1_chunk.dateheure DESC
               Sort Method: quicksort  Memory: 145kB
               ->  Append  (cost=0.00..524.55 rows=8970 width=284) (actual time=0.013..0.856 rows=1126 loops=1)
                     ->  Seq Scan on _hyper_1_1_chunk  (cost=0.00..12.30 rows=230 width=284) (actual time=0.012..0.014 rows=3 loops=1)
                     ->  Seq Scan on _hyper_1_2_chunk  (cost=0.00..12.30 rows=230 width=284) (actual time=0.014..0.021 rows=30 loops=1)
                     ->  Seq Scan on _hyper_1_3_chunk  (cost=0.00..12.30 rows=230 width=284) (actual time=0.016..0.023 rows=30 loops=1)
[[ ... 30 Seq Scan lines redacted out ... ]]
                     ->  Seq Scan on _hyper_1_34_chunk  (cost=0.00..12.30 rows=230 width=284) (actual time=0.010..0.017 rows=30 loops=1)
                     ->  Seq Scan on _hyper_1_35_chunk  (cost=0.00..12.30 rows=230 width=284) (actual time=0.006..0.013 rows=30 loops=1)
                     ->  Seq Scan on _hyper_1_36_chunk  (cost=0.00..12.30 rows=230 width=284) (actual time=0.011..0.017 rows=30 loops=1)
                     ->  Seq Scan on _hyper_1_37_chunk  (cost=0.00..12.30 rows=230 width=284) (actual time=0.018..0.025 rows=30 loops=1)
                     ->  Seq Scan on _hyper_1_38_chunk  (cost=0.00..12.30 rows=230 width=284) (actual time=0.006..0.012 rows=30 loops=1)
                     ->  Seq Scan on _hyper_1_39_chunk  (cost=0.00..12.30 rows=230 width=284) (actual time=0.005..0.008 rows=13 loops=1)
 Planning Time: 15.402 ms
 Execution Time: 9.945 ms
(49 rows)

                                                                                                                    QUERY PLAN

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 WindowAgg  (cost=4.75..4.82 rows=2 width=292) (actual time=0.134..0.167 rows=30 loops=1)
   ->  Sort  (cost=4.75..4.75 rows=2 width=284) (actual time=0.123..0.125 rows=30 loops=1)
         Sort Key: _hyper_1_38_chunk.source, _hyper_1_38_chunk.compteur, _hyper_1_38_chunk.extension, _hyper_1_38_chunk.fluide, _hyper_1_38_chunk.grandeur, _hyper_1_38_chunk.variante, _hyper_1_38_chunk.unite, _hyper_1_38_chunk.dateheure DESC
         Sort Method: quicksort  Memory: 27kB
         ->  Append  (cost=0.14..4.74 rows=2 width=284) (actual time=0.010..0.035 rows=30 loops=1)
               ->  Index Scan using _hyper_1_38_chunk_communitymultifluidesreleve_unique on _hyper_1_38_chunk  (cost=0.14..2.36 rows=1 width=284) (actual time=0.009..0.016 rows=17 loops=1)
                     Index Cond: ((dateheure >= '2024-01-01 00:00:00+00'::timestamp with time zone) AND (dateheure < '2024-02-01 00:00:00+00'::timestamp with time zone))
               ->  Index Scan using _hyper_1_39_chunk_communitymultifluidesreleve_unique on _hyper_1_39_chunk  (cost=0.14..2.36 rows=1 width=284) (actual time=0.012..0.016 rows=13 loops=1)
                     Index Cond: ((dateheure >= '2024-01-01 00:00:00+00'::timestamp with time zone) AND (dateheure < '2024-02-01 00:00:00+00'::timestamp with time zone))
 Planning Time: 0.650 ms
 Execution Time: 0.209 ms
(11 rows)
```

**Comment by akuzm** [comment] 2024-02-12 10:48
Thanks for the script, I can reproduce these plans. I think it's the correct behavior of upstream Postgres -- the window functions are evaluated after the `WHERE` clause, so the condition `dateheure >= '2024-01-01' AND dateheure < '2024-02-01'` cannot be moved under evaluation of `LAG`, because it can change the result.

**Comment by cdu-genedis** [comment] 2024-02-12 10:53
Hello@akuzm. Thanks for looking into this.

> the window functions are evaluated after the `WHERE` clause, so the condition `dateheure >= '2024-01-01' AND dateheure < '2024-02-01'` cannot be moved under evaluation of `LAG`, because it can change the result

But then why does the ("direct") SELECT statement work ? It's when the SELECT is encapsulated within the VIEW that things go awry. Is this what you meant ?

**Comment by akuzm** [comment] 2024-02-12 10:57
> But then why does the ("direct") SELECT statement work ? It's when the SELECT is encapsulated within the VIEW that things go awry. Is this what you meant ?

The problem is that the meaning of the statement is different depending on whether you use the view. When you write the WHERE directly in the query, it is applied before the window functions. But when you wrap it into a view, and then select from this view with another WHERE clause, that clause is applied after window functions, not before as in the original query. That's the difference. There is the same problem with aggregate functions.

**Comment by cdu-genedis** [comment] 2024-02-12 11:03
Stored procedure it is then (with a mandated WHERE clause) 😄 
Thanks for clarifying this out.

**Comment by akuzm** [comment] 2024-02-12 11:22
Yeah, I think making it a stored procedure with `LANGUAGE SQL` should give a good query plan. I'll close the issue then.

**Closed by akuzm** 2024-02-12 11:22 UTC
Labels: bug, planner
