### ISSUE TITLE
[Enhancement]: Remove the early access warning that autorebalancing is not supported in Multinode UI 

### ISSUE THREAD

**Issue by vineethapai** [timescale/timescaledb#4531] opened 2022-07-20 14:23 UTC
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Multi-node

### What does the enhancement do?

Auto rebalancing of chunks in Multinode is supported with the 2.7.1 release. The cloud UI for Multinode continues to show the early access warning that auto rebalancing of chunks is not supported. This warning should be removed.

**Comment by Brandon-Timescale** [comment] 2022-07-20 15:20
Couple of issues

- combine multi-node FFs to one and call it #multi-node-early-access
- Change Multi-node description from "High ingest rate (> 100k rows per seconds)" to "High ingest rates (> 100k rows per second)"
- Delete the description line below "Contact Us" that says "we will give you access after validation..."

**Comment by abattenb** [comment] 2022-07-20 20:18
Closed by: https://github.com/timescale/web-cloud/pull/2532

**Comment by svenklemm** [comment] 2022-07-25 08:36
Looks like this was fixed but not closed.

**Closed by svenklemm** 2022-07-25 08:36 UTC
Labels: enhancement

**Comment by Brandon-Timescale** [comment] 2022-07-25 16:07
The current contact us email address is: support@timescale.com 

We need to change that to customer-success@timescale.com

The customer success email automatically creates salesforce issues and the support one doesn't.

**Comment by abattenb** [comment] 2022-07-25 19:54
@Brandon-Timescale This is going to need a Backend update, or an alternate solution. We post to an GraphQL endpoint `SendSupportEmail`, but Front End doesn't set which email address it gets delivered to.

**Comment by abattenb** [comment] 2022-07-25 21:50
I should probably clarify, I can absolutely worth with someone to get this out with a toggle or something in the API. I just need someone else to look into it with me, it's a just outside our codebase for the time being.

**Comment by Brandon-Timescale** [comment] 2022-07-26 16:17
@lukas-bernert should we create an impediment for this?

**Comment by lukas-bernert** [comment] 2022-07-27 07:42
@Brandon-Timescale can you get back to Rana?
This doesn't seem like a huge painpoint. So far 4 users requested MN.
+ The request is already filed as a Salesforce case, so I'm not entirely sure what the problem is.

Let's clarify this first with CSM.

[Looking at this](https://iobeam.slack.com/archives/CS7EV8SHW/p1658660634555509), there should already be Salesforce cases.
