### ISSUE TITLE
ts-restore: run failed while updating extension: failed to update extension version: ERROR: "rides_daily" is not a materialized view

### ISSUE THREAD

**Issue by Twenty7** [timescale/timescaledb#3668] opened 2021-10-07 15:51 UTC
**Relevant system information:**
 - OS: Alpine 10.2.1_pre1 / Alpine 10.3.1_git20210424 / MacOS 11.6
 - PostgreSQL version: 13.2 / 13.4
 - TimescaleDB version: dump (2.2.0) -> restore (2.4.2)
 - Installation method: Docker & Source on Mac

**Describe the bug**
Error with ts-restore when restoring continuous aggregate on a newer version of timescaledb
Example: Dump database on 2.2.0, then restore on 2.4.2

**To Reproduce**

 - Extract data.zip and run the following in the same dir
```
# Setup tsdb 2.2.0
docker run -d --name ts-restore-v220 -p 5433:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:2.2.0-pg13
sleep 5
PGPASSWORD=password createdb tsdb220 -h localhost -p 5433 -U postgres
PGPASSWORD=password psql tsdb220 -h localhost -p 5433 -U postgres < setup.sql

# Dump
ts-dump -dump-pause-jobs -jobs 4 --db-URI=postgresql://postgres:password@localhost:5433/tsdb220 --dump-dir=dump/

# Setup tsdb 2.4.2
docker run -d --name ts-restore-v242 -p 5434:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:2.4.2-pg13
sleep 5
PGPASSWORD=password createdb tsdb242 -h localhost -p 5434 -U postgres

# Restore
ts-restore --db-URI=postgresql://postgres:password@localhost:5434/tsdb242 --dump-dir=dump/ -jobs 4 -do-update 0
```

**Expected behavior**
Restore to complete without errors

**Actual behavior**
ts-restore gives following error:
```
2021/10/06 17:14:35 pg_restore: finished main parallel loop
2021/10/06 17:14:35 pg_restore run failed while updating extension: failed to update extension version: ERROR: "rides_daily" is not a materialized view (SQLSTATE 42809)
```

Logs from Postgres:
```
2021-10-07 00:14:34.500 UTC [162] CONTEXT:  PL/pgSQL function inline_code_block line 12 at RAISE
2021-10-07 00:14:34.551 UTC [164] LOG:  terminating TimescaleDB job scheduler due to administrator command
2021-10-07 00:14:34.551 UTC [164] FATAL:  terminating connection due to administrator command
2021-10-07 00:14:34.552 UTC [165] LOG:  terminating TimescaleDB background job "Telemetry Reporter [1]" due to administrator command
2021-10-07 00:14:34.553 UTC [1] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 164) exited with exit code 1
2021-10-07 00:14:34.794 UTC [165] FATAL:  terminating connection due to administrator command
2021-10-07 00:14:34.797 UTC [1] LOG:  background worker "Telemetry Reporter [1]" (PID 165) exited with exit code 1
2021-10-07 00:14:35.419 UTC [185] ERROR:  "rides_daily" is not a materialized view
2021-10-07 00:14:35.419 UTC [185] CONTEXT:  SQL statement "ALTER MATERIALIZED VIEW rides_daily SET (timescaledb.materialized_only='f') "
	PL/pgSQL function inline_code_block line 21 at EXECUTE
2021-10-07 00:14:35.419 UTC [185] STATEMENT:  ALTER EXTENSION timescaledb UPDATE
2021-10-07 00:14:35.425 UTC [186] ERROR:  tried calling catalog_get when extension isn't loaded
2021-10-07 00:14:35.426 UTC [1] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 186) exited with exit code 1
2021-10-07 00:14:35.460 UTC [190] ERROR:  tried calling catalog_get when extension isn't loaded
2021-10-07 00:14:35.462 UTC [1] LOG:  background worker "TimescaleDB Background Worker Scheduler" (PID 190) exited with exit code 1
```

**Additional context**
 - The error happens regardless of adding the flag `-do-update 0` or not.
 - The only way I found to restore without the error was to restore using the same exact version.

[data.zip](https://github.com/timescale/timescaledb/files/7305161/data.zip)

**Comment by konskov** [comment] 2022-06-17 13:20
Hi @Twenty7 , ts-dump/restore is depreciated at this point, we are not actively maintaining it and what we recommend instead is using pg_dump / pg_restore. Please note however, that it is unsafe to do pg_dump with one version of timescaledb and pg_restore with another. The recommended way would be to restore using the same version and then upgrade to the newer version (or update the version before dumping).  
I am closing the issue for now because I was not able to reproduce it using the recommended approach.

**Closed by konskov** 2022-06-17 13:20 UTC
Labels: bug, continuous_aggregate, pg13, backup-and-restore, docker-build, MacOS
