### ISSUE TITLE
Feature: allow indexing by aggregated values in cont:s aggregate

### ISSUE THREAD

**Issue by stoxx** [timescale/timescaledb#2421] opened 2020-09-18 18:52 UTC
I was developing a summary table to alleviate my need in #2418 and found this approach to be unusable.

I wanted to create a continuous aggregate, that would track min/max, or bounding boxes of data values in a sensor/time blocks. I was hoping to index the ranges so I can quicky look up which devices have had values in range x at time y, and then possibly look up the actual data.

Continuous aggregate values (like min/max) cannot be indexed, like this:
```
# create view unit_position_box with ( timescaledb.continuous ) as 
select unit_id,time_bucket('1 hour',time) as time, 
  min(latitude) min_lat, max(latitude) max_lat, 
  min(longitude) min_lon, max(longitude) max_lon 
from unit_position_report 
group by 1,2;
CREATE VIEW
# create index unit_box_lat on unit_position_box(min_lat,max_lat);
ERROR:  "unit_position_box" is not a table or materialized view
```
(this would have evolved into some kind of numrange GIST index, or a cube index, or a geography index, but I never got that far)

After looking up a bit more of the details of CA implementation, i understand why it might be non-trivial, and specifics would differ between different aggregates.

However i believe indexing by outputs (it can be a lossy index) would be useful, hopefully for other use cases as well. For my use case, I will now have to do a traditional aggregate table with trigger updates, or a workaround (of a workaround) like in #2420.

**Comment by erimatnor** [comment] 2021-02-25 13:12
I believe this is a duplicate of https://github.com/timescale/timescaledb/issues/1229.

**Closed by erimatnor** 2021-02-25 13:12 UTC

**Comment by stoxx** [comment] 2021-02-25 21:59
Yes, as far as after all the noise it is about documentation (or ideally, a more helpful message or syntax sugar) on _how_ to create such secondary indexes.
