### ISSUE TITLE
[Bug]: Cannot create nested continuous aggregates on a particular table schema.

### ISSUE THREAD

**Issue by t-matz** [timescale/timescaledb#5633] opened 2023-04-28 06:01 UTC
### What type of bug is this?

Configuration

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I would like to create continuous aggregates from another continuous aggregate. It can be created fine as expected when I use table1 as base hypertable but it can't be if I use table2, those have exactly same columns only except the order of column definition.

* table1
```sql
CREATE TABLE IF NOT EXISTS "table1"(
  time TIMESTAMP WITH TIME ZONE NOT NULL,
  num INTEGER
);
```
* table2
```sql
CREATE TABLE IF NOT EXISTS "table2" (
  num INTEGER,
  time TIMESTAMP WITH TIME ZONE NOT NULL
);
```

### TimescaleDB version affected

2.9.1

### PostgreSQL version used

15.1

### What operating system did you use?

Ubuntu 20.04.5 LTS x64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### How can we reproduce the bug?

* Create hypertables for both table1 and table2

```sql
CREATE TABLE IF NOT EXISTS "table1"(
  time TIMESTAMP WITH TIME ZONE NOT NULL,
  num INTEGER
);

SELECT create_hypertable('table1', 'time', chunk_time_interval => INTERVAL '24 hours', if_not_exists => TRUE, migrate_data => TRUE);

CREATE TABLE IF NOT EXISTS "table2" (
  num INTEGER,
  time TIMESTAMP WITH TIME ZONE NOT NULL
);

SELECT create_hypertable('table2', 'time', chunk_time_interval => INTERVAL '24 hours', if_not_exists => TRUE, migrate_data => TRUE);
```

* Create 2 continuous aggregates against table1

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS t1_1sec
WITH (timescaledb.continuous) AS
SELECT
  time_bucket('1 second', time) as t,
  sum(num) as sum1sec 
FROM table1
GROUP BY 1
WITH NO DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS t1_5min
WITH (timescaledb.continuous) AS
SELECT
  time_bucket('5 minute', t) as t2,
  sum(sum1sec) as sum5min
FROM t1_1sec
GROUP BY 1
WITH NO DATA;
```

those should be created as expected.

* Create 2 continuous aggregates against **table2**

```sql
CREATE MATERIALIZED VIEW IF NOT EXISTS t2_1sec
WITH (timescaledb.continuous) AS
SELECT
  time_bucket('1 second', time) as t,
  sum(num) as sum1sec 
FROM table2
GROUP BY 1
WITH NO DATA;

CREATE MATERIALIZED VIEW IF NOT EXISTS t2_5min
WITH (timescaledb.continuous) AS
SELECT
  time_bucket('5 minute', t) as t2,
  sum(sum1sec) as sum5min
FROM t2_1sec
GROUP BY 1
WITH NO DATA;
```

t2_1sec is created as expected, but error on t2_5min creation.

```
postgres=# CREATE MATERIALIZED VIEW IF NOT EXISTS t2_5min
postgres-# WITH (timescaledb.continuous) AS
postgres-# SELECT
postgres-#   time_bucket('5 minute', t) as t2,
postgres-#   sum(sum1sec) as sum5min
postgres-# FROM t2_1sec
postgres-# GROUP BY 1
postgres-# WITH NO DATA;
ERROR:  time bucket function must reference a hypertable dimension column
```

**Comment by konskov** [comment] 2023-04-28 07:09
hi @t-matz, thank you for the reproduction steps. This issue is fixed in versions 2.9.2 and higher (commit https://github.com/timescale/timescaledb/pull/5133) , so please upgrade to resolve this.

**Comment by konskov** [comment] 2023-04-28 07:11
I'll go ahead and close this issue since there is already a fix for it available in later versions, please let us know if you still have any trouble after upgrading. Thanks!

**Closed by konskov** 2023-04-28 07:11 UTC
Labels: bug

**Comment by t-matz** [comment] 2023-04-28 07:28
I got it. Thank you!
